### ISSUE TITLE
Cannot Build Local Billboard

### ISSUE THREAD

**Issue by kimberlybaum** [naver/billboard.js#1005]
## Description
`npm start` fails when trying to build my local version. Terminal output:
`/Users/kimbaum/Documents/billboard.js-master/config/webpack.config.plugin.js:19
	if (dirent.isDirectory()) {
	           ^
TypeError: dirent.isDirectory is not a function`

Steps to reproduce:
1. git clone https://github.com/naver/billboard.js.git
2. npm install
3. npm start

Any input on this issue would be appreciated!

**Comment by netil** [comment]
Make sure if your dev node.js version is >=`10.10.0`.
The version requirement is only for build & dev.

- https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_dirent_isdirectory
