### ISSUE TITLE
y-axis label not centered on y-axis with position: 'outer-middle' option

### ISSUE THREAD

**Issue by heppa** [naver/billboard.js#1011]
## Description
When using the option 'outer-middle' for the y axis label position, I would expect the label to be centered along the y-axis. Instead, it seems, that the original svg text-anchor:end style attribute is kept. 

## Steps to check or reproduce
https://codepen.io/anon/pen/GVyezR

simply use any graph and and add:

` axis:{
      y: {
        label: {
          text: 'This is a very long label centered',
          position: 'outer-middle'
        }
      }
    },`

You will see, that this is a problem with longer labels and depending on the length, it partially even disappears.

## Existing Workaround:
dynamically change the style value for the label to text-anchor: middle after successful rendering.

## Potential fixes
* When using outer-middle as option, the text-anchor style value should be 'middle' instead of 'end'.
* It would be nice on top of that, if there was a documentation with all possible values and their behavior for attributes that have several options.

Many thanks!

**Comment by netil** [comment]
Hi @heppa, confirmed the bug and thanks for the report.

**Comment by netil** [comment]
![image](https://user-images.githubusercontent.com/2178435/62592760-50a2b800-b90f-11e9-9470-3177c82b9e6f.png)

This is the screenshot according the 'position' option value for y Axis label text.
- outer-top -> `text-anchor:end`
- outer-middle -> `text-anchor:middle`
- outer-bottom -> `text-anchor:start`

**Comment by heppa** [comment]
Hi Jae Sung,

many thanks for your quick reaction and the ultra-quick fix and release! ;)
