### ISSUE TITLE
Error when hiding y2 axis, but having y2 data

### ISSUE THREAD

**Issue by pakerhoi** [naver/billboard.js#1016]
## Description

The billboardjs chart fails with error, when using `axis.y2.show: false` with y2 axis data. 

### Error:
```
Error in /turbo_modules/billboard.js@1.10.0/dist/billboard.js (8719:86)
yScaleGetter.call(...) is not a function
```

## Expected behaviour
The chart should show a line of data that is related to the y2 axis, but y2 axis scale itself should be hidden. Note, that y axis can be hidden with `axis.y.show: false` and there is no error.

This worked well in the previous versions, but started to fail after an upgrade.

If this behaviour is by design, please update the docs to elaborate what `axis.y.show: false` does and find another way to hide the y2 axis. Also the way y axis works should be consistent with how y2 axis works.

## Steps to check or reproduce

The code to reproduce:

```
import "billboard.js/dist/theme/insight.css";
import bb from "billboard.js";

var chart = bb.generate({
  data: {
    columns: [
      ["data2", 50, 20, 10, 40, 15, 25]
    ],
    axes: {
      data2: "y2"
    }
  },
  axis: {
    y2: {
      show: false,
    }
  },
  bindto: "#additionalYAxis"
});
```

See it live here:
https://stackblitz.com/edit/v6mvnu-sld8qb?file=index.js

**Comment by netil** [comment]
Hi @pakerhoi, this is intended design, basically to not generate unused nodes(#717).
The changes was applied since [`1.8.0`](https://github.com/naver/billboard.js/releases/tag/1.8.0).

To make work, set `axis.y2.show=true` and control the visibility by css.
```css
.bb-axis-y2 {
	display: none;
}
```

I'll be adding this info on APIs doc.
