### ISSUE TITLE
Time series tooltips

### ISSUE THREAD

**Issue by Hortplus-Millar** [naver/billboard.js#1019]
## Description
On the XAxisTickTimeseries example page it appears the zoom and tool tips are enabled in the code. 

```
zoom: {
    enabled: {
      type: "drag"
    }
  },
  tooltip: {
    format: {
      title: function(x) {
		return d3.timeFormat("%Y-%m-%d")(x);
   }
    }
  },
```

However they don't seem to be working on the graph.

It seems like this is a bug, or have I misinterpreted the example?

## Steps to check or reproduce
https://naver.github.io/billboard.js/demo/#Axis.XAxisTickTimeseries

**Comment by netil** [comment]
Hi @Hortplus-Millar, it seems some side effect from the `1.10.0` release.
It's working well on the previous `1.9.5`.
