### ISSUE TITLE
can i insert text to background?

### ISSUE THREAD

**Issue by sunghwanjung** [naver/billboard.js#1023]
![차트](https://user-images.githubusercontent.com/38849804/62915846-e7b8b580-bdd0-11e9-808c-950b20d29f23.PNG)

i try to make chart like that. 
i use regions and made background-color like picture.
but i can,t insert text( "양호", "보통", "관심", "주의"  ) to background like picture

can i insert text like picture?

**Comment by netil** [comment]
Hi @sunghwanjung, you need to combine with [grid](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.grid) and [regions](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.regions) options with some style definition.

![image](https://user-images.githubusercontent.com/2178435/62920873-f2c81180-bde1-11e9-806d-c1daffff43f5.png)

Checkout the online working example I made:
- https://jsbin.com/wicedul/edit?html,css,js,output

**Comment by sunghwanjung** [comment]
감사합니다
