### ISSUE TITLE
Tooltip jumps to only specified xAxis ticks values

### ISSUE THREAD

**Issue by Slava-iTechArt** [naver/billboard.js#1028]
## Description

Starts with 1.10 version, using an area spline chart with multiple series seems to make a tooltip jumps through only the visible x-axis ticks. In 1.9 it works as expected and a tooltip is displayed for every point (see gifs).
## Steps to check or reproduce

How it works with 1.9:

![billboard-1 9](https://user-images.githubusercontent.com/46603740/63027164-1ad47500-beb5-11e9-911b-d0cd02eff22f.gif)

With billboard 1.10:
![billboard-1 10](https://user-images.githubusercontent.com/46603740/63027270-4eaf9a80-beb5-11e9-93a5-6065240febc0.gif)

I may notice that it jumps over visible ticks and skip any other hidden tricks.

After did some research, looks like with the latest version tooltips are only shown under the values defined in [x.axis.tick.values](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4values) which is our case.

```{
axis: {
   x: {
      tick: {
         centered: true, 
         count: 7, 
         culling: false,
         values: [1, 2, 3, 4, 5, 6, 7]
      },
   }
},
data: {
   columns: [
      ['1', 300 numbers],
      ['2', 300 numbers],
      ['3', 300 numbers],
      ['4', 300 numbers],
      ['5', 300 numbers],
      ['6', 300 numbers],
      ['7', 300 numbers],
      ['8', 300 numbers],
      ['x', 300 timestamps],
   ],
   type: 'area-spline',
   x: 'x'
}
```

Is there a bug or incorrect billboard usage?

It's worth to say that this might directly be related to an issue found on the billboard [demo](https://naver.github.io/billboard.js/demo/#Axis.XAxisTickValues) page for defining X Axis Tick Values where you can only see a tooltip for the second point.

**Comment by netil** [comment]
Hi @Slava-iTechArt, thanks for the report.
I'll be trying fix the issue ASAP and release the patch.

**Comment by santicros** [comment]
Hello. I'm still seeing this jumps. Do I have to configure anything to be smooth at the x axis?

Thanks

**Comment by netil** [comment]
Hi @santicros, can you make a reproducible demo?

**Comment by santicros** [comment]
Hey @netil I think I understood it a bit wrong, sorry. What I wanted was the tooltip to be smooth through two points of data, so it would show intermediate values of the two data items. Is it very complicated?
Thanks for your work!!
