### ISSUE TITLE
Depend on individual d3 components

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1042]
The codebase already imports from individual d3 components (`d3-time-format` & co). But the package.json still depend on the full d3 package. This has some drawbacks:

- it does not work with yarn in PnP mode (as this mode only allows you to require your dependencies, not hoisted transitive dependencies as it does not perform hoisting at all)
- it relies on an internal detail of the package manager implementation (the fact that its use of hoisting will let you access transitive dependencies in most cases), which might not always be true (this is the reason why Yarn PnP fails, but some weird cases could happen in other package managers too where they would not hoist)
- it makes the project download useless packages (as billboard does not rely on all d3 components, but only on some of them)

It would be great to change dependencies to depend on components directly.

**Comment by netil** [comment]
Hi @stof, done. Thanks for the suggestion!

**Comment by stof** [comment]
@netil do you have any idea when this will be released ?
