### ISSUE TITLE
How to translate labels "High", "Mid" and "Low"

### ISSUE THREAD

**Issue by gcherem** [naver/billboard.js#1046]
## Description

How to translate or change **High**, **Mid** and **Low** labels from range chart tooltips?

## Steps to check or reproduce

Make any Range Chart, and the tooltip shows labels in english

**Comment by netil** [comment]
Try with [tooltip.contents](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option if you need to customize contents.

```js
   contents: function(d, defaultTitleFormat, defaultValueFormat, color) {
         d;  // d is the data object array containing all the correspondent data

         return ... // formatted html as you want
     },
```
