### ISSUE TITLE
Question about linechart

### ISSUE THREAD

**Issue by gcherem** [naver/billboard.js#1047]
## Description

In linecharts, can I change the line color according the **y** value? For instance, if the value is lower then 100, green, otherwise, red (a callback to calculate the color?)

![image](https://user-images.githubusercontent.com/47535363/63549018-f3f5ee80-c505-11e9-96c6-63d26041a7df.png)

**Comment by netil** [comment]
try the below example. Is not same as you need, but you can get some hint on how to implement.
- https://naver.github.io/billboard.js/demo/#ChartOptions.ColorTiles3

**Comment by gcherem** [comment]
Thanks!

**Comment by fbjorn** [comment]
Hi @netil ! I'm trying to solve the same problem as OP, but I can't understand from the demo how to implement it. I'm lacking experience with D3, so it looks a bit hard. Could you provide a bit more details if you have spare time? 
Thanks in advance

**Comment by netil** [comment]
@fbjorn the example link above I mentioned, it uses applying svg's [linearGradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient), where basically it doesn't needed handle d3.js for this.

Also checkout the link, might help to implement.
- https://stackoverflow.com/questions/42874203/linear-gradient-across-svg-line
