### ISSUE TITLE
Tooltip not working with Zoom on mobile deveice

### ISSUE THREAD

**Issue by ivayloc** [naver/billboard.js#1056]
## Description

I have enabled tooltips and zoom functionality and on mobile devices (iPad and iPhone with iOS v12.3.1) on touch the tooltip is now displayed. When I disable the zoom the tooltip is properly displayed on touch.
## Steps to check or reproduce
https://naver.github.io/billboard.js/demo/#Interaction.Zoom

**Comment by netil** [comment]
Hi @ivayloc, thanks for the report.
I'll be heading for this.
