### ISSUE TITLE
Diverging bar chart support?

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#1057]
## Description
Is it possible to format a billboard bar chart to look like this?
![image](https://user-images.githubusercontent.com/11950094/63871811-713fba00-c971-11e9-923b-062b5c420c0c.png)

**Comment by netil** [comment]
Hi @irislieuw, there's no simple way doing that. But, you can make to render like this way, by some tricky addition.

Checkout the demo that I made, hope this helps.
- https://jsfiddle.net/netil/2mxj7wke/

![image](https://user-images.githubusercontent.com/2178435/63901063-0b6d3400-ca3e-11e9-90ef-341a4be688c2.png)
