### ISSUE TITLE
is it possible to use custom value ticks?

### ISSUE THREAD

**Issue by doubletuna** [naver/billboard.js#1066]
## Description

Hello and thanks for this useful dev!

would it be possible to add support for custom value ticks, so we can present graphs such as:
![image](https://user-images.githubusercontent.com/44400357/64161010-90dd5380-ce45-11e9-92fa-d1c4ec1a8e82.png)

possible data1 values would then be: ["data1", "T1a","T1c"]

Cheers

DT

**Comment by netil** [comment]
Hi @doubletuna, you can with the combination of the data value and the axis' tick options.

Checkout the example:
- https://jsfiddle.net/netil/d03n5L7m/

<img width="477" alt="스크린샷 2019-09-03 오후 9 36 27" src="https://user-images.githubusercontent.com/2178435/64173801-015e9180-ce93-11e9-813b-83feda2255fb.png">

**Comment by doubletuna** [comment]
@netil awesome! works like a charm

cheers!

**Comment by doubletuna** [comment]
Hello @netil 
could you please assist with adding a time series as ticks? (series of scattered dates instead of 0,1,2,3,4,5.. )

cheers

DT
