### ISSUE TITLE
Axis.x.tick.culling.max doesn't apply to subchart x-axis in v1.10.2

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#1068]
## Description
Axis.x.tick.culling.max doesn't get applied to the subchart's x-axis in v1.10.2

## Steps to check or reproduce
Behavior in 1.9.5 (culling.max = 3, and only 3 tick labels are shown)
https://jsfiddle.net/irislieuw/qfajr2yd/
![image](https://user-images.githubusercontent.com/11950094/64299859-92834600-cf2f-11e9-8b88-9124a27e45f9.png)

Behavior in 1.10.2 (same chart as above, but all tick labels are shown in the subchart x-axis)
https://jsfiddle.net/irislieuw/7xfuagrc/
![image](https://user-images.githubusercontent.com/11950094/64299867-9a42ea80-cf2f-11e9-8ddf-b8aef9bb9a75.png)

**Comment by netil** [comment]
Hi @irislieuw, thanks for the report.
