### ISSUE TITLE
Line chart being filled in oddly, unintended

### ISSUE THREAD

**Issue by samuelneff** [naver/billboard.js#1072]
## Description

I'm rendering a line chart and instead of a simple line, the end points of the line are being connected and a polygon is created.

![Screen Shot 2019-09-08 at 12 48 29 AM](https://user-images.githubusercontent.com/1799385/64483602-1315a100-d1d3-11e9-9237-5866f3acae92.png)

## Steps to check or reproduce
Here's my code:

```js
import bb from 'billboard.js';

    chart = bb.generate(
    {
        "data": {
            "columns": [
                [
                    "data",
                    5,
                    5,
                    6,
                    6,
                    6,
                    6,
                    7,
                    7,
                    8,
                    8,
                    9,
                    9,
                    10,
                    11,
                    11,
                    12,
                    13,
                    14,
                    15,
                    17
                ]
            ],
            "types": {
                "data": "line"
            }
        },
        bindto: chartRef.current // this is an HTML element reference
    }
  );
```

**Comment by samuelneff** [comment]
I was able to resolve by adding an explicit `fill: none` to my stylesheet. I don't know where the fill was coming from though--not in `billboard.css` and didn't show up in devtools as being applied from any stylesheet.

**Comment by netil** [comment]
Hi @samuelneff, if base css file isn't loaded(or included) will get unexpected renderings.

```js
// base css file should be loaded
import "billboard.js/dist/billboard.css";
```

If no style is applied and for some reason line element (`<path>` element on below screenshot) having `fill:#000`, will get the result you mentioned.

![image](https://user-images.githubusercontent.com/2178435/64496859-42680300-d2e4-11e9-8f97-73794405f619.png)
