### ISSUE TITLE
 What is the basis for showing or not seeing the x-axis scale value?

### ISSUE THREAD

**Issue by smile02** [naver/billboard.js#1077]
I am using a LineChart type.
The format of receiving data is json method.
As in the photo, I specified the x-axis value as the (date time)
There are times when I don't see a value on the scale.

![x_axis_hide](https://user-images.githubusercontent.com/40282909/65410097-7256f080-de24-11e9-8653-edad6d4a1ba7.PNG)
//If you don't see the x-axis value

![x_axis_show](https://user-images.githubusercontent.com/40282909/65410099-7256f080-de24-11e9-879e-f8118d042c29.PNG)
//When you see the x-axis value

![data받는 값](https://user-images.githubusercontent.com/40282909/65410359-19d42300-de25-11e9-8d75-731b2c514732.PNG)
//The part that maps json data.

![x축](https://user-images.githubusercontent.com/40282909/65410361-19d42300-de25-11e9-991a-265151f68ae6.PNG)
//This is the x-axis tick value setting part.

thank you.

**Comment by netil** [comment]
Hi @smile02, can you provide full working reproducible code as below link?
- https://jsfiddle.net/netil/5otsj814/

**Comment by smile02** [comment]
Yes.
I'm using a date search to show a chart.

First, the code corresponds to the condition that the x-axis scale is not shown.
[190903_190904_testData.txt](https://github.com/naver/billboard.js/files/3645193/190903_190904_testData.txt)


The following code corresponds to the condition where the x-axis scale is shown.
[190904_190905_testData.txt](https://github.com/naver/billboard.js/files/3645195/190904_190905_testData.txt)


* Refer to the sample you sent by link
To match your current environment.

**Comment by netil** [comment]
@smile02, there was a bug on displaying tick with counts (checkout more details from #1078).
Tyr with the fixed version by installing:

```js
npm install billboard.js@next
```

**Comment by smile02** [comment]
I am
I'm using the downloaded billboard.js / billboard.css / insight.css file
How do I apply the above commit?

**Comment by netil** [comment]
@smile02 you can download from `dist` folder from below location:
- https://unpkg.com/browse/billboard.js@1.11.0-next.3/

**Comment by smile02** [comment]
Thank you very much.
