### ISSUE TITLE
Gauge Chart Ranges

### ISSUE THREAD

**Issue by MartijnHarmenzon** [naver/billboard.js#1082]
Is it possible to make something like the image below with the Gauge Chart?

![gauge](https://user-images.githubusercontent.com/23123158/65829572-351cb380-e2a7-11e9-882b-29a2b9c04f0e.png)

For example, I would like to have five performance ranges: 0-20, 20-40, 40-60, 60-80 and 100-120. Each range will have it's own color. For example 0-20 is green and 100-120 is red. Preferably showing the ranges as labels on the chart.

Is this possible?

**Comment by netil** [comment]
Hi @MartijnHarmenzon, there's no way at this moment.

**Comment by heckmac** [comment]
Any updates on this? @MartijnHarmenzon did you find a solution?

**Comment by MartijnHarmenzon** [comment]
@heckmac Unfortunately not.

**Comment by norbertbede** [comment]
hi @netil 

we are implementing billboarjs for an opensource project. 
we are looking for same/similar improvment.

+1 vote

**Comment by netil** [comment]
@MartijnHarmenzon @norbertbede, it took pretty long time to implement this.
See #3635
