### ISSUE TITLE
how to change border size to line chart 

### ISSUE THREAD

**Issue by yoon23** [naver/billboard.js#1083]
how to change border size ???

**Comment by yoon23** [comment]
so change font size???

**Comment by netil** [comment]
Hi @yoon23, if you check the SVG node generated via dev tools, every nodes has their own class name applied.
![image](https://user-images.githubusercontent.com/2178435/65926640-324dca00-e431-11e9-872d-5f5f757f6ce8.png)

Basically, you need to load a base css file for styling. So, if you need to change some styles of specific element 1) check the target node 2) Update or add css rule for that target from base css file
- https://naver.github.io/billboard.js/release/latest/dist/billboard.css
