### ISSUE TITLE
chart.load(), chart.flow() I can't update my data.

### ISSUE THREAD

**Issue by smile02** [naver/billboard.js#1086]
안녕하세요!

![interval](https://user-images.githubusercontent.com/40282909/66538072-d7695080-eb5d-11e9-822f-c365544d67b0.PNG)
위 사진과 같이 1초단위로 getChart2()함수를 통해서 차트의 정보를 불러오고 있습니다.
현재, 데이터를 보관하는 변수 chart_rows에서는 갱신되는 데이터의 값이 저장되고 있지만
그 변수의 값을 chart.load()에서 사용을 하면 데이터의 값이 갱신되는 것이 아닌,
맨 처음에 초기화된 값을 보여주고 있습니다.

![x축 사진](https://user-images.githubusercontent.com/40282909/66538256-8d349f00-eb5e-11e9-8594-27b234f53670.PNG)

값은 다른 페이지에서 1분주기로 넣고있습니다.
chart.flow()를 사용했을 때에도 갱신이 되지 않는 문제가 있었는데,

						flow: function() {							
							this.start && this.inst.flow({
								data:{
									json: chart_rows
								},							
								length: 1,
								duration: 2000,
								done: this.flow.bind(this)							
							});
						}
제가 사용한 방식의 문제가 있는것인지 질문드립니다.

감사합니다.

**Comment by netil** [comment]
Hi @smile02, can you provide some working reproducible code?

BTW, about data loading you can check the below documentation which can help on your case.
- [How to implement realtime chart?](https://github.com/naver/billboard.js/wiki/How-to-implement-realtime-chart%3F)
- [How behaves for dynamic loading](https://github.com/naver/billboard.js/wiki/How-behaves-for-dynamic-loading%3F)

**Comment by smile02** [comment]
Thank you for the related content!
Reproducible code
I will tell you how to test.

First of all, let's check with what you sent.

**Comment by smile02** [comment]
재현가능한 환경을 어떻게 해야할지 모른다고 말씀드렸던것은

A라는 페이지에서는 1분주기로 DB에 데이터를 넣고있습니다.
B라는 페이지에서는 1초, 10초, 1분...주기로 데이터를 조회하고 있습니다.

그리고, 보내주셨던 링크 참고하여 데이터 조회하는 부분 테스트를 진행했습니다.

우선, 방식은 flow()보다는 load()로 하는것이 목적에 더 가까워 load()로 테스트하였습니다.

chart.load({불러올 데이터})로 하거나 chart = bb.generate({불러올 데이터})로 해도
A라는 페이지에서 1분주기로 넣고있는 가장 최근날짜가 보이는것을 확인하였습니다.

그런데, load()는 차트의 갱신이 일어나지 않지만
generate()는 차트의 갱신이 일어나는 것이 확인되었습니다.

`						interval = setInterval(function() {
							//getChart();
//							getChart();

							console.log(chart_rows[chart_rows.length-1].tdate);
							
							//load
							//chart = bb.generate
							//chart.load
							
							
							chart.load({
							    mimeType: "json",
								data: {
//chart_rows는 1초주기로 가져온 데이터입니다.
									json: chart_rows,			    
									keys: {
										 x: "tdate",
										 y:""+trend_y+"",
										 value: chart_chkArray, 
									}	
									,colors: chart_data_colors[0],
								    axes: {
								        trend_y2: "y2"
								      },
									names:chart_data_names[0],									
					               onclick: function(d, element) {
					            	   
//					           	   console.log(d.id);
//					            	   console.log(element);
								    	$("#cmt_value").text(d.value);
								    	isVisible("Y");
								    	
								    	line_index = d.x;
										l001001_comment();
										
										$("#pointModal").modal('show');
										
										/*
										if(d.id==trend_y){
											$("#pointModal").modal('show');		
										}else if(d.id=="cnt"){
											$("#overModal").modal('show');
										}			 
										*/
										
								    	pointModalClose();
								     }
									//위에 색이 있어도 컬러는 효과있음.
									,color: function(color, d) {			
								         if (typeof d === "object") {       
								           if (d.value) {
//								        	  console.log(d);					
								        	 var c_value = 0;
								        	 var c_color = "";
								        	
									           if(d.id == "r_comment"){
									        	   c_color = trend_comment_realColor;								        	   
									           }else if(d.id == "h_comment"){
									        	   c_color = trend_comment_historyColor;
									           }else{
									        	   c_color = color;
									           }	           
									           
								        	  return c_color;			        	  
								             // for data type (ex. line, bar)
								           } else {
								            // return "blue";
								            var else_color="";
								             if(d.id == "r_comment"){
								            	 else_color="white";	 
								             }else if(d.id == "h_comment"){
								            	 else_color="white";
								             }else{
								            	 else_color=color;
								             }
								             return else_color;
								           }					   
								           // for label
								         } else {
								        	 var else2_color="";
								        	 if(d.id == "h_comment"){
								        		 else2_color="white";
								        	 }else if(d.id == "r_comment"){
								        		 else2_color="white";
								        	 }else{
								        		 else2_color=color;	 
								        	 }
								           return else2_color;
								         }
								       }
								},
								axis: {
								    x: {
							    		label: "날짜/시간",
										 type: "category",
									    tick: {
									        centered: true,
								            outer: false,
									         count: trend_x_count,
									        tooltip: true,
									        text: {
									            position: {
									                x: -24
									              }
									          }
									      }
								      },
								      	y: {			      	
								    		min:trend_y_min,
								    		max:trend_y_max,
								    		tick:{
								    			count:trend_y_count,
								    			tooltip: true
								    		}
									      }
								      ,y2: {
											show: trend_y2_bool,
											min:trend_y2_min,
											max:trend_y2_max
										}							      
									},legend: {
									    contents: {
									      bindto: "#legend",
									      template: function(title, color) {
									    	  
//									    	  console.log(id[id.length-1]);

											var result = "";
											
											if(title != 'h_comment' && title != "r_comment"){
												if(chart_legendArray[chart_i].indexOf(title) != -1 && title != 'h_comment' && title != "r_comment"){
													result += "<span style='display:block;color:white;background-color:" + color + ";padding:10px;margin:1px;'>"+chart_legendArray[chart_i]+"</span>";
//													result2 += "<span style='display:block;color:white;font-size:12px;background-color:" + color + ";padding:10px;margin:1px;'>"+title+":"+chart_legend_valueArray[chart_i]+"</span>";
												}
												
												chart_i++;
												if((chart_legendArray.length) == chart_i){
													chart_i = 0;												
												}				
											}
											
											return result;
									     }
									    },
									    hide:["r_comment","h_comment"]
									},
									grid: {
										x:{
											show:trend_x_grid
										},
										y:{
											show:trend_y_grid
										},
										front:true
									},
								point: {				
								   show: true,
							         r: function(d) {
							             var result = 0.2;
							             
							           if(d.id == "r_comment"){		        	   
							             result = 5;
							           }else if(d.id == "h_comment"){		        	   
							             result = 5;
							           }else{
							             result = 0.2;
							           }
							           
							           return result;
							       }
								},		
								zoom: {
								    enabled: {
								      type: "drag"
								    },
//								    rescale: true,
								    onzoomend: function(domain) {
//								    	console.log(domain);			    	
								    	$("#sidx").val(domain[0]);
								    	$("#eidx").val(domain[1]);	
								    	setTimeout(function(){
								    		zoomdate();
								    	},200);			    	
//								    	change_chart();
								    },resetButton: {
								         text: "줌 해제"
								     }
								  },
								  tooltip:{				  
									    format: {
									     	name: function(name, ratio, id, index) { 
												
									     		return name; 
									     	},
									        value: function(value, ratio, id) {
									        	//console.log(id);
									        	
									        	var result;
									        	
//									        	name(name, ratio, id, index)
												
									        	if(id == "r_comment"){
									        		//result = "변경할 수 있을까?";
									        		result = "실시간-코멘트";
									        	}else if(id == "h_comment"){
									        		result = "히스토리컬-코멘트";								        		
									        	}else{
									        		result = value;
									        	}	
											
									  		return result;
									     }
									    }		      
								  },
								bindto: "#chart"
							});
							}, 1000);`

위 코드는 현재 테스트중인 코드입니다.


제가 궁금한것은 load()를 사용할 때 추가해야하는 옵션이 있는것인가요?

감사합니다.

**Comment by netil** [comment]
@smile02 it should provide at least simplified version of reproducible code, because I can't not determine all the local variable values `ex. chart_rows` used on your options.

Also, I'm seeing that you're using unsupported options when calling `.load()`. Try fix that first.
- https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load

**Comment by smile02** [comment]
안녕하세요.
테스트 가능한 코드 입니다.

[수정전_사용.txt](https://github.com/naver/billboard.js/files/4096330/_.txt)


이렇게 사용하려고 했던 이유는 1초마다 갱신된 값을 가져와서
차트에 표현하려고 했습니다.
그러나, 위와 같은 방법으로 하니 차트에서 값을 불러올때마다 깜빡거리는 현상이 발생하는것을
확인했습니다.

generate를 사용하면 새로운것을 생성한다는 느낌이 들어서 그런것일거라고 생각은 드는데
어떻게 다른방법으로 구현해야할지 생각이 안나서 질문드렸었습니다.

2019년 10월달에 답변받은 내용 참고하여 테스트 한 내용입니다.

[수정후_사용.txt](https://github.com/naver/billboard.js/files/4096308/_.txt)


위와 같은 방법으로 처음에는 generate를 사용하고
1초마다 갱신할때에는 load를 사용하는 함수를 불러오는 방식을 생각하여 적용했습니다.
그러나, 차트가 갱신이 되지 않았습니다.

또, 맨 처음 수정전_사용에 don()함수 안에 getChart2()를 호출하는 함수를 사용하는 방식으로
해도 갱신이 되지 않아서 질문드립니다.

제 접근 방식이 잘못된건가요?
방법을 알려주시면 감사하겠습니다.

**Comment by netil** [comment]
@smile02, I'm seeing incorrect options are used on your code.

```js
var getChart2 = function(){
   ...
        // your code
	chart.load({
	      data: {
		json: jsonData,
	        keys: {
			x:"tdate1",
	        	value : ["data1","data2","data3"]
	        }
	      },
	      bindto: "#chart"
	}); 
	
       // update as
	chart.load({
		json: jsonData,
		keys: {
			x:"tdate1",
			value : ["data1","data2","data3"]
		}
	});
```

**Comment by smile02** [comment]
Hello.
Thank you for answering my question.

Applying the code you have confirmed that the trend flicker does not occur.

The example was the best answer I could give.

Can I ask you two questions?
Including json and keys in the data key value
The difference between not including it in the data key value

2. bindto key value
I wonder what it means to write down the name of the chart.

**Comment by netil** [comment]
1. For keys, read the [`data.keys`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4keys) description. If you're loading same data with same key, you can omit the key.
```js
// Also works in your example.
chart.load({json: jsonData});
```

2. [`bindto`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.bindto) is to specify where the chart will be rendered. On loading there's no need to specify again.

**Comment by smile02** [comment]
Your message was very helpful.

If you have any questions, we will leave your inquiry.
Thank you.
