### ISSUE TITLE
Is y3 axis available?

### ISSUE THREAD

**Issue by mining2706** [naver/billboard.js#1090]
Is y3 axis available?

![image](https://user-images.githubusercontent.com/42030649/66973281-79df8180-f0d2-11e9-9fe2-73888d71dc40.png)

It would be good if the colors of the y-axis and the axis are the same.

**Comment by netil** [comment]
Hi @mining2706, checkout the example.
- https://naver.github.io/billboard.js/demo/#Axis.MultiAxes

You can add multiple axes by [`axis[ x | y | y2 ].axes` options](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y2%25E2%2580%25A4axes)

**Comment by mining2706** [comment]
우선 제가 아주 잘 사용하고 있는 것에 감사드립니다. 사용하기 정말 좋았습니다.

주로 예제를 보고 개발을 진행하여서 예제,playground를 아주 많이 보았습니다. ^^

개발하다가 x 축은 같이 사용하는데 y 축을 여러개 사용하여 표현하는 차트가 많이 발생하였습니다.

하지만 y 축의 범위가 같이 사용할수 있으면 같이 사용하고 있습니다 (알려주신 예제로 하고 있습니다.)

문제는 y 축이 3개 이상일때는 y축의 범위가  

y축  10,000,000 ~ 10,000,000,000
y2축  0 ~ 100
y3축 0.01 ~ 0.9  

이렇게 되다보니 ...사실 하나의 y축으로 다 표현할수 있지만  각 축의 갭이 잘 표현이 되지 않아서
축의 단위를 다르게 할 수 있는 방법이 있었으면 하는 생각이 들어서 제안했습니다.

최초 질문의 그래프를 보시면 각 y축의 범위가 다르고 , 그래프의 색깔과 축의 색깔이 동일하여
인식하기 좋아서  제안해보았습니다.

**Comment by netil** [comment]
@mining2706, thanks for the suggestion.
Well, currently the scales for added axes are based on its original scale value.

To have different scales, maybe a new options `axes.scales` should be implemented as follows.
I'll try considering adding this for next future release.
```js
y: {
   axes: [
     {
	 scales: [10, 1000],
         ...
```

**Comment by mining2706** [comment]
thank you. Looking forward to the next version.

**Comment by mining2706** [comment]
var chart = bb.generate({
  data: {
    columns: [
	["data1", 0.5, 0.200, 0.100, 0.400, 0.150, 0.250],
	["data2", 50, 20, 10, 40, 15, 25],
	["data3", 5000, 2000, 1000, 4000, 1500, 2500]
    ],
    axes: {
      data1: "y",
      data2: "y2",
	data3: "y2"
    }
  },
  axis: {
    y2: {
      		show: true,
				   axes: [
							{
								domain: [0, 1000],
								tick: {
									count: 5
								}
							}
					 ]
    }
  },
  bindto: "#additionalYAxis"
});

![image](https://user-images.githubusercontent.com/42030649/69294112-4ef6c900-0c4e-11ea-8451-5e0453734031.png)

제가 잘못 이해하는 것일까요? 

y2축을  data2 [0~50] , data3 [1000 ~ 5000]으로  각각의 축으로 사용하고 싶은데요

한번만 확인 부탁드립니다.

**Comment by netil** [comment]
@mining2706, the `close` doesn't mean it is released. It means solved and merged to master branch.
If you need to use the updated version, you have two choices:
- from CDN
  https://unpkg.com/browse/billboard.js@1.11.0-next.7/dist/
- or Install `next` tagged from npm
  ```sh
  npm install billboard.js@next
  ```
