### ISSUE TITLE
Is there are something like chart.js' stepSize?

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1098]
## Description
I've tried to show x thick which has number that multiply of 0.12 for example: [0.12, 0.24, 0.36...] not using ```values: []``` .

I've searched on the official document, it seems this functionality is not provided which looks similar chart'js' [stepSize](https://www.chartjs.org/docs/latest/axes/cartesian/linear.html#tick-configuration-options) or canvas.js' [interval](https://canvasjs.com/docs/charts/chart-options/axisy/interval/).

**Comment by qkreltms** [comment]
I solved this issue using this function, but It would be better to be added chart'js' stepSize feature in further release. :
```javascript
const createNumbers = (
    start: number,
    end: number,
    multiply: number = 0,
    interval: number = 1,
    // undefeind일시 정수 값 나옴
    fixedSize: number | undefined = undefined
  ) => {
    const numbers = [];
    for (let i = start; i <= end; i += interval) {
      if (multiply !== 0 && i % multiply !== 0) {
        continue;
      }

      numbers.push(parseFloat(i.toFixed(fixedSize)));
    }

    return numbers;
  };

//Usage
  const yLabels = [...createNumbers(2.788014434745625, 3.627024000297884, 0, 0.16, 2)];
  console.log(yLabels)
 //Array(6)
 //0: 2.79
 //1: 2.95
 //3. 11
 //3. 27
 //...
```

**Comment by netil** [comment]
@qkreltms, there's no `stepSize` option currently, but it seems useful to be implemented.
