### ISSUE TITLE
Tooltips not shown after generating chart when mouse already on window chart position

### ISSUE THREAD

**Issue by bennettdams** [naver/billboard.js#1099]
## Description
When you place the mouse at a position in the browser window where a chart is going to be generated, it will not show a tooltip after the chart is generated.

## Steps to check or reproduce
Simple example where generating the chart is done with an interval:
https://codesandbox.io/s/quiet-dust-h9cbh

1. Load the page
2. Place the mouse in the window where the chart is going to be generated
3. Wait for interval to generate the chart

-> no tooltip shown, you need to move the mouse to show a tooltip

**Comment by nirmal93guna** [comment]
When the mouse is kept at the position before the chart is generated, the event will not be captured, since the chart is not generated yet. Thats why, it works only after the chart is generated. This is how it works in any place.
