### ISSUE TITLE
How to get element in data.onover?

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1100]
## Description
[This](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4onover) says onover has d of argument, but want to get ctx

I want to get <circle /> element and want to manipulate it.

Any Ideas? 
```
data: {
    onover: function(d) { ... }
}
```

In options.d.ts in ```"billboard.js": "^1.10.2"```
```
   onover?(d: DataItem, element?: any): void;
   // When logs element it prints undefined
```

**Comment by qkreltms** [comment]
I found the way how to get circles using ```onafterinit()``` 

```
    onafterinit: function(ctx: any) {
      const patientDataIndex = 3;

      // Get circles.
      patientPointPositions = ctx.$.line.circles._groups[patientDataIndex].map((circle: any) => ({
        x: parseInt(circle.getAttribute("cx")),
        y: parseInt(circle.getAttribute("cy"))
      }));
    },
```

**Comment by netil** [comment]
@qkreltms, there're inconsistency between type definition and API definition.
For `data.onover/onout`, will not pass element argument. So, the current type definition are incorrect.

So, for now do this to get `<circle>` element.
```js
onover: function(d) {
	const node = this.$.main.select(`.bb-shapes-${d.id} .bb-shape-${d.index}`).node();

	console.log(node);
}
```

I'll be trying to fix this issue by passing "current element" as defined in type definition.
