### ISSUE TITLE
Tooltip appears even set line.point when set xs property

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1104]
## Description
When I tested it without xs property, tooltip doesn't appears in case my mouse pointer is on the other line's points which is not included in ```line.point: []```

Code:
```javascript

bb.generate({
    bindto: "#chart",
    line: { point: ["data1"] },
    tooltip: { grouped: false },
    data: {
        columns: [
            ["data1", 30, 200, 100, 170, 150, 250],
            ["data2", 10, 20, 30, 40, 50],
        ],
        types: {
          data1: "line",
          data2: "area-spline"
        },
        colors: {
          data1: "red",
          data2: "green"
        }
    }
});
```
![bug2](https://user-images.githubusercontent.com/25196026/67833317-add19280-fb27-11e9-9baa-2b6e271f67e6.png)

But when I tried it with xs property, it appears.

```javascript
bb.generate({
    bindto: "#chart",
    line: { point: ["data1"] },
    tooltip: { grouped: false },
    data: {
        xs: { xAverage: "yAverage", data1: "data2" },
        columns: [
            ["data1", 30, 200, 100, 170, 150, 250],
            ["data2", 10, 20, 30, 40, 50],
            ["xAverage", 10, 40, 20, 30, 50],
            ["yAverage", 10, 20, 30, 40, 50]
        ],
        types: {
          data1: "line",
          data2: "area-spline"
        },
        colors: {
          data1: "red",
          data2: "green"
        }
    }
});
```
![bug](https://user-images.githubusercontent.com/25196026/67833410-e2454e80-fb27-11e9-9683-54c4e6a20898.png)

Please check whether it's bug or intended feature.

If it's intended feature, then how to disable tooltip showing which is not included in  ```line.point: []```?

## Steps to check or reproduce
https://codepen.io/qkreltms/pen/ZEEXXzN?editors=0010

**Comment by netil** [comment]
@qkreltms, `tooltip.point` is about showing point element, nor about event.
So, even not showing point, the tooltip will work. If you want control the display of tooltip checkout some of [tooltip.onshow](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option.

**Comment by qkreltms** [comment]
@netil do you know how to disable interaction boundary of the blue line of second code snippet to disable tooltip?

**Comment by qkreltms** [comment]
I solved this issue by doing this in ```React```
```    
  const chartRef = createRef<any>();
  useEffect(() => {
    // options의 tooltip.show는 state에 반응하지 않음
    // 그러므로 config를 사용해 직접 show 값을 넣어줘서 다시 랜더링
    const chartInstance = chartRef.current.chartInstance;
    chartInstance.config("tooltip.show", isTooltipVisible)
  }, [isTooltipVisible])

data: {
      onout: (d: any) => {
        setIsTooltipVisible(false);
      },
      onover: (d: any) => {
        if (d.id !== "xPatientPoints") {
          setIsTooltipVisible(false);
        } else {
          setIsTooltipVisible(true);
        }
      },
   ...

return <Chart2 style={{ cursor: "default"}} options={options} ref={chartRef}></Chart2>
```
