### ISSUE TITLE
y-axis culling for zoomed chart

### ISSUE THREAD

**Issue by rall** [naver/billboard.js#1106]
I ran into an issue with a time series chart configured with a y-axis culling max value.

Occasionally, when zoomed in, the y-axis labels display randomly. Here's an example:

![image](https://user-images.githubusercontent.com/24905/67895261-8a5f1580-fb30-11e9-9ee8-a2de2e4bbbaf.png)

The temporary workaround I'm using is to call the internal `setCulling()` method in the `onZoomEnd` callback:

```
this.chart.config('zoom.onzoomend', () => {
  this.chart.internal.axis.setCulling();
});
```

Does this sound like a bug or is it more likely I'm doing something wrong? If it's a bug and something like my workaround is the fix I'm happy to make a pull request.

**Comment by netil** [comment]
Hi @rall, thanks for the report!

**Comment by rall** [comment]
thanks for the fix!
