### ISSUE TITLE
onzoom API doesn't provide domain object

### ISSUE THREAD

**Issue by upgle** [naver/billboard.js#1109]
## Description

https://github.com/naver/billboard.js/blob/862156fc9c3c975af09aef07e95cd61d5cf3d727/src/config/Options.js#L141

The onzoom API had returned domain object, but now it doesn't.

- "billboard.js": "1.7.1" (working)
- "billboard.js": "1.8.1" (not working)
- "billboard.js": "1.10.2" (not working)

It expects to receive a domain object, but there is no domain object (`undefined`)

```javascript
     onzoom: (domain) => {
        console.log('onzoom', domain)
      },
```
## Steps to check or reproduce

```javascript
bb.generate({
    bindto: "#chart",
    zoom: {
      enabled: {
        type: 'drag',
      },
      rescale: false,
      onzoom: (domain) => {
        console.log('onzoom', domain)
      },
      resetButton: true,
    },
    data: {
        columns: [
            ["data1", 30, 200, 100, 170, 150, 250],
            ["data2", 130, 100, 140, 35, 110, 50]
        ],
        types: {
          data1: "line",
          data2: "area-spline"
        },
        colors: {
          data1: "red",
          data2: "green"
        }
    }
});
```

![image](https://user-images.githubusercontent.com/5635513/68357815-e5f55880-0159-11ea-8b90-b3bd248945dd.png)

**Comment by netil** [comment]
Hi @upgle, thanks for the report.
