### ISSUE TITLE
Release with individual component dependencies

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1113]
Hi,

https://github.com/naver/billboard.js/issues/1042 has been fixed, which reduces the size of dependencies a lot. Is there any ETA for a release including this refactoring yet ?

**Comment by netil** [comment]
Hi @stof, the regular release schedule is about every 3 months period. The last was on Aug., and within this month will be happening new one.

Meanwhile, you can use `@next` tagged release which released with the latest changes.
```sh
npm i billboard.js@next
```

**Comment by stof** [comment]
Well, I'm not yet using billboard.js. But this migration to individual components is a good reason to me to migrate from C3 to billboards, as it avoids loading lots of d3 packages (and d3+c3 are currently my biggest contributors to the bundle size). I'm fine if a new one happens this month.

Btw, would it be worth documenting the regular release schedule somewhere so that we can know about it to have an idea when a release might happen ? I just found a mention about it in the blog post of the 1.10 release, but that's not a place where I would have searched for it.

**Comment by netil** [comment]
@stof , https://github.com/naver/billboard.js/wiki/Release-workflow#schedule
