### ISSUE TITLE
[bug] bars width are so thick and overlapped each other.

### ISSUE THREAD

**Issue by createall** [naver/billboard.js#1115]
## Description
I made a bar chart with 2 series.
As you can see in attached file. bars width is so thick and overlap each other.

## Steps to check or reproduce
You can reproduce the symptom, with attached script.

Thanks in advance.
![billboard_chart_error](https://user-images.githubusercontent.com/1954932/68732136-b17c1380-0615-11ea-9a32-f68b0e29a316.png)
[testscript.txt](https://github.com/naver/billboard.js/files/3839364/testscript.txt)

**Comment by netil** [comment]
Hi @createall, thanks for the report!
You can try the fixed version by installing `@next`.

```sh
npm i billboard.js@next
```
