### ISSUE TITLE
Chart resize on container height change is at a slow pace.

### ISSUE THREAD

**Issue by nirmal93guna** [naver/billboard.js#1142]
## Description
When we resize the height of the container of the graph, the height takes considerable time to achieve the size of the window. I have added a example of going fullscreen and coming out.

## Steps to check or reproduce
![billboard-height-change-slow](https://user-images.githubusercontent.com/14155901/69804425-88a67180-1204-11ea-85ba-a519fc4d56ce.gif)

**Comment by netil** [comment]
@nirmal93guna, can you provide a reproducible code?

**Comment by nirmal93guna** [comment]
Hi @netil . I was able to fix this issue. This was not related to the library. Not sure what is the issue which caused it, though, was able to fix it with css changes. Thank you for your time and sorry for the wrong alarm
