### ISSUE TITLE
Update TextOverlap plugin's module

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#1144]
## Description

The [`d3-voronoi`](https://github.com/d3/d3-voronoi) used from TextOverlap plugin was deprecated.
It should replaced to [`d3-delaunay`](https://github.com/d3/d3-delaunay) instead.

Ref #977, #1048

**Comment by netil** [comment]
@kimberlybaum, would you want to try?

**Comment by adschm** [comment]
If this is ever update, consider reviving the issue/suggestion in #2191
