### ISSUE TITLE
"zerobased" option for datatypes line, scatter and bubble

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1149]
## Description
In our local c3.js implementation we are using the "zerobased" option for line and scatter.
As we are migrating from c3.js to billboard.js we want to make sure that we will be able to use the functionality we implemented in our local c3.js implementation and as this option could also be useful for others, we would like to implement it in billboard.

Here are the examples how it would look like:

`line: { zerobased: false }`
![line_zerobased_false](https://user-images.githubusercontent.com/42860868/70032749-6323ba00-15ae-11ea-865f-c5be2e02c5e6.png)

`line: { zerobased: true }`
![line_zerobased_true](https://user-images.githubusercontent.com/42860868/70032751-6454e700-15ae-11ea-8794-8421f6d5e834.png)

`scatter: { zerobased: false }`
![scatter_zerobased_false](https://user-images.githubusercontent.com/42860868/70032754-65861400-15ae-11ea-8b7e-96526dc59f40.png)

`scatter: { zerobased: true }`
![scatter_zerobased_true](https://user-images.githubusercontent.com/42860868/70032755-661eaa80-15ae-11ea-82d6-aa0414d1fb41.png)

`bubble: { zerobased: false }`
![bubble_zerobased_false](https://user-images.githubusercontent.com/42860868/70219806-c136d580-1745-11ea-9e92-a9ed47dcf79b.png)

`bubble: { zerobased: true }`
![bubble_zerobased_true](https://user-images.githubusercontent.com/42860868/70219821-cdbb2e00-1745-11ea-8486-52c6f39884ee.png)

**Comment by netil** [comment]
@michkami, great work! and thanks for the contribution.
I'll be reviewing for the merge.
