### ISSUE TITLE
rotate is missing in the types of the Y axis

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1158]
When using the `rotate` option of the ticks of Y axis for a rotated chart, everything works as expected (my ticks in the axis are indeed rotated by 45deg). But the typescript compiler complains about option, saying it does not exist.

**Comment by netil** [comment]
Hi @stof, thanks for the report.

As you mentioned, the `axis.y.tick.rotate` is implemented, but not documented even at API docs.
I'll adding that.
