### ISSUE TITLE
When using a bar chart group, is there a way to expose the total of the groups at the top of the bar?

### ISSUE THREAD

**Issue by nanumhn** [naver/billboard.js#1159]
안녕하세요. 우선 유용한 차트를 이용에 감사드립니다.
질문) 바 차트 이용 시 여러 개의 값을 그룹으로 설정하여, 차트를 생성 하는데요.
그룹 데이터의 합계 값을 그룹 바 상단에 노출하는 방법을 문의 드립니다.
그룹 내 각 항목의 값은 노출하는 것은 확인이 되었는데요. 합계 값을 구하는게 어렵네요.
부탁 드리겠습니다.

Automatic translation :)
> Hello. First of all, thank you for using the useful chart.
> Question) When using bar charts, you create a chart by setting multiple values into groups.
> I would like to ask you how to expose the sum value of your group data to the top of the group bar.
> It has been confirmed that the values of each item in the group are exposed. It's hard to get the total value.
> I ask a favor of you.

## Steps to check or reproduce

![billboardjs-bar-chart-QnA-20191210](https://user-images.githubusercontent.com/4599005/70489522-60414000-1b3f-11ea-9bac-06f81642af34.png)

**Comment by netil** [comment]
Hi @nanumhn, there're many ways to achieve this.
Checkout the example for one of those ways.
- https://jsfiddle.net/netil/vj1gkepz/

**Comment by nanumhn** [comment]
Thank you for your help and your work !!!
