### ISSUE TITLE
Color pattern actually accepts null due to the implementation, but types reject that

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1162]
## Description
In the implementation, it is actually possible to pass `null` in the color pattern, which will not set the fill color in the graph thanks to the way the `attr` method of `d3-selection` works. This is useful when building a widget where the color should be controlled by CSS.
But when doing that, the Typescript compiler reports a problem, as it accept only strings (or a callback generating the color string)

## Steps to check or reproduce

```js
import { bb } from 'billboard.js'

const progress = 0.8;
const element = document.querySelector('.condition-chart-donut');
const donutTitle = 'some text';

bb.generate({
    bindto: element,
    data: {
      columns: [
        ['fill', progress],
        ['background', 1 - progress]
      ],
      type: 'donut',
      order: null
    },
    color: {
      pattern: [null, null]
    },
    legend: {
      show: false
    },
    donut: {
      title: donutTitle,
      label: {
        show: false
      },
      width: 5,
      expand: false
    },
    interaction: {
      enabled: false
    },
    size: {
      height: 175,
      width: 175
    }
});
```

```scss
.condition-chart-donut {
  margin: 0 auto;

  .bb-arc-fill {
    fill: $themeColor;
  }

  .bb-arc-background {
    fill: rgba($themeColor, 0.15);
  }
}
```

This allows to have a chart looking like this (well, I have some extra customization of the title to handle the bolding, not reproduced above):
![image](https://user-images.githubusercontent.com/439401/70702258-15096780-1cce-11ea-8351-ddb45371268f.png)

And I can change the color of the chart by changing my CSS with a different theme color.

This code is working perfectly to achieve my need. However, when checking types with `tsc` with strict null checks (I'm using the `tsc --noEmit --checkJS --allowJS --downlevelIteration --lib es5,es6,dom,dom.iterable --esModuleInterop --strictNullChecks assets/js/widget/condition-chart.js` command for that), I'm getting this error:

```
assets/js/widget/condition-chart.js:36:5 - error TS2322: Type '{ pattern: null[]; }' is not assignable to type '{ pattern?: string[] | undefined; threshold?: { unit?: string | undefined; values?: number[] | undefined; max?: number | undefined; } | undefined; tiles?: (() => SVGPathElement[]) | undefined; onover?: string | ... 2 more ... | undefined; }'.
  Types of property 'pattern' are incompatible.
    Type 'null[]' is not assignable to type 'string[]'.
      Type 'null' is not assignable to type 'string'.

36     color: {
       ~~~~~

  node_modules/billboard.js/types/options.d.ts:94:2
    94  color?: {
        ~~~~~
    The expected type comes from property 'color' which is declared here on type 'ChartOptions'
```

**Comment by stof** [comment]
Should types/doc be updated to mention `null` as  valid valid in color pattern ?

**Comment by netil** [comment]
@stof, good point, but normally I can't expect from users knowing how behaves `null` as you do. To be officially accepting `null` as one of possible value, it should have some simple usage about it, but I think isn't really clear or is quite difficult to give an generalized usage form.

If you need to control the color value according its `Theme`, how about considering put `!import` rule on your css rule definition?

```css
.condition-chart-donut {
  margin: 0 auto;

  .bb-arc-fill {
    fill: $themeColor !import;
  }

  .bb-arc-background {
    fill: rgba($themeColor, 0.15) !import;
  }
}
```

This will make to have more priority than the inlined `fill` property set.

**Comment by stof** [comment]
@netil that might be an option. But isn't the goal of the specific classes to allow easy styling with CSS ? Having to use `!important` for all such styling kinda defeats this purpose.
I find the usage of `null` quite handy in such case. I'm fine keeping that an advanced feature, but types have to be compatible with all features.

**Comment by netil** [comment]
@stof, would you like to send PR for this?
