### ISSUE TITLE
How can make candle chart?

### ISSUE THREAD

**Issue by Jeanne-Oh** [naver/billboard.js#1167]
Hello.

I want to create a candlestick chart, a kind of stock chart.
I would like to fill the bar between the minimum and maximum values with the x and y axes apart.
Can I use a billboard to construct a vertical bar graph?

For Example.
![image](https://user-images.githubusercontent.com/59049511/71163425-64cccd80-2290-11ea-937b-c6e9e7dfd64a.png)

**Comment by netil** [comment]
Hi @Jeanne-Oh, currently there's no support for candle type chart, but definitely is in our roadmap plan(Ref. #76).

**Comment by netil** [comment]
The works for new `candlestick` type reaching the end.
Ref. https://github.com/naver/billboard.js/issues/76#issuecomment-789611403
