### ISSUE TITLE
Pie chart interactions are broken for some data names in 1.11

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1168]
## Description
When data names contains characters which  are not allowed in class names without escaping, the interactions of the Pie chart are broken (I haven't checked other chart types).

## Steps to check or reproduce
Go on https://jsfiddle.net/stof70/wrbLksg7/2/ and hover on the chart. The console will show errors.

https://jsfiddle.net/stof70/dw19pngm/2/ is exactly the same code, but loads billboards 1.10.2, and it does not have the bug (because it generates some normalized ids)

**Comment by stof** [comment]
note that maybe other types are affected too, I haven't checked.

**Comment by netil** [comment]
@stof, thanks for the report!
