### ISSUE TITLE
Null values are displayed as 0 when data.regions are specified

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#1172]
## Description
Line charts that have null data in them aren't rendered properly when data.regions are used to make portions of the line dashed. 

The dashed regions of the line are applied properly, but all null values are displayed as zeros.
![image](https://user-images.githubusercontent.com/11950094/71204192-64aedc80-2254-11ea-891e-67ada919e11b.png)

## Steps to check or reproduce
If you comment out the `regions` object the line properly renders null values. If the `regions` object is passed, null values are plotted as zeros (but don't show up in the tooltip).
https://jsfiddle.net/irislieuw/qnsk8w1z/28/

**Comment by netil** [comment]
Hi @irislieuw, thanks for the report!
