### ISSUE TITLE
chart.flush() is different with docs 

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1186]
Check out these:

1. 
https://github.com/naver/billboard.js/blob/0c19653137ab4307ffac81607aa1c02f9760b4ed/src/api/api.chart.js#L44

2.
https://github.com/naver/billboard.js/blob/0c19653137ab4307ffac81607aa1c02f9760b4ed/types/chart.d.ts#L468

3.
https://naver.github.io/billboard.js/release/latest/doc/api_api.chart.js.html

4.
https://naver.github.io/billboard.js/release/latest/doc/Chart.html#flush

**Comment by netil** [comment]
Hi @qkreltms, the second parameter is only for internal use, but it was described wrongly in API doc.
This was already corrected by https://github.com/naver/billboard.js/commit/f4c94fda8d3cda9f33cf4213f951826a2fe1f6b0.
