### ISSUE TITLE
Question: Make Focused Arc on Donut larger?

### ISSUE THREAD

**Issue by TzolkinB** [naver/billboard.js#1189]
## Description
For the donut, the focused arc is barely larger than the de-focused. Is there a way to make the section that is hovered larger? I know the de-focused sections have opacity but for my use case, it is still difficult to distinguish which section is hovered.

<img width="338" alt="Screen Shot 2019-12-31 at 12 21 23 PM" src="https://user-images.githubusercontent.com/10334517/71628855-48059380-2bc8-11ea-98d3-a276691f1a26.png">

## Steps to check or reproduce
See sample screenshot of current behavior. Unable to show my use case for proprietary reasons.

Thank you!

**Comment by netil** [comment]
Hi @TzolkinB, there's no option to make expanded area more bigger for now. It looks good adding as new option.
For now, you can try emphasize more making more smaller the de-focused area by adding:

```css
.bb-defocused path {
	stroke-width: 5px;
}
```
