### ISSUE TITLE
"onrendered" is not called after render completes.

### ISSUE THREAD

**Issue by ddurung101** [naver/billboard.js#119]
## Description

References the rendered element information and creates another element.

When rendering is complete, billboard.js should call "onrendered". However, it is called beforehand.

So other elements are drawn incorrectly.

**Comment by netil** [comment]
Could you provide reproducible demo for your case?
IMO, there're a lot of different opinions when it really means `rendered`.

Just, simple onrendred callback looks working good.
- http://jsbin.com/newaza/edit?html,js,output

**Comment by ddurung101** [comment]
This is the screen I tested in Chrome.

![chart](https://user-images.githubusercontent.com/19185315/29647184-f17a8be2-88c2-11e7-8765-dd94b2da9021.gif)

I often see it on Android phones.

**Comment by netil** [comment]
turn off auto resize option.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.resize
```js
resize: {
     auto: false
}
```

The resize event fires when viewport's size changes. It means even you don't rotate, there're situation which resize can be fired(ex. when the address bar appears, etc.).

So, for mobile environment turn off the auto resize, and attach proper device orientation event, and then call `.resize()` method.
- https://naver.github.io/billboard.js/release/latest/doc/Chart.html#resize
```js
var chart = bb.generate(...);

window.addEventListener("onorientationchange", () => {
    chart.resize();
});
```
