### ISSUE TITLE
Null data point blocks other points and prevents tooltip from showing

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#1199]
## Description
With scatter and bubble charts, null data points cover other points behind them and prevent tooltips from showing. 

## Steps to check or reproduce
https://www.loom.com/share/dc098a8f399b457c9c23a7d893adbdcd

https://jsfiddle.net/irislieuw/198fnaht/

**Comment by netil** [comment]
Hi @irislieuw, thanks for the report.
