### ISSUE TITLE
Separate x-axis labels from legend labels

### ISSUE THREAD

**Issue by MartynJacques-Arm** [naver/billboard.js#1220]
## Description
The x-axis labels and legend labels are grabbed from the same string at the beginning of the data series, it'd be nice if these could be set separately for our use case of adding scaling labels to the legend only e.g. when adding k, M, G, T scaling labels, we only want them to show up in the legend, not the x axis too. 

<img width="1005" alt="legendWithScaling" src="https://user-images.githubusercontent.com/42978102/73171545-e36f2300-40f8-11ea-9a7d-63136f78fb79.png">

**Comment by netil** [comment]
Hi @MartynJacques-Arm. Could you specify more in detail? You can specify the `lenged` and x Axis' label in current implementation.

![image](https://user-images.githubusercontent.com/2178435/73226031-fe519e00-41b1-11ea-8e56-e03305311713.png)

**Comment by MartynJacques-Arm** [comment]
Sure, apologies I wasn't clear enough! We want to add the scale label to the tooltip legend only, not the static legend below the chart, is this possible? 

<img width="1005" alt="legendWithScaling" src="https://user-images.githubusercontent.com/42978102/73252279-656f5280-41b2-11ea-9f4f-93570d331694.png">

**Comment by MartynJacques-Arm** [comment]
Perfect, that lead me to what I needed, thank you!
