### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bahrus** [naver/billboard.js#123]
## Description
The [Zoomable Treemap](http://bl.ocks.org/ganeshv/6a8e9ada3ab7f2d88022) chart type is an extremely useful chart type.  Adding support to it in billboard.js would greatly increase its popularity, in my opinion.

**Comment by netil** [comment]
thanks @bahrus for the suggestion.
We'll take considering this in our future plans!

- https://github.com/naver/billboard.js/wiki/Roadmap#new-chart-types

**Comment by paupololi** [comment]
Are there any update with this feature?
Thanks in advance

**Comment by pixobit** [comment]
Also interested in this

**Comment by netil** [comment]
It took long time to be implemented, but finally is here!
The initial implementation won't support zoomable functionality, but it will be having more enhancement further.
