### ISSUE TITLE
Clone y/y2-axis domain from the other y/y2-axis if no data is bound to one of them

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1231]
## Description
If there is no data bound to y2-axis and y2-axis is shown, it sets the domain of y2-axis to [0, 1].
The same happens if no data is bound to y-axis.
_All columns bound to y-axis:_ 
![1  All data bound to y](https://user-images.githubusercontent.com/42860868/73829489-51a39c00-4803-11ea-9fb3-c3f21bf802be.png)

For setting the domain of y2-axis you have to bind atleast one data column to y2-axis.
_'data3' bound to y2-axis:_ 
![2  One data bound to y2](https://user-images.githubusercontent.com/42860868/73829657-a515ea00-4803-11ea-9654-7b1e058a7378.png)

For the case of showing the both y- and y2-axis and not binding data to one of them, it would be great if it would clone the domain of the opposite y-axis per default. 

It would look like this:
_All columns bound to y-axis:_ 
![3  All data bound to y](https://user-images.githubusercontent.com/42860868/73830707-684af280-4805-11ea-9e9c-d788539ac2a0.png)

_'data3' bound to y2-axis:_ 
![4  One data bound to y2](https://user-images.githubusercontent.com/42860868/73830722-6e40d380-4805-11ea-9956-9c694ee5f457.png)

It can be achieved by changing following code in **domain.js**:

```
97	if (yTargets.length === 0) { // use current domain if target of axisId is none
98		return $$[axisId].domain();
99	}

change to

97	if (yTargets.length === 0) { // use current domain if target of axisId is none
98		return axisId === "y2" ? $$.y.domain() : $$.getYDomain(targets, "y2", false);
99	}
```
Is there anything against implementing this in billboard?

## Steps to check or reproduce
1. Open [CategoryAxis Example](https://naver.github.io/billboard.js/demo/#Axis.CategoryAxis)
2. Use the code below.

Example code:
```
var chart = bb.generate({
  data: {
    columns: [
		['data1', -1000, -750, -500, -250, 0, 250, 500, 750, 1000],
		['data2', -250, 0, 250, 0, -250, 0, 250, 0, -250],
		['data3', 100, 75, 50, 25, 0, -25, -50, -75, -100]
    ],
	axes: {
		data1: 'y',
		data2: 'y',
		data3: 'y'
	}
  },
  axis: {
    x: {
      type: "category",
      categories: [
        "cat1",
        "cat2",
        "cat3",
        "cat4",
        "cat5",
        "cat6",
        "cat7",
        "cat8",
        "cat9"
      ]
    },
	y2: {
		show: true
	}
  },
  bindto: "#categoryAxis"
});
```

**Comment by netil** [comment]
Hi @michkami, thanks for the suggestion and it sounds reasonable.
Is changing default behavior which will affect those are using as is, but there's no meaning showing y2 Axis without correlating with the data bound.

Can you send PR for this? And don't forget adding changes to API doc.
