### ISSUE TITLE
Is there are ways to control DOM when being resized?

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1235]
## Description
I'm trying to delete some nodes when chart is resized.
When I tried it using onresized(ctx) {}
ex: 
```js
onresized(ctx) {
  for (let texts of ctx.$.text.texts._groups) {
        let textIndex = 0;
        for (let text of texts) {
          // remove all texts in texts._groups
          text.remove();
        }
  }
}
```
It's not work. 
Any ideas?

**Comment by netil** [comment]
@qkreltms, is because when chart is resized, `redraw` process is called. Redraw is the process to redraw chart elements based on the chart bound element size, because it needs to be adjusted as is.

So, even you remove text nodes manually, within the redraw process, it will redraw again which will end up adding again in your case.

In this case, try updating your config to not show data label texts. Do:

```js
onresized: function(ctx) {
	ctx.config("data.labels", false);
}
```

**Comment by qkreltms** [comment]
@netil than regenerate the chart is the best way if I delete some texts not all of texts when "resized()"?

I also tried, but failed:
```js
let timer: any = null;
// ...

onresized() {
  const time = 1000;

      if (timer) {
        clearTimeout(timer);
      }

      console.log("timer: " + timer);
      timer = setTimeout(function() {

      for (let texts of ctx.$.text.texts._groups) {
          let textIndex = 0;
          for (let text of texts) {
            // remove all texts in texts._groups
            text.remove();
          }
       }

      }, time);
}
```

**Comment by qkreltms** [comment]
What I tried is when resize() is called then set isResize = true, when resized() is called then set isResize = false, when isResize is true then regenerate the chart.

```js
    let isResize: boolean = false;
    const options = {
      //...
         onresize(ctx) {
            if (isResize) {
              const time = 100;

            if (this.timer) {
              clearTimeout(this.timer);
            }

            this.timer = setTimeout(() => {
             // regenerate the chart
             // bb.generate({ ... });
              this.renderChart();
            }, time);
    }
       },
        onresized(ctx) {
         setIsResize(false);
       },
       //...
    }
```

**Comment by netil** [comment]
@qkreltms, I don't know what's the purpose on doing this, but rather than removing from tree, try handling the visibility.

```js
  onresized: function(ctx) {
    ctx.$.text.texts.each(function(d, i) {
      if (i > 0) {
        this.style.display = "none";
      }

      console.log(this, d, i);
    });
  },
```
