### ISSUE TITLE
Demo: Wrong x axis length when scrollbar is shown

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1237]
## Description
If the "_Sample code_" area is longer than the window it will display the scrollbar on the right side of the body.
Iin this case the "_Sample code_" area is initialized after the chart which means that the scrollbar will be rendered after the chart calculated x axis length.
The problem here is that `$$.currentWidth` is set at the time when the scrollbar **is not** shown which will result in wrong `$$.currentWidth` calculation. After first resize of the chart it will calculate the width properly.
This bug cost me some of my time because I thought my code was wrong as I was testing it in my local demo samples.

## Steps to check or reproduce
1. Open [this example](https://naver.github.io/billboard.js/demo/#Axis.AxisLabelPosition).
2. Click on "sample1" in the legend to hide one column.
3. Compare the x axis length before and after hiding "sample1" (should be about 17 pixel difference on Chrome and Firefox).
4. Add `body { overflow-y: scroll;}` to "billboard.scss" and go to step 1.

**Comment by netil** [comment]
Thanks @michkami, for the details!
Updated demo page, making `y scrollbars` to appears.
