### ISSUE TITLE
Tooltip is out of the screen after change orientation

### ISSUE THREAD

**Issue by softage0** [naver/billboard.js#1239]
## Description
Tooltip is out of the screen after change orientation.

## Steps to check or reproduce
On a mobile device landscape orientation, tab the most right item and change to portrait orientation,
and the tooltip left outside of the chart.

Please see the below screen capture:
![RPReplay_Final1581993086](https://user-images.githubusercontent.com/7719707/74698809-67bd4d80-5242-11ea-8ad1-96442b0e3fb8.gif)

**Comment by netil** [comment]
Hi @softage0, thanks for the report. I'll check that.

**Comment by netil** [comment]
@softage0, you can implement using `tooltip.onshown` option, updating tooltip's position unit as `%`.

```js
  tooltip: {
	  doNotHide: true,
	  onshown: function(ctx) {
		const tooltip = ctx.$.tooltip;

		if (tooltip.style("display") === "block" && tooltip.style("top").indexOf("%") === -1) {
			["top", "left"].forEach(v => {
				const size = ctx.internal[v === "top" ? "currentHeight" : "currentWidth"];

				tooltip.style(v, `${parseInt(tooltip.style(v)) / size * 100}%`);
			});
		}
	  }
  },
```

To facilitate this, it would useful implement new `tooltip.position.unit` option.

**Comment by softage0** [comment]
It looks it doesn't work on the latest release version which is `1.12.0-next.2`.
And `tooltip.position.unit` doesn't be supported yet, so I will wait for the next release.

**Comment by netil** [comment]
@softage0, just released `next.3`. Try testing installing `npm i billboard.js@next`

**Comment by softage0** [comment]
Thanks @netil ,
It mostly solves the problem.
But it shows some type errors with TypeScript, so I asked PR for that: https://github.com/naver/billboard.js/pull/1247

And this is trivial, but the tooltip still looks little different after change orientation.
FYI, I left screenshots:

### original
![IMG_9142](https://user-images.githubusercontent.com/7719707/75003039-cdf7d980-54a9-11ea-9351-4a925d9567f1.PNG)

### after change orientation
![IMG_9141](https://user-images.githubusercontent.com/7719707/75003062-df40e600-54a9-11ea-9acd-4a5640684450.PNG)

**Comment by netil** [comment]
@softage0, to make this feature as default, removed the new `tooltip.position.unit` option implemented to solve this issue.
Instead of approaching using some option, applied an internal logic to determine tooltip's position as percentage without the necessity of setting any option.

![tooltip-orientation](https://user-images.githubusercontent.com/2178435/75230266-af217c00-57f6-11ea-990b-3ffd9b5cf4fc.gif)

**Comment by softage0** [comment]
@netil Sounds good!
Do you have any plan to release this feature?

**Comment by netil** [comment]
The feature is already implemented. Official release will be out next month.
Before the official, I'll be releasing RC(@next) version.
- https://github.com/naver/billboard.js/wiki/Release-workflow#minor

Also, you can try with the `nightly` for the test.
- https://github.com/naver/billboard.js#nightly-version

**Comment by softage0** [comment]
Thanks @netil,
I will update it after release.

By the way, after the nightly version applied, there is still a trivial UI bug which a guideline doesn't show after change orientation.

### initial
![initial](https://user-images.githubusercontent.com/7719707/75750083-b43a7a00-5d66-11ea-9797-f230b30eeca3.png)

### after change orientation
![after-change](https://user-images.githubusercontent.com/7719707/75750106-be5c7880-5d66-11ea-8fbc-fd9d56effa82.png)

**Comment by softage0** [comment]
@netil 
After updating the official release, minor guideline bug is also gone.
Thanks for your help.
