### ISSUE TITLE
Type for this in tooltip callback functions

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1246]
Currently, the tooltip callback functions (`contents` and `position`, maybe others as I haven't checked other function options) are called with `this` set to the chart object. I'm not sure whether this is an intended API or a side-effect of the implementation of the default callback. But the typescript types don't describe that, which lead typescript to complain when using `this` (as it thinks `this` will be the `options.tooltip` object where the callback is defined, and so does not have the same properties).

**Comment by stof** [comment]
Looking at it further, `this` is not actually the `Chart` object, but the `ChartInternal` object. So this may not be an intended API but an accidental one.

**Comment by netil** [comment]
@stof, is not intended. These are kind of a "legacy" code since the fork. I let them "as is", to not break 
 possible compatibility that users might have.

Probably it should be re-organized to be run in its own instance context in the next major release.

**Comment by stof** [comment]
If this is not intended, next major version should probably change the call `fn.call($$, ...)` to `fn(...)` indeed.
And then, not having the ChartInternal as `this` type in the typescript types already provides a warning that they should not rely on it. I'll look at my own code to avoid using `this` in thee places.
