### ISSUE TITLE
chart.data has incorrect TS definitions

### ISSUE THREAD

**Issue by ECrownofFire** [naver/billboard.js#1248]
## Description
The [TS definition file](https://github.com/naver/billboard.js/blob/395a604489e4474c013779643153fcea7a17b6e0/types/chart.d.ts#L127) for `data.shown()` has an incorrect type definition, it should be `DataArray` and not `Data`.

The same seems to be true of the function call as well.

## Steps to check or reproduce
N/A

**Comment by netil** [comment]
Hi @ECrownofFire, thanks for the report. I also fixed other `.data()` APIs return type.
