### ISSUE TITLE
Should remove events when chart.destroy is called

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1257]
## Description
I had done some async logics in onresize, onresized and I've found some memory leaks in some situations and found that onresize and onresized events is attached on ```window.addEventListener("resize", ...)``` in [here](https://github.com/naver/billboard.js/blob/master/src/internals/ChartInternal.js#L1139-L1158).

As a result of this, why don't you delete events using ```removeEventListener()``` when ```chart.destroy()``` is called?

**Comment by netil** [comment]
@qkreltms, is already implemented.
- https://github.com/naver/billboard.js/blob/master/src/api/api.chart.js#L97

All the resize releated event options are controlled from internal `resizeFunction` object. So, in normal circumstances calling `.destroy()` will be detached.

If you have some reproducible code or example, it would be appreciated :)

**Comment by qkreltms** [comment]
I think it's related ```reac.js```

[![Edit billboardjs resize onresize bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/billboardjs-resize-onresize-bug-28fvz?fontsize=14&hidenavigation=1&theme=dark)

![ezgif-3-154a1434245f](https://user-images.githubusercontent.com/25196026/75505935-eb83f080-5a1f-11ea-8bea-5a35952d105c.gif)
