### ISSUE TITLE
[Suggestion] show chart lines up on the axis lines

### ISSUE THREAD

**Issue by softage0** [naver/billboard.js#1258]
## Description

show chart lines upon the axis lines

## Steps to check or reproduce

<img width="360" alt="Screen Shot 2020-02-27 at 1 48 17 PM" src="https://user-images.githubusercontent.com/7719707/75413201-49ed9800-5968-11ea-9ac3-c412171a793e.png">
If chart lines and axis lines are overlapped, chart point is covered by axis line.
It would look better if the chart point shows up on the axis line.

**Comment by netil** [comment]
Hi @softage0, you can use [`clipPath`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.clipPath) option for that.

Checkout the demo: 
- https://naver.github.io/billboard.js/demo/#ChartOptions.clipPath

**Comment by softage0** [comment]
@netil Thank you so much. It just works as expected. :)
