### ISSUE TITLE
data.sort: null not work in bar chart.

### ISSUE THREAD

**Issue by insight1111** [naver/billboard.js#127]
## Description

In bar chart, only data.order:null not work.
sample,
[https://codepen.io/insight1111/pen/WEggyG](https://codepen.io/insight1111/pen/WEggyG)

order: 'desc' and order: 'asc' is work.
And, C3.js is work above code.

**Comment by netil** [comment]
thank @insight1111 for the issue. I'll look for that.

**Comment by netil** [comment]
I don't see any issue on data ordering.
- https://codepen.io/netil/pen/NvOPJR
![image](https://user-images.githubusercontent.com/2178435/29757609-19bf1154-8be8-11e7-800a-301297973a81.png)

As API description says, `changes the order of stacking the data and pieces of pie/donut`. Also, the demo you provided the order option value null is quoted, which the correct way is not quoting `null`.
```js
// valid order value
"order":  "asc", "desc" or null 
```

If is still not working in your case, provide a working demo for the check.

**Comment by insight1111** [comment]
thank you for answer and show your code, @netil.
Sorry, my explanation was not enough. I want order tooltip that displayed when hover chart in non-stacked bar chart.
please try delete `groups:` block from your code, and hover chart to show tooltip.
tooltip's order isn't influence `order` property.
But it's works properly in stacked chart. Only non-stacked chart has above behavior.

**Comment by netil** [comment]
@insight1111 okay, isn't about data ordering, it's about tooltip ordering.

**Comment by netil** [comment]
There's ambiguity implementing this. To be clear on ordering, tooltip & data shouldn't be attached.
Making tooltip order option will be more consistent and clear.

```js
tooltip : {
    order: ["asc" | "desc" | null]
}
```

**Comment by insight1111** [comment]
thank you, netil!
I think it's more cleary approach.
