### ISSUE TITLE
X axis label position overlaps with rotated tick label

### ISSUE THREAD

**Issue by LeonardAB** [naver/billboard.js#1270]
## Description

When the tick labels are rotated, they take more spaces vertically. The position of the x axis label is not adjusted to this, thus overlaps with the tick labels. Adding `padding.bottom` does not solve the problem because padding is added below the axis label, not below the tick labels.

![image](https://user-images.githubusercontent.com/14308605/75841332-d1c41e00-5e10-11ea-92fa-e5fcbd573e87.png)

## Steps to check or reproduce

https://jsfiddle.net/phy9jL78/1/

**Comment by michkami** [comment]
It seems like adding a check for `axis_x_tick_rotate` in `dyForXAxisLabel()` in 'Axis.js' line [445](https://github.com/naver/billboard.js/blob/master/src/axis/Axis.js#L445) to the code at the bottom resolves this issue. 
I have not tested it for any edge cases, so maybe @netil knows a better solution.

without legend
![Screenshot_2020-03-04 billboard js - examples(1)](https://user-images.githubusercontent.com/42860868/75885382-b532e080-5e26-11ea-9ae7-cc23a6a46a95.png)

with legend
![Screenshot_2020-03-04 billboard js - examples(2)](https://user-images.githubusercontent.com/42860868/75885378-b2d08680-5e26-11ea-87b4-7edd10949155.png)

``` javascript
dyForXAxisLabel() {
	const $$ = this.owner;
	const config = $$.config;
	const isInner = this.getXAxisLabelPosition().isInner;
	const xHeight = config.axis_x_height;

	if (config.axis_rotated) {
		return isInner ? "1.2em" : -25 - this.getMaxTickWidth("x");
	} else if (config.axis_x_tick_rotate) {
		return $$.getHorizontalAxisHeight("x") - 10;
	} else if (isInner) {
		return "-0.5em";
	} else if (xHeight) {
		return xHeight - 10;
	} else {
		return "3em";
	}
}
```

**Comment by netil** [comment]
@LeonardAB, thanks for the report.
@michkami, thanks for the catch up~!
