### ISSUE TITLE
`title` is not a parameter of `ChartOptions`

### ISSUE THREAD

**Issue by kchoworks** [naver/billboard.js#1275]
## Description

I can't put a title in a chart in the **Angular development environment**. If you uncomment the commented part in `app.component.ts` in the sample link below, you will get an error that `title` is not a parameter of `ChartOptions`.

## Steps to check or reproduce

Please check the example below.
[sample](https://stackblitz.com/edit/angular-rvimeh?file=src%2Fapp%2Fapp.component.ts)

**Comment by netil** [comment]
@kchoworks thanks for the report!
Just added the missing 'title' definition.
