### ISSUE TITLE
Too bloated DOM with empty/hidden SVG elements

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#1288]
## Description

Library generates too many redundant DOM elements with no use. Drawing many charts on one page can potentially slow down entire page due to the heavy object model.

## Steps to check or reproduce

Open https://naver.github.io/billboard.js/demo/#Chart.DonutChart example, inspect the Donut SVG element. 

There are elements like ``<g class="bb-chart-bars">`` and ``<g class="bb-chart-lines">`` , and others, which has nothing to do with original Donut I believe. These should not be polluted into DOM if they are not in use.

**Comment by netil** [comment]
Hi @creage, the issue will be solved as part of `v2`
Try the early v2 build, where you can find unnecessary DOM generation.
- https://github.com/naver/billboard.js/tree/v2/dist

**Comment by netil** [comment]
@creage, just released first RC of `v2.

Using v2, will get reduced node generation in a range of `4 ~ 50%`.
Checkout the [changelog](https://github.com/naver/billboard.js/blob/next/CHANGELOG-v2.md#reduced-node-generation) for more details.

**Comment by netil** [comment]
Ref. #36
