### ISSUE TITLE
how can I fix y axis value?

### ISSUE THREAD

**Issue by ohrory218** [naver/billboard.js#1291]
## Description
I try to set y axis's min value at 0, max at 20.
And I want to show these axis value on the chart exactly in the same way as I tried to set. not -2 or 22
but it seems like calculating these values automatically.
how can I fix this?

## Steps to check or reproduce

![image](https://user-images.githubusercontent.com/54361848/77298170-d7d15e80-6d2d-11ea-9d5e-0b7a2efc842f.png)

**Comment by netil** [comment]
Hi @ohrory218, is because of padding value given to the bottom and top. If there's no padding bottom, the line will be rendered sticked to the bottom x Axis line.

If you don't want to be padded, set padding values to 0. Checkout the example I made.
- https://jsfiddle.net/netil/xt3pv5ao/

**Comment by ohrory218** [comment]
thanks a lot!
