### ISSUE TITLE
Bar chart : onover on every bar

### ISSUE THREAD

**Issue by ugoQ** [naver/billboard.js#1293]
It looks like a strange behavior to me :
On a bar chart with multiple "columns", the data.onclick event gives me the exact bar on which I clicked, but the data.onover gives me every bar of the tick/day, like if the onover was triggered for every bar at once...
Is it possible to have the same behavior as for onclick ? I don't use the tooltips if that can be of any help.

You can try and reproduce the "issue" on the examples here : https://naver.github.io/billboard.js/demo/#Chart.BarChart

And you add the onover on the code :

```
var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 100, 140, 200, 150, 50]
    ],
    type: "bar",
    onover: function(d) {
       console.log(d);
    }
  },
  bar: {
    width: {
      ratio: 0.5
    }
  },
  bindto: "#barChart"
});
```

Thanks in advance for any advice or tip !

**Comment by ugoQ** [comment]
My goal is to display a different cursor for each bar with onover, and/or maybe a custom tooltip for each bar...

**Comment by netil** [comment]
Hi @ugoQ, try with below options.

```js
onover: function(d) {
    // use 'd.id' to distinguish and implement different behavior for each data
    if (d.id === "data1") {
	console.log(1);       
    } else {
	console.log(2);
       }
    }
},
tooltip: {
    // using this option, will make displaying tooltip separately
    grouped: false
},
```

**Comment by ugoQ** [comment]
I feel dumb, I never saw this "grouped" option for tooltip... I discovered it just after posting this issue...
I am using it with some customization and it works great thanks !

However for this onover thing I am still not able to know which bar I am hovering, when I hover one bar in a group of bars, onover is called for each bars all at once.
Maybe I'll just give up with my cursor idea it's not a big deal !

Many thanks for your help.

**Comment by netil** [comment]
@ugoQ, `data.onover` works for entire data series for same x Axis datas.

If you need to update cursor depend the data, try this:

<img src=https://user-images.githubusercontent.com/2178435/77628594-9b02a300-6f8b-11ea-8d37-1d9f153c9901.gif width=250>

```js
  tooltip: {
    grouped: false,
    onshown: function(ctx, d) {
        let cursor = null;

        if (d.length === 1) {
            if (d[0].id === "data1") {
                cursor = "zoom-in";
            } else {
                cursor = "zoom-out";
            } 

            ctx.$.chart.style("cursor", cursor);
        }
    },
    onhidden: function(ctx) {
        ctx.$.chart.style("cursor", null);
    }
  },
```

**Comment by ugoQ** [comment]
Many thanks for your help !
