### ISSUE TITLE
Using column data names as x axis category

### ISSUE THREAD

**Issue by CAWeissen** [naver/billboard.js#1294]
## Description
I have a dataset that looks like this:
`columns: [
    ["Category 1", 25],
    ["Category 2", 20],
    ["Category 3", 17],
    ["Category 4", 38]
],`

I'd like to be able to use the name on each dataset defined in `columns` as the category on the x-axis of a chart. I also want to keep the label showing the value on the right side of the bar. I've found a way to do it, but the data structure is pretty complicated. Is there a way to keep the `columns` data simple without using `null` to skip groups, as in my example below?

![Screen Shot 2020-03-25 at 1 55 29 PM](https://user-images.githubusercontent.com/1842622/77576286-57d10300-6eab-11ea-8a26-ba38bf2f181d.png)

## Steps to check or reproduce
Here's a CodePen showing what is needed to accomplish this, which I find very bloated:
https://codepen.io/CAWeissen/pen/dyoQGdw

**Comment by netil** [comment]
Hi @CAWeissen, try like this way.

```js
bb.generate({
    axis: {
        rotated: true,
        x: {
            type: "category",
            categories: ["Category 1", "Category 2", "Category 3", "Category 4"]
        },
        y: {
            show: false
        }
    },    
    data: {
        columns: [
            ["data", 25, 20, 17, 38]
        ],
        color: function(color, d) {
            // specify colors patterns as array
            return ["red", "green", "blue", "grey"][d.x];
        },
        labels: true,
        type: "bar"
    }
});
```

**Comment by CAWeissen** [comment]
@netil That works perfectly, thank you for your help!
