### ISSUE TITLE
bug(arc): label threshold not working properly for Pie and Donut

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1298]
## Description
By setting `label_threshold` for pie or donut it rerenders wrong texts after hiding columns.
As you can see in the example below (dame config as at the bottom of this issue), it shows `25.0%` on `data1`, which shouldn't be there, as the threshold is set to `0.2` and `data1`'s value is 10.
![bug](https://user-images.githubusercontent.com/42860868/78114428-8dbd3c80-7401-11ea-8b63-e83b988cf936.gif)

This is how it should look like:
![fix](https://user-images.githubusercontent.com/42860868/78114430-8eee6980-7401-11ea-96cb-abfed5841048.gif)

It seems like changing [this](https://github.com/naver/billboard.js/blob/master/src/shape/arc.js#L287) condition to:
```typescript
const text = isUnderThreshold ?
	($$.getArcLabelFormat() || $$.defaultArcValueFormat)(value, ratio, id).toString() :
	"";

setTextValue(node, text, [-1, 1], hasGauge);
```
will fix the problem, as it will replace the text with `value < threshold` with an empty string.

## Steps to check or reproduce
1. Open [this chart](https://naver.github.io/billboard.js/demo/#Chart.PieChart)
2. Use following code:
```javascript
var chart = bb.generate({
  data: {
    columns: [
	["data1", 10],
	["data2", 30],
	["data3", 60]
    ],
    type: "pie"
  },
  pie: {
	label:{
		threshold: 0.2
	}
  },
  bindto: "#pieChart"
});
```
3. Hide `data3`.
4. Show `data3`

**Comment by netil** [comment]
@michkami, thanks for the report!
I'll check that.
