### ISSUE TITLE
`area.zerobased: false` and `linearGradient`

### ISSUE THREAD

**Issue by davidhund** [naver/billboard.js#1302]
## Description
I have an `area-spline` chart with points between values between 1536 - 2047.
`area.zerobased` is set to `false` to maximize the visualization. `area.linearGradient` is set to `true`.

Now there is no visible gradient, because the `bb-area` is too large (and extents below the actual chart) so one only sees the top-part of the gradient (which looks like solid color).

![zerobased is false](https://user-images.githubusercontent.com/260518/78231705-81a1af80-74d3-11ea-924e-6c0e0bf78ed6.png)

When setting `area.zerobased: true` the gradient is fine:

![zerobased is true](https://user-images.githubusercontent.com/260518/78231717-836b7300-74d3-11ea-96fd-84f6052f80df.png)

My guess is that the `bb-area` should be resized to be vertically smaller (less high) so that the bottom of the gradient aligns properly with the bottom of the chart. E.g. the `zoom-rect` and  `event-rect` elements are sized correctly.

See how the `bb-area` is too high: 
![too high](https://user-images.githubusercontent.com/260518/78232177-27551e80-74d4-11ea-9b03-cb2522bf4e06.png)

**Comment by netil** [comment]
Hi @davidhund, thanks for the report!

Actually isn't a bug, but in this circumstances can be.
The shapes(not only for area, also for bar), will be drawn from the 0 even y Axis min is set. Is because to handle cases like rendering grouped(stacked) shapes.

I'll try fix for non-grouped shape rendering to not surpass x Axis range.

**Comment by davidhund** [comment]
Hello @netil - Thank you for picking this up so quickly!

I am using v1.12.2 now but see no difference in my charts.
Are you sure this fixes it for _vertical_ gradients too?

I guess the issue is that the last `linearGradient` `y` stop should be on the _rendered_ bottom of the chart area, not on the `0` position?

**Comment by netil** [comment]
@davidhund, I tested with below options.

```js
bb.generate({
	data: {
		columns: [
			["data1", 3000, 2000, 2000]
		],
		type: "area"
	},
	axis: {
		y: {
			min: 1000,
			padding: {
				bottom: 0
			}
		}
	},
	area: {
		linearGradient: true
	}
});
```
And as you can see the difference from the previous version. 
Provide full generation option, if has no changes from the new release.

- Left: `1.12.2` / Right: `1.12.1`
![image](https://user-images.githubusercontent.com/2178435/78357149-e3edd380-75eb-11ea-9246-d2ce11cdd38c.png)

![image](https://user-images.githubusercontent.com/2178435/78357061-b2750800-75eb-11ea-884a-cd64dcd45b68.png)
