### ISSUE TITLE
Charts are broken on mobile when no x focus grid is shown

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1306]
## Description
The code at https://github.com/naver/billboard.js/blob/01ba388477367c4c1bf7a52083331abbec34b136/src/internals/grid.js#L389 calls `.datum()` on a d3 selection, while this selection can be empty. Calling this method on an empty selection triggers a TypeError by accessing a property on `null`.

## Steps to check or reproduce

This happens when `grid.focus.show` is set to `false` in options of a line chart. It only affects touch devices.

**Comment by stof** [comment]
I'm using version 1.12.1

**Comment by netil** [comment]
@stof thanks for the report.
