### ISSUE TITLE
bug(shape): incorrect rendering of bar/area

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1316]
## Description
As for now it is necessary to set `axis_y/y2_min` if `zerobased` is false, because without setting `axis_y/y2_min` it would render the area/gradient the way like it was before the changes in https://github.com/naver/billboard.js/commit/a47a8290b59c579610ba1ffdd4a3916a8f975a71.
This changes seem to negatively affect the rendering of the area/bar columns.

The code in the jsfiddle example below renders the chart like this:
![wrong](https://user-images.githubusercontent.com/42860868/78898085-81755700-7a73-11ea-96e9-1330100983f9.png)

`data1` is bound to y-axis and `data2` is bound to y2-axis.
`axis_y/y2_min` is set to -1000 and `axis_y/y2_max` is set to 1000.

Before the commit the chart would be rendered like this:
![right](https://user-images.githubusercontent.com/42860868/78898586-55a6a100-7a74-11ea-9a3b-49b7380fdbb8.png)

As you can see in the first picture, it doesn't really make sense to render the bars from `axis_y2_min` to the value of the column. It should render like in the second picture from 0 to the value of the column.
In this case, it should always start rendering area/bar from 0 to the column value.

I modified your example from https://github.com/naver/billboard.js/issues/1302#issuecomment-608390067 in `[this](https://jsfiddle.net/michkami/don7bqts/)` fiddle, and as you can see, it starts to draw the area from `axis_y_min` to the value of the column, which is wrong in my opinion.

Woultn't it make more sense to make the rendering of the area/bar independent from `axis_y/y2_min`?
If `zerobased` is true, it works properly, as long as `axis_y/y2_min` is not set. If `zerobased` is false, wouldn't it be possible to scale the column values from the rendered `axis_y/y2_min` and `axis_y/y2_max`?
Like in this example from 1900 to 3000.
![example1](https://user-images.githubusercontent.com/42860868/78905331-1ed58880-7a7e-11ea-8a2d-d8b29a582489.png)

## Steps to check or reproduce
https://jsfiddle.net/michkami/L05avd9c/

**Comment by netil** [comment]
Thanks for the report. Side-effect caused by #1304 and needs to be reverted.
