### ISSUE TITLE
bug(shape): Incorrect rendering of stacked area charts

### ISSUE THREAD

**Issue by LucasMontero** [naver/billboard.js#1326]
## Description
White rectangles appear on areas group while the data that should be there is displayed at the top of the area.

As you can see in the following gif, The data doesn't change but you can see how it is being displayed wrongly

![report](https://user-images.githubusercontent.com/7733283/79239327-bc5efc80-7e70-11ea-9c26-663d7718619e.gif)

## Steps to check or reproduce
https://stackblitz.com/edit/l5a3qv?file=index.ts

**Comment by netil** [comment]
Hi @LucasMontero, thanks for the report.

**Comment by netil** [comment]
Is a side-effect caused by https://github.com/naver/billboard.js/commit/23ab7a6.
