### ISSUE TITLE
bug(gauge): 'getTranslation' not working in IE and Edge

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1329]
## Description
On mouseover alle gauge value texts disappear as yo can see here:
![bug](https://user-images.githubusercontent.com/42860868/79430579-6d78aa80-7fc9-11ea-8ccb-c69769665ef8.gif)

How it should look like:
![fix](https://user-images.githubusercontent.com/42860868/79430581-6e114100-7fc9-11ea-8739-d28edf921d00.gif)

Both gifs are taken in Microsoft Edge:
- Microsoft Edge 44.18362.449.0
- Microsoft EdgeHTML 18.18363

Same behaviour in IE11:
- Version: 11.592.18362.0
- Update version: 11.0.170 (KB4534251)

As the `length` property is not standardized ([more info at MDN](https://developer.mozilla.org/en-US/docs/Web/API/SVGTransformList)),  [getTranslation](https://github.com/naver/billboard.js/blob/master/src/internals/util.js#L233) should use `baseVal.numberOfItems` instead of `baseVal.length`.
In this case the funcion could be also refactored from
```javascript
/**
 * Gets the SVGMatrix of an SVGElement
 * @param {SVGElement} element
 * @return {SVGMatrix} matrix
 * @private
 */
const getTranslation = node => {
	const transform = node ? node.transform : null;
	const baseVal = transform ? transform.baseVal : [];

	return baseVal.length ? baseVal.getItem(0).matrix : {a: 0, b: 0, c: 0, d: 0, e: 0, f: 0};
};
```
to
```javascript
/**
 * Gets the SVGMatrix of an SVGGElement
 * @param {SVGGraphicsElement} node
 * @return {SVGMatrix} matrix
 * @private
 */
const getTranslation = node => {
	const transform = node ? node.transform : null;
	const baseVal = transform && transform.baseVal;

	return baseVal && baseVal.numberOfItems ?
		baseVal.getItem(0).matrix :
		{a: 0, b: 0, c: 0, d: 0, e: 0, f: 0};
};
```

Should I make a pull request?

## Steps to check or reproduce
1. Open [MultiArcGauge](https://naver.github.io/billboard.js/demo/#GaugeChartOptions.GaugeTypeMulti) in IE or Edge.
2. Hover over any column.

**Comment by netil** [comment]
@michkami, please if you can. :)
