### ISSUE TITLE
Add an event handler for clicking anywhere inside a chart

### ISSUE THREAD

**Issue by danbai02** [naver/billboard.js#1330]
## Description
I would like to use the 'drag' zoom type with the reset button hidden and be able to zoom back out of the chart when the area containing chart data is clicked. Adding an event handler for when the inside of a chart is clicked would make this possible.

**Comment by netil** [comment]
you can attach click event handler manually.

```js
  onafterinit: function(ctx) {
	ctx.$.main.on("click", function() {
	    chart.unzoom();
	});
  }
```

**Comment by danbai02** [comment]
Thank you, that's really helpful!
