### ISSUE TITLE
css applied in onrendered function is un-applied when data series is toggled

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#1343]
## Description
CSS that is applied from within the onrendered function gets partially reset/overwritten when a data series is toggled visible/not visible.

As far as i can tell its affecting the fill property specifically

This isn't happening in v1.11

## Steps to check or reproduce
If you toggle a series using the legend, the circle fill gets reset. Resizing the chart makes the correct css get reapplied
https://jsfiddle.net/irislieuw/uhfsr1wc/
https://www.loom.com/share/72036222f0ae4c0294547342c77dcb4b

**Comment by netil** [comment]
@irislieuw, style data points using css class instead of node handling.
And the use of `onrendered` isn't good option here, because it is called on every rendering occasions like resize, toggle, etc.

```css
.bb-circle-3 {
	opacity: 1;
	stroke-width: 0.3%;
	stroke-dasharray: 0.04%, 0.45%;
	stroke-linecap: round;
	fill: white !important;
}
```
```js
var chart = bb.generate({
  data: {
    columns: [
		["hello there", 230, 280, 251, 400, 150, 546, 158],
		["hellogoodbye", 130, 357, 151, 400, 250, 250, 395],
		["billboard rules", 330, 280, 320, 218, 450, 150, 500],
		["data series name", 300, 310, 500, 201, 510, 125, 445],
		["data-series-name", 100, 180, 130, 140, 102, 160, 300],
		["data%series%name", 300, 80, 10, 150, 106, 130, 330],
		["Test with space", 20, 50, 10, 100, 20, 50, 0],
		["1.test", 130, 220, 120, 129, 410, 100, 440],
    ],
    type: "line",
  },
  point: {
  	r: 0
  },
  onafterinit: function(ctx) {
	ctx.$.line.circles.filter(".bb-circle-3")
		.style("r", "0.8%");
  }
});
```

**Comment by irislieuw** [comment]
@netil unfortunately styling using a css class isn't an option for us - we're using billboard in custom dashboards that dynamically change node styling depending on the data.

Is there any other way to get this to work? It wasn't a problem in previous versions..

This is what we are using this for by the way - to show the optimal point on a curve vs where you're currently at. The colored vs white fill is very effective. 
![image](https://user-images.githubusercontent.com/11950094/80002400-70194b00-8474-11ea-914a-088a2f2cce86.png)

**Comment by netil** [comment]
@irislieuw, the issue was caused by #1276 changes, not being called `onrendered` after the data toggle. (It will be released as patch)

Well... there're different way styling dynamically, but take in consideration that `onrendered` callback is called in every moments when redraw is happening like resize, data toggle, etc.
