### ISSUE TITLE
bug(arc): mouse events are breaking transitions

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1347]
## Description
We have following data structure:
One column can have multiple children, which can also have multiple children and so on.
The value of the parent column is equal to the sum of the children column values.

If you click on column in the chart, it unloads current columns and loads the children columns of the clicked column and so on. We call it "drill down". In the example below you can "drill down" to the third level of children elements.
As you can see here:
![now](https://user-images.githubusercontent.com/42860868/79955531-37cb3a00-847f-11ea-8dde-e733e7e2f643.gif)
If you click on the column, it unloads and loads new columns, but the transition gets interrupted by `mouseover` event and the arc doesn't expand to the full size.
It should look like this (don't worry about the arc not expanding and focusing on mouseover, I disabled `expandArc` and `$$.api.focus()` to be able to show the expected behaviour):
![expected](https://user-images.githubusercontent.com/42860868/79954486-ad360b00-847d-11ea-9f9c-39aaeef54a2a.gif)
It seems like `$$.transiting` doesn't have the right state in [arc.on("mouseover")](https://github.com/naver/billboard.js/blob/master/src/shape/arc.js#L693).
This function also calls [selectArc](https://github.com/naver/billboard.js/blob/master/src/shape/arc.js#L659) which calls `$$.expandArc(id)` and `$$.api.focus(id)` which trigger some transitions that intterupt the transition triggered on redrawing the pie.

## Steps to check or reproduce
1. Open [this example](https://stackblitz.com/edit/piedrilldown?file=index.ts)
2. Click around the center of the pie chart to trigger columns update.
3. Don't move your mouse. It will stop the pie transition.
4. If you resize window or hide the column the chart will redraw to expected size.

**Comment by netil** [comment]
well, if you remove the call of `chart.flush()` will solve the issue, but it will remove the transition effect between the data loads.
```js
function showChildren(chart, columns, dataNameTitles) {
 ...
  done: () => {
      setTimeout(() => {
        chart.flush(true);
      }, 0);
  }
```

If you go through step by step, it flows as:

> click data area &rarr; unload &rarr; 1st pie's transition ends ($$.transiting = false)
> &rarr; mouseover event fired on 2nd pie's element &rarr;  it interfere 2nd pie's transition (because of $$.transiting = false).

**Comment by michkami** [comment]
I already tried without 
```javascript
done: () => {
      setTimeout(() => {
        chart.flush(true);
      }, 0);
  }
```
and it works fine if the legend is positioned at the bottom of the chart.
But if yo position the legend to right side, the chart and the legend don't resize properly if legen item texts are long.
You need to trigger the resize manually, for example by toglling a legend item:
![legend_resize](https://user-images.githubusercontent.com/42860868/80080482-fce60680-8551-11ea-9cc3-e00a6403af6b.gif)

In the end the transition would be nice to have, it would also work without, but there is still the resizing issue, which is the main reason for me using `chart.flush(true)`.

**Comment by netil** [comment]
did you tried `chart.resize()` instead of `.flush()`?

**Comment by michkami** [comment]
> 
> 
> did you tried `chart.resize()` instead of `.flush()`?

Yes, I did. It resize correctly, but the transition from old to new data isn't as smooth as if without `chart.resize()`.
without `chart.resize()`             |  with `chart.resize()`
:-------------------------:|:-------------------------:
![no_resize](https://user-images.githubusercontent.com/42860868/80082647-f0af7880-8554-11ea-9edb-310bdf69c304.gif)  |  ![with_resize](https://user-images.githubusercontent.com/42860868/80082656-f1e0a580-8554-11ea-98af-3d93d5725af0.gif)

As you can see the transition on the left one is much smoother than on the right.

**Comment by netil** [comment]
Is not a clear solution, but this will work as expected on your case. 
I'll be considering if there's an effective solution for this.

```js
 done: () => {
		const {svg} = chart.$;
		const duration = chart.config("transition.duration");

		setTimeout(() => {
			svg.style("pointer-events", "none");
			chart.flush(true);

			setTimeout(() => {
				svg.style("pointer-events", null);
			}, duration);
       }, 0);
    }
```

**Comment by michkami** [comment]
I tested it in our code and it works!
Thank you @netil :)
