### ISSUE TITLE
Log scale in y-axis

### ISSUE THREAD

**Issue by mechswitch** [naver/billboard.js#1351]
## Log scale implementation
Please implement log scale option in y- axis or please suggest if it can be achieved now through any other method.

Its a request.

**Comment by netil** [comment]
Hi @mechswitch, currently there's no explicit log representation for y Axis.
y Axis ticks values are dependent of the data value you set.

**Comment by mechswitch** [comment]
Any chances of including it in near future?

**Comment by netil** [comment]
@mechswitch, yeap. I'll be considering to implement this.

**Comment by RonnyWeiss** [comment]
Would be really cool to have this!

**Comment by netil** [comment]
@mechswitch, @RonnyWeiss released [`2.0.0-next.8`](https://github.com/naver/billboard.js/releases/tag/2.0.0-next.8) with the new "log" type implementation.
