### ISSUE TITLE
Detach the repository from c3js fork.

### ISSUE THREAD

**Issue by fanthos** [naver/billboard.js#136]
## Description
When I am trying search code in this repo, I got this from Github:
`Sorry, forked repositories are not currently searchable.`

According to this link https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork , this repo can be detached from the c3js fork.

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

**Comment by netil** [comment]
@fanthos good suggestion. We'll try taking this into consideration.

**Comment by netil** [comment]
@fanthos done. Repo is now detached.
Thanks for the suggestion again!
