### ISSUE TITLE
Tooltip for points on right side of chart shifted excessively when chart is centered

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#1362]
## Description
When a chart is centered in a container and doesn't fill up the whole space (for example some kind of aspect ratio is set), the tooltip for the points on the right side of the chart get shifted depending on how much space is on the sides of the chart

![image](https://user-images.githubusercontent.com/11950094/80406197-89f1ce00-8878-11ea-8f03-6e029e88ccef.png)

## Steps to check or reproduce
This fiddle contains an example of this. I'm centering the chart using display: flex, but horizontal centering using margin: 0 auto does the same thing

https://jsfiddle.net/irislieuw/076ftdk4/

https://www.loom.com/share/054b9e68e3f047c8880322ff41c56d3a

**Comment by netil** [comment]
possible side-effect caused by https://github.com/naver/billboard.js/commit/8dba2134da94036437bda48a59aa5fca2dfb1d2e.
