### ISSUE TITLE
bug(area): grouped area is not stacked correctly

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1365]
## Description
As you can see in the gif below, "data3" and "data4" is not stacked correctly even though the texts are positioned correctly.
![bug](https://user-images.githubusercontent.com/42860868/80475285-f20fe500-8948-11ea-8fc2-62596a089c14.gif)

It seems to happen only if there is more than 1 data group. It doesn't matter to which axis the data is bound to.
I tested the example below with 6 data columns, with 3 groups including 2 columns each and the second and third group doesn't stack correctly, only the first one.

It also doesn't matter how many columns a group contains.

_Group1: data1+ data2; Group2: data3-6_
![grafik](https://user-images.githubusercontent.com/42860868/80479100-d3145180-894e-11ea-9cbe-832d9a061ae0.png)

## Steps to check or reproduce
1. Open [this example](https://stackblitz.com/edit/stacked-area-bug)
2. Hide "data1" and "data2".

**Comment by netil** [comment]
It seems a side-effect of `v1.7`. It wasn't happening until `v1.6.2`.

**Comment by michkami** [comment]
That was fast.
Thank you @netil :)
