### ISSUE TITLE
Chart is empty if only one data.

### ISSUE THREAD

**Issue by fanthos** [naver/billboard.js#137]
## Description
The chart show no line or point if only one data in dataset.
I have point.show:false in data settings.

If one line have only one data, **draw a circle for the line** even if point.show is false.

## Steps to check or reproduce
https://jsfiddle.net/fanthos/o2rrhh7e/

**Comment by netil** [comment]
Well... this is the perspective differentiation. Agree in some point, in cases which needs to ignore some options, but thinking the purpose of the option, which they're explicitly set by the user, those options should behave as expected.

In most cases we think that in this case, something should be rendered even the option is blocking to render, but how about if the user's intention is to not show anything? We can't figure out the real user's intention correctly.

And this issue can be handled by user changing option value, so behaving differently as options were described isn't good idea.
