### ISSUE TITLE
bug(arc): wrong single arc 'totalSum' calculation 

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1376]
## Description

As you can see in the gif below, the arc angles are not scaled correctly to the `totalSum` value.
![bug](https://user-images.githubusercontent.com/42860868/80814524-58586a00-8bcc-11ea-882f-3c463f3669e7.gif)
This happens because because the hidden targets are ignored in [getTotalDataSum()](https://github.com/naver/billboard.js/blob/50f9fb1dc42d6a7abe34606847bcab0b62784a27/src/data/data.js#L324).

`getTotalDataSum()` is only used in 2 lines ([first line](https://github.com/naver/billboard.js/blob/50f9fb1dc42d6a7abe34606847bcab0b62784a27/src/shape/arc.js#L102) and [second line](https://github.com/naver/billboard.js/blob/50f9fb1dc42d6a7abe34606847bcab0b62784a27/src/data/data.js#L795)).
Second line already subtracts the hidden values form total sum.
![grafik](https://user-images.githubusercontent.com/42860868/80816571-0b769280-8bd0-11ea-8d46-f05634b251f2.png)

Subtracting hidden targets values from `totalSum` seems to be enough to fix this bug.
Alternatively you could remove the caching form `getTotalDataSum()` and make the function calculate the `totalDataSum` of `filteredDataTargets` on every function call.

Changing `getTotalDataSum()` to 
```javascript
getTotalDataSum() {
	const $$ = this;

	return mergeArray($$.filterTargetsToShow($$.data.targets)
		.map(t => t.values))
		.map(v => v.value)
		.reduce((p, c) => p + c);
}
```
(and removing the substraction from [this line](https://github.com/naver/billboard.js/blob/50f9fb1dc42d6a7abe34606847bcab0b62784a27/src/data/data.js#L795)) doesn't seem to have any side affects. Tests are also passing.

Which way to fix do you prefer @netil?
I prepared both variants, so I could make the pull request.

How it should look like:
![fixed](https://user-images.githubusercontent.com/42860868/80814527-59899700-8bcc-11ea-80e7-3ca2848f012b.gif)

## Steps to check or reproduce
1. Open [this example](https://stackblitz.com/edit/bug-gauge-total-sum).

**Comment by netil** [comment]
The current implementation is following the pie's behaves on hidden data. But when is approaching this with the literal meaning of `gauge`, it seems the updated version fits more.

what do you think on this? @michkami, @scholchr

**Comment by michkami** [comment]
What we can definitely say now is that the actual implementation doesn't scale correctly, because as you can see in the first gif above, data1 shouldn't change the percentage as long as maximum stays at 200.

There are minimum and maximum values that the arcs should be scaled to if the legend is enabled.
If the legend would be disabled, the scaling is ok because you can't change the data shown in the chart.
Most of the examples I have seen yet don't have a legend, as they show the minimum, the maximum and the current value. So maybe it should be considered if the legend or hiding data makes any sense in the gauge chart.
On the other hand you could just update the maximum everytime you hide some data, so it would always scale from 0% to 100%.

It should definitely be considered if it makes more sense to just hide the data and move the arcs or change the maximum and always scale from 0% to 100%.

**Comment by netil** [comment]
> as you can see in the first gif above, data1 shouldn't change the percentage as long as maximum stays at 200.

Seems more reasonable displaying data based on that criteria. `gauge` type is for visualizing data to the indicated `max` value, so toggling(hiding) data, shouldn't be affecting remained data's ratio.
