### ISSUE TITLE
Full circle "gauge" chart backgrounds are only half-circles

### ISSUE THREAD

**Issue by djpeterson83** [naver/billboard.js#140]
## Description
When setting a gauge to full circle (`"gauge"."fullCircle" = true`), the background only draws for half the circle (as if `"fullCircle"` were set to `false`).  

Additionally, the labels don't quite make sense for a full circle, but they can be shut off using `"gauge"."label"."show" = false`, so this isn't as big of a deal.

## Steps to check or reproduce
The following HTML document shows two gauges.  The first chart has a value below 50% where you can see the background only renders half the circle, and the second has a value greater than 50% showing the background incorrectly disappearing entirely, but the colored circle renders correctly.  I would expect the background to draw the entire circle in all cases.  Tested on latest Chrome build.
```
<!DOCTYPE html>
<html>
    <head>
        <!-- Load D3.js -->
        <script src="https://d3js.org/d3.v4.min.js"></script>

        <!-- Load billboard.js with style -->
        <script src="billboard.js"></script>
        <link rel="stylesheet" href="billboard.css">
    </head>
    <body>
        <div id="chart1"></div>
        <div id="chart2"></div>
        <script>
            (function(){
                bb.generate({
                "data": {
                  "columns": [
                    ["data", 45]
                  ],
                  "labels": false,
                  "type": "gauge"
                },
                "gauge": {
                    "fullCircle": true,
                    "label": {
                      "show": false
                    }
                },
                "tooltip": function() {},
                "bindto": "#chart1"
              });

              bb.generate({
              "data": {
                "columns": [
                  ["data", 65]
                ],
                "labels": false,
                "type": "gauge"
              },
              "gauge": {
                  "fullCircle": true,
                  "label": {
                    "show": false
                  }
              },
              "tooltip": function() {},
              "bindto": "#chart2"
            });
            })();
        </script>
    </body>
</html>
```

**Comment by netil** [comment]
confirmed the bug.
The expected background will look like as below, right? @djpeterson83 
And also the label text isn't centered.

![image](https://user-images.githubusercontent.com/2178435/30467316-c09d8e4e-9a1e-11e7-9a54-1e06d5e602b9.png)

Try fix before the upcoming release. Thanks for the report.

**Comment by djpeterson83** [comment]
Yep, that's what I would expect.  Thanks for looking into this!
