### ISSUE TITLE
Tooltip is mispositioned on very narrow horizontal bar charts

### ISSUE THREAD

**Issue by rmales** [naver/billboard.js#1400]
## Description
On very narrow horizontal bar charts tooltips are mispositioned (too far left). I think this is due to the calculation that runs when the tooltip right edge position exceeds the chart width:
https://github.com/naver/billboard.js/blob/master/src/internals/tooltip.js#L264-L267

## Steps to check or reproduce
Example: https://jsfiddle.net/9xvs0pca/

**Comment by netil** [comment]
Hi @rmales, thanks for the report.

When tooltip x/y coordinate values set to minus value,  it means that the tooltip is not fully shown.
The current implementation only covers for the y position. I think adding for x will fix the issue.
