### ISSUE TITLE
Label threshold option for stacked charts.

### ISSUE THREAD

**Issue by patrickcate** [naver/billboard.js#1427]
It would be great if the `label.threshold` option was available stacked bar charts as they are for pie charts. I've found that with stacked charts sometimes the "slices" can be too small to fit the data labels.

**Example:**

![Screen Shot 2020-06-01 at 10 34 48 AM](https://user-images.githubusercontent.com/6277206/83473312-3f570900-a457-11ea-817e-a4bd243da99f.png)

**Comment by netil** [comment]
Hi @patrickcate , thanks for the suggestion.

```js
bar: {
    label: {
	threshold: 0.1
    }
}
```

The option is implemented on the next major release v2, and you can you now by installing:
```sh
npm install billboard.js@next
```
