### ISSUE TITLE
add threshold option for gauge labels like it's for pie and donut

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1439]
Hello

For Pie and Donut Charts It's possible to set a threshold when labels should not be shown when they are under threshold. I looked into the code and saw that for Donuts this is not handled.

Could you please add this for donut charts?
```js
gauge: {
     label: {
         threshold: 0.1
   }
};
```
Kind Regards

Ronny

**Comment by netil** [comment]
Hi @RonnyWeiss, thanks for the suggestion.

The option is implemented on the next major release v2, and you can you now by installing:
```sh
npm install billboard.js@next
```

**Comment by RonnyWeiss** [comment]
Thank you for quick answer and adding this feature to v2 release! I will try it quickly! 

Kind regards

Ronny
