### ISSUE TITLE
Different css classes for single and multi gauge

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1440]
Hello

At first thank you very much for this great chart libary!!!!!!

Could you please add a css class which allows different styles e.g. for the text color between single and multi gauges?

In Pie and and Donut Charts the label text are set white by css. But Donuts have black. When using black it works for both single and multi gauge but I want to have white labels when single and black for multi. 

Kind regards

Ronny

**Comment by netil** [comment]
@RonnyWeiss, you can change the color by updating css rule.

```css
.bb-chart-arc .bb-gauge-value {
	fill: red;
}
```

**Comment by RonnyWeiss** [comment]
I Know but I want to Set White like its default for pie and Donut. Problem is in Single gauge, White is ok. But in multi gauge the Labels are outside of the chart, so then I want to Set Black. But I have no difference between the two gauges in css. So it would be cool if you could add an additional class to multi gauges or make generally two Different css classes for gauge types.

Kind regards

Ronny

**Comment by netil** [comment]
`data.labels.colors` option is for that, but I'm seeing that there's a bug for Arc(pie/donut/gauge) types not applying the given option.

I'll be fixing that.

**Comment by RonnyWeiss** [comment]
Cool Thing when we handle it like this. That would be great thank you so I can Set it for All by option and can skip it to Set it by css 👌

**Comment by netil** [comment]
@RonnyWeiss, checkout `v2.0.0-next.4` release.
