### ISSUE TITLE
Missing bottom padding for gauge charts legend

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1441]
Hello

When using Gauges with Legends then therese no padding at the bottom of the legend. The others charts types have the padding at the bottom.

Gauge:
![gauge](https://user-images.githubusercontent.com/30749177/84488085-f8abaf00-ac9f-11ea-87bb-605304b07843.png)

Line:
![line](https://user-images.githubusercontent.com/30749177/84488192-1c6ef500-aca0-11ea-84b0-89d6e3b37d7c.png)

Would be very cool if you could fix that.

Kind regards and a nice weekend

Ronny

**Comment by watnab** [comment]
https://github.com/naver/billboard.js/blob/b929b989c3b440a95b94de022f597d3a1947b480/src/internals/ChartInternal.js#L936-L938

**Comment by michkami** [comment]
> 
> 
> https://github.com/naver/billboard.js/blob/b929b989c3b440a95b94de022f597d3a1947b480/src/internals/ChartInternal.js#L936-L938

This code is my fault. I added it to create a gap between legend and gauge labels, as there was no padding between them.
As far I can see 10 pixel seem to be too much, it should be rather 4 pixel (same as between gauge label and gauge) gap to make it look more symetric.

I actually don't think that the legend is the only problem for the missing padding at the bottom of the chart.
If you remove `+ (hasGauge ? 10 : 0)` there will be bottom padding if the legend is enabled and positioned at the bottom, but if you set `legend_show = false` or/and `gauge_labels_show = false }` gauge still won't have padding at the bottom.

By removing `+ (hasGauge ? 10 : 0)` you can see, that the legend container does not render at the end od the gauge label container but in the middle of them.
![grafik](https://user-images.githubusercontent.com/42860868/85001938-94339880-b154-11ea-9b53-ba765436c105.png)

The reason for this could be that the starting y coordinate for gauge labels is placed in the arc (not outside like you can see in the screenshot below) and is than moved by https://github.com/naver/billboard.js/blob/b929b989c3b440a95b94de022f597d3a1947b480/src/shape/arc.js#L843 to the final position under the arc.
![grafik](https://user-images.githubusercontent.com/42860868/85002871-bd085d80-b155-11ea-9ad9-62420bb443eb.png)

But as I wrote above, adding margin to the legend won't fix the issue for all use cases.

**Comment by watnab** [comment]
It seems `g.bb-chart-arc`(the content of `g.bb-chart`) of the gauge should be a bit smaller.
However I could not find which function calculate the height.
![gauge](https://user-images.githubusercontent.com/36845428/85081352-b4239480-b206-11ea-92cf-b9dc39d82b0c.png)
![donut](https://user-images.githubusercontent.com/36845428/85081353-b4bc2b00-b206-11ea-9e79-e70d0dc34945.png)
![radar](https://user-images.githubusercontent.com/36845428/85081349-b259d100-b206-11ea-8d69-c15843015192.png)
I added the red border to the `svg` element.

**Comment by michkami** [comment]
@watnab gauge height is calculated here:
https://github.com/naver/billboard.js/blob/b929b989c3b440a95b94de022f597d3a1947b480/src/internals/ChartInternal.js#L535-L541

I tried few things and got following results:
Description | Single | Multi
--- | --- | ---
Labels: true && Legend: bottom | ![single-labelsTrue-legendBottom](https://user-images.githubusercontent.com/42860868/85108609-5300be80-b210-11ea-9f0a-f993d56f06a8.png) | ![multi-labelsTrue-legendBottom](https://user-images.githubusercontent.com/42860868/85108639-5c8a2680-b210-11ea-866e-4a225c21efe5.png)
Labels: true && Legend: right | ![single-labelsTrue-legendRight](https://user-images.githubusercontent.com/42860868/85108757-8c392e80-b210-11ea-95e8-932373e4f333.png) | ![multi-labelsTrue-legendRight](https://user-images.githubusercontent.com/42860868/85108765-8f341f00-b210-11ea-96aa-f1357db104c0.png)
Labels: false && Legend: bottom | ![single-labelsFalse-legendBottom](https://user-images.githubusercontent.com/42860868/85108794-9d823b00-b210-11ea-9432-8fc1cee04dc7.png) | ![multi-labelsFalse-legendBottom](https://user-images.githubusercontent.com/42860868/85108786-9b1fe100-b210-11ea-9b8a-75f59d5de68e.png)
Labels: false && Legend: right | ![single-labelsFalse-legendRight](https://user-images.githubusercontent.com/42860868/85108844-b559bf00-b210-11ea-90d5-b595dd71a98d.png) | ![multi-labelsFalse-legendRight](https://user-images.githubusercontent.com/42860868/85108851-b854af80-b210-11ea-816a-8f222883ecc8.png)
Labels: false && Legend: false | ![single-labelsFalse-legendFalse](https://user-images.githubusercontent.com/42860868/85108873-c1458100-b210-11ea-94bd-b8e23c9bf9da.png) | ![multi-labelsFalse-legendFalse](https://user-images.githubusercontent.com/42860868/85108881-c3a7db00-b210-11ea-9f23-1ad1315396b2.png)

I removed `+ (hasGauge ? 10 : 0)` from:
```javascript
} else if (target === "legend") {
	x = $$.margin3.left;
	y = $$.margin3.top;
}
```
I added following function to arc.js:
```javascript
getPaddingBottomForGauge() {
	const $$ = this;
	const defaultGaugeLabelHeight = 20; // value returned by 'getGaugeLabelHeight' if 'label_show: true'
	const legendShow = $$.config.legend_show;
	const gaugeLabelShow = $$.config.gauge_label_show;

	if (legendShow && gaugeLabelShow) {
		return $$.getGaugeLabelHeight() * ($$.isLegendRight ? 1.5 : 1);
	} else if (legendShow && !gaugeLabelShow) {
		return defaultGaugeLabelHeight * 1.5;
	} else if (!legendShow && gaugeLabelShow) {
		return $$.getGaugeLabelHeight() * 1.5;
	} else {
		return defaultGaugeLabelHeight * 1.5;
	}
```
changed the `arcHeight` calculation like to this:
```javascript
$$.arcHeight = $$.height - ($$.hasType("gauge") ? $$.getPaddingBottomForGauge() : ($$.isLegendRight ? 0 : 10));
```

It works for all gauge types, and it's only breaking 1 gauge test which can be easily updated.

If this solution is ok for @netil I could make a pull request.

**Comment by netil** [comment]
@michkami, can you make PR to `v2` branch?

**Comment by netil** [comment]
From the PR (the right screenshot), will make have padding at the bottom.

![image](https://user-images.githubusercontent.com/2178435/85661177-5fde5000-b6f1-11ea-9012-3bb291d2e14a.png)

But after the update, size of the `gauge` itself will become more smaller than before.
The differences can be compared with the screenshot.
- left: current / right: PR update

**Comment by RonnyWeiss** [comment]
I think this is ok! Another solution would be to position the legend more to the value title so gauge does not get smaller. But this is up to you how you handle that. The current workaroud of mine was also to make the gauge little bit smaller in the height and to put a small padding outside of the svg

**Comment by michkami** [comment]
> 
> 
> I think this is ok! Another solution would be to position the legend more to the value title so gauge does not get smaller. But this is up to you how you handle that. The current workaroud of mine was also to make the gauge little bit smaller in the height and to put a small padding outside of the svg

Positioning the legend closer to value would overlap gauge min and gauge max as you can have multiple data columns:
![grafik](https://user-images.githubusercontent.com/42860868/85664873-0d823c80-b6bb-11ea-84af-a5cff97a2f84.png)
![grafik](https://user-images.githubusercontent.com/42860868/85664930-1d018580-b6bb-11ea-95a5-b8081d97139a.png)

@netil I think it is necessary to make the `gauge` a bit smaller, as the gauge and the legend are rendered into the same container.

**Comment by RonnyWeiss** [comment]
Yes you're right then it's problem. So making the gauge smaller would be the best solutions! Thank you very much for fixing that! 

Kind regards

Ronny
