### ISSUE TITLE
TypeError: can't access property "each", $$.$el.text is null is 2.0.0-Next3

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1444]
Hello

I immediately wanted to test the new feature with the Gauges and tried the new release 2.0.0 Next3. The following error came immediately:

![callstack](https://user-images.githubusercontent.com/30749177/84625673-0e111b00-aee4-11ea-9976-cdf9610df6ac.JPG)

with following json:

[chart json.txt](https://github.com/naver/billboard.js/files/4778422/chart.json.txt)

I follow this up to the code line and saw it was a new function:

![Unbenannt](https://user-images.githubusercontent.com/30749177/84625724-23864500-aee4-11ea-8fc9-5861baf53d7c.JPG)

Does it need a fix or is my json wrong?

Kind regards

Ronny

**Comment by netil** [comment]
@RonnyWeiss, don't need to explicitly set `data.labels` option. Just removing, will work.
```js
data: {
   "labels":false,  // remove this option
}
```

BTW, There's an issue where triggers this issue when set to `false`, I'll be fix that.

**Comment by RonnyWeiss** [comment]
You're fast! Thank you try fixed version when avail.

Kind regards

Ronny
