### ISSUE TITLE
describe try, catch block on document

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1454]
## Description
```bb.generate``` function can occurs an error in some cases for example:
```js
var chart = bb.generate({
  data: {
    xs: { "data1": "data1x" },
    columns: [
      ["data1x"],
	["data1", 30, 200, 100, 400, 150, 250]
    ],
    type: "spline"
  },
  bindto: "#chart"
});

error:

billboard.min.js:10 Uncaught Error: x is not defined for id = "data1".
    at VM230 billboard.min.js:10
    at Array.forEach (<anonymous>)
    at t.convertDataToTargets (VM230 billboard.min.js:10)
    at t.value (VM230 billboard.min.js:10)
    at t.value (VM230 billboard.min.js:10)
    at t.value (VM230 billboard.min.js:10)
    at new t (VM230 billboard.min.js:10)
    at Object.generate (VM230 billboard.min.js:10)
    at VM235 pen.js:2
```
The users may not be noticed generate can throws errors.
Why don't we describe try, catch block on this document section [generate](https://naver.github.io/billboard.js/release/latest/doc/bb.html#.generate)?

## Steps to check or reproduce
https://codepen.io/qkreltms/pen/XWXpNYj?editors=1111

**Comment by netil** [comment]
Hi @qkreltms, added a `note` for the possibility of throwing error cases.
Thanks for the suggestion!
