### ISSUE TITLE
Question about how to center the data label in the bar chart

### ISSUE THREAD

**Issue by HyukCheolShin** [naver/billboard.js#1456]
## Description
There was a request in the bar chart that the position of the datalabel should always be central.
So we handled it using the method of modifying the y-value of text in "onrendered".
![image](https://user-images.githubusercontent.com/56674023/85101664-dedd0f80-b23d-11ea-98b7-451a945bc6fb.png)

I want to know if there is a better way.

## Steps to check or reproduce
https://jsfiddle.net/s0215/6a1dwnrs/

**Comment by netil** [comment]
Hi @HyukCheolShin, you can use [`data.labels.centered`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4labels) option to align labels text position to be centered.

Checkout the second example:
- https://naver.github.io/billboard.js/demo/#Data.DataLabel

**Comment by HyukCheolShin** [comment]
Thank you very much!
