### ISSUE TITLE
Suggestion on how to show data labels unconditionally

### ISSUE THREAD

**Issue by HyukCheolShin** [naver/billboard.js#1457]
## Description
In the chart, data labels become invisible for many reasons, and customers must be seen.
(X-axis, y-axis overlaps, or when the font size of the datalabel is large, etc.)
I used a method to modify the position of the text in the datalabel.
![image](https://user-images.githubusercontent.com/56674023/85103034-d89c6280-b240-11ea-967b-28640e21e0b6.png)

I hope there is an option to make data labels visible unconditionally.

## Steps to check or reproduce
https://jsfiddle.net/s0215/uxdg5w3r/

**Comment by netil** [comment]
[`bar.label.threshold`](https://github.com/naver/billboard.js/issues/1427) option is implemented to the new coming `v2.0`.

You can install the v2 release by:

```js
npm install billboard.js@next
```

**Comment by HyukCheolShin** [comment]
I'll try. Thank you.

**Comment by HyukCheolShin** [comment]
I tried, but it wasn't the result I wanted.
I want to see all the data labels hidden on the x-axis.

https://jsfiddle.net/s0215/uda1sktg/

**Comment by netil** [comment]
`bar.label.threshold` option is to control text label visibility giving a minimum condition of ratio.
I think isn't something you need. 

I'm not clear your question, but in your example above remove `axis.y.padding` option to make visible all data text label.

```js
  axis: {
    y: {
      min: -150,
      max: 1600,
      // padding: 0
    }
  },
```
and you can use [`data.labels.position`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4labels) option to handle text label's position.

```js
data: {
    labels: {
        // set x, y coordinate position
        position: {
           x: -10,
           y: 10
        },

        // or set x, y coordinate position by each dataset
        position: {
           data1: {x: 5, y: 5},
           data2: {x: 10, y: -20}
        }
    }
}
```

**Comment by HyukCheolShin** [comment]
I had a lot of concerns because the implementation method was limited due to customer requests.
It was very helpful.
Thank you.
