### ISSUE TITLE
Subchart is not working or wrong scaled in V2.0.0-Next5

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1458]
Hello 

I tried out V2.0.0-Next5 and your last fixes work great but subcharts are not working correctly:

![grafik](https://user-images.githubusercontent.com/30749177/85126865-98cc7f80-b22e-11ea-8e91-680cb5fa0527.png)

![grafik](https://user-images.githubusercontent.com/30749177/85126929-bf8ab600-b22e-11ea-84b3-10183f8b0dab.png)

finalChartData is:

[chartconf.txt](https://github.com/naver/billboard.js/files/4804247/chartconf.txt)

Hope you can fix the problem! Thank you

Kind regards

Ronny

**Comment by netil** [comment]
@RonnyWeiss, thanks for the report.
It seems having an issue related with the data.groups. I'll be dig on this.

**Comment by RonnyWeiss** [comment]
Thank you will test fix again :-)

**Comment by RonnyWeiss** [comment]
could you also please fix the blank spüace between the legend and the subchart? I can not set by any setting that subchart is directly above the legend?

**Comment by netil** [comment]
@RonnyWeiss, done. Try the [`next.6`](https://github.com/naver/billboard.js/releases/tag/2.0.0-next.6) :)
