### ISSUE TITLE
Autopadding of chart when legend is shown V2.0.0-Next6

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1468]
Hello 

I would be very helpful when lgend is on the right or on the bottom that the chart sizes exactly like this the legend and chart are shown correctly:

![grafik](https://user-images.githubusercontent.com/30749177/85400654-0d6a2b80-b559-11ea-849d-cbbe5cf4d952.png)

I know when I would set right padding then it works but I don't know real size of legend
[chartjson.txt](https://github.com/naver/billboard.js/files/4819139/chartjson.txt)

Would be very cool if you fix that

kind regards

Ronny

**Comment by watnab** [comment]
Why do you set `padding.right` to `30` in `chartjson.txt` ? Can you omit it?
```js
  "padding": {
    "bottom": 10,
    "left": 50,
    "right": 30,
    "top": 15
  }
});
```

https://naver.github.io/billboard.js/release/latest/doc/Options.html#.padding
> padding.right
> &lt;optional>

**Comment by RonnyWeiss** [comment]
Yes I can omit this by set a larger right padding but I do not know how large the legend is:

![grafik](https://user-images.githubusercontent.com/30749177/85410428-5cb75880-b567-11ea-992f-c6314ead5976.png)

sould would be better if you could calculate legend size and make auto padding or I can set max char length of legend items.
But I know you could get size of Text Items with D§ function so auto padding should not be the problem I think. Hope you can do that.

Thank you!

**Comment by watnab** [comment]
https://jsfiddle.net/1gaqyLms/
It seems the library will pad for right side legend automatically when config `padding.right` is omitted.

**Comment by watnab** [comment]
The reason why you set `padding.right` may be that you want to set padding right of right legend.
However `padding.right` seems to mean space between main chart and legend when legend is right side.

**Comment by RonnyWeiss** [comment]
Thanks for that hint so I will try to omit padding in future for legend

**Comment by RonnyWeiss** [comment]
I tired auto padding and it worked nice for legend but at the top I have problems:

![grafik](https://user-images.githubusercontent.com/30749177/85505118-e01b8d00-b5ed-11ea-9ba7-df65aa6831d9.png)

so it does not look very nice. Maybe you could fix that then it's possible to use auto padding because auto padding is much smarter then set it  on every chart

**Comment by RonnyWeiss** [comment]
The same is surely also when using second y2 axis

**Comment by RonnyWeiss** [comment]
Would it be possible to left only on padding Parameter null and this is then auto calculated? I think this improves usability a lot 😀

**Comment by watnab** [comment]
> but at the top I have problems:
> The same is surely also when using second y2 axis

* It may be other issue than "padding.**right** vs **right** legend".
* I could not find the way to reproduce it.

----
> Would it be possible to left only on padding Parameter null and this is then auto calculated?

"set value to null"(e.g. `bottom: null`) may mean "omit value" as far as I had tried.
However I could not find about it in the api doc.

**Comment by RonnyWeiss** [comment]
Sorry my mistake ommit only one values does also work! That's great. I will close Issues. Sorry for that!
