### ISSUE TITLE
Empty space between chart, subchart and legend in V2.0.0-Next6

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1469]
Hello

Could you please fix the empty space between chart, subchart and the legend?

![grafik](https://user-images.githubusercontent.com/30749177/85400997-9719f900-b559-11ea-92b6-a04d7333908b.png)

[chartjson.txt](https://github.com/naver/billboard.js/files/4819147/chartjson.txt)

I don't know how to fix that by settings parameters

Kind regards

Ronny

**Comment by watnab** [comment]
https://naver.github.io/billboard.js/release/latest/doc/Options.html#.padding
It seems `padding.bottom` means space between main chart and subchart when subchart is shown.

https://naver.github.io/billboard.js/release/latest/doc/Options.html#.subchart
It seems `subchart.axis.x.tick.text.show` is false in your PNG image not `chartjson.txt` .

I could not find parameter to set padding bottom of subchart.

**Comment by RonnyWeiss** [comment]
But padding bottom should be padding below subchart and currently it's set to 10 so the blank spaces I think are larger then 10 so it must be another bug.

**Comment by watnab** [comment]
> should be padding below subchart

> https://naver.github.io/billboard.js/release/latest/doc/Options.html#.padding
> The padding of the chart element.

It seems that here "the chart" means "only main chart rather than whole chart" .
https://jsfiddle.net/j2L08u1g/1/

**Comment by RonnyWeiss** [comment]
so should I try to set text false or will you fix that when I only set subchart true that size fits?

**Comment by watnab** [comment]
> will you fix

I'm not auther of this library. So I can not decide what is true. I'm just waiting for the official release of v2.0.0.

----

> so should I try to set text false
> ?

Here I could not see what you want to do.

----

It seems the library does not shrink padding below subchart even when x-axis of subchart is hidden.
![bottom](https://user-images.githubusercontent.com/36845428/85515364-fea67600-b637-11ea-9c87-5da0a2811988.png)
( show whole axis / hide tick.text / hide tick / hide axis )

----

Workaround? : It seems the margin bottom of the svg element can be minus.

**Comment by RonnyWeiss** [comment]
That'S why is set chart conf like in the example: https://naver.github.io/billboard.js/demo/#Interaction.SubChart

But I get not the same results. Current conf is that:

[chartjson.txt](https://github.com/naver/billboard.js/files/4823829/chartjson.txt)

and it looks like:

![grafik](https://user-images.githubusercontent.com/30749177/85516722-ce8eb100-b5fe-11ea-9411-be0559aef96d.png)

with V2.0.0-Next6

**Comment by RonnyWeiss** [comment]
The problem is that labels not shown in V2.0.0-Next6 you can set what you want it's not working:

[chartjson1.txt](https://github.com/naver/billboard.js/files/4823882/chartjson1.txt)

And the bottom padding of subchart is always set by x Axis height but this can be omit when labels are not shown so the blank space gets smaller

**Comment by watnab** [comment]
https://jsfiddle.net/kqcrzjto/
In my environment (Win10/Chrome), text of subchart are shown (with CDN/2.0.0-next.6).
![result](https://user-images.githubusercontent.com/36845428/85518829-a5404600-b63b-11ea-8270-43236d0b6556.png)

**Comment by watnab** [comment]
> It seems the library does not shrink padding below subchart even when x-axis of subchart is hidden.
I tried with CDN/2.0.0-next.6.
![axis](https://user-images.githubusercontent.com/36845428/85520260-9e1a3780-b63d-11ea-841e-4f15830c5ae3.png)

**Comment by RonnyWeiss** [comment]
I checked it in jsfiddle and the problem was css! it has hidden the elements. So we can close this
