### ISSUE TITLE
Collapse Legend or scrollable legend

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1470]
Hello 

It would be cool to collapse the legend e.g. like a hamburger menu and when have many series that the legend Items are scrollable e.g. when having a small chart and legend is higher then the chart.

like this:

![grafik](https://user-images.githubusercontent.com/30749177/85401381-3b03a480-b55a-11ea-97be-1b673d019641.png)

Thank you!

Kind regards

Ronny

**Comment by netil** [comment]
@RonnyWeiss, you can make your own custom legend for that. 

Checkout the example:
- https://jsfiddle.net/netil/c3uoj68f/

**Comment by RonnyWeiss** [comment]
Ok thank I will try it. 😀
