### ISSUE TITLE
Could not find a declaration file for module 'billboard.js/dist/billboard.pkgd'.' implicitly has an 'any' type.   Try `npm install @types/billboard.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'billboard.js/dist/billboard.pkgd';`ts(701

### ISSUE THREAD

**Issue by Dionne97** [naver/billboard.js#1473]
## Description

I have installed the nightly version for billboard I get this error. I assumed that this version has the typings but i still get this issue. I'm fairly new at using typescripts. I am not sure how to go about this

**Comment by netil** [comment]
Hi @Dionne97, if you don't have some specific needs to use the `nightly`, is recommended use the latest version.
```sh
npm install billboard
```
