### ISSUE TITLE
Scroll affects bar width

### ISSUE THREAD

**Issue by watnab** [naver/billboard.js#1476]
## Description
It seems srolling zoomed bar chart affects the width of bars.

## Steps to check or reproduce
1. Show https://jsfiddle.net/psc1gjm4/
2. Scroll to the right(Drag the chart to the left).

**Comment by watnab** [comment]
The width of bar will get narrow.
![1](https://user-images.githubusercontent.com/36845428/86096230-fa71d100-baed-11ea-896a-97fa578006f6.png)
![2](https://user-images.githubusercontent.com/36845428/86096235-fc3b9480-baed-11ea-8a94-254dfbf5ca85.png)

**Comment by watnab** [comment]
https://jsfiddle.net/5962c3pn/
billboard.js v1.11.1 won't reproduce this issue.

**Comment by netil** [comment]
The update of width size by zoom was applied from #1185.
This issue seems related with that update. I'll check for that.

Thanks for the report!

**Comment by watnab** [comment]
> This issue seems related with that update.

[93184a2](https://github.com/naver/billboard.js/pull/1191/commits/f3d217e3e828855aa5d86fdcde2ced1a704b64ee)

> The width of bar will get narrow.
- In `getBarW`, `tickInterval` will change. `$$.subX.domain()[1]` and `maxDataCount` won't change.
- In `xx(d)`, `$$.zoomScale(d)` will change.
- In `scale(d)` of `getCustomizedScale`, `scaleValue(d)` will change.

In d3.js,
- In `scale(x)` of `transformer$1`, the value `output` returned will change.
- In `function(x)` of `bimap(domain, range, interpolate$$1)`, `d0(x)` will change.

`getCustomizedScale` will be called from `zoom.updateTransformScale`.

> $$.zoomScale = $$.getCustomizedScale(newScale);

I could not see what's the right way to update scale.

**Comment by watnab** [comment]
It seems zoomScale should not change even if x-offset will get larger when scrolling to right.
X-offset may possibly affect zoomScale.

**Comment by netil** [comment]
@watnab, released [`2.0.0-next.8`](https://github.com/naver/billboard.js/releases/tag/2.0.0-next.8) with the fix.
<img src=https://user-images.githubusercontent.com/2178435/86322024-21a6da80-bc75-11ea-8bb4-a9ca2002509c.gif width=350>
