### ISSUE TITLE
Angular project : import issue

### ISSUE THREAD

**Issue by sergew92** [naver/billboard.js#1520]
Hello all,
first, let me thank you for this wonderful library !

So, I'm into an issue with billboard 2.0 on an Angular project, 

This line raises an error :
`import bb, {line} from "billboard.js";`

> Module '"../../../node_modules/billboard.js/types"' has no exported member 'line'. Did you mean to use 'import line from "../../../node_modules/billboard.js/types"' instead?

I've reproduced the error on a minimal angular project here:
https://stackblitz.com/edit/angular-ivy-etb6ue?file=src%2Fapp%2Fapp.component.ts

Can you help me please? 

Kamsamida !

**Comment by michkami** [comment]
`import bb from "billboard.js";` and `"line"` instead of `line()` will make it work.

But I would also be interested into making `import bb, {line} from "billboard.js";` work in our Angular app.

**Comment by netil** [comment]
Hi @sergew92, thanks for the report.
Well, there's a missing export declaration in types definition. I'll be fixing ASAP with patch release.
