### ISSUE TITLE
Billboard.js can be another 20 KB smaller.

### ISSUE THREAD

**Issue by praisedpk** [naver/billboard.js#1524]
Hi @netil

I read your [exciting blog post on medium](https://medium.com/@alberto.park/billboard-js-2-0-is-out-15e84b52ab11) about how you worked hard to get the performance improvements for version 2 of billboard.js.

Knowing that you are concerned about build size and performance, I have created [Billboard.js CDN](https://pagecdn.com/lib/billboardjs) (on PageCDN) that compresses JS and CSS files very hard to reduce their transfer sizes. PageCDN hosts only a collection of high quality libraries, and now Billboard.js is part of it. 

Here are some numbers:

                                 PageCDN         Current         Saving
                             --------------------------------------------
    billboard.pkgd.min.js      115.77 KB       138.10 KB       22.33 KB
    d3.min.js                   67.37 KB        75.40 KB        8.03 KB
    billboard.min.js            54.28 KB        64.33 KB       10.05 KB
    billboard.min.css            1.53 KB         1.84 KB        0.31 KB

So, billboard.js on PageCDN is around 18-22 KB smaller than normal due to better compression. The files are available on CDN here: [Billboard.js](https://pagecdn.com/lib/billboardjs) and [D3](https://pagecdn.com/lib/d3).

Adding these CDN links on download & installation section is helpful for users looking to reduce JS size. If you allow, I can proceed with a PR to add it.

Thanks.

**Comment by praisedpk** [comment]
Here are the resources used in this comparison of Transfer Sizes. New releases are pulled automatically from npm. Please let me know if you need any input from me.

    https://pagecdn.io/lib/d3/5.16.0/d3.min.js
    https://d3js.org/d3.v5.min.js    
    
    https://pagecdn.io/lib/billboardjs/2.0.0/billboard.pkgd.min.js
    https://naver.github.io/billboard.js/release/latest/dist/billboard.pkgd.min.js
    
    https://pagecdn.io/lib/billboardjs/2.0.0/billboard.min.js
    https://naver.github.io/billboard.js/release/latest/dist/billboard.min.js
    
    https://pagecdn.io/lib/billboardjs/2.0.0/billboard.min.css
    https://naver.github.io/billboard.js/release/latest/dist/billboard.min.css

Thanks.

**Comment by netil** [comment]
> Adding these CDN links on download & installation section is helpful for users looking to reduce JS size. If you allow, I can proceed with a PR to add it.

Hi @praisedpk, well looks good.
Can you add it for [Using CDN](https://github.com/naver/billboard.js#using-cdn) section?
