### ISSUE TITLE
bug(axis): autorotated x axis tick texts are cut off at the end of x axis

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1530]
## Description
Autorotated x axis tick texts are broken in V2.
As you can see in the screenshot below, the texts get cut at the end of the x axis.
![Screenshot_2020-07-20 billboard js - examples](https://user-images.githubusercontent.com/42860868/87930294-17177e00-ca88-11ea-9a55-f0706d1d69af.png)

How it should look like:
![Screenshot_2020-07-20 billboard js - examples(1)](https://user-images.githubusercontent.com/42860868/87930323-1f6fb900-ca88-11ea-962a-17b8569cd662.png)

It looks like the x axis clip path is cutting them off, as you can see below :

xAxisClipPathWidth = 524.5437140659369
![grafik](https://user-images.githubusercontent.com/42860868/87934946-6792d980-ca90-11ea-8f65-72bbb8fc6957.png)

7419f44c38037681a886e113b3e70a69b7cc1434 says, that x axis clip path fits the real axis size. Wouldn't the real axis size include the overflow, if autorotate is enabled and `getAxisTickRotate()` returns value > 0?

Adding `getXAxisTickTextY2Overflow()` to https://github.com/naver/billboard.js/blob/master/src/ChartInternal/internals/clip.ts#L61 fixed the problem for me locally.

## Steps to check or reproduce
1. Open https://naver.github.io/billboard.js/demo/#Axis.XAxisTickAutorotate

**Comment by netil** [comment]
Hi @michkami, the issue comes from the axes' left/right clip size adjustment(#1449). 

To not clipped, you can use [axis.x.clipPath](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4clipPath) option.
Set `false` to not apply `clip-path` attribute for x axis.

```js
axis: {
    x: {
       clipPath: false
    }
}
```

**Comment by michkami** [comment]
thx @netil :)
Somehow I didn't find this commit.
