### ISSUE TITLE
Change areas and lines position when area's opacity is 1

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1543]
## Description
How about adding an option changing areas and lines position when area's opacity set to 1?

When I set area's opacity 1, lines are look faint.

![캡처1](https://user-images.githubusercontent.com/25196026/88004379-e136d000-cb41-11ea-810b-f0c20b70d8ca.PNG)

![캡처](https://user-images.githubusercontent.com/25196026/88004129-55bd3f00-cb41-11ea-8c1e-9f6063e8e6e5.PNG)

When i changed each position it looks good 

![켑차22](https://user-images.githubusercontent.com/25196026/88004344-cbc1a600-cb41-11ea-9191-d126f40f8909.PNG)

![캡처2](https://user-images.githubusercontent.com/25196026/88004317-bba9c680-cb41-11ea-8214-4317eb524de9.PNG)

I was able to fix this by adding these lines
```js
  const changeLinesAndAreasPosition = (ctx: any) => {
    const lines = d3.select<SVGElement, SVGElement>(ctx.element).selectAll<SVGGElement, SVGGElement>(".bb-chart-line > .bb-lines").nodes();
    d3.select<SVGGElement, SVGElement>(ctx.element).selectAll<SVGGElement, SVGGElement>(".bb-chart-line > .bb-areas").nodes().forEach((area, index) => {
      if (area.parentNode) {
        area.parentNode.insertBefore(area, lines[index]);
      }
    })
  }
```

## Steps to check or reproduce
https://codepen.io/qkreltms/pen/JjGwLgo

**Comment by netil** [comment]
Hi @qkreltms, the only difference between the node stacking order changes is to make line to be positioned over area element. Hence to make line to be rendered more sharper.

If that is something you need, how about styling with css prop. rather than handling node stacking?
Adding `stroke-width` will make that.

```js
.bb-area-data1 {
  opacity: 1 !important;
  fill: lightgray !important;
  stroke-width: 1px;
}
```

**Comment by qkreltms** [comment]
@netil I've already tried, but it also looks not clear than changing node stacking and also looks faint```stroke-width: n(n>1)```

**Comment by netil** [comment]
similar as [grid.front](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.grid) option can be implemented for that.

```js
area: {
    // default is 'true'. false make to be positioned behind the line element
    front: false,  
}
```
