### ISSUE TITLE
Flush does not resize to larger container

### ISSUE THREAD

**Issue by melloc01** [naver/billboard.js#155]
## Description
Hi, when I try to create a dynamic height chart it does not behave as expected when calling Flush().

Well, it does when adding, but not when removing rows from the widget.
You can easily check on the link below:
## Steps to check or reproduce

Webpack Bin: https://www.webpackbin.com/bins/-KvENeYh5CIurFss_QDr

Add 3 rows then remove 3 rows

**Comment by netil** [comment]
Thanks for the report. I'll try to check the issue.

**Comment by netil** [comment]
I'll look more on that issue, but before to make some changes, you can add some code to solve the issue.
Just removing `max-height` from chart element will work.

```js
    redraw () {
        this.highcharts.reflow()
      
        // remove max-height prop from the chart element
        this.bb.internal.selectChart.style("max-height", null);
        this.bb.flush();
    }
```

**Comment by melloc01** [comment]
That's sweet @netil, thanks for the workaround. It will help me get going while you dive into the internals, thank you!

**Comment by julien** [comment]
@netil why not remove `max-height` from the `selectChart`?

**Comment by netil** [comment]
@julien That's an easy approach. Removing is easy, but need to taking care on others side effect which can cause.

**Comment by netil** [comment]
When there's no `max-height` property set, it's getting bigger every resize event happens.
Setting `max-height` at the initialization, it prevents through pass initial height. 

I'm trying to figure out what's going on there. And the weird thing is even removing all the child nodes within `<svg>` still happens this behavior.

![max-height](https://user-images.githubusercontent.com/2178435/33933762-1077face-e03a-11e7-89c7-c7394078b5d5.gif)

**Comment by netil** [comment]
It was fixed applying `display:block` css property to `<svg>` element.
