### ISSUE TITLE
Types are not updated for v2

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1551]
## Description
The changelog and migration guides for v2 are saying that the context parameter of calback-ish options has been removed in favor of using `this`. but the type definitions don't reflect such change. Either the types are broken, or the upgrade guide and changelog are wrong.

**Comment by netil** [comment]
Could you try nightly?
- https://github.com/naver/billboard.js#nightly-version

**Comment by stof** [comment]
Well, my own project is not yet migrated to v2 (I have a blocker in our own code that needs to be resolved first). I discovered that issue when reviewing the upgrade path.
