### ISSUE TITLE
how to merge data same name

### ISSUE THREAD

**Issue by kuju** [naver/billboard.js#1577]
## Description

데이터 컬럼들을 병합하여 하나의 컬럼처럼 그래프는 나오지만 tooltip에는 병합전 데이터 항목이 나오게 하고 싶습니다
## Steps to check or reproduce

example
```
var chartSpline = bb.generate({
	bindto: "#barChart",
	data: {
		type: "bar",
		columns: [
			["data1", 30, 200, 100, 170],
			["data2", 130, 100, 140, 35],
			["data3", 50, 150, 240, 135],
			["data4", 10, 50, 40, 105],
		],
		stack: {
			normalize:true
		},
		groups: [["data1", "data2", "data3", "data4"]]
	},

});
```
데이터가 위와 같을떄 
data1, data2를 합쳐서 name1로 표시  (항목에 name1, data3, data4 3개만 표시)
마우스 오버시 툴팁에서는 data1, data2의 데이터가 각각 표현되게 할 방법이 없을까요?

그림으로 예를 들면 아래 그림 처럼 툴팁은 전체 데이터가 표시 되지만 bar 그래프 밑의 데이터 항목은 그림과 다르게 name1, data3, data4로 병합하는 방법이 있을까요?
![image](https://user-images.githubusercontent.com/32897013/88898654-00dba000-d288-11ea-8fb3-b35a67ea9a90.png)

**Comment by netil** [comment]
Hi @kuju, I think there're 2 possible approaches to fulfill this. 

### 1) Merge data and visualize separately in tooltip

This approach needs to manage 2 types of data:
- a) Generate merged data as you need from the original
- b) The "real" data, where needs to be used from tooltip

This will work well, except the tooltip. For tooltip needs to be display the calculated percentage and so on.
It'll be quite cumbersome handle this.

### 2) Make to visualize two dataset as one.

This approach will not altering "original" data, and makes others(shape rendering and legend) works as merged.

Checkout the example for this:
- https://jsfiddle.net/netil/as6dtygk/20/
