### ISSUE TITLE
Addition to "who's using billboard.js" wiki

### ISSUE THREAD

**Issue by patrickcate** [naver/billboard.js#1586]
I have a couple additions to the "Who's using billboard.js" section of the wiki. Below are the markdown entries, but feel free to edit as needed. Also, thanks for the great library!

## Companies & Organizations

```
- #### [hr.nih.gov] <https://hr.nih.gov>
  > National Institutes of Health: Office of Human Resources
```

## Projects

```
- #### [National Institutes of Health FEVS Survey Results](https://hr.nih.gov/workforce/fevs/2019-fevs-survey-results)
  > National Institutes of Health (NIH) data visualization of Federal Viewpoints Survey (FEVS) survey results.
```

**Comment by netil** [comment]
Hi @patrickcate, thanks for sharing this!
Just added to the list 😄
