### ISSUE TITLE
zoom not working for bar charts (bars do not resize)

### ISSUE THREAD

**Issue by kiezuz** [naver/billboard.js#16]
## Description
bars do not resize when zooming.
## example
`<html>

<head>

</head>

<body>

    <div id="chart1"></div>

    
    <script src="https://d3js.org/d3.v4.min.js"></script>

    
    <script src="billboard.js"></script>
    <link rel="stylesheet" href="billboard.css">

    <script>
        var chart = bb.generate({
            "data": {
                "columns": [
                    [
                        "data1",
                        30,
                        200,
                        100,
                        400,
                        150,
                        250
                    ],
                    [
                        "data2",
                        130,
                        100,
                        140,
                        200,
                        150,
                        50
                    ]
                ],
                "type": "bar"
            },
            "zoom": {
                "enabled": true
            },
            "bar": {
                "width": {
                    "ratio": 0.5
                }
            },
            "bindto": "#chart1"
        });
    </script>

</body>

</html>`

**Comment by netil** [comment]
@kiezuz, confirmed. The bar type not zooming.
