### ISSUE TITLE
Multiple Timeseries in One Chart

### ISSUE THREAD

**Issue by gitmopp** [naver/billboard.js#160]
## Description
Is it possible to have multiple timeseries in one chart?

## Steps to check or reproduce
I tried the following code, which didn' t work.
```
var chart = bb.generate({
  "data": {
    "xs": {
      "data1": "x1",
      "data2": "x2"
    },
    "columns": [
	["x1", "2013-02-01", "2013-03-02", "2013-04-03", "2013-05-04", "2013-06-05", "2013-07-06"],
	["x2", "2013-02-01", "2013-03-15", "2013-04-11", "2013-05-04", "2013-06-01", "2013-07-06"],
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 20, 180, 240, 100, 190]
    ]
  },
  "axis": {
    "x1": {
      "type": "timeseries",
      "tick": {
        "format": "%Y-%m-%d"
      }
    },
    "x2": {
      "type": "timeseries",
      "tick": {
        "format": "%Y-%m-%d"
      }
    }
  },
  "bindto": "#TimeseriesChart"
});
```

**Comment by netil** [comment]
Sorry, multiple axes are supported only for y axis.
If you check the API doc, only `axis.x` option is available.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis:x:type

But, we're considering as the future implementation feature.
- https://github.com/naver/billboard.js/wiki/Roadmap#new-optionsfeatures

**Comment by gitmopp** [comment]
Thank you for the information
