### ISSUE TITLE
X ticks overlap legend for categorical X data

### ISSUE THREAD

**Issue by kmatarese** [naver/billboard.js#1602]
## Description

If you have more than a couple dozen categories (or if your screen width is smaller) the categorical data names on the X axis overlap the legend. It would be nice if the vertical spacing was automatically adjusted based on the rotation of the X ticks and the length of the longest X-tick.

## Steps to check or reproduce

This would happen with many chart types but here is a simple area chart example:

<img width="602" alt="Screen Shot 2020-08-12 at 6 03 22 PM" src="https://user-images.githubusercontent.com/18007191/90072864-2758fc80-dcc6-11ea-9180-975ae7ef508a.png">

```
import "billboard.js/dist/theme/insight.css";
import bb from "billboard.js";

const dataLen = 20;

var chart = bb.generate({
  data: {
    columns: [
        ["category"].concat(Array.from(new Array(dataLen),(val,index) => "category " + index )),
    	["data"].concat(Array.from(Array(dataLen).keys())),
    ],
    x: "category",
    types: {
      data: "area",
    }
  },
  axis: {
    x: { type: 'category' }
  },
  bindto: "#areaChart"
});
```

**Comment by kmatarese** [comment]
I have found that you can use the x-axis height option to help alleviate this. For now I can try to adjust that value based on the x-axis values for categorical charts. I still think it would be worthwhile for this to be automatic so I'll leave the issue open.

```
axis: {
  x: {
    height: 100
  }
}
```

**Comment by michkami** [comment]
> If you have more than a couple dozen categories (or if your screen width is smaller) the categorical data names on the X axis 
> overlap the legend. It would be nice if the vertical spacing was automatically adjusted based on the rotation of the X ticks and 
> the length of the longest X-tick.

It overlaps only if `axis: {
	x: { 
		tick: {
			multiline: true
		}
	}
}` is enabled. For not multilined XAxisTickTexts the XAxisHeight is calculated correctly.

> 
> EDIT: found a few other options that help a bit. I conditionally apply the following and do a hack-ish height adjustment:
> 
> ```js
> axis: {
>   x: {
>     height: myHeight,
>     tick: {
>       fit: true,
>       multiline: false,
>       rotate: 60,
>       culling: false,
>       format: (index, name) => {
>         return name.substr(0, 15);
>       }
>     }
>   }
> }
> ```

In this example you actually don't need to set height manually.
As you can see [in this example](https://stackblitz.com/edit/long-x-axis-texts?file=index.ts) x axis height is calculated automatically depending on the longest text.

I would also recommend enabling ` axis: {
	x: { 
		tick: {
			autorotate: true
		}
	}
},` if you use the chart on small and big displays, as the XAxisTickTexts will be rotated automatically if there is not enough space between 2 category ticks.

**Comment by kmatarese** [comment]
Thanks @michkami. You are correct that the height is fluid when `multiline` is `false`. I've also moved my legend into a separate div as I'm working on customizing that, so I'm no longer seeing any major issues with the x-axis running into the legend. I'll close this unless I come across another case of it happening with the new settings.
