### ISSUE TITLE
Highlighting a specific data point

### ISSUE THREAD

**Issue by 1beb** [naver/billboard.js#161]
## Description
Is there a way to highlight one or more data points with a different colour. Imagine a bar graph that is all black with 5 bars where 2 of the bars are a different colour? 

I've tried passing an array to the `data: { color: array }` but it seems as though it can only take one colour. 

Alternatively, if there's not way to colour specific data points, then perhaps there's a way to use two data groups but make them not dodge each other (then use 0 points for all except those that you want to colour).

**Comment by netil** [comment]
In that case, you can use `data.color` function to change the color of specific data points.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data:color

```js
	data: {
        color: function(color, d) {
            // will make 3rd and 4th data as red color
			if (d.index && d.index == 2 || d.index == 3) {
				color = "red";
			}

			return color;
        }
	}
```
![image](https://user-images.githubusercontent.com/2178435/31422388-2da96ab2-ae88-11e7-97c5-a2c4c83eb781.png)

Check out the online working demo:
- https://jsbin.com/duxutis/edit?html,js,output

**Comment by 1beb** [comment]
Excellent. Feel free to close.
