### ISSUE TITLE
'step' and 'areaStep' not connecting null values on X-Axis-Type-Category

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1637]
## Description
What I wan to do:
I want to connect null values on data types 'step' and 'area-step'. To reach this, I was using `line: { connectNull: true }`, which should work, as I would expect all lines to connect null values regardless of the data type.
As you can see in the example below, the line is drawn wrongly.
![grafik](https://user-images.githubusercontent.com/42860868/91175849-b06a2d80-e6e1-11ea-86e8-bc3b2b7914de.png)

It happens only with following options: `line: { connectNull: true }` and `axis: { x: { type: "category" } }`.
I tested it in 2.0.3 and 1.12.10. Same behaviour on both versions.

## Steps to check or reproduce
1. Open [this example](https://stackblitz.com/edit/connectnull-broken?file=index.ts)
I set the data type as string, because using the imported function doesn't work for me. I get following error: `billboard_js_1.step is not a function`. Seems like extending the data types is not working in all environments.

**Comment by netil** [comment]
Hi @michkami, thanks for the report, I'll check the issue.

**Comment by netil** [comment]
fixed the issue, rendering as it should be.
<img src=https://user-images.githubusercontent.com/2178435/91292677-d111b080-e7d1-11ea-9ede-2bc3b2a2694f.png width=500>
