### ISSUE TITLE
Default to parent size without padding when size is not specified

### ISSUE THREAD

**Issue by temetski** [naver/billboard.js#164]
## Description

Hi!

When generating billboard charts without specifying a `size` attribute, the default behavior is to take the size of the parent container. This however doesn't play so well with parent containers that have padding values.

The implementation uses `offSetWidth` or `getBoundingClientRect`, but it might be cleaner (and more dynamic) to default to the parent's size without padding and borders

**Comment by netil** [comment]
Thanks @temetski for the suggestion.
I'll try to consider this behavior for the next release~ :)

**Comment by julien** [comment]
Hi @temetski,

Would you have an example use case where this doesn't work well?

I've tried in Firefox (57.0.1 ), Chrome(62.0.3202.94) and Safari (11.0.1) and the chart seems to be sized correctly according to the parent's size even if this one has padding/margins.

Thanks!

**Comment by julien** [comment]
The chart's element has a `max-height` set to `320px` in most cases, maybe that's what is causing this issue? @netil what do you think?

**Comment by netil** [comment]
Well, this issue seems related to #155.
The direct cause is the `max-height`, but just removing not solve the issue.
It should have some checks removing this.

Anyway, this isn't a major issue on the usage, so it can be procrastinated to the next release.

**Comment by netil** [comment]
> default to the parent's size without padding and borders

Well, I don't agree on this. The size should be based following the parent's dimension accordingly.
If wants to be sized without padding, the correct approach is remove padding property from the parent node.
