### ISSUE TITLE
튜토리얼 설명이 너무 부실합니다.

### ISSUE THREAD

**Issue by gichang-yang** [naver/billboard.js#165]
예제에서 html문에 
<script src="billboard.js"></script>
    <link rel="billboard.css">
라고 명기해 놨는데 예를들면, 노드에서는
<script src="/node_modules/billboard.js/dist/billboard.js"></script>
    <link rel="stylesheet" href="/node_modules/billboard.js/dist/billboard.css">
라고 표시하는식으로 좀 구체적으로 어디서 어떤 파일을 링크시켜야 하는지 알려줄 필요성이 있고,

또 , 
var chart = bb.generate({ ... 
같은경우는 bb가 도대체 뭔지, 만약 import 시켜야 할 것이 있다면 
var bb =require('billboard'); 같은 좀더 구체적인 설명이 필요해 보입니다.

[참조]
https://realm.io/docs/javascript/latest/ -> 이곳의 getting started 파트

**Comment by netil** [comment]
Thanks for the suggestion, but I don't think the doc is weak.
The file path can differ depending on the user's environment. I think this is really 'basic' knowledge without the detailed clarification.

Anyway, I'll try to add some more details on that.

**Comment by vBlueFlag** [comment]
what a kindly answer;;

**Comment by Rocher0724** [comment]
bb가 billboard 인걸 이제야알았습니다...
