### ISSUE TITLE
Input order gets ignored if the type of name is number (w/ order: null)

### ISSUE THREAD

**Issue by BlackBindy** [naver/billboard.js#1652]
### String Name Case
![image](https://user-images.githubusercontent.com/12558317/92343652-413c0280-f0ff-11ea-8df8-64bb0fe79ede.png)
```ts
// input data
// - name: desc order
// - data: asc order
[
  ["d", 10],
  ["c", 20],
  ["b", 30],
  ["a", 40],
]
// => rendered: "d" -> "c" -> "b" -> "a" (as expected)
```

### Number Name Case
![image](https://user-images.githubusercontent.com/12558317/92343593-1c478f80-f0ff-11ea-9996-6811e2deaf09.png)
```ts
// input data
// - name: desc order
// - data: asc order
[
  ["4", 10],
  ["3", 20],
  ["2", 30],
  ["1", 40],
]
// => rendered: "1" -> "2" -> "3" -> "4" (no...)
```

### description
When `order: null` option is enabled, the data should be rendered in order of the original input data. As you can see above, if you use **string as names** of data, it works as you expected. Even though the names are in descending order, chart is rendered in ascending order because that's how the original data is ordered.

But when you use **number as names**, it certainly breaks the rule and re-arrange the data in descending order (= ascending order in 'name' perspective).

I think if `order: null` is used, the data should remain its order in the original input data no matter what. Thank you.
<br>

## Steps to check or reproduce
**`order: null` should be used.**

### String case
```ts
import bb from "billboard.js";

var chart = bb.generate({
  data: {
    columns: [
      ["d", 10],
      ["c", 20],
      ["b", 30],
      ["a", 40],
    ],
    order: null,
    type: "pie",
  },
  bindto: "#pieChart"
});
```

### Number case
```ts
import bb from "billboard.js";

var chart = bb.generate({
  data: {
    columns: [
      ["4", 10],
      ["3", 20],
      ["2", 30],
      ["1", 40],
    ],
    order: null,
    type: "pie",
  },
  bindto: "#pieChart"
});
```

**Comment by netil** [comment]
HI @BlackBindy, thanks for the report.

The issue was already reported by #1198. And the issue comes from that Object key with number, the order is not guaranteed as the assign order. Checkout the #1198 for more details.
