### ISSUE TITLE
Setting ticks changes width of bar charts for timeseries

### ISSUE THREAD

**Issue by temetski** [naver/billboard.js#166]
## Description

Hi again.

I'm switching over my charts from `nvd3` to `billboard.js` since the documentation of the API's is much more thorough. I have an issue with how bar charts are implemented in conjunction with the ticks, particularly for timeseries charts.

Hiding all the ticks is not an option for me, so I'm thinking if it is possible to set the number of ticks without stretching the bars? Or a helper function that can programatically hide other ticks would be great.

## Steps to check or reproduce

Creating the chart with default settings
![image](https://user-images.githubusercontent.com/6328105/31643213-e81e1346-b321-11e7-8196-3389419182ff.png)

Attempting to reduce the number of ticks via 
```
  axis: {
    "x": {
      "type": "timeseries",
      "tick": {
        format: d => timeFormat('%-m/%-d/%y')(d),
        count: 8
      }
    }
}
```
![image](https://user-images.githubusercontent.com/6328105/31643243-0e1fe52e-b322-11e7-99ee-a5c95fef6721.png)

**Comment by netil** [comment]
@temetski, could you provide the generation code? (preferably jsfiddle, jsbin, etc)

**Comment by temetski** [comment]
Sorry, took a while to get back to this.

Here's a sample generation code. I laid out two charts, one with the default tick counts and the other with a specified number of tick counts.
https://jsfiddle.net/xurbjL9k/

**Comment by netil** [comment]
@temetski, confirmed the issue.
The default bar width is based on the tick counts, so when set to limit tick count, it gets wrong width value.

I'll fix the issue, but before to be solved and released, you can fix setting bar width's value explicitly.
```js
    bar: {
	    width: {
	    	ratio: 0.035
        }
    },
```

**Comment by temetski** [comment]
Thanks a lot. I know about the `width.ratio` option, but I felt that it was too much of a hack and probably not intended. 👍
