### ISSUE TITLE
Cannot create custom plugins by extending Plugin class

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#1665]
## v2 is a TS code now, and there is no JS version of Plugin class
One of my charts has a custom plugin, that is built based on the `Plugin` class of `billboard`. 

```js
import Plugin from 'billboard.js/src/plugin/Plugin';

export default class CustomPlugin extends Plugin {
...
}
```
This code does not work anymore. Yes, I can import TS version, but that will require adding a TS compiler to my build, which I would like to avoid.

**Comment by netil** [comment]
I see. Let me figure out for any solution on this.

**Comment by creage** [comment]
Well, having it as a ES6 class needs it to be compiled first, and usually `node_modules` are excluded from compilations.

Can we have a compiled version of that plugin class in the `/dist/` folder please?

**Comment by mayfield** [comment]
Could really use this too.
