### ISSUE TITLE
IE11 fails to render chart tooltip

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#1670]
## Description
Running v2.1.0-next.2, I have a `Bar` chart. When rendered in IE11, no tooltips are visible, and when clicking on the chart, an error appears in console
```
Unable to get property 'index' of undefined or null reference
```
My debugging shows that method `generateEventRectsForSingleX` fails to `$$.getDataIndexFromEvent(event)`, and is always **-1**.

P.S. `Line` chart has the same issue. 

## Steps to check or reproduce
Just try to render a `Bar` chart using ESM imports, with `tooltip` in IE11, open devtools. Hover over the chart - no tooltip displayed. Click on the chart - error in console.

**Comment by netil** [comment]
It seems having a side effect from the #1650.
Thanks for the report.

**Comment by netil** [comment]
@creage, try with the `2.1.0-next.3`.

**Comment by creage** [comment]
@netil fix confirmed. Works fine now (with additional `line()` call, otherwise it is still broken as stated in #1663 )

**Comment by netil** [comment]
@creage, try with the 2.1.0-next.4.

**Comment by creage** [comment]
@netil looks fixed now. Thank you!

When should we expect this version to be released (as non-next version)?

**Comment by netil** [comment]
@creage, I'm planning for next week.
