### ISSUE TITLE
bar chart isn't working on master branch

### ISSUE THREAD

**Issue by sculove** [naver/billboard.js#17]
## Description
I want to create bar chart but, billboard draw line chart.
master branch version is broken.
but, packaged version is ok.

## Steps to check or reproduce
```js
 var chart = bb.generate({
  "data": {
    "columns": [
      [
        "data1",
        30,
        200,
        100,
        400,
        150,
        250
      ],
      [
        "data2",
        130,
        100,
        140,
        200,
        150,
        50
      ]
    ],
    "type": "bar"
  },
  "bar": {
    "width": {
      "ratio": 0.5
    }
  },
  "bindto": "#chart"
});
```
![2017-06-18 4 35 28](https://user-images.githubusercontent.com/1383952/27259014-2b1c71c0-5444-11e7-9bb3-cf74b33308d9.png)

**Comment by sculove** [comment]
![2017-06-18 4 49 59](https://user-images.githubusercontent.com/1383952/27259104-3aae70aa-5446-11e7-97b0-7ee2a7325140.png)

**Comment by sculove** [comment]
the local dist files differ from published version. @netil plz. check it

**Comment by netil** [comment]
@sculove I did test right now, but It's working fine. Let's try to check together.

**Comment by sculove** [comment]
the babel transforms `[].concat(ids)` to `[ids]` on Mac

**Comment by netil** [comment]
In some Mac works fine, but in others fails. It's not a logical problem, is about transpiling issue.
