### ISSUE TITLE
Crashes interacting on multi x axes chart with point focus only enabled

### ISSUE THREAD

**Issue by lnnrtngl** [naver/billboard.js#1703]
## Description
Great work on billboard.js loving it so far, however;

When point.focus.only enabled:
```
"point": {
  "focus": {
    "only": true
  }
}
```

And zooming dragging or interacting in on multi x axes chart, crashes with:

`Error in /turbo_modules/billboard.js@2.1.1/dist/billboard.js (4391:18)
Cannot read property 'id' of undefined`
on Chrome

`Error in /turbo_modules/billboard.js@2.1.1/dist/billboard.js (4391:16)
d is undefined`
on Firefox

## Steps to check or reproduce
https://stackblitz.com/edit/6fahxr?file=index.js

**Comment by netil** [comment]
Hi @lnnrtngl. Thanks for the report. I'll check the issue.
