### ISSUE TITLE
https://naver.github.io/billboard.js/release/latest/doc/CONTRIBUTING.md Not Work!

### ISSUE THREAD

**Issue by ryudung** [naver/billboard.js#171]
## Description

https://naver.github.io/billboard.js/release/latest/doc/CONTRIBUTING.md

404 page find.

**Comment by netil** [comment]
@ryudung, contribution guide doc is located at
- https://github.com/naver/billboard.js/blob/master/CONTRIBUTING.md

It wasn't served and will not from the location you mentioned.
