### ISSUE TITLE
Can we do grouped bar like this?

### ISSUE THREAD

**Issue by mageshveeraa** [naver/billboard.js#1712]
## Description
Can we do grouped bar like this? showing Total as background bar with light background color.

![sort_on_totals](https://user-images.githubusercontent.com/29809713/95557681-c3875180-0a32-11eb-9b0a-f4bf1c20152d.png)

**Comment by mageshveeraa** [comment]
@netil  Any workaround for this kind of chart?

**Comment by netil** [comment]
Hi @mageshveeraa, there's no straight option for this, but you can make with some work and limitation.

You need to evaluate the total sum from your data and need to specify exact bar width's value.
Checkout the working example from below link.
- https://jsfiddle.net/netil/9omxLhb3/

<img src=https://user-images.githubusercontent.com/2178435/95716358-52e86b00-0ca6-11eb-9939-6b2e2db3766a.png width=500>

**Comment by mageshveeraa** [comment]
Thanks @netil, will check it out.
