### ISSUE TITLE
Parse failures should cause generate to fail

### ISSUE THREAD

**Issue by totalhack** [naver/billboard.js#1714]
## Description

If you setup a chart with the code below it will display a bunch of errors in the console but not throw an error in the generate() call, so you just end up with a useless chart and a lack of a good way to catch the situation (to notify the user for example). It looks like util.ts is taking this approach on purpose:

```
function parseDate(date: Date | string | number | any): Date {
	let parsedDate;

	if (date instanceof Date) {
		parsedDate = date;
	} else if (isString(date)) {
		const {config, format} = this;
		parsedDate = format.dataTime(config.data_xFormat)(date);
	} else if (isNumber(date) && !isNaN(date)) {
		parsedDate = new Date(+date);
	}

	if (!parsedDate || isNaN(+parsedDate)) {
		console && console.error &&
			console.error(`Failed to parse x '${date}' to Date object`);
	}

	return parsedDate;
}
```

## Steps to check or reproduce

```
import "billboard.js/dist/theme/insight.css";
import bb from "billboard.js";

var chart = bb.generate({
  data: {
    x: "x",
    columns: [
	["x", "2013-01-01 00:00:00", "2013-01-02 00:00:00", "2013-01-03 00:00:00", "2013-01-04 00:00:00", "2013-01-05 00:00:00", "2013-01-06 00:00:00"],
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 340, 200, 500, 250, 350]
    ]
  },
  axis: {
    x: {
      type: "timeseries",
      tick: {
        format: "%Y-%m-%d"
      }
    }
  },
  bindto: "#timeseriesChart"
});
```

You may ask why not fix the x data or adjust the tick format? I am drawing charts from user-generated warehouse definitions and user-generated data, so I don't have complete control over that and want to be able to more gracefully handle a situation like this. I had hoped to just be able to catch any `generate` errors and notify the user so they can potentially address the issue. 

I know it's unusual to store dates represented as a full datetime string, but it's not impossible to find in the wild. For example the popular python `pandas` package has a datetime64 dtype (for both dates and datetimes) that seems to do this. So in addition to me trying to catch this earlier, it would be good to have a better way to catch/react to it with Billboard JS.

**Comment by netil** [comment]
Hi @totalhack, thanks for the suggestion and seems very useful in that occasion.
I'll be considering how to improve on this.
