### ISSUE TITLE
tooltip disappears when cursor is on a vertical grid line #question

### ISSUE THREAD

**Issue by patbourgoin** [naver/billboard.js#172]
## Description
The tooltip disappears when the cursor is on a grid line and I think it should stay, we should see it.

## Steps to check or reproduce
You can reproduce the issue with the official example see below. Move your cursor on the vertical grid line and a pixel or 2 on the left or right and you will see the tooltip disappears.
https://naver.github.io/billboard.js/demo/#Grid.OptionalXGridLines

Thanks

**Comment by netil** [comment]
thanks @patbourgoin for the report.
I'll check for that.

**Comment by netil** [comment]
The chart has `rect` area(background colored rectangle  area in the below image), which interact with the user's action.
![image](https://user-images.githubusercontent.com/2178435/31756631-f364b88a-b4df-11e7-921d-f485aa8d1eb2.png)

If the cursor is located outside of those rectangles, event won't fire. That means tooltip will not appear on that area. This is the default behavior applied on interaction.

If your case happens as explained, this isn't a bug. BTW we'll take this in as future improvements.

**Comment by patbourgoin** [comment]
Thanks for the information.
I appreciate the quick answer.

**Comment by netil** [comment]
If you have any further questions or suggestions, plz don't hesitate opening an issue. :)
