### ISSUE TITLE
Line chart

### ISSUE THREAD

**Issue by BhavikThakkar** [naver/billboard.js#1735]
HI,

we are using Billboard.Js charts in our Angular application. we need one feature called " Line Chart with vertical line cutting through the marker" like below

![image](https://user-images.githubusercontent.com/9841783/96856944-13770700-147c-11eb-9b84-b73f56c6acb9.png)

**we shall able to give below property**

able to set the start point , stop point and color of this line

please suggest how we can achieve this

**Comment by netil** [comment]
you can achieve this by using custom data point.
- https://jsfiddle.net/netil/hg1t3mwr/3/

BTW, the library doesn't do everything and can't provide a "magical solution" for every needs.
Take time to figure out to solve your needs.
