### ISSUE TITLE
how to control axis inner option and data.onover

### ISSUE THREAD

**Issue by hyunjunkim-93** [naver/billboard.js#1736]
## Description
Hello, I'm using billboard.js with Vue.
There are two questions while using it.

1. How to get rid of an outer line in the axis?
In the doc, I found only the internal option but that is only about that is the line is inner or not (axis.y.inner option).

1.1 And if I want to hide the axis line only, how do I? There is a control option. But it hides both text and axis.

![스크린샷 2020-10-23 오전 10 40 30](https://user-images.githubusercontent.com/62981465/96946761-4244ba00-151c-11eb-8cd9-a2d57ade7bca.png)

2. Why the data.`onover` method not working? I found that the functionality must be extended after v2.0 in this issues tab. But in my case, which module is imported? How to know which module is needed?

## Steps to check or reproduce
The code below
``` js
import bb, { line } from 'billboard.js';
import 'billboard.js/dist/billboard.css';

export default {
	name: 'Test',

	mounted() {
		const lineChart = bb.generate({
			data: {
				type: line(),
				columns: [
					['data1', 30, 50, 60, 70, 80],
					['data2', 50, 60, 70, 90, 100],
				],
				onclick(d, el) {
					console.info('work'),
					console.info(d);
					console.info(el);
				},
			},
			bindto: '#chart',
		});
	},
};
```

**Comment by hyunjunkim-93** [comment]
Sorry, 2nd question is working well.
I added an option that is `line.point = false`. That's my fault.

**Comment by netil** [comment]
> How to get rid of an outer line in the axis?

  you can use [axis.y.tick.outer](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4outer) option. Set to `false` if want to hide outer line

> And if I want to hide the axis line only,

  You can control each chart's element by setting css rule. To hide y Axis line visibility add below rule.
  ```css
  .bb-axis-y path.domain {
       display: none;
  }
  ```

**Comment by hyunjunkim-93** [comment]
Everything is good.
Thanks a lot for your comment in spite of my carelessness.
