### ISSUE TITLE
Sample code is not correct.

### ISSUE THREAD

**Issue by bexoss** [naver/billboard.js#174]
## Description
Thanks for sharing this great library, it is first time to naver helps me. haha.
Anyway, I think there are some problems of sample codes which is in examples. 

For example, If you go to this page, 
https://naver.github.io/billboard.js/demo/#Axis.YAxisTickFormat

You can see sample code. I thought I can reproduce the chart into my view, but I couldn't. 
Because ` "format": " >-$,"` is incorrect.  If you copy-and-paste of this code into your html view, You can't see the chart. Because of syntax error.

Perhaps this is a problem of this line https://github.com/bexoss/billboard.js/blob/master/demo/chart.js#L170 
But I'm not possible to make a pull request because I'm busy, 
but I believe you guys can fix this. :D 

## Steps to check or reproduce
Copy-and-Paste will make you error which doesn't show chat.

**Comment by netil** [comment]
thanks @bexoss for the report.

The code used for the example, is actually reformatted by replacing the generation code.
I think there's an issue on that.
