### ISSUE TITLE
eventRect is undefined

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#1752]
## Description
Manual resizes of a chart sometimes causes an undefined reference in `updateEventRect()` call, when is executed by binding created in `generateEventRectsForSingleX()`  in this code

```js
 rect.on("mouseover", function () { return $$.updateEventRect(); })                
```
`updateEventRect()` [expects an argument](https://github.com/naver/billboard.js/blob/735ff23ecd5cb48c4701b2d94f0b7104189a6f7b/src/ChartInternal/interactions/eventrect.ts#L184), while the binding above [does not pass any](https://github.com/naver/billboard.js/blob/735ff23ecd5cb48c4701b2d94f0b7104189a6f7b/src/ChartInternal/interactions/eventrect.ts#L389).
## Steps to check or reproduce

Create a chart, set auto resizing to false.

Call a resize manually (from code), and try to mouseover the chart while it is being resized.
```js
node_modules\billboard.js\dist\billboard.esm.js:11242 

Uncaught TypeError: Cannot read property 'attr' of undefined
    at ChartInternal.updateEventRect (node_modules\billboard.js\dist\billboard.esm.js:11242)
    at SVGRectElement.eval (node_modules\billboard.js\dist\billboard.esm.js:11408)
    at SVGRectElement.eval (node_modules\d3-selection\src\selection\on.js:27)
```

**Comment by netil** [comment]
Hi @creage, thanks for the report. I'll check the issue.
