### ISSUE TITLE
IE11 - chart bars are not rendered when unselecting some bars

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#1758]
## Description
In IE11, when rendering a `Bar` chart with huge numbers, and later hiding this big bar by clicking on it's legend title - chart does not render the rest of the bars.

## Steps to check or reproduce
Using IE11, go to the Examples page https://naver.github.io/billboard.js/demo/#Chart.BarChart, and replace the code with the one below
```js
var chart = bb.generate({
  data: {
   columns: [
     ["a", 34.21],
     ["b", 0],
     ["c", -306.86],
     ["unselect me", -99999999999],
     ["e", -989],
     ["f", 0]
    ],
    type: "bar"
  },
  bar: {
    width: {
      ratio: 0.5
    }
  },
  bindto: "#barChart"
});
```
Now click on **unselect me** label in chart's legend. I expect the rest of the bars to gain their actual height proportionally, as they do in Chrome browser.

**Comment by netil** [comment]
confirmed the issue, but hard to determine what is the cause.
same path definition works when generate without `unselect me` data, but not appearing when is together.

Seems the IE's issue, but need to spend time for workaround.

**Comment by netil** [comment]
Applying `display:none` for the hidden dataseries element's node will fix the issue.

The current `opacity` property approach works when data range is `["unselect me", -9999999],`.
Weird behavior, but is not surprising how IE behaves weirdly in many occasions.
