### ISSUE TITLE
loading new data breaks onover, onout and onclick events on some columns

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1761]
## Description
My use case:
One column can have multiple children, which can also have multiple children and so on.
If you click on the column (in this case bar or point in a line chart), it unloads current columns and loads the children columns of the clicked column.

### Example data structure:
- Column1
  - 10 ChildColumns
- Column2
  - 2 ChildColumns
- ColumnX
  - 0 - Y ChildColumns
    - 0 - Z ChildColumns
      - ...

### The Problem
If you click on the first bar, it will load the same amount of bars and mouseevents work on all bars.
If you click on the second bar, it will load 2 bars and mouseevents work only on the first bar.

It seems if you load less columns than in the actual structure level, it breaks the `onover`, `onout` and `onclick` events as you can see in the example below.

![eventRect](https://user-images.githubusercontent.com/42860868/98126618-14655b00-1eb6-11eb-890b-54a35c979ac2.gif)

EDIT:
I'm using the same data structure for pie/donut and it works as expected not breaking any mousevents. Seems like it only happens on types: `area`, `areaSpline`, `areaStep`, `bar`, `line`, `spline`, `step`
Surprisingly, type `scatter` works as expected.

## Steps to check or reproduce
1. Open [StackBlitz](https://stackblitz.com/edit/bardrilldownbug)
2. Hover over all bars (it should show tooltip on every bar).
2. Click on the **first** bar.
3. Hover over all bars (it should show tooltip on every bar).
4. Click on the **second** bar (it will load 2 columns).
5. Hover over all bars (it will only show tooltip for the first bar).

**Comment by netil** [comment]
Hi @michkami, thanks for the report.
It seems a side-effect caused by the changes from #1642

If you try with the prior version of 2.1, it works as expected.
I'll check the issue soon.
