### ISSUE TITLE
How to change the legend color?

### ISSUE THREAD

**Issue by imvivian** [naver/billboard.js#1763]
## Description

I am currently renewing my website in dark mode.
So, I want to change the color of the **legend** describing the chart.
It's currently black, but I want to change it to white.
How can I change it?
I hope for a quick answer.
Thank you.

## Steps to check or reproduce

![image](https://user-images.githubusercontent.com/71866536/98213652-bb1a2c00-1f88-11eb-8a50-90846de8d723.png)

**Comment by netil** [comment]
Hi @imvivian, the legend colors are correlated with the data colors.
That means, if changes the data color, legend will follows that.

But, if you want change different than the data, you can add some css rule defining it.
The below example will make `data1` legend to be red instead the original color.
```css
/* .bb-legend-item-DATA-NAME */
.bb-legend-item-data1 .bb-legend-item-tile {
    stroke: red !important;
}
```

**Comment by imvivian** [comment]
Thank you for your answer.

But what I want is to change the legend **text** color.
I've tried several methods, but I can't change it.

![image](https://user-images.githubusercontent.com/71866536/98314797-1a744c80-201a-11eb-9748-ff52c997576b.png)
<image_01>
↑ The picture attached above is one of the methods I found.

![image](https://user-images.githubusercontent.com/71866536/98314961-717a2180-201a-11eb-9d37-ae0320d89c72.png)
<image_02>
↑ Couldn't I make it like a picture on top of it the way I found it?


**I will recap the question.**
1. I want to change the text color of the legend. How to change the text color?
2. Can I make it like <image_02> the way I found it?

**Comment by netil** [comment]
For detailed customization, not always is possible using methods nor the options provided.
Every chart elements are represented as node element and you can apply changes via CSS.

```css
.bb-legend-item-data1 text {
    fill: red;
}
```

**Comment by imvivian** [comment]
> For detailed customization, not always is possible using methods nor the options provided.
> Every chart elements are represented as node element and you can apply changes via CSS.
> 
> ```css
> .bb-legend-item-data1 text {
>     fill: red;
> }
> ```

Thank you.
Thanks for solving the problem!
Have a nice day!!
