### ISSUE TITLE
Radar chart labels

### ISSUE THREAD

**Issue by Nicolas469** [naver/billboard.js#1765]
## Description
The 'x' row is not treated as the data labels (cfr screenshots).

## Steps to check or reproduce
A) Billboard imported in a Angular project with npm i billboard.js

B) Creation of a radar chart:
```
import bb, { radar as bbRadar } from 'billboard.js';

bb.generate({
  data: {
    x: 'x',
    columns: [
      ['x', 'Data A', 'Data B', 'Data C', 'Data D', 'Data E'],
      ['data1', 330, 350, 200, 380, 150],
      ['data2', 130, 100, 30, 200, 80],
      ['data3', 230, 153, 85, 300, 250]
    ],
    type: bbRadar(),
    labels: true
  },
  bindto: `#chart-${this.chartAreaId}`
});
```

## Result

![2020-11-05_151931](https://user-images.githubusercontent.com/16453431/98252568-653e8780-1f7a-11eb-8e45-61fde0aee627.png)

## Expected result

![2020-11-05_151940](https://user-images.githubusercontent.com/16453431/98252591-6a033b80-1f7a-11eb-8d04-c5f834c62e77.png)

**Comment by netil** [comment]
Thanks for the report.
