### ISSUE TITLE
Billboard.js not working with vue

### ISSUE THREAD

**Issue by Rednas83** [naver/billboard.js#1778]
## Description
I am trying to get billboard up and running with vue2 but I find no/little succes. I thinks it's crashing during import.

Any help would be greatly appreciated.

Btw the typescript codepen works in my environment, but not in the actual codepen.
![image](https://user-images.githubusercontent.com/25219229/99187008-629b1980-2754-11eb-8f1c-f000a02e341f.png)
..But crashes after a refresh
![image](https://user-images.githubusercontent.com/25219229/99187031-7ba3ca80-2754-11eb-82f2-494c040443fe.png)

## Steps to check or reproduce
https://codepen.io/rednas83/pen/jOrdRgz (Javascript)
https://codepen.io/rednas83/pen/gOMqJZe (Typescript, not working)

**Comment by netil** [comment]
Hi @Rednas83, I'm seeing that you're importing modules using a customized CDN.
Depending which environment or tooling, need to setup things based on.

Using the "normal" approach, it works fine.
- https://codesandbox.io/s/competent-lamport-hjvs3?file=/src/App.vue:492-590

**Comment by Rednas83** [comment]
Thanks for the updated codesandbox. I hoped I could reproduce the self error there after refreshing in my normal environment.
![image](https://user-images.githubusercontent.com/25219229/99911813-1c672c80-2cf7-11eb-914b-93f9be99c8e9.png)
![image](https://user-images.githubusercontent.com/25219229/99911832-399bfb00-2cf7-11eb-951f-63ef5d0602dd.png)
![image](https://user-images.githubusercontent.com/25219229/99911841-43bdf980-2cf7-11eb-839e-188357994d16.png)

My environment is
*Nuxt 2.14.7 (Server Side Rendered)
*Vue

Any idea how this can be fixed?

**Comment by netil** [comment]
@Rednas83, plz provide some reproducible online code for check up.

**Comment by Rednas83** [comment]
Hereby the nuxt environment with a added trend page for billboard
https://codesandbox.io/s/bold-swirles-5p8ud?file=/pages/trend.vue

When you hit refresh there is the self error

**Comment by Rednas83** [comment]
Hi @netil , any updates?

**Comment by netil** [comment]
@Rednas83, confirmed. It seems referencing global(window for browser, global for node) throwing the error.
Prioritizing Node.js reference(global or globalThis) fix the issue from the example you shared.

**Comment by Rednas83** [comment]
Thanks @netil for this solution. How can I make this update locally? I tried updating the browser.ts file and restarting the node/nuxt application. But it keeps taking the old version of browser.ts. Should I wait for the official update or is there another way?

**Comment by netil** [comment]
try installing `nightly` build.
- https://github.com/naver/billboard.js#nightly-version

**Comment by netil** [comment]
@Rednas83, published to npm. You can install the fixed version by
```sh
$ npm i billboard.js@next
```
