### ISSUE TITLE
Line chart label line break question.

### ISSUE THREAD

**Issue by smile02** [naver/billboard.js#1784]
## Description

When the point value is not null, 
I ask a question because I need a line break function while showing the comment for the position as a label.

Line breaks are not made even with \n.

## Steps to check or reproduce

https://jsfiddle.net/smile02/Lx5ebknp/1/

**Comment by netil** [comment]
@smile02, line break using `\n` aren't supported for now.
Added the implementation where will be available for next release.

**Comment by smile02** [comment]
Is the next version you mentioned is version 2.1.4?

The version I used was 1.12.0-next.5.

And, even if it is applied as version 2.1.4, line breaks are not displayed even if it is marked with'\n' in the LineChart, it is displayed as a blank.

**Comment by netil** [comment]
@smile02, not yet released to npm.
You can try using by installing `nightly`.
- https://github.com/naver/billboard.js#nightly-version
