### ISSUE TITLE
How can you push data to an existing pen

### ISSUE THREAD

**Issue by Rednas83** [naver/billboard.js#1789]
## Description
With load you can add a new pen, but how can you push data to an existing pen?

Something like:
```
      data.push({
        columns: [
          ["data1", 300],
          ["data2", 200],
          ["data3", 100],
        ],
      })
```
Whereby data is the generated chart.

**Comment by Rednas83** [comment]
Is this possible?

I think it could be very usefull for live charts.

**Comment by netil** [comment]
For data loading, there's `.load()` API, which is the only way to load data for existing generated chart.
For more details about data loading, checkout the below doc.
- https://github.com/naver/billboard.js/wiki/How-behaves-for-dynamic-loading%3F

**Comment by Rednas83** [comment]
This is great for new charts, but not suitable for pushing/appending new data/columns into an existing chart. 

What I am looking for is something like:

```
 chart.push({
        columns: [
          ["data1", 2],
          ["data2", 3],
          ["data3", 4],
        ],
      })
```
Whereby chart is the generated chart.

**Comment by netil** [comment]
This has been implemented by:
- https://github.com/naver/billboard.js/pull/2143
