### ISSUE TITLE
Change Series Hide ,show Behavior on Legend Click  

### ISSUE THREAD

**Issue by ThakkarKhushbu** [naver/billboard.js#1798]
Current Behavior of series on Click of legend : 

![image](https://user-images.githubusercontent.com/30835218/100423269-b93c1800-30b1-11eb-8965-ae302028f5d4.png)

If we click on legend For Data 2 , Data 2 series will gone Hide , only Data 3 will series will display .

Expected Behavior : Can we do reverse of it , if i click on Data 2 , only Data 2 series shall display and rest get Hide ?

Clicking on legend. Can it SHOW rather than HIDE the selected series

**Comment by michkami** [comment]
Check this comment, I think it could be helpful:
https://github.com/naver/billboard.js/issues/1404#issuecomment-632539880
It hides all data except of the double clicked one.

**Comment by ThakkarKhushbu** [comment]
HI ,

Is there any way to get All legend Id's ?

**Comment by netil** [comment]
@ThakkarKhushbu, you can use [`.data.shown()`](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#data%25E2%2580%25A4shown).
Will return all data shown(not hidden) array.

```js
chart.data.shown().map(v => v.id);
// will return ["data2", "data3"]
```
