### ISSUE TITLE
Start/stop angle for a gauge

### ISSUE THREAD

**Issue by Nicolas469** [naver/billboard.js#1803]
## Description
Would it be possible to get an option to control the start and stop angles of gauges ?
For now, we can only have 180° and 360° (with fullCircle option) gauge.

The goal is to generate something like this:
![gauge](https://user-images.githubusercontent.com/16453431/101243364-182c0d80-3700-11eb-9b69-a48d68d733b1.png)

[I know that there already is a "startingAngle" option but it's rather useless for a gauge...]

Thanks !

**Comment by michkami** [comment]
This one is similiar to #1633 and I'm actually working on it, but I was a little bit busy in the last weeks wirh some other stuff.
I'm struggling a bit with the placement of the min and max gauge label, as it is pretty hard to find the best option which will work for the most cases.

If you want, you can check my [WIP branch](https://github.com/michkami/billboard.js/tree/issue/1633-WIP), test it locally and give me some feedback.
Not full circled gauge is actually rotating the min and max labels depending on the position, but I think I will drop this, as it is pretty hard to actually calculate the position ürecisely enough.
