### ISSUE TITLE
Gauge's arc background color

### ISSUE THREAD

**Issue by Nicolas469** [naver/billboard.js#1804]
## Description
It's already possible to control the color of the main arc of a gauge but would it be possible to control the background color ?

To get something like this for example:

![gauge_background](https://user-images.githubusercontent.com/16453431/101243453-cfc11f80-3700-11eb-8def-07b4ff1ebf46.png)

With CSS, we could override the class **bb-chart-arcs-background**. For example:

```
.bb-chart-arcs .bb-chart-arcs-background {
  fill: black;
}
```

but I would like this color to be dynamically set.

Thanks

**Comment by netil** [comment]
try by installing the `next` tagged version.
```sh
$ npm i billboard.js@next
```
```js
bb.generate({
  ...,
  gauge: {
      background: "red"
  }
});
```

**Comment by Nicolas469** [comment]
It worked, thanks.
[But I had to reverse this commit: https://github.com/naver/billboard.js/commit/8f84cb326b6c6b0dc341ae65b9cdcdae53e7e9b0]

**Comment by netil** [comment]
Updated the condition to get global reference as f41c542c8
