### ISSUE TITLE
How to hide y axis tick text?? - typescript

### ISSUE THREAD

**Issue by juyoungpark718** [naver/billboard.js#1814]
## Description
I want to hide y axis tick text. so i tried to do example in [example site](https://naver.github.io/billboard.js/demo/#Axis.HideTickLineText)
but typescript occured error.

Error is
```
Type '{ show: false; }' is not assignable to type '{ position?: { x?: number | undefined; y?: number | undefined; } | undefined; }'.
Object literal may only specify known properties, and 'show' does not exist in type '{ position?: { x?: number | undefined; y?: number | undefined; } | undefined; }'.
```

Maybe i think that y.tick.text.show is not defined ChartOptions.axis property.(the same for y2)
If I tried the wrong way, I would like you to tell me the right way.

thanks

**Comment by netil** [comment]
Hi @juyoungpark718, thanks for the report!
I'll fix that.

**Comment by netil** [comment]
try by installing the `next` tagged version.
```sh
$ npm i billboard.js@next
```

**Comment by juyoungpark718** [comment]
thanks!! I will try it!
