### ISSUE TITLE
Using "total" as field in bar chart, the width of the bar specific to "total" becomes 0, when max-width property is set.

### ISSUE THREAD

**Issue by SowmithYatam** [naver/billboard.js#1818]
## Description
I have investigated in the billboard.js code and figured out that“total” is used as keyword in a specific structure, which in combination with max width setting, ends up in 0 width for that specific bar instead of the value set.
the issue is in generateGetBarPoints method.
Method $$.getBarW(axis, barTargetsNum) inside generateGetBarPoints returns a number if max width is not set, while it returns this structure {width: result, total: []} if max width is set.

## Steps to check or reproduce
https://codesandbox.io/s/simple-billboardjs-line-chart-forked-cqmro?file=/src/Hello.js

**Comment by netil** [comment]
Hi @SowmithYatam, thanks for the report.
I'll check the issue.
