### ISSUE TITLE
How can I control the outerRadius of the donut chart

### ISSUE THREAD

**Issue by joomation** [naver/billboard.js#1825]
## Description
Hello Billboard Team Can I customize the donut chart's outerRadius as follows? 
It is expressed fixedly not not expanded by an interaction

## Steps to check or reproduce

![donut_issue](https://user-images.githubusercontent.com/28975129/102293906-63a9ab80-3f8b-11eb-9c00-7621931c7877.png)

**Comment by netil** [comment]
Hi @joomation, for now only `innerRadius` is supported.
- https://naver.github.io/billboard.js/demo/#PieChartOptions.InnerRadius

I'll be considering the support for the next release.
