### ISSUE TITLE
2.2.0-next.2: global is not defined

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1826]
## Description
I tested `billboard@2.2.0-next.2` **and** the changes made in #1816 in my local angular 8 project (both separately) and I'm getting an error in dev and prod build in Chrome, Firefox and Internet Explorer:
![grafik](https://user-images.githubusercontent.com/42860868/102329726-044a9c00-3f89-11eb-84ce-1cd15c10325f.png)

## Steps to check or reproduce
1. Create new Angular 8 Project
2. Add `billboard@2.2.0-next.2` and `d3@5.16.0` as dependecies.
3. Add random chart to app component.
4. Start the app with `ng start`

**Comment by netil** [comment]
thanks @michkami, for the report.
