### ISSUE TITLE
Callback for label colors?

### ISSUE THREAD

**Issue by tony** [naver/billboard.js#1845]
Hi, thank you for the project!  This is amazing! And it's TypeScript! (And happy new year!)

Here's a sandbox: https://stackblitz.com/edit/zwjmtr?file=index.ts

## Description
Briefly: The labelling of colors doesn't accept callbacks but normal coloring does

My personal context: I want to use a callback for labels so I can adjust the color of the text based on background (which I look up via the label name, then run a calculation on): `return chroma(dataStore[label.id]).get("lab.l") > 80 ? "black" : "white";`

Context: [`Data.DataColor`](https://naver.github.io/billboard.js/demo/#Data.DataColor) supports passing a callback:

Example:

```javascript
var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 20, 50, 40, 60, 50],
	["data2", 200, 130, 90, 240, 130, 220],
	["data3", 300, 200, 160, 400, 250, 250]
    ],
    type: "bar", // for ESM specify as: bar()
    color: function(color, d) {
	// d will be "id" when called for legends
	return (d.id && d.id === "data3") ?
		d3.rgb(color).darker(d.value / 150).toString() : color;
    },
    labels: {  // However, label coloring doesn't accept color (callback)
      color: function(color, d) {
	// d will be "id" when called for legends
	return (d.id && d.id === "data3") ?
		d3.rgb(color).darker(d.value / 150).toString() : color;
      }
    }
  },
  bindto: "#dataColor"
});
```

As in the example above, we can fill colors via a callback, but there isn't a reciprocal callback for label colors.

![image](https://user-images.githubusercontent.com/26336/103441430-9e5e4580-4c13-11eb-9856-ef98cdc69cab.png)

## Steps to check or reproduce

There isn't a callback for [`Data.DataLabelColors`](https://naver.github.io/billboard.js/demo/#Data.DataLabelColors)

Here's a sandbox: https://stackblitz.com/edit/zwjmtr?file=index.ts

**Comment by netil** [comment]
Hi @tony, thanks for the warm comments.
Unfortunately there's no callback support for `data.label.colors` option for now.

I'll be considering add the feature for the next release.
