### ISSUE TITLE
How to suggest / contribute updated StackBlitz demos?

### ISSUE THREAD

**Issue by tony** [naver/billboard.js#1846]
Is there a place where we can update code in the demos?

## Description
For TypeScript sandbox [X Axis Tick Timeseries](https://naver.github.io/billboard.js/demo/#Axis.XAxisTickTimeseries)

Before: https://stackblitz.com/edit/uxpffm--run?file=index.ts

After (added missing s3 and types): https://stackblitz.com/edit/kjsk6s?file=index.ts

**Comment by netil** [comment]
checkout the related code from here:
- https://github.com/naver/billboard.js/blob/master/demo/chart.js#L493

And send PR(make sure to read contribution doc) for the contribution. :)
- https://github.com/naver/billboard.js/blob/master/CONTRIBUTING.md
