### ISSUE TITLE
Fill colors mismatch with tooltip colors?

### ISSUE THREAD

**Issue by tony** [naver/billboard.js#1847]
Is there a canonical way to specify these?

## Description

![image](https://user-images.githubusercontent.com/26336/103443899-eb98e200-4c28-11eb-8009-14620205e795.png)

## Steps to check or reproduce

Sandbox example: https://stackblitz.com/edit/chart-mouseover-tooltip-colors?file=index.ts

**Comment by netil** [comment]
It seems the specified color value from `data.color` isn't applied for tooltip.
Thanks for the report.

**Comment by netil** [comment]
The second param should pass data type, rather than the data id string.
So, your example code need to be change as follows.
```js
color: (color, label) => {
     // as-is: return dataStore[label] ?? color;
     // to-be: return dataStore[label.id] ?? color;
}
```

**Comment by tony** [comment]
@netil Hi there

I updated to 2.2.0-next.4 here,

can you explain what needs to be changed?  I don't see an `.id` output in the `colors`

https://github.com/tony/cv/pull/1171/files#diff-24a94a1493a54600961bb8d87c244813ba47ddbcdee350436d7853af7a35c4d6R255

https://cv-react-v2.git-pull.com/dev/branch/v2-billboard.js-next/

**Comment by netil** [comment]
@tony try again with the `next.5` release.

You can try the fixed version at:
- https://stackblitz.com/edit/chart-mouseover-tooltip-colors-kclknn?file=index.ts

**Comment by tony** [comment]
@netil Looks good

Visit https://cv-react-v2.git-pull.com/dev/branch/v2-billboard.js-next/ and refresh

![image](https://user-images.githubusercontent.com/26336/104092412-64abc100-5249-11eb-969b-3be092168e1e.png)

![image](https://user-images.githubusercontent.com/26336/104092419-74c3a080-5249-11eb-96eb-96e428378d24.png)
