### ISSUE TITLE
More than 1500 points doesn't recognize mouse events

### ISSUE THREAD

**Issue by roblav96** [naver/billboard.js#185]
![img](https://i.imgur.com/iRnpl3S.png)
The tooltips aren't shown and the zoom feature doesn't work.

**Comment by netil** [comment]
Hi @roblav96, thanks for the report.
Could you provide the generation code for check?

**Comment by netil** [comment]
From the benchmark page, this can be tested with specifying 1.5k data size w/o error.
- https://naver.github.io/billboard.js/demo/benchmark/
