### ISSUE TITLE
Any example of function typed Data.order?

### ISSUE THREAD

**Issue by BlackBindy** [naver/billboard.js#1863]
## Description
I want to use function typed `Data.order` option but I cannot find a proper way to do it.
<br>

| ![image](https://user-images.githubusercontent.com/12558317/104150629-d76d9580-541d-11eb-9491-7def1c196066.png) |
| :-: |
| description |

| ![image](https://user-images.githubusercontent.com/12558317/104150657-f0764680-541d-11eb-8b59-8d0dea250520.png) |
| :-: |
| type definition |

1. it seems like type definition and API description doesn't match (I'm pretty sure that the type of each data must not be a simple `string`)
2. there is no example to follow
3. I tried to figure out what `data` parameter would represent by using some `console.log`s, but it seems like the function is never called once. (there was no log printed on Console with the code below)
    ```js
    data: {
        order: function(...data) {
          console.log(data);
        },
    ...
    ```

<br>

Can you make an example of a function that can be used in `Data.order` function?

**Comment by netil** [comment]
Hi @BlackBindy, when `data.order` option function value is set, is working for non-arc types only for now.
If you're using gauge, donut or pie only "asc", "desc" & null are accepted.

I'll be considering the implementation for the next release.

**Comment by BlackBindy** [comment]
> Hi @BlackBindy, when `data.order` option function value is set, is working for non-arc types only for now.
> If you're using gauge, donut or pie only "asc", "desc" & null are accepted.
> 
> I'll be considering the implementation for the next release.

thanks for your reply 👍🏼 

then, if I want to set `order: null` to keep the order of the input on donut chart, will putting a prefix such as `_` on each key (if keys are number value) be the only solution?

```js
// original data
{
  100: 10,
  101: 20,
  ...
}

// to
{
  _100: 10,
  _101: 20,
  ...
}
```

of course it might work, but if I attach a prefix once, I have to detach it everytime I need to use those keys (which never looks elegant enough).

**Comment by netil** [comment]
@BlackBindy, fixed the issue. I'll be releasing `next` tagged version soon.
So, if you're not hurry recommend use the fixed version.
