### ISSUE TITLE
eventRect is not resizing correctly after loading new data

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#1864]
## Description
As you can see in the GIF below, the event rect is not resizing correctly, after loading new data.
![01  Small window size](https://user-images.githubusercontent.com/42860868/104167393-88fbcf00-53fc-11eb-92cd-68142cd082df.gif)

The larger the window, the more accurately the event rect is calculated, but you can see in the GIF below, that it is still not fully resized.
![02  Large window size](https://user-images.githubusercontent.com/42860868/104167397-8ac59280-53fc-11eb-899b-9a10b2a83be3.gif)

It does not work in `2.2.0-next.5` and `2.1.4`, but I didn't test it in previous releases.

## Steps to check or reproduce
1. Open [this example](https://stackblitz.com/edit/eventrect?file=index.ts).
2. See first GIF above.
3. See second GIF above.

**Comment by netil** [comment]
@michkami, confirmed. Thanks for the report, I'll dig into that.

**Comment by michkami** [comment]
Fast as always :) 
Tested it in my local project and now it works as expected.
Thanks for fast fix!
