### ISSUE TITLE
controlling opacity for scatter plot points

### ISSUE THREAD

**Issue by blazespinnaker** [naver/billboard.js#1867]
https://github.com/naver/billboard.js/blob/6ff9aec01d831c8fe2449da6b87121281829f209/src/ChartInternal/shape/point.ts#L42

Hard codes the opacity for scatter plots.  It'd be good if this was config as the points can be hard to see, especially when you want to distinguish between different colors on a combo chart that has both scatter and lines (scatter is the only way to call attention to particular points on a line, afaik)

I added

``point_scatter_opacity: 0.5,` to `

https://github.com/naver/billboard.js/blob/af1dbd7acbc687095e5712edb2fedbee0ffddce1/src/config/Options/common/point.ts

and
`
return isValue(d.value) ? (this.isScatterType(d) ? this.config.point_scatter_opacity : opacity) : 0;`

If there is a better way to do this, please let me know.

**Comment by netil** [comment]
well, I agree inline styling aren't good in may ways. It should be removed and give more flexibility for those wanting styling only by own css rules.
