### ISSUE TITLE
Programatic zoom on timeseries chart does not work

### ISSUE THREAD

**Issue by ebencollins** [naver/billboard.js#1868]
## Description
It seems that `chart.zoom(domain)` doesn't have any effect since version 1.8.1 when `axis.x.type` is `timeseries`

Expected outcome: Chart zooms to show only points in the passed domain
Actual outcome: No apparent change in chart domain

## Steps to check or reproduce
- https://jsfiddle.net/mcs5nh3y/ - timeseries chart zoom with v2.1.4 (doesn't work)
- https://jsfiddle.net/36hynej8/ - non timerseries chart zoom with v2.1.4 (works)
- https://jsfiddle.net/nz5s9Lo2/ - timeseries chart zoom with v1.8.1 (works)
- https://jsfiddle.net/7605gr1t/ - timeseries chart zoom with v1.9.0 (doesn't work)

**Comment by netil** [comment]
Hi @ebencollins, thanks for the report. I'll check that.

**Comment by netil** [comment]
Seems the side effect caused by the call of `withinRange()`.
 https://github.com/naver/billboard.js/commit/ec24c2cc6e91fa43930eea6a2d851a2080ced47c#diff-59c53a667c95a96fe0e27f13571c8e4f7167e372dc109b02edfb67ac7170af89R46
