### ISSUE TITLE
table view

### ISSUE THREAD

**Issue by blazespinnaker** [naver/billboard.js#1873]
a simple table view would be ideal.   many charting libraries have this.   all the data and structure is there and being able to transform  between chart and table view would be useful in some cases.

**Comment by netil** [comment]
@blazespinnaker, can you give an explicit example for this?

**Comment by blazespinnaker** [comment]
Here's a couple:

https://developers.google.com/chart/interactive/docs/gallery/table

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/export-data/showtable/

Sometimes you want to see a visual / trending overview, sometimes you want to see precise #s

**Comment by netil** [comment]
Got it. I think it'll be more adequate being implemented as plugin.
I'll be considering it. Thanks.

**Comment by blazespinnaker** [comment]
Another use of table view is debugging the library itself to quickly verify that graphs are lining up ask expected.

**Comment by blazespinnaker** [comment]
fwiw, used tabulator here.  Pretty good html table lib
