### ISSUE TITLE
How to fill in missing time series data?

### ISSUE THREAD

**Issue by captainadd49** [naver/billboard.js#1886]
## Description

I am unable to create a time series chart with inconsistent data. If I have a missing data point, I would like it to connect the two adjacent points instead of leaving it blank.
![image](https://user-images.githubusercontent.com/34423634/104953900-2a929b80-597c-11eb-83f8-0c6cc038ba38.png)
How do I get it to connect the two blue dots without leaving a gap in the middle?
## Steps to check or reproduce

Here is my code that I am working with now

```
var chart = bb.generate({
    data: {
      x: "x",
      xFormat:'%Y-%m-%d %H:%M:%S',
      columns: [
  	["x", "2013-01-01 22:05:00", "2013-01-02 23:12:00", "2013-01-03 12:23:34", "2013-01-04 07:15:32", "2013-01-05 02:02:03", "2013-01-06 05:05:05"],
  	["data1", 30, 200, null, 400, 150, 250],
  	["data2", 130, 340, 200, 500, 250, 350]
      // {{ date | safe}},
      // {{value | safe}}
      ],
      type: "line", // for ESM specify as: line()
    },
    axis: {
      x: {
        type: "timeseries",
        tick: {
          format: "%Y-%m-%d %H:%M:%S"
        }
      }
    },
    bindto: "#lineChart"
  });
```

**Comment by netil** [comment]
Hi @captainadd49, you can use [`line.connectNull`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.line) option for this.

```js
    line: {
      connectNull: true
    },
```

<img src=https://user-images.githubusercontent.com/2178435/104975914-52970300-5a3f-11eb-9a06-93453d68c69a.png width=500>
