### ISSUE TITLE
in Version 2.2.0 syntax error occurs in IE11

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1913]
Hello tried the ne version also in IE11 and syntax error occurs!

Would you please fix that?

Kind regards

Ronny

**Comment by michkami** [comment]
I updated to 2.2.0 in my local angular 8 project and had no syntax errors in IE11 yet.

**Comment by RonnyWeiss** [comment]
I use this file:

https://naver.github.io/billboard.js/release/latest/dist/billboard.min.js

and got the error in ie can you please check that:

![grafik](https://user-images.githubusercontent.com/30749177/106263899-496b1a80-6225-11eb-93d2-e3d757c39026.png)

**Comment by RonnyWeiss** [comment]
i just use an other file name :-)

**Comment by RonnyWeiss** [comment]
in full file the error occurs in line 20,21
![grafik](https://user-images.githubusercontent.com/30749177/106264237-b383bf80-6225-11eb-92fe-9460d4f4a216.png)

**Comment by netil** [comment]
Hi @RonnyWeiss, the issue comes from Webpack v5, where webpack's runtime code uses ES2015 syntax.
- https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11

After adding config option to transpile for older browser, looks working fine.
I'll be release the patch version soon.

**Comment by RonnyWeiss** [comment]
Thank you very much. :-)
