### ISSUE TITLE
Question for selecting region in pie chart

### ISSUE THREAD

**Issue by bryceosterhaus** [naver/billboard.js#192]
Hi, I am using a pie chart I was wondering if it is possible to use the "focus" behavior and styling for when a region of the pie is selected.

For example, I want to click on the region of the pie and show a list of items within that segment somewhere else. So for the styling of the pie, I want it to look like below and not reset its focus when I move the cursor over different parts of the pie. I only want to change when selected.

<img width="390" alt="screen shot 2017-11-16 at 9 54 03 am" src="https://user-images.githubusercontent.com/6843530/32907295-6f29d542-cab4-11e7-8ec5-b67060ca2b5c.png">

I wanted to use the data events for 'onover' and 'onselected' but I couldn't find a way to prevent their default behavior.

Is this possible at the moment, or should I stick to the default behavior or focusing and selecting?

**Comment by netil** [comment]
I made an example how to handle that.
- https://jsbin.com/boyusuz/3/edit?html,js,output

The key points are:
- Remove bound events
  ```js
    onrendered: function() {
        // remove all mouse bound events
	    this.main.selectAll(".bb-arcs path")
            .on("mouseover",null)
            .on("mouseout",null)
            .on("mousemove",null);
    }
  ```
- Update the CSS as your needs
  ```js
  /* Set opacity for defocused data area */
  .bb-target.bb-defocused { opacity: 1 !important; }
  ```

![pie-select](https://user-images.githubusercontent.com/2178435/32930266-f630fd8a-cba0-11e7-932e-a952a95e7fc0.gif)

**Comment by bryceosterhaus** [comment]
Thanks for the example and quick reply!

**Comment by bryceosterhaus** [comment]
@netil is there any place I can find documentation on `this.main`?

**Comment by netil** [comment]
@bryceosterhaus, internal(or private) properties/methods is not really "officially" recommended to be used, because those values and behaviors  can be changed in the future release not maintaining backward compatibility. 

So, if you use one of those not documented, it means can have some issue upgrading with future release.

Taking this in mind, the 'correct' and basic approach will be :

```js
// Every callback options are bound and called at the same context.
// That means `this` is pointing the chart instance you generated,
// which technically you can approach internal values.
onrendered: function() {
      // this code should be substitute
      // this.main.selectAll(".bb-arcs path")

      // the above is equivalent as
      d3.select("#chart g").selectAll(".bb-arcs path")
  }
```
