### ISSUE TITLE
Configuration item interaction causes a chart to fail to render

### ISSUE THREAD

**Issue by kevkj** [naver/billboard.js#1924]
## Description
The configuration item "interaction" provides the opportunity to disable user interaction with the chart. Using the configuration item with enabled: false will result in the chart not being rendered properly.

## Steps to check or reproduce
https://naver.github.io/billboard.js/demo/#Grid.GridLines

Add the following to the configuration
```js
  interaction: {
    enabled: false
  },
```

**Comment by netil** [comment]
Hi @kevkj, thanks for the report. I'll check the issue.
