### ISSUE TITLE
X-axis Ticks lag behind as subchart is brushed

### ISSUE THREAD

**Issue by doug-the-guy** [naver/billboard.js#1949]
## Description
When brushing a subchart, the x-axis ticks laterally lag behind their corresponding data points. When brushing stops, they finally snap to them.

## Steps to check or reproduce
This is demonstrated in this fiddle:
[jsFiddle w/ billboard](https://jsfiddle.net/doug_the_guy/kmeLwdxc/14/) (billboard v2.2.3, d3 v4.13)

Compare this to c3js where the ticks keep up with their data points:
[jsFiddle w/ c3](https://jsfiddle.net/doug_the_guy/kjce6ofm/2/) (c3 v0.7.20, d3 v4.13)

**Comment by netil** [comment]
@doug-the-guy thanks for the report.
Agree that needs to be improve on this. I'll be checking the issue.
