### ISSUE TITLE
Legend doesn't always update when toggling plots

### ISSUE THREAD

**Issue by doug-the-guy** [naver/billboard.js#1950]
## Description
If there is an alternative way to toggling plots, like a button for showing all of the plots and one for hiding all of them, the corresponding legend items don't always toggle accordingly.

## Steps to check or reproduce
[jsFiddle](https://jsfiddle.net/doug_the_guy/kmeLwdxc/17/) (billboard v2.2.3, d3 v4.13)
To reproduce, follow these steps:
1. Toggle data2 plot by clicking it in the legend.
2. Click the "Hide All" button.

The blue data1 plot hides, but its legend does not toggle. It _will_ if you hover and unhover over it.

There are other bad state combinations that can be uncovered if you randomly toggle by the legend or buttons.

Adding `chart.flush()` does not fix it.
Explicitly passing in the plot keys to `show/hide` also does not fix it.

**Comment by netil** [comment]
Confirmed. I'll check the issue, thanks for the report.
