### ISSUE TITLE
horizontal bar chart labels cut off. sizing issue?

### ISSUE THREAD

**Issue by tjohannto** [naver/billboard.js#1955]
I have a fixed size horizontal bar chart with potentially rather long labels. The label with the biggest data sometimes gets cut off althought there still would be space to reduce the space for the bars as well as I to add a parameter for adding top padding for Y. 
```
y: {
      show:false,
        padding : {
            top: Math.ceil(maxLabelWidth)
        }
    }
```
It uses the max label width in px measured by 
```
function getWidth(text, font) {
  const canvas = document.createElement('canvas'),
        context = canvas.getContext('2d');
  context.font = font;
  return context.measureText(text).width;
}

```
![image](https://user-images.githubusercontent.com/45257386/108492482-82872f80-72a5-11eb-83af-2f9a63ac0aae.png)

see https://jsfiddle.net/ojrq6ydk/

It seems to be an internal BB sizing issue. Am I right there? Is there a way to prevent the labels from beeing cut off?

**Comment by netil** [comment]
In that case you can use [clipPath](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.clipPath) option.

```js
const chart1 = bb.generate({
  bindto: d3.select('#chart1'),
  clipPath: false,
  ...
};
```

**Comment by tjohannto** [comment]
Thanks for your quick reply. I have updated my jsfiddle using clipPath. 
It is still not as expected:

![image](https://user-images.githubusercontent.com/45257386/108511782-a6a43a00-72c0-11eb-9737-bf813a2854a9.png)

pls see https://jsfiddle.net/ojrq6ydk/10/

**Comment by netil** [comment]
with a combinations of `clipPath + padding.right` will make to display full text.
![Kapture 2021-02-22 at 17 50 10](https://user-images.githubusercontent.com/2178435/108684596-72d24a00-7536-11eb-96e7-fc1de5449da6.gif)

```js
  clipPath: false,
  padding: {
    right: 100
  },
```

**Comment by tjohannto** [comment]
Thank you very much for your answer. I just needed to additionally move the padding parameter from y-axis (like used in C3) to main config ;)
