### ISSUE TITLE
Insert Image into Region

### ISSUE THREAD

**Issue by CalebKester** [naver/billboard.js#1968]
I need a custom image to be used at a region or on the x axis. I think I need to use the onrendered function to insert this smilar to #834 but am struggling with getting anything to work.

Here's the design I'm working off of. I had to do something similar with the tooltip, but that was easily done by a ::before css element.

![image](https://user-images.githubusercontent.com/1319995/109743958-25d61f80-7b97-11eb-8072-6d5dfe0e115e.png)

**Comment by netil** [comment]
Hi @CalebKester, this can be achieved by adding and updating necessary nodes manually.
I made a working online demo:
- https://jsfiddle.net/netil/h596c1qu/

![Kapture 2021-03-04 at 18 29 08](https://user-images.githubusercontent.com/2178435/109942550-a4f26180-7d17-11eb-9003-beb22542f7f6.gif)

There're two parts of configurations, where you need to update.
I guess you can understand without other explanation.

```js
onrendered: function() {
    const {x} = this.internal.scale;

    // (1) scale position according tick value
    const pos = {
        x1: x(3),
        x2: x(5)
    };

    // (2) configuration
    const strokeWidth = 2;
    const outerLineHiehgt = 5;
    const imageSize = {width: 20, height: 20};		
    const imgUrl = "https://github.githubassets.com/images/icons/emoji/unicode/1f603.png";

    const axisX = this.$.main.select(".bb-axis-x");

    let g = axisX
    .selectAll("g.line")
    .data([1]);

    const gEnter = g.enter()
    .append("g")
    .classed("line", true);

    gEnter.append("line").classed("x", true).style("stroke", "red").style("stroke-width", strokeWidth);
    gEnter.append("line").classed("outer", true).style("stroke", "red").style("stroke-width", strokeWidth);
    gEnter.append("image").attr("href", imgUrl).attr("width", imageSize.width).attr("height", imageSize.height);

    g = g.merge(gEnter);

    g.select("line.x")
    .attr("x1", pos.x1)
    .attr("x2", pos.x2);

    g.select("line.outer")
    .attr("x1", pos.x2)
    .attr("x2", pos.x2)
    .attr("y1", -outerLineHiehgt)
    .attr("y2", outerLineHiehgt);

    g.select("image")
    .attr("x", pos.x1 - (imageSize.width/2))
    .attr("y", -(imageSize.height/2));
}
```

**Comment by CalebKester** [comment]
Thank you! this was incredibly helpful! Both how the internal scale works as well as how to select and append d3.
