### ISSUE TITLE
Tooltip is placed incorrectly after zooming

### ISSUE THREAD

**Issue by typingtanuki** [naver/billboard.js#197]
## Description

The tooltip showing on hover follows the mouse very well until user starts zomming.
After that the tooltip show at the position it would have shown if the user did not zoom at all instead of near the data point.

## Steps to check or reproduce

* Open this example: https://naver.github.io/billboard.js/demo/#Interaction.Zoom
    * Hover and see that the tooltip horizontal position is always close to each point
* Zoom-in using the mouse wheel (the more the better)
    * Hover again and see that the tooltips are not following the data points anymore

**Comment by netil** [comment]
I'll take a look on that. Thanks for reporting the issue.

**Comment by OliverFischer** [comment]
Tested on firefox, chrome and safari. point event raising the tooltip works correctly, but it seems that the calc for the display position does not reflect the zoom level, tooltips are shown on positions of a higher/lower zoom level. Seems to me that the positioning of the tooltip only does not reflect the current zoom level.

**Comment by typingtanuki** [comment]
I looked into the issue and got something working using:
`$$.x.orgDomain()` and `$$.zoomScale.domain()` inside `tooltipPosition`.

Does this seem like a good solution ? (I am not sure which API is recommended to fetch the zoom extent)

Also I look at c3 code and the position calculation is the same as current billboard code. The difference might be at which level the tooltip is attached resulting in zoom being applied or ignored from the coordinates. Is it better to try to stick with c3 or is it OK to come up with a different solution ?
Is the tooltip position returned from `tooltipPosition` part of the API you want to preserve compatibility with ?
