### ISSUE TITLE
sectioned time series 

### ISSUE THREAD

**Issue by tiarnan-conlon** [naver/billboard.js#1971]
Hi, love the library, thanks for all the hard work!
Would anybody be able to suggest how i could create a chart like this?
I can create a timeseries with all the events but can't figure out how to colour the sections
![image](https://user-images.githubusercontent.com/77328473/110122757-eaff0200-7db7-11eb-8510-a802f0595af0.png)
It's just a timeseries of an on/off event, I can create a timeseries with all the events but can't figure out how to colour the sections
Thanks!

**Comment by tiarnan-conlon** [comment]
Can get pretty close with this:
`
var chart = bb.generate({
  data: {
    x: "x",
    columns: [
	["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
	
["data1", 100, 100, 100, 0, 0, 100],
	["data2", 0, 0, 0, 100, 100, 0]
    ],
    types: {
      data1: "area", // for ESM specify as: areaSpline()
      data2: "area", // for ESM specify as: areaSpline()
    },
    groups: [
      [
        "data1",
        "data2"
      ]
    ]
  },

  axis: {
    x: {
      type: "timeseries",
      tick: {
        format: "%Y-%m-%d"
      }
    }
  },
  bindto: "#timeseriesChart"
});`

but the edges are sloped.

**Comment by netil** [comment]
Hi @tiarnan-conlon, you can try [regions](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.regions) option.
Checkout the online demo:
- https://jsfiddle.net/netil/bc1or4p5/

<img src=https://user-images.githubusercontent.com/2178435/110265011-ed529d80-7ffd-11eb-9259-9258ac7935d7.png width=500>

**Comment by tiarnan-conlon** [comment]
Hi @netil this looks perfect thanks
