### ISSUE TITLE
x.axis.max with date don't work anymore

### ISSUE THREAD

**Issue by pvictor** [naver/billboard.js#1981]
## Description
When using `x.axis.max` with a date for a timeserie chart an error occurs.
It worked with older versions (< 2.0.0)

## Steps to check or reproduce

With latest version, if you uncomment `max` option it breaks : https://codepen.io/pvictor-r/pen/ExNGebL

With 1.12.11 it works: https://codepen.io/pvictor-r/pen/GRNzppO

Code to reproduce:

```js
var chart = bb.generate({
  data: {
    x: "x",
    columns: [
      ["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
      ["data1", 30, 200, 100, 400, 150, 250],
      ["data2", 130, 340, 200, 500, 250, 350]
    ],
    type: "line", 
  },
  axis: {
    x: {
      max: "2013-01-04", // <- generate an error
      type: "timeseries",
      tick: {
        format: "%Y-%m-%d"
      }
    }
  },
  bindto: "#timeseriesChart"
});
```
Thanks!

Victor

**Comment by netil** [comment]
Hi @pvictor, confirmed the issue.
Thanks for the report.
