### ISSUE TITLE
tooltip for every second x axis label

### ISSUE THREAD

**Issue by shahkiin** [naver/billboard.js#1990]
## Description
Hi, I have a problem with displaying tooltips for X axis labels. Exactly this error occurs when we have more than 15 labels to show. Then, when you hover the mouse over the labels, the tooltips are displayed for every second label. Any of you may have already encountered such a situation, or know what to do in such a situation?

## Steps to check or reproduce
Example below
https://lgugdd.stackblitz.io
https://stackblitz.com/edit/lgugdd?file=index.js

**Comment by netil** [comment]
Hi @shahkiin, confirmed the issue. For some x Axis ticks, title element aren't generated.
I'll be checking the issue.

**Comment by netil** [comment]
The issue happens only for rotated axis. Non rotated works fine.
