### ISSUE TITLE
Toggle subchart after migration from c3 to 1.12.11

### ISSUE THREAD

**Issue by bj00rn** [naver/billboard.js#1993]
## Description
We are in the process of migrating from `c3`
Seems that toggling subchart no longer works after migration from `c3` to billboard.

Has this api been removed?

"billboard.js": "1.12.11",

## Steps to check or reproduce

Invoking `chart.subchart.show()` after initialisation gives error  `Uncaught TypeError: Cannot read property 'show' of undefined`

Working c3 example: http://jsfiddle.net/bqgcxo4a/5/

**Comment by netil** [comment]
Hi @bj00rn, is because billboard.js forked C3.js `v0.4.11`, where subchart API didn't implemented.
I'm not sure providing subchart API is useful, but anyway.

I made an online example of toggling subchart based on billboard.js v2.x.
- https://jsfiddle.net/netil/pft82L6d/

I highly recommend to migrate to 2.0, rather than 1.x.

**Comment by bj00rn** [comment]
> Hi @bj00rn, is because billboard.js forked C3.js `v0.4.11`, where subchart API didn't implemented in that version.
> I'm not sure providing subchart API is useful, but anyway.
> 
> I made an online example of toggling subchart based on billboard.js v2.x.
> 
> * https://jsfiddle.net/netil/pft82L6d/
> 
> I highly recommend to migrate to 2.0, rather than 1.x.

Thanks!

Will move to 2.x, in the process of migrating and notices the subchart api wasn't working after migrating. 

Would you consider a PR backporting subchart api functionality from C3 i n current version of billboard?

**Comment by netil** [comment]
@bj00rn, I'll be implementing this for the next `v3` release.

**Comment by bj00rn** [comment]
> @bj00rn, I'll be implementing this for the next `v3` release.

awesome!! 🌹 🌷 🥇
