### ISSUE TITLE
produce production/minimized code with v3 (d3v6)

### ISSUE THREAD

**Issue by tjohannto** [naver/billboard.js#2023]
With BBjs v2.x and d3 v5 I did use Babel and UglifyJS to produce minimized "production" javascript files. With BB v3.x and d3 v6 this does not seem to work properly, at least with my current settings. 

Are there any guides, howtos or recommendations how to minimize JS files that use BBjs v3.x and d3 v6?

**Comment by netil** [comment]
Hi @tjohannto, basically there's no breaking changes affecting in terms of bundling.

I'm not sure if you're facing issue on:
- producing the 'build' bundle file
- the build isn't working properly
- the build isn't working for legacy browsers (ex. IE11)
   if so, for legacy browser build, checkout the doc: 
   https://github.com/naver/billboard.js/wiki/How-to-bundle-for-legacy-browsers%3F

if possible share your build configuration and detailed issue to figure out more in detail.

**Comment by tjohannto** [comment]
There are breaking changes as d3v6 now uses ES2015 or ES6. For example selection.nodes() now uses Array.from() which does not work when using "old" Babel/UglifyJS solution because Babel transpills the code...

The issue is about build my application using BBjs v3.x. I think I'll "just" have to use another solution than UglifyJS and Babel to produce min files.
