### ISSUE TITLE
Sequentially exporting dashboard of charts

### ISSUE THREAD

**Issue by tjohannto** [naver/billboard.js#2030]
We are still in the process of migrating our reporting solution form C3js to billboardsJS as well as to ES6+. As billboardJS provides an export function that enables us to remove all canvg references, which is good, we are now face an issue which I can’t solve even after two days of searching and investigating, or at least I was not able to find any solution I like 😉.

Obviously, I am not a “pro” in modern Javascript programming and I thought anyone here you might have one of your brilliant ideas. Also I very much hope it is OK to ask such a "howto" question here. (is it?)

I have produced some pseudo code example to illustrate the problem:
```
const pdf = new jsPDF( /*orientation*/ 'landscape', /*unit*/ layoutSettings.unit, /*format*/ layoutSettings.format, /*compressPdf*/ compressionMode !== 'NONE');
const chartsSelection = d3.selectAll("div.chart-container").filter(function(){ return this.style.display !== "none"; });
[...]
chartsSelection.each(function() {
[...]
const svgContainer = d3.select(this).select("svg").node();
[...]
let imgSize = { width: summaryPie ? layoutSettings.maxWidth * 3/4 : layoutSettings.maxWidth, height: chartImgHeight };
const bbChart = angular.element(svgContainer.parentNode).data();
const originalHeight = svgContainer.clientHeight;
const originalWidth = svgContainer.clientWidth;
imgSize = chartRenderService.getChartSize(bbChart, imgSize.width, imgSize.height);
bbChart.export({
  width: imgSize.width,
  height: imgSize.height,
  preserveAspectRatio: false,
  mimeType: 'image/png'
}, dataUrl => {
  pdf.addImage(dataUrl, format, posX, posY, imgSize.width, imgSize.height, name, compressionMode);
});
[...]
}
pdf.save('report.pdf');

```
The export() function of billboardJS uses a callback function when the dataUrl has been created successfully, which is asynchronous, obviously. But we need the chart images to be added to the PDF sequentially correctly in the original sequence (as, for example the PDF will have several pages). Also the next step after the while loop (saving the pdf) should not be started until all images have been added to the PDF.

Do you have any guidance how to deal with that?

**Comment by netil** [comment]
I'm not sure if I understood correctly, 
- There're multiple charts generated where need to be exported in sequential order.
- As of `.export()` works asynchronously, the if is called even sequentially, there're possibility to not being exported sequentially.


```js
bb.generage(...);

function exportToImg() {
	const cb = dataUrl => {
		const img = document.createElement("img");

		img.src = dataUrl;	
		document.body.appendChild(img);

		inst.length && inst.shift().export(null, cb);
	}

	const inst = bb.instance.concat();

	inst.shift().export(null, cb);
}
```

**Comment by tjohannto** [comment]
Thank you very much. I have decided for a solution like this:
```
const chartSelection = d3.selectAll("div.chart-container");
 
const chartsArray = Array.from(chartSelection);
// promiseArray has the same ordering as chartsArray
const promiseArray = chartsArray.map((chart, chartIndex) => {
  const node = d3.select(chart).select('svg').node();
  const chart = angular.select(node.parentElement).data();
  // something like...
  return new Promise(resolve => {
      const dataUrl = chart.export(...);
      // any other calculations could go here...
     resolve({
chartIndex,
width,
height, 
dataUrl,
});
  };
});
Promise.all(promiseArray).then(items => {
  items.forEach(imgData => pdf.addImage(...));
  pdf.save(...)   
})
```
I simply do not prefer using recusrive functions ;)
