### ISSUE TITLE
Q: How to set initial subchart range on load

### ISSUE THREAD

**Issue by kinekt4** [naver/billboard.js#2037]
## Description

I'm implementing the Billboard Subchart: https://naver.github.io/billboard.js/demo/#Interaction.SubChart

I would like to be able to set the initial subchart range when chart loads without user interaction.

Such as like this: https://codepen.io/apexcharts/pen/rqWeBX

Is it possible? I've clicked through the docs but I haven't found anything.

## Steps to check or reproduce

* Start with this: https://naver.github.io/billboard.js/demo/#Interaction.SubChart
* End with this: https://codepen.io/apexcharts/pen/rqWeBX

**Comment by netil** [comment]
Hi @kinekt4, yes you can.
I made an example where at the initialization will select specified subchart range.

I'll be adding as new option for next release to facilitate the process.

```js
bb.generate({
  data: {
    columns: [
		["sample", 30, 200, 100, 400, 150, 250]
    ],
    type: "line"
  },
  subchart: {
    show: true
  },
  onafterinit: function() {
	  const {x}= this.internal.scale;

          // specify the initial range for subchart selection according x Axis domain value
	  const range = [2, 3]; 

	this.internal.brush.move(
		this.internal.brush.getSelection(),
		range.map(v => x(v))
	);
  }
});
```
