### ISSUE TITLE
Passing a number as the padding of the x axis breaks

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#2038]
## Description
The type definitions for `axis.x.padding` are saying that it expects `{ left?: number, right?: number } | number`. But passing a `number` breaks. It looks like `Axis.getPadding()` handles it fine but not `Axis.getXAxisPadding()`

## Steps to check or reproduce
Create a timeseries X axis using ticks and padding. It breaks when passing the padding as a number (instead of putting the same padding on both sides)

**Comment by netil** [comment]
Hi @stof, I'm not getting error with below option.
Could you share reproducible option?

```js
bb.generate({
  data: {
    x: "x",
    columns: [
	["x", "2020-01-01", "2020-01-02", "2020-01-03", "2020-01-04", "2020-01-05", "2020-01-06"],
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 340, 200, 500, 250, 350]
    ],
    type: "line"
  },
  axis: {
    x: {
      type: "timeseries",
      tick: {
        format: "%Y-%m-%d"
      },
      padding: 100
    }
  }
});
```

**Comment by netil** [comment]
Is reproducible when subchart is shown, and dragging subchart area happens the error.
@stof  I'll check the issue. Thanks for the report!
