### ISSUE TITLE
How to plot with non-uniform x axis values

### ISSUE THREAD

**Issue by esquires** [naver/billboard.js#2052]
## Description

I would like to create a chart with x values that have non uniform changes but have the plot show the x axis labels with a uniform change. 

Here is a plot from [matplotlib](https://matplotlib.org/) showing the x axis formatting I was hoping to create.
```python
import matplotlib.pyplot as plt
plt.plot([0.1, 0.3, 0.6, 0.9, 10], [4, 1, 6, 8, 10])
plt.show()
```
![temp](https://user-images.githubusercontent.com/9272110/115267882-adf09400-a107-11eb-94a5-e52826038f15.png)

Can you help me see how to create this axis in billboard?

Here is an image of the billboard chart with the same parameters:

![billboard](https://user-images.githubusercontent.com/9272110/115268527-5b63a780-a108-11eb-80d8-944820240679.png)

## Steps to check or reproduce
HTML File
```html
<!-- index.html -->
<div id='lineChart'></div>
```

Javascript File
```js
import "billboard.js/dist/theme/insight.css";
import bb from "billboard.js";

var chart = bb.generate({
  data: {
    xs: {
      data1: "x1",
    },
    columns: [
	["x1", 0.1, 0.3, 0.6, 0.9, 10],
	["data1", 4, 1, 6, 8, 10],
    ],
    type: "line",
  },
  bindto: "#lineChart"
});
```

**Comment by netil** [comment]
Hi @esquires, specify x Axis type as 'category'.
> **Ref.** Checkout which are x Axis types and its differences: https://github.com/naver/billboard.js/issues/2009#issuecomment-810217648


```js
  axis: {
  	x: {
      	  type: "category",
          tick: {
      	    centered: true
          }
       }
  },
```
I made an online working example:
- https://jsfiddle.net/netil/0vgz395y/

<img src=https://user-images.githubusercontent.com/2178435/115318322-7ee62b00-a1b8-11eb-913a-c7e51875bb9a.png width=500>

**Comment by esquires** [comment]
Thanks @netil! I very much appreciate your response. I think the problem with using `type: 'category'` is that it makes the horizontal distances between the data the same even though there is a clustering in the x region of 0 to 1 and then an outlier measurement at 10. In the graph you showed this clustering is not apparent since each datapoint is plotted with the same horizontal change from the previous datapoint. In other words, the tick marks and labels are equidistant even though the underlying measurement is not.

Is it possible to make the green line in the graph I sent stay the same and just adjust the tick labels and axis? Here is some more detail:

![billboard](https://user-images.githubusercontent.com/9272110/115329745-c04aec00-a160-11eb-88d7-35519d2c525e.png)

**Comment by netil** [comment]
Hmm, IMO is not correct way to represent data without correlating data and its corresponding axis tick values.

To fulfill your requirement, it needs deal with some trick(but, as I said is not recommended as correct approach to visualize data values).
- https://jsfiddle.net/netil/0vgz395y/9/

<img src=https://user-images.githubusercontent.com/2178435/115340902-8b7f7900-a1e2-11eb-9240-af8e7fa2e664.png width=500>

**Comment by esquires** [comment]
Thanks for the feedback! I think you make an interesting point that this may not be the correct way to represent the data. Is the recommended approach to use categorical?

Other charting libraries I have used (e.g. the matplotlib plot in the original post) default to having tick labels not line up with the data (users then use circles on the datapoint to highlight where the measurements occurred). In billboard, if we use `type: line` then we get x labels on top of each other (this is the 2nd plot in the original post) so the x axis labels are not legible (this can be worsened by adding more measurements with x values between 0 and 1). If we use `type: categorical` then it seems like it misrepresents the data since measurement outliers (the x values are clusters around 0 to 1 with an outlier measurement at 10) are shown equidistant from each other.

Is there a recommended way to represent this type of data with billboard?

**Comment by netil** [comment]
@esquires, forget about the previous comment.
With the below example, you can make it in more simple way.
- https://jsfiddle.net/netil/0vgz395y/16/

```js
bb.generate({
  data: {
    x: "x",
    columns: [
	["x", 0.1, 0.3, 0.6, 0.9, 10],
	["data1", 4, 1, 6, 8, 10]
      ],
      type:"line"
  },
  axis: {
    x: {
      tick: {
        values: [0, 2.5, 5, 7.5, 10]
      }
    }
  },
  bindto: "#chart"
});
```

**Comment by esquires** [comment]
Thanks!
