### ISSUE TITLE
Incorrect type definition of TooltipOptions.onshow

### ISSUE THREAD

**Issue by BlackBindy** [naver/billboard.js#2056]
## Description
```ts
export interface TooltipOptions {
  // ...
  onshow?(this: Chart, selectedData: DataItem): void;
}
```
Current type definition of `TooltipOptions.onshow` is like above. But when I tested it, it seems like the type of `selectedData` is `DataItem[]` not `DataItem` as defined.

<br>

![image](https://user-images.githubusercontent.com/12558317/115484409-bb378b00-a28d-11eb-9296-ea7be630b59e.png)
> the result of `console.log(selectedData)`

<br>

## Steps to check or reproduce
```ts
bb.generate({
  // ...
  tooltip: {
    onshow: selectedData => {
      console.log(selectedData);
    }
  }
});
```

**Comment by netil** [comment]
Hi @BlackBindy, thanks for the report.
Would you like to send PR for the fix?
