### ISSUE TITLE
Heatmap Support

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#2064]
Hello

Is it possible to add a heatmap support into your chart lib? 

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
An example could be: https://www.d3-graph-gallery.com/heatmap.html

**Comment by adschm** [comment]
+1

**Comment by aklen** [comment]
+1

**Comment by norbertbede** [comment]
+1

**Comment by RonnyWeiss** [comment]
Thank you very much for implementing this!
