### ISSUE TITLE
Opacity for regions

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2068]
When using x-based regions in a (timeseries) line plot, I'm able to adjust the fill color for the regions by using a custom class. However, the fill-opacity of the child `rect` element is set via a style attribute to the rect directly, so I can only overwrite it via

```
.mycustomregionclass rect {
    fill-opacity: 0.4 !important;
}
```

Since using !important is not really desirable, I wonder whether a) there is another way to achieve this in a nicer way or b) the implementation can be changed somehow so the rect style can be overwritten.

Example of created region:
```
<g class=" bb-region bb-region-3 chart-time-region">
<rect x="32" y="0" width="0" height="266" style="fill-opacity: 0.1;"></rect>
</g>
```

**Comment by netil** [comment]
well, the `fill-opacity` property is set internally during the rendering process.
So, if you want to remove the inline prop setting, need to remove it manually within `onrendered` callback.

```js
  onrendered: function() {
	this.$.main.selectAll(".bb-region rect")
		.style("fill-opacity", null);
  }
```

**Comment by adschm** [comment]
Okay, so
* this then is still global for all regions, but since I _remove_ the property, I would then be able to define my own values via CSS separately (just without important)?
* How stable are the "internal" class names (like .bb-region) expected to be? I wondered several times already whether it's really worth adding a custom class name via the relevant APIs or whether I could just use the internal ones for my custom CSS?

**Comment by adschm** [comment]
In the meantime, I can confirm that the workaround with _onrendered_ is working for me. Thanks!

**Comment by netil** [comment]
@adambot great!. Anyway, I'll look for the possibility to implement an option to avoid inline css setting.
But in that case those removed css props should be set separately by the users. Is to give an alternative option who wants style separately.

**Comment by netil** [comment]
well, there're several reasons, but mainly to handle visibility of chart elements and also for transitions.
For ex. doing click or mouseover on legend items, data series will react applying opacity, where inline css props are playing in that scenario.

**Comment by netil** [comment]
removed setting inline css for some props.
- checkout the details at #2094
