### ISSUE TITLE
Question concerning other shapes than "circles" for line points #feature

### ISSUE THREAD

**Issue by julien** [naver/billboard.js#209]
## Description

This question is related to #173

While it's nice to be able to use other shapes than circles for line charts, it might be more interesting to be able to alternate between these different shapes.

Since an image is worth a thousand words, this screenshot might be more explanatory:

<img width="975" alt="alternate-markers" src="https://user-images.githubusercontent.com/5572/33438357-df85ea38-d5ea-11e7-8e10-f565671eea5c.png">

The goal would be to make it easier to distinguish between the different lines. (i.e. If you have difficulty distinguishihng colors).

As a solution, I'm proposing #208

What do you think of the idea?

Thanks!

**Comment by jbalsas** [comment]
I'm attaching a couple of designs from our UX team that show the motivation (specially from an accessibility perspective) of these changes (and others like line and fill patterns).

<img width="745" alt="31398949-f16baa6c-adea-11e7-8d7d-78b4b405121e" src="https://user-images.githubusercontent.com/905006/33441250-8462e7a2-d5f2-11e7-8b8d-c463e7bd14a5.png">

<img width="821" alt="31398951-f189ad32-adea-11e7-91cb-56c5edb6d9a9" src="https://user-images.githubusercontent.com/905006/33441359-c4c75d28-d5f2-11e7-931b-614fdb0d2ebf.png">
