### ISSUE TITLE
Wrong tooltip position when zoom by scroll

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#2095]
## Description
![grafik](https://user-images.githubusercontent.com/30749177/118715989-9995d900-b824-11eb-9ed8-ac66a0d6f547.png)

When I use scroll zoom and try to zoom in the the tooltip position get wrong when moving the cursor. Maybe because of rescale. 

## Steps to check or reproduce
You can reproduce this also here in this sample chart:

https://naver.github.io/billboard.js/demo/#Interaction.Zoom

just zoom in and move mouse cursor then the marker and tooltip have both the wrong position!

**Comment by watnab** [comment]
It seems the wrong data item gets hovered.
https://github.com/naver/billboard.js/blob/fde6a897bec6c7dab8726e3ab3bcbefe4186ba36/src/ChartInternal/data/data.ts#L643

**Comment by RonnyWeiss** [comment]
Can this also happen when nullish data is given like in the issue #2096 ?

**Comment by watnab** [comment]
`getDataIndexFromEvent(event): number` calls 
`findIndex(arr, v: number, start: number, end: number, isRotated: boolean): number`.
```javascript
const index = findIndex(
	coords,
	isRotated ? e.clientY - rect.top : e.clientX - rect.left,
	0,
	coords.length - 1,
	isRotated
);
```

`findIndex` may mean binary search.
It seems zooming won't refresh `coords`.
However it seems dragging horizontally after zooming will refresh `coords`.

----

- Zoom seems to make the marker wrong position.
-  Drag seems to make the marker right position. it does not resolve tooltip position though.

**Comment by watnab** [comment]
https://naver.github.io/billboard.js/demo/#Interaction.DragZoom
The marker and tooltip seem to have both the right position in drag zoom example.

**Comment by watnab** [comment]
> refresh `coords`.

https://github.com/naver/billboard.js/blob/af1937054c7659158b4bf893db53b7aebfcc1bc0/src/ChartInternal/interactions/eventrect.ts#L291

https://github.com/naver/billboard.js/blob/af1937054c7659158b4bf893db53b7aebfcc1bc0/src/ChartInternal/interactions/zoom.ts#L194-L200

When wheeled, startEvent.clientXY === e.clientXY.
