### ISSUE TITLE
Wrong autoscale of y axis

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#2096]
## Description
![grafik](https://user-images.githubusercontent.com/30749177/118810275-f688a200-b8ab-11eb-83e4-21152c7f47bc.png)

As you can see the autoscale of the y axis is really bad could you please check this

## Steps to check or reproduce
I uploaded you the chart config as json file on the issue so could you please try that by yourself

With that you can check it also in your samples pages:

![grafik](https://user-images.githubusercontent.com/30749177/118810492-3d769780-b8ac-11eb-9f4a-e9b3fb82e212.png)

[chart config.txt](https://github.com/naver/billboard.js/files/6508548/chart.config.txt)

**Comment by watnab** [comment]
`groups` seems to cause this. I don't know the reason.

```javascript
var chart = bb.generate({"bindto": "#barChart",
  "data": {"type": "bar","labels": true,
    "columns": [
      ["1180",74.07,null],
      ["2012",null,35.49]
    ],
    "groups": [["1180","2012"]]
  }
});
```

**Comment by bhonermann** [comment]
Just stating that I'm facing the same issue and that it goes away when not using `groups`.

**Comment by netil** [comment]
Hi @RonnyWeiss, confirmed the issue.
It happens for grouped data containing nullish data.
