### ISSUE TITLE
The option to place the labels on the bottom

### ISSUE THREAD

**Issue by jsong0605** [naver/billboard.js#21]
## Description

AFAIK, the labels are rendered on the upper-side of the chart by default.
There's no option to manipulate the position of labels, so far.

The easiest way (but bothering ;() is increasing the 'y' value of <text> element manually.
However, changing the 'y' value by hand may cause a blink.
Because, this re-rendering follows the default rendering on the default position.

I'd like to place the label on the bottom by handling the option which could be a solution to the above problem at the same time.

If you guys have a possible way, please add it to the following release.

I believe that there must be other users who seriously need it.

Thanks ~ :)

## Steps to check or reproduce

```js
        var chart = bb.generate({
            bindto: "#_temperature",
            interaction: {
                enabled: false
            },
            legend: {
                show: false
            },
            data: {
                x: "x",
                columns: [
                    ['x', 1, 2, 3, 4, 5],
                    ['data1', 7, 9, 13, 16, 20],
                    ['data2', 2, 2, 5, 7, 10]
                ],
                labels: true
            },
            axis: {
                x: {
                    show: false
                },
                y: {
                    show: false
                }
            },
            tooltip: {
                show: false
            },
            point:   {
                show: false
            }
        });
```

<img width="427" alt="issue" src="https://user-images.githubusercontent.com/25364015/27279601-19b2ce48-5520-11e7-831b-ded1178adb81.png">

**Comment by netil** [comment]
@jsong0605 thanks for suggestion!
Actually there's no option for that, if you need to manipulate label text position, you should do handling directly.

For ex., below option will set text lower than the original position.
```js
var chart = bb.generate({
	...
	onrendered: function() {
	        d3.selectAll(".bb-texts .bb-text").each(function() {
		        var text = d3.select(this);
		        text.attr("y", (+text.attr("y") + 20))
	        });
	}
});
```

![image](https://user-images.githubusercontent.com/2178435/27282007-35f87e96-5529-11e7-9a6f-4986c3faa2f6.png)

We will take in considering for the next release. thanks!

**Comment by jsong0605** [comment]
I really appreciate your answer! ~ :)

As far as I'm concerned, the 'onrendered' function follows the default rendering on the default position.

So, the blicking problem still remains to be resolved.

Could I please have a solution for that matter, if you have one~ ?

**Comment by netil** [comment]
@jsong0605 you mean flickering of the text?

well, in that occasion to avoid `flickering`, set opacity to 0 for text nodes and re-set to 1 on `onrendered` callback.

```css
.bb-texts text.bb-text {
     opacity: 0;
}
```

```js
var chart = bb.generate({
	...
        onrendered: function() {
	    d3.selectAll(".bb-texts .bb-text").each(function() {
	      var text = d3.select(this);
	
	      text
	        .attr("y", (+text.attr("y") + 20))
	        .style("opacity", "1");
	    });
        }
});
```

Checkout the online demo :
- http://jsbin.com/jolote/edit?html,js,output

**Comment by jsong0605** [comment]
Yes, that's the issue what I meant.

Thanks for the detail solution to detour the issue. :)
