### ISSUE TITLE
How to update x axis label?

### ISSUE THREAD

**Issue by h4wldev** [naver/billboard.js#211]
## Description
How to update x axis label?

Chart generate code
```javascript
var chart = bb.generate({
  "data": {
    "x": "x",
    "columns": [
	["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 340, 200, 500, 250, 350]
    ]
  },
  "axis": {
    "x": {
      "type": "timeseries",
      "tick": {
        "format": "%Y-%m-%d"
      }
    }
  },
  "bindto": "#chart"
});

```

**Comment by netil** [comment]
The label and tick text are different. Seeing your generation code I'm guessing that you want to change tick text rather than the label, don't you?

![image](https://user-images.githubusercontent.com/2178435/33534254-bb7cf742-d8e9-11e7-857b-a2de6d245aef.png)

For x Axis label manipluation check out:
- [axis.x.label](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis:x:label) API

**Comment by h4wldev** [comment]
@netil That's right. I meant i want to change tick text. How can i do for that.

**Comment by netil** [comment]
Check out [tick.format](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis:x:tick:format) option for that.

You can return a string value from `format` function.
When you set as below,
```js
		"axis": {
			"x": {
				"type": "timeseries",
				"tick": {
					"format": function(x) {
						// x is the datetime data
						return "abc";
                    }
				}
			}
		},
```
the result will be as:
![image](https://user-images.githubusercontent.com/2178435/33534576-99437f3c-d8eb-11e7-9a2a-764fe2ac3b9b.png)

**Comment by h4wldev** [comment]
@netil I meant update tick text after generated. using like setTimeOut

**Comment by netil** [comment]
I don't what is your purpose of the usage, but you can handle directly it.
And there's no API for that purposes.

```js
onrendered: function() {
        d3.selectAll(".bb-axis-x .tick tspan").each(function(v) {
	        this.textContent = "111";
        })
},
```

**Comment by h4wldev** [comment]
Okay. I got it.

I want using it on SPA(vue.js) component. like this 😢 . Thx to your kindness 👍 

![image](https://user-images.githubusercontent.com/14465407/33536759-6d96c93e-d8fa-11e7-9efb-8fde9973f79c.png)

**Comment by netil** [comment]
There's a 3rd party for Vue.js, maybe is worth to checkout.
- https://github.com/naver/billboard.js/wiki/Third-party-applications#vuejs

And if you need get some help, it's good provide enough info & example. Without it, the answer can be limited and sometimes it's misunderstood the point.

Hope to get solved. If you need more help plz, open new issue :)
