### ISSUE TITLE
same x axis labels, different tooltip's title on the bar chart

### ISSUE THREAD

**Issue by ghyoo91** [naver/billboard.js#2110]
## Description

I want to draw a bar chart which has 

```
data : {
            x: "x",
            columns: [
                ["x", "G1S1", "G1S2", "G3S3", "G4S4", "G5S5"],
                ["value", 1, 2, 3, 4, 5],
            ],
            type: "bar",
},
axis: {
    x: {
      type: "category"
    }
},
```

But also I want to make the x axis by the first two letters of x column, ["G1", "G1", "G3", "G4", "G5"],  - then the each point will be (G1, 1), (G1, 2), (G3, 3), (G4, 4), (G5, 5). 
And the tooltip's title when I mouse over to each point have to show  "G1S1", "G1S2", "G3S3", "G4S4", "G5S5".

It seems like when I change the x columns to ["x", "G1", "G1", "G3", "G4", "G5"], then the same x axis value(G1) then its value added together.
The graph shows (G1, 3), (G3, 3), (G4, 4), (G5, 5) at this time. Besides, the tooltip's title shows only  "G1", "G3", "G4", "G5".

How can I do this?

**Comment by watnab** [comment]
I couldn't see the way.
It seems that both axis.x.tick and tooltip call [`axis.x.tick.format`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4format) .
[`tooltip.format.title`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) will receive x index in this case.

**Comment by netil** [comment]
Hi @ghyoo91, you can achieve this by using with the combination of [`axis.x.tick.format`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4format) and [`tooltip.format.title`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip).

```js
 bb.generate({
    data : {
        x: "x",
        columns: [
            ["x", "G1S1", "G1S2", "G3S3", "G4S4", "G5S5"],
            ["value", 1, 2, 3, 4, 5],
        ],
        type: "bar",
    },
    axis: {
        x: {
            type: "category",
            tick: {
                format: (index, categoryName) => categoryName.replace(/\dS/, "")
            }
        }
    },
    tooltip: {
        format: {
            title: function(x) { 
                return this.categories()[x];
            }
        }
    }
});
```

<img src=https://user-images.githubusercontent.com/2178435/119914007-4812ea00-bf9a-11eb-92a1-6fa3a7e52001.png width=500>

**Comment by ghyoo91** [comment]
I solved this problem with the combination of axis.x.tick.format and tooltip.format.title, as you mentioned.
I've tried one each, but not at the same time.
Thank you for kind(and also instant) reply!! and I'm sorry for my late comment.
