### ISSUE TITLE
[feature] grid and region for gauge chart

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2120]
I'm trying to build a gauge chart with threshold values displayed inside the chart.

Therefore, it would be helpful if one could have lines or regions defined for the gauge chart as well, similar to what is done for a line plot:

```
        grid: {
            x: {
                lines: [
                    {
                        value: 2,
                        text: 'lower threshold'
                    },
                    {
                        value: 5,
                        text: 'upper threshold'
                    }
                ]
            }
        },
        regions: [
            {
                start: 3,
                end: 4,
                class: 'chart-optimum-region'
            }
        ]
```

I suspect that regions would be hard to deal with reasonably, but drawing lines could be doable and should work for both single/multi type.

Is there already any hook available to hack this in right now?

**Comment by netil** [comment]
Hi @adschm, thanks for the issue. This might be similar with #1082.
I will consider for the next release.
