### ISSUE TITLE
Gauge: Unexpected result with min/max for "single" type

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2123]
If I set the min/max properties for the "single" gauge plot, the arc drawn is much too big and seems miscalculated.

My aim is to show absolute numbers within tolerances, where e.g. min=40 °C, max=60 °C, actual=50°C.

https://jsfiddle.net/adschm/q20syvg8/5/

This is either a calculation bug or a misinterpretation of the usage by me ...

Doing the same with the "multi" type appears to work as expected:

https://jsfiddle.net/adschm/tbdngpLj/3/

**Comment by netil** [comment]
@adambot, want to hear opinions about the data representation.

When, data value is 50, min=40, max=60, well it make sense.
<img src=https://user-images.githubusercontent.com/2178435/121126732-9b6f1d00-c863-11eb-8bfc-1629c4172c9b.png width=250>

what representation should have, when data value is 50, min=-40, max=60?
should graph occupy in a range of -40 ~ 50?, -40 ~ 10 or 0 ~ 50(letting blank `-40 ~ 0` range)?
<img src=https://user-images.githubusercontent.com/2178435/121126783-b17cdd80-c863-11eb-9ae3-f4c58fe9a714.png width=250>

Little bit confusing, when min starts from negative value. Gauge used to displaying the amount within a range.
The first example also can be represented occupying 40 ~ 90 (which is representing 50).

**Comment by adschm** [comment]
First, let me note that I'm using this for displaying a value within bounds, where I do not care about the percentage value at all. I'm replacing it by the value via gauge->format->return value. So, my view is certainly subjective.

Coming back to the question, my expectation for a percentage value in a linear range would be that it's linear too. So, based on your example, -40=0%, -30=10%, -20=20%, ... 60=100% etc. Anything else would look like an error to me.

So, percent = (value - min) / (max - min)

There might be observables where this makes no sense. But for each of those I could think of, choosing a negative value for min would not have made sense at all, either.
