### ISSUE TITLE
bindThis should check for undefined

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#2132]
## Description
When creating a new `Chart`, the `bindThis` method should check if the **key** is defined and not null. Otherwise [this line](https://github.com/naver/billboard.js/blob/430cef77666695b9717da53cb20f7ee8783db8af/src/Chart/Chart.ts#L92) fails:

```js
const hasChild = Object.keys(fn[key]).length > 0; // this fails if the 'fn[key]' is null or undefined
```

Safe way

```js
const hasChild = fn[key] != null && Object.keys(fn[key]).length > 0;
```

**Comment by netil** [comment]
Hi @creage, thanks for the report.
Would you like send PR(and its test case) for this?
