### ISSUE TITLE
[bug] Line: flow() breaks (drag-)Zoom

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2140]
I show historic timeseries data and then add "live" data points by using .flow() function to append the latest datapoint to that view. As soon as .flow() is executed the first time, drag-zoom is broken. (Before the first trigger is executed, everything works fine.)

Sometimes it's starting to work again after some time or a few tries, but this is not reproducible (whereas the broken zoom is).

A simple example is found here:
https://jsfiddle.net/adschm/2t0ao5h4/18/

_Just try to drag-zoom. Setting refresh variable to false will produce a zoomable plot._

Chromium-based console gives me the following (transition id varies) for each unsuccessful click:
```
Uncaught Error: transition 837 not found
    at vo (d3.v6.min.js:2)
    at Pn.zn.transition (d3.v6.min.js:2)
    at AxisRendererHelper.transitionise (billboard.custom.js:9434)
    at SVGGElement.<anonymous> (billboard.custom.js:9519)
    at ji.each (d3.v6.min.js:2)
    at AxisRenderer.create (billboard.custom.js:9510)
    at billboard.custom.js:10216
    at Array.forEach (<anonymous>)
    at Axis.redraw (billboard.custom.js:10213)
    at Axis.redrawAxis (billboard.custom.js:10253)

vo	@	d3.v6.min.js:2
zn.transition	@	d3.v6.min.js:2
transitionise	@	billboard.custom.js:9434
(anonymous)	@	billboard.custom.js:9519
each	@	d3.v6.min.js:2
create	@	billboard.custom.js:9510
(anonymous)	@	billboard.custom.js:10216
redraw	@	billboard.custom.js:10213
redrawAxis	@	billboard.custom.js:10253
redraw	@	billboard.custom.js:5382
zoom	@	billboard.custom.js:16477
(anonymous)	@	billboard.custom.js:17306
call	@	d3.v6.min.js:2
e	@	d3.v6.min.js:2
g	@	d3.v6.min.js:2
(anonymous)	@	d3.v6.min.js:2
```

**Comment by netil** [comment]
Hi @adschm, thanks for the report. I'll check the issue.

**Comment by adschm** [comment]
BTW: Is there a simpler function available to "just append data" (to an existing series)? I only use .flow() here because I didn't find anything else, but I do not need all the additional animation handles ...

**Comment by netil** [comment]
@adschm, to simply load data dynamically, use [.load()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load) instead of .flow().

**Comment by adschm** [comment]
The way I understand .load() is that it _replaces_ data when I specify an already existing data id?

My problem is that my first DB query for the data is typically expensive, so I don't want to re-query or concatenate data more often than necessary.

How would I change my referenced example to achieve the same result by using load?

**Comment by netil** [comment]
@adschm for dynamic data loading, checkout the wiki doc.
- https://github.com/naver/billboard.js/wiki/How-behaves-for-dynamic-loading%3F

**Comment by adschm** [comment]
@netil Thanks for packaging append, it seems to work from a quick test and resolves my specific use-case.

However, does this actually fix the reported issue, i.e. zoom broken after flow()? If drag-zoom does not make sense during flow(), it should be disabled in this case. Otherwise, it should be fixed properly, IMO.

**Comment by netil** [comment]
> However, does this actually fix the reported issue, i.e. zoom broken after flow()? If drag-zoom does not make sense during flow(), it should be disabled in this case. 

Doing some interaction during the middle of the transition, will eventually make an unexpected behavior or result.
Maybe adding some prevention to not interact is needed.

**Comment by netil** [comment]
doing drag after the `.flow()` will not throw error.
![Kapture 2021-06-30 at 18 52 20](https://user-images.githubusercontent.com/2178435/123941831-80f91100-d9d5-11eb-8707-e5b213e08b4a.gif)
