### ISSUE TITLE
[feature/question] trigger when data row is shown/hidden

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2146]
In an area-step chart, I'm adding various vertical (grid) lines and regions, which are all contextually linked to one of the data sets (= each of the added feature has exactly one data series it belongs to).

Now, when toggling display for one data series, e.g. by clicking the connected legend entry, I would like to also toggle the "connected" lines and regions. I'm currently struggling to hack this inside onrendered, but actually it would be desirable to address by one (or both) of these two hooks:

1. implement two event functions .onshown() and .onhidden(), similar to what data.onselected() does for individual points. Those could probably quite easily be called inside show.ts's showHide() function.
2. Create a more generic way to actually _link_ objects like grid lines and/or regions to data series, so when the data for one data series is "hidden", the rest also gets hidden automagically. I'm not sure whether the trade-off between complexity and benefit is really positive here, though.

**Comment by netil** [comment]
@adschm have your tried [`legend,item.onclick`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.legend)? I guess is more proper handling from there.

> Create a more generic way to actually link objects like grid lines and/or regions to data series, so when the data for one data series is "hidden", the rest also gets hidden automagically. I'm not sure whether the trade-off between complexity and benefit is really positive here, though.

well, it can be useful for some, but to implement a new functionality it should have some broad necessity for that.
I'll be considering for future release.

**Comment by adschm** [comment]
It's not so much the trigger itself I care about, but that .onshown() and .onhidden() would include the target state of the change (which is present in showHide() anyway).

At the moment, I'm using rather unelegant `let hidden = !(this.internal.state.hiddenTargetIds.indexOf(key) < 0)` for this.
Is there a way to directly use the .isTargetToShow function [1] in onrendered and/or legend.item.onclick()?

[1] https://github.com/naver/billboard.js/blob/b4c5dc288dab0638d399865120572c854758b782/src/ChartInternal/data/data.ts#L437

**Comment by adschm** [comment]
Okay, I mostly managed myself (classes for grid lines/regions are assigned by me and should be obvious to understand):

```
        legend: {
            item: {
                onclick: function (id) {
                    let visible = this.internal.isTargetToShow(id);

                    this.toggle(id);

                    this.$.main.selectAll(".chart-bound-" + id + ", .chart-region-" + id)
                        .style("display", visible ? "none" : "")
                        .style("opacity", visible ? "0" : "");
                }
            }
        }
```

Feedback welcome.

With this solution I think the priority for the feature request is low to very low now.
