### ISSUE TITLE
Normal zoom doesn't update x grid line/label positions

### ISSUE THREAD

**Issue by ebencollins** [naver/billboard.js#2155]
## Description
The position of x grid lines don't get updated when zooming/panning using the normal zoom feature (drag zoom works as expected)

![](https://i.imgur.com/6wowNZM.gif)

## Steps to check or reproduce
https://stackblitz.com/edit/ag6gai
```
var chart = bb.generate({
  data: {
    columns: [['data2', 130, 340, 200, 500, 250, 350]],
    type: 'line'
  },
  zoom: {
    enabled: true
  },
  grid: {
    x: {
      lines: [{ value: 3, text: '123' }]
    }
  },
  bindto: '#chart'
});
```

**Comment by netil** [comment]
Hi @ebencollins, thanks for the report. I'll check the issue.

**Comment by netil** [comment]
drag zoom works fine, only happens for wheel zoom type.
