### ISSUE TITLE
error in label names in data.labels.backgroundColors when spaces in label names (v3.1.0)

### ISSUE THREAD

**Issue by tjohannto** [naver/billboard.js#2160]
## Description
when label names have spaces (like for country names etc) the created filter does have an inavalid url like `url(#bb-1624614616765-labels-bg-data 11)`

![image](https://user-images.githubusercontent.com/45257386/123407120-e26f4900-d5ab-11eb-8838-896b16eee59a.png)

## Steps to check or reproduce
https://jsfiddle.net/ujayzdfo/

**Comment by netil** [comment]
Hi @tjohannto, thanks for the report. I'll be releasing patch for this.
