### ISSUE TITLE
Min and max broken

### ISSUE THREAD

**Issue by thegamerx1** [naver/billboard.js#2161]
## Description
Charts have wrong min max i think its because float values in input
![27_06_2021_firefox_FimJdV8Pp2](https://user-images.githubusercontent.com/34986564/123554587-f15b2480-d780-11eb-999e-e9d1e228d846.png)
fiddle: https://jsfiddle.net/j9sw67ny/
```js
chart = bb.generate({
	data: {
		columns: [["data", 0]],
		type: area(),
	},
	legend: {
		show: false,
	},
	tooltip: {
		show: false,
	},
	point: {
		show: false,
	},
	axis: {
		y: {
			max: 100,
			min: 0,
			tick: {
				count: 3,
			},
		},
	},
	bindto: element,
})
```
		
![27_06_2021_firefox_QlT99dutf8](https://user-images.githubusercontent.com/34986564/123554501-97f2f580-d780-11eb-89c1-fb24d9b6af64.png)

**Comment by thegamerx1** [comment]
pls fix

**Comment by netil** [comment]
Hi @thegamerx1, try by setting [axis.y.padding.bottom=0](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4padding) to remove bottom gap.

```js
axis: {
    y: {
        max: 100,
        min: 0,
        tick: {
            count: 3,
        },
        padding: {
            bottom: 0
        }
    },
},
```

**Comment by thegamerx1** [comment]
i got that fixed is there a way to fix the padding on the left too?
![28_06_2021_firefox_Qy6NTXFVIt](https://user-images.githubusercontent.com/34986564/123611930-628eec00-d802-11eb-9476-2ebb8d04d74d.png)
