### ISSUE TITLE
Confused by construction of line chart

### ISSUE THREAD

**Issue by mpushki** [naver/billboard.js#2172]
## Description
Nonmonotonic data were sorted on chart. Line changes dots order: 
I expect ....30.78724, 27.10858, 23.81462
but on chart ....30.78724, 23.81462, 27.10858
```
0: "line"
		1: 53.76645
		2: 42.11748
		3: 42.45012
		4: 37.57594
		5: 34.72687
		6: 30.78724
		7: 27.10858
		8: 23.81462		
0: "x_line"
		1: "9489.23"
		2: "7989.08"
		3: "6019.04"
		4: "4506.77"
		5: "3281.06"
		6: "2280.16"
		7: "1803.39" -> this value
		8: "2055.86"
```
is it possible not to sort by axis?

## Steps to check or reproduce
https://jsfiddle.net/mpushki/vnkfm5zh/

**Comment by netil** [comment]
@mpushki, if you don't want x to be sorted and display following the order of the input try with below options.

<img src=https://user-images.githubusercontent.com/2178435/124212129-5f10a300-db29-11eb-98d1-c02a96e63f4f.png width=500>


```js
bb.generate({
  data: {
    xs: {
      line: "x_line",
    },
    xSort: false,
    columns: [
	    ["x_line", 9489.23, 7989.08, 6019.04, 4506.77, 3281.06, 2280.16, 1803.39, 2055.86],
	    ["line", 53.76645, 42.11748, 42.45012, 37.57594, 34.72687, 30.78724, 27.10858, 23.81462]
    ],
    type: "line",
  },
  axis: {
  	x: {
    	type: "category",
      tick: {
      	centered: true
      }
    }
  },
  bindto: "#chart"
});
```

**Comment by mpushki** [comment]
Thanks, That is exactly what I need
