### ISSUE TITLE
Upgrading billboard.js from 3.0.3 to 3.1.1 in Next JS breaks my app

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [naver/billboard.js#2181]
## Description
I am using Nextjs with billboard js for my app. The app was working fine until i tried bumping up billboard.js from 3.0.3 to 3.1.1 which started giving me this error

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /${project_path}/node_modules/d3-axis/src/index.js
require() of ES modules is not supported.
require() of /${project_path}/node_modules/d3-axis/src/index.js from /${project_path}/node_modules/billboard.js/dist/billboard.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ${project_path}/node_modules/d3-axis/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at webpackUniversalModuleDefinition (/${project_path}/node_modules/billboard.js/dist/billboard.js:12:28)
    at Object.<anonymous> (/${project_path}/node_modules/billboard.js/dist/billboard.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  code: 'ERR_REQUIRE_ESM'
}
```
I was thinking the problem was with my code for a long time, until recently, i tried setting up a fresh NextJS project to test this out. And, **the exact same issue happened there as well**, with the exact same error as above.

I have tried it with CRA(create-react-app) and it works without any problem, the problem is only with NextJS.

## Steps to check or reproduce

1. create a fresh next js project (`npx create-next-app app_name`)
2. install billboard.js (`npm i billboard.js`)
3. create an import statement in index.js(`import bb from 'billboard.js'`)
4. `npm run dev`

**CodeSandbox link:** https://codesandbox.io/s/billboardjstest-q65g8?file=/pages/index.js

**Comment by netil** [comment]
Confirmed the issue.
I could reproduce the issue and it doesn't happens on `v3.0.3`, but it happens in the above versions.

I'm assuming something related to the d3.js version update, because the updates from `3.0.x` &rarr; `3.1.x` there's no related(module) changes at all.

**Comment by sudo-NithishKarthik** [comment]
Thank you for the acknowledgement @netil 😄  . But, the if it's an issue with d3.js version update, then it should not work with ReactJS as well right ? ,but it does 😕 . So, do you think it's got something to do with how NextJS handles things ?

**Comment by netil** [comment]
billboard.js `v3.1.x`'s d3's dependencies updated to `v3` and one of the biggest changes of d3 is the adoption of `type:module`, where it forcing to use ESM only. (Ref. [package.json "type" field](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling))
- https://github.com/d3/d3-axis/releases/tag/v3.0.0

**Comment by sudo-NithishKarthik** [comment]
I see, So I will have to do some workaround till NextJS supports ESM, thank you @netil for your support 😄

**Comment by netil** [comment]
@sudo-NithishKarthik released the patch version.
Try installing latest `v3.1.2` and will work.

**Comment by sudo-NithishKarthik** [comment]
Thank you @netil

**Comment by netil** [comment]
Ref. https://github.com/vercel/next.js/issues/24334
