### ISSUE TITLE
If you go to another page before the chart load is complete, it will not be interrupted

### ISSUE THREAD

**Issue by a-sshu** [naver/billboard.js#2192]
If you move to another page before the end of the chart loading, the chart is drawn at the bottom even though there is no specified area.

Is there any way to stop loading the chart?

**Comment by netil** [comment]
try by handling with the Page Visibility API.
- https://developer.mozilla.org/ko/docs/Web/API/Page_Visibility_API

**Comment by a-sshu** [comment]
I solved this with display hide() and  $(".bb").remove().

But if "bb.generate" is called and the chart is moved to another page before it is drawn (using jquery load()), it will not stop and when the load is complete, the chart will be append to the "body".

I would like to stop before the chart loading is completed, not by trickery.
Is there a way to stop it?

**Comment by a-sshu** [comment]
I found another way.

Still can't stop loading charts, but it's the neatest way I've ever found.

` if($(chartArea).length < 1){
    $("body > .bb").remove();		  
  }`
