### ISSUE TITLE
[BUG] Programatic zoom resets after wheel in then out

### ISSUE THREAD

**Issue by jimmy764** [naver/billboard.js#2194]
## Description
After setting zoom programmatically, scrolling in one step then out one step will reset zoom to original (as if `.unzoom` had been called).

I observed this with Chrome 91 & Firefox 90, but not Firefox 89.

## Steps to check or reproduce
1. Load chart with "zoom" example
2. Add programmatic zoom
3. Scroll in (at least one step)
4. Scroll out (at least one step)

https://stackblitz.com/edit/udgqfr?file=index.js
```
var chart = bb.generate({
  data: {
    columns: [
	["sample", 30, 200, 100, 400, 150, 250, 150, 200, 170, 240, 350, 150, 100, 400, 150, 250, 150, 200, 170, 240, 100, 150, 250, 150, 200, 170, 240, 30, 200, 100, 400, 150, 250, 150, 200, 170, 240, 350, 150, 100, 400, 350, 220, 250, 300, 270, 140, 150, 90, 150, 50, 120, 70, 40]
    ],
    type: "line",
  },
  zoom: {
    enabled: true, 
  },
  bindto: "#zoom"
});

chart.zoom([24, 30]);
```

**Comment by netil** [comment]
Hi @jimmy764, thanks for the report.
