### ISSUE TITLE
wrong type of parameter 'id' of LegendOptions.item.onclick

### ISSUE THREAD

**Issue by bb-in-hoodie** [naver/billboard.js#2203]
## Description
![image](https://user-images.githubusercontent.com/12558317/126253663-265f4168-55f7-45f7-b15b-dce28826b4b7.png)
:-:
tested using the example code in [Legend Template1 example](https://naver.github.io/billboard.js/demo/#Legend.LegendTemplate1)

even though the parameter `id` of `LegendOptions.item.onclick` is defined as `DataItem` type, it actually is a `string` type value which shows the id of a selected legend item.

<br>

![image](https://user-images.githubusercontent.com/12558317/126253838-be88390f-61db-4896-9e2c-1d64b7bc6337.png)
:-:
options.d.ts > LegendOptions > item

`onclick`, `onover`, `onout` share the same parameter type.

<br>

## Steps to check or reproduce

```ts
// base css
import 'billboard.js/dist/theme/insight.css';
import bb from 'billboard.js';

// for ESM environment, need to import modules as:
// import bb, {pie} from "billboard.js"

var chart = bb.generate({
  data: {
    columns: [['data1', 100], ['data2', 300], ['data3', 200]],
    type: 'pie' // for ESM specify as: pie()
  },
  legend: {
    contents: {
      bindto: '#legend',
      template:
        "<span style='color:#fff;padding:10px;background-color:{=COLOR}'>{=TITLE}</span>"
    },
    item: {
      onclick: id => console.log(id)
    }
  },
  bindto: '#legendTemplate1'
});
```

**Comment by netil** [comment]
Hi @bb-in-hoodie, thanks for the report. Will be fixed soon.
