### ISSUE TITLE
Feature: Timeline chart like Google Charts

### ISSUE THREAD

**Issue by fanthos** [naver/billboard.js#221]
## Description
Add timeline chart like Google Charts Timeline would be great.

https://developers.google.com/chart/interactive/docs/gallery/timeline

I have a simple timeline chart based on D3.js
https://github.com/fanthos/d3-gtimeline-ha

Related screenshot on:
https://github.com/home-assistant/home-assistant-polymer/pull/429

**Comment by netil** [comment]
Yeap, supporting different types as possible can increase the usability of the library.
Thanks for the suggestion, will take this considering for the future release!

or if you can, it'll be great send a PR for this :)

**Comment by Nomercy10** [comment]
Hello,
I have been using this library for almost a year now, its been an amazing experience so far. I am looking to implement a timeline chart but as the feature is not there currently, wanted to know if it is considered in the upcoming releases.
Thankyou
