### ISSUE TITLE
Float number sometimes showing long `0` or `9`.

### ISSUE THREAD

**Issue by fanthos** [naver/billboard.js#222]
## Description
In some case float number in axis not rounding, showing very long float number with `0` or `9`.
![bbjs_hass](https://user-images.githubusercontent.com/1490719/33940322-7a5a2fa2-e049-11e7-80ff-a0ce52e90135.PNG)
Not sure it is D3.js issue or bb.js issue, hope it can be fixed.

**Comment by fanthos** [comment]
This issue is related to float number epsilon.
```javascript
axis.y.tick.format = (y) => parseFloat(y.toFixed(14));
```
should be current workaround for this.

**Comment by netil** [comment]
@fanthos, that could be a solution for now.
This happens on D3's scaling, I'll try look to improve that :)
