### ISSUE TITLE
playground area-spline question

### ISSUE THREAD

**Issue by cut20032002** [naver/billboard.js#224]
## Description

In data.type section, area-spline is not supported. In the description, it supports area-spline too, but it doesn't work. Are there any way to simulate area-spline?

## Steps to check or reproduce

The code is like this. I run this code in <try> page which is supported by codepen, and it only shows typical lines.
```json
{
    "data": {
        "columns": [
            ["data1", 30, 200, 100, 400, 150],
            ["data2", 50, 20, 10, 40, 15],
            ["data3", 50, 20, 10, 40, 15],
            ["data4", 30, 200, 130, 400, 30],
            ["data5", 50, 20, 10, 40, 415]
        ],
        "type": "area-spine"
    }
}
```

**Comment by julien** [comment]
Hi @cut20032002,  

In the example code you posted above, there's a typo. 
Chainging `area-spine` to `area-spline` should work. (tested with `1.1.1`and `1.2.0`)

**Comment by cut20032002** [comment]
I think the playground has a typo in area-spline.
I just pasted the code from the playground.
Anyway, when i change from area-spine to area-spline, it works well. Thank-you.

**Comment by julien** [comment]
@cut20032002 I hadn't understood correctly,  you're right there's a typo in the playground.

**Comment by markwinter** [comment]
I opened a PR to fix this typo https://github.com/naver/billboard.js-playground/pull/3
