### ISSUE TITLE
[Question] How to determine D3 version to use with compiled files

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2240]
I use the precompiled, non-bundled billboard[.min].js files in my project, with a separate d3[.min].js file, both from cdnjs.

In this context, I wonder how to determine the correct version of the d3 package to choose. I noticed the jump-forward-jump-backward change recently regarding 7.0.

Can recent billboard 3.1.2/3.1.3 be used with d3 v7 already? And how could one determine this generically without having to compare all the d3-* subdependencies from the npm file?

**Comment by netil** [comment]
> In this context, I wonder how to determine the correct version of the d3 package to choose. I noticed the jump-forward-jump-backward change recently regarding 7.0.

The recent update(Ref. #2181), only affects in a environment where billboard.js is consumed as module by importing from code level. If you're using the compiled UMD version will have no effect and also it can be used with d3.js v7.

The basic dependency info is described at readme.
- https://github.com/naver/billboard.js#dependency-by-version

If you're aware of the d3 version, you can check the [package.json's dependencies](https://github.com/naver/billboard.js/blob/master/package.json#L68) section to determine.
Or simply use pkgd version where comes with compatible d3.js version.

**Comment by adschm** [comment]
> > In this context, I wonder how to determine the correct version of the d3 package to choose. I noticed the jump-forward-jump-backward change recently regarding 7.0.
> 
> The recent update(Ref. #2181), only affects in a environment where billboard.js is consumed as module by importing from code level. If you're using the compiled UMD version will have no effect and also it can be used with d3.js v7.

Okay, thanks.

> 
> The basic dependency info is described at readme.
> 
> * https://github.com/naver/billboard.js#dependency-by-version

Oh, I actually overlooked the "+" after v6.x ...

> 
> If you're aware of the d3 version, you can check the [package.json's dependencies](https://github.com/naver/billboard.js/blob/master/package.json#L68) section to determine.

That's what I was referring to with "without having to compare all the d3-* subdependencies from the npm file".

So, I would have to look at the packages from D3's package.json and then "compare" with billboard's package.json. That's not undoable, but also not really convenient.

> Or simply use pkgd version where comes with compatible d3.js version.

That's not an option for me, since it won't expose the global d3 variable. I'm using d3.format() and d3.timeFormat() for custom formatting.
And duplicating stuff by adding the relevant d3 packages again on top of packaged d3 does not seem a nice solution to me (though it might theoretically require less space compared to using "entire" d3.min.js.)

In any case, thanks for showing me all the options.
