### ISSUE TITLE
Safari does not support window.requestIdleCallback()

### ISSUE THREAD

**Issue by suby90** [naver/billboard.js#2247]
## Description
On Jun 18, `window.requestIdleCallback` was added to improve rendering in `load.ts`. However, I believe the Safari does not support this method yet, `window.requestIdleCallback`, so it causes errors for the browser. Could you check this error?

I appreciate your help in advance.

https://github.com/naver/billboard.js/commit/1938c611cc375f5b6a91b27fd489cb3523d166ce#diff-4bf4d54cac8895eaaef3f98ca174a4d2ec37160d5d2a01dda28ac7f3c4f996fc

**Comment by netil** [comment]
Hi @suby90, thanks for the report. I'll check that.

**Comment by netil** [comment]
@suby90 , try with `3.1.4` release
