### ISSUE TITLE
Bar chart - Data labels are not shown when ALL the data values are 0

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2251]
## Description
Data labels are not shown when data values are zero. Even giving threshold didnt help. It works fine if atleast one data value is non-zero.

## Steps to check or reproduce
https://codepen.io/5r1m/pen/qBmgPGN

Actual result :
Labels are not shown when ALL the data values are zero:
["data1", 0, 0],
["data2", 0, 0]

Expected result:
Data labels should be shown even when all the values are zero

**Comment by netil** [comment]
Hi @5r1m, thanks for the report.
