### ISSUE TITLE
[Bug] zoom.onzoom* functions trigger multiple times since 3.1.3 (for drag zoom)

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2254]
Between 3.1.2 and 3.1.3, drag-zoom has changed it's behavior so that zoom.onzoomend is called twice for each zoom event, and .onzoom is called multiple times (didn't count how often). I haven't checked onzoomstart.

This behavior is unchanged in 3.1.4.

Just use the examples below, zoom in once and look at the console output.

Broken (3.1.4):
https://jsfiddle.net/adschm/kzgfbdtp/1/

Working (3.1.2):
https://jsfiddle.net/adschm/et1Lnjgm/11/

**Comment by netil** [comment]
Thanks for the report. It seems the side-effect caused by 4eee2d8.
I'll check the issue.

**Comment by adschm** [comment]
@netil 3.1.5 fixes onzoomend, but onzoom is still triggered multiple times, i.e. NOT fixed.

This can be seen in my "old" fiddles on the top, since the "broken" version uses the "latest" billboard.js.

**Comment by adschm** [comment]
This should be reopened.

**Comment by adschm** [comment]
@netil Ping.

**Comment by adschm** [comment]
It's currently unclear whether this is possibly fixed by 9d352b618d646bc86a93b3000936b4f7b9ef1435

jsfiddle does not understand files from raw.githubusercontent directly, so it's a little bit of pain to test the nightlies correctly.

**Comment by netil** [comment]
@adschm, here's the event triggering table based on the different zoom types.
The only difference from the previous version is by API call, where this need to be aligned.

and for `nightly` recommend to install pointing github directly.
- https://github.com/naver/billboard.js#nightly-version

type | version | events
:--: | :--: | :--:
drag | 3.1.2 | start(triggers when mousedown) -> zoom -> end
&nbsp; | latest | start(triggers when mousedown) -> zoom -> end    
wheel | 3.1.2 | start -> zoom … zoom (triggers multiple zoom) -> end
&nbsp; | latest | start -> zoom … zoom (triggers multiple zoom) -> end
API call | 3.1.2 | trigger one 'zoom' event
&nbsp; | latest | zoom … zoom (triggers multiple zoom)

**Comment by adschm** [comment]
I tested with the latest nightly (directly in my project) and the behavior seems to be as expected, i.e. as you describe it above. (I only ever looked at drag zoom, can't say anything about wheel.)

From a logical point of view, I'm not really convinced that .zoom() function should not trigger zoomend. From a practical point of view, having a difference between zoom() function and manually triggered zoom is valuable (i.e. not triggering zoomend on zoom() function call). So, it's probably best to keep it as it is right now :-)
