### ISSUE TITLE
subchart.show() gives error in ESM environment

### ISSUE THREAD

**Issue by shashi278** [naver/billboard.js#2255]
## Description

I'm trying to use billboard.js in my Vue app but this subchart is not working properly.
I'm getting `$$.unbindZoomEvent is not a function` error when trying to show the subchart using `subchart.show()`. The same is coming up when using `subchart.toggle()` for showing the subchart, no problem when hiding.
Although I've gone through the docs, I'm not sure if I'm missing something or it's an actual bug. I'd be grateful if someone could have a look at it. Thanks!

billboard.js version: 3.1.4

## Steps to check or reproduce

Here's a minimal reproducible example:
### App.vue
```vue
<template>
  <div id="subchart"></div>
</template>
```
### main.js
```js
// for ESM environment, need to import modules as:
import bb, { line, subchart } from "billboard.js";
import "billboard.js/dist/theme/insight.css";

const chart = bb.generate({
  data: {
    columns: [["sample", 30, 200, 100, 400, 150, 250]],
    type: line()
  },
  subchart: {
    enabled: subchart()
  },
  bindto: "#subchart"
});

chart.subchart.show();
```
And here's the same on codesandbox: https://codesandbox.io/s/billboardjs-subchart-n6rno?fontsize=14&theme=dark&file=/src/main.js:0-358

## Update:
The error seems to be coming from 3.1.4 . Switiching back to 3.1.3 resolves my problem.

**Comment by netil** [comment]
Hi @shashi278 thanks for the report. I'll check the issue.
