### ISSUE TITLE
Wrong type definition on data.onshown/onhidden in options.d.ts

### ISSUE THREAD

**Issue by bb-in-hoodie** [naver/billboard.js#2275]
## Description

https://github.com/naver/billboard.js/commit/af98eb7b988d5fb976a135ec34237c7e78bdb165#diff-3cd76992dbf6767bbb6b03890cd0173c9602172b7d6b8cb5b05703164b583c38

the parameter of each onshown and onhidden must be `ids: string[]` while it is missing.

**Comment by netil** [comment]
Hi @bb-in-hoodie, thanks for the report.
