### ISSUE TITLE
step-after cursor/tooltip placement incorrect when used with timeseries or type specified per id

### ISSUE THREAD

**Issue by ebencollins** [naver/billboard.js#2287]
## Description
Step charts with type `step-after` will incorrectly place the cursor/tooltip when using with a timeseries x axis or when specifying `data.types` per id instead of `data.type`.

It seems that the timeseries issue is caused by `$$.scale.x($$.getXValue(d.id, index))` always returning a negative number, eg `-2873303` in ![eventrect.ts#L420](https://github.com/naver/billboard.js/blob/367a4c37b114f56d9d595063556464caaeb569b5/src/ChartInternal/interactions/eventrect.ts#L420).

It seems the issue with specifying `data.types` instead of `data.type` is that the data fed to `isStepType` (and `isTypeOf)` does not include an id, and thus ![`const dataType = this.config.data_types[id] || this.config.data_type;`](https://github.com/naver/billboard.js/blob/367a4c37b114f56d9d595063556464caaeb569b5/src/ChartInternal/internals/type.ts#L112) evaluates to `undefined` .

Expected behavior (cursor/tooltip always displays for the point to the left): 
![expected behavior](https://i.imgur.com/QiI7tYK.gif)

Broken when using timeseries axis:
![broken with timeseries](https://i.imgur.com/7N4GKIb.gif)

Broken when specifying `data.types` instead of `data.type`:
![broken with `data.types`](https://i.imgur.com/UzKnFxD.gif)

## Steps to check or reproduce
Working example with linear x axis: https://stackblitz.com/edit/yz3zpm-a7ytrb
Broken example with timeseries x axis: https://stackblitz.com/edit/5smqjm-fvag3z
Broken example with types specified per id: https://stackblitz.com/edit/yz3zpm-urpr1q

**Comment by netil** [comment]
HI @ebencollins, thanks for the report. I'll check the issue.

**Comment by ebencollins** [comment]
@netil Thanks for looking into this!
Would it be possible to have the functionality fixed rather than removed?
For `step-after` and `step-before` types, it feels a lot more intuitive for the tooltip to appear for the values that are under the cursor rather than the closest point.
For example

**Comment by ebencollins** [comment]
@netil Thanks for looking into this!
Would it be possible to have the functionality fixed rather than removed (at least as a configurable option)?
For `step-after` and `step-before` types, it feels a lot more intuitive for the tooltip to appear for the values that are under the cursor rather than the closest point.

For example, in the below `step-after` chart, when mousing over the line at 300, I would expect to see the tooltip for the point at (0, 300) rather than (1, 350)
![](https://i.imgur.com/wfDtNpK.png)
