### ISSUE TITLE
Console errors in bar chart: Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "0"

### ISSUE THREAD

**Issue by cosmo0** [naver/billboard.js#2295]
## Description

When adding a bar chart, it triggers a bunch of errors in the console: `Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "0"`

It looks like it's working nonetheless, so maybe these errors can be ignored?

It doesn't display this behavior with BillboardJS 3.0.3 (I didn't try with another version).

## Steps to check or reproduce

- open the devtools console
- open https://jsfiddle.net/cosmo0/m2wxzLfv/4/

![image](https://user-images.githubusercontent.com/3973850/131477996-0e8a5ec2-f1de-4572-aca4-860c9bf8c66f.png)

**Comment by GDFaber** [comment]
Hi @cosmo0, thanks for reaching out. It seems to me that the path objects are invalid and should either be completed or be skipped. I'll take a look at it.

**Comment by GDFaber** [comment]
billboard tries to show targets with value "null" and calls a d3 transition for them, which causes the errors. I think I got it sorted out but want to do a little more testing on this.

**Comment by netil** [comment]
@cosmo0, can you try testing with the RC release?
Remove `v3.5.1` from your fiddler and add the following
- https://unpkg.com/billboard.js@3.2.0-next.4/dist/billboard.js

Checkout the RC release example
- https://jsfiddle.net/netil/e7nzm2jx/1/

**Comment by cosmo0** [comment]
Sure! I'm on a break right now but I'll check when I get back (start of next month).

**Comment by hyunje-moon** [comment]
i figured out that error is thrown when column elements are `0`.

```js
billboard.generate({
  ...
  data: {
    columns: [
      ['columnA', 0, 0, 0, 0],
      ['columnB', 0, 0, 0, 0],
    ],
    type: bar(),
  },
  ...
})
```

**Comment by hyunje-moon** [comment]
it does not happen in `3.2.0-next.4` :)

**Comment by GDFaber** [comment]
Interesting, then I should check if my use cases work with ```next``` as well before pushing anything :) Thanks.

**Comment by cosmo0** [comment]
@netil 

> @cosmo0, can you try testing with the RC release? Remove `v3.5.1` from your fiddler and add the following

Thanks, tried it with 3.2.0-next.6 and it doesn't throw the errors anymore.

I'll let you close the issue :)

**Comment by GDFaber** [comment]
Nice, thank you @netil and @cosmo0. I'll close this one then.
