### ISSUE TITLE
Upgrade Webpack 3.0 for performance

### ISSUE THREAD

**Issue by sculove** [naver/billboard.js#23]
## Description
webpack 3.0 supports `single scope hoisting`.
if we apply it, we get the low file size and fast loading speed.

**Comment by netil** [comment]
- Ref: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b#3750

**Comment by sculove** [comment]
we should be waiting for other libaray until update.
- webpack 3.0.0
- webpack-dev-server 2.5.0
- karma-webpack 2.0.3
- inject-loader 3.0.0

**Comment by netil** [comment]
1.0.1 dist files are built using webpack 3.0
- https://github.com/naver/billboard.js/tree/1.0.1/dist

Not changed the repo code due to webpack plugins compatibility with 3.0

**Comment by netil** [comment]
Take a look if is applicable.

- [CommonJS Tree Shaker plugin for Webpack](https://github.com/indutny/webpack-common-shake)

**Comment by netil** [comment]
With greenkeeper integration, dependencies will be automatically updated.
Checkout #65 for the auto PR.

**Comment by sculove** [comment]
inject-loader is updated.
