### ISSUE TITLE
Uncaught TypeError: $$.showCircleFocus is not a function

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2310]
## Description
In package.json:
"billboard.js": "3.1.5",

Inside app using require (as we are still in ES5)
const bbChart = require('billboard.js'); and strict mode enabled.

## Steps to check or reproduce
Having a bar chart and when simulating in chrome as a device <img width="62" alt="Screenshot 2021-09-09 at 12 58 57 PM" src="https://user-images.githubusercontent.com/47805716/132642132-17c8791b-2e98-4f06-8bb8-bf5f61c967e8.png"> and post rendering change the orientation in chrome using <img width="43" alt="Screenshot 2021-09-09 at 12 59 02 PM" src="https://user-images.githubusercontent.com/47805716/132642255-fae4fdcf-78d3-47e0-983d-fbfae731465d.png"> and when we do that we see exception:
<img width="445" alt="Screenshot 2021-09-09 at 12 41 49 PM" src="https://user-images.githubusercontent.com/47805716/132642315-709df394-512e-46ca-b26c-9fc3bd79122d.png">

When I see $$ prototype, I dont find showCircleFocus in it:
<img width="731" alt="Screenshot 2021-09-09 at 12 55 39 PM" src="https://user-images.githubusercontent.com/47805716/132642480-45578d17-5cad-451b-915f-0b9dbd23d464.png">

Unfortunately, I am unable to reproduce the issue when tried to reproduce in a standalone html file. Thanks in advance.

**Comment by netil** [comment]
Hi @5r1m, can you share the generation option code?

**Comment by 5r1m** [comment]
Below is the option being passed:

{
  "bindto": "#BarChart4",
  "zerobased": true,
  "padding": {},
  "grid": {
    "focus": {
      "show": false
    },
    "x": {
      "min": 0,
      "show": false
    },
    "y": {
      "show": false
    }
  },
  "data": {
    "type": "bar",
    "columns": [
      [
        "data1",
        50,
        20,
        40,
        33,
        13
      ],
      [
        "data2",
        80,
        50,
        65,
        64,
        6
      ]
    ],
    "labels": {
      "show": true,
      "colors": "rgba(57,62,75,1)"
    },
    "names": {
      "data1": "Some data",
      "data2": "Some other data"
    }
  },
  "bar": {
    "padding": 3,
    "width": {
      "ratio": 0.3
    }
  },
  "size": {
    "width": 708,
    "height": 354
  },
  "axis": {
    "x": {
      "type": "category",
      "categories": [
        "test1",
        "test2",
        "test3",
        "test4",
        "test5"
      ],
      "tick": {
        "show": false
      }
    },
    "y": {
      "tick": {
        "show": false
      },
      "max": 60
    },
    "rotated": true
  },
  "legend": {
    "show": false
  },
  "interaction": {},
  "tooltip": {
    "show": true
  }
}

**Comment by netil** [comment]
It happens on touch environment with `grid.focus.show=false` set. It will throw error when resize event is triggered.
I'll fix the issue, but if you want prevent throwing, just remove `grid.focus.show` option. (or set "true").

**Comment by 5r1m** [comment]
Thanks @netil , I have tried removing setting focus with false and with this, issue is not reproducible anymore. Will remove it for the time being.
