### ISSUE TITLE
Some issues with types

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2316]
I'm currently using billboard.js with plain JS files, where ESlint is employed to have soft type-checking in my IDE. The billboard.js types are provided via npm.

This has identified a few issues of different (though generally low) severity, which I'd like to present/report and discuss here, hoping this is considered valuable enough.

Note that all of this is just about the types reported, the operation of the code itself is fine.

### 1. "this" for load.done:

```
var bbchart = bb.generate(...) # generate some chart
bbchart.load({
   json: somedata,
   done: function() {
      # in here 'this' has wrong type
      dosomething();
   }
});
```

Inside the done() function, ESlint won't properly detect the type "Chart" for `this`, but thinks the type is actually the args array from the definition here:
https://github.com/naver/billboard.js/blob/master/types/chart.d.ts#L347

I'm not sure whether this is an ESlint/TS parsing bug or whether one could specify this for the done?: statement in the definition:
https://github.com/naver/billboard.js/blob/master/types/chart.d.ts#L366

### 2. zoom() only accepts numbers

`zoom([start, end])` only has type number[], although string is accepted for timeseries data:
https://github.com/naver/billboard.js/blob/master/types/chart.d.ts#L226

### 3. export.preserveaspectratio should be optional

export() works perfectly fine without setting preserveAspectRatio, so the type should be optional

https://github.com/naver/billboard.js/blob/master/types/chart.d.ts#L513

### 4. export() callback might return void

The callback function used with export() may return nothing (void) and will still work; however, the type requires string return value.

https://github.com/naver/billboard.js/blob/master/types/chart.d.ts#L514

**Comment by netil** [comment]
@adschm, thanks for looking into this!

**Comment by adschm** [comment]
I've tested with 3.2.0-next.5, and all issues are resolved there _except_ the zoom for string dates.

I will provide a PR for this in a minute, and also add one for another type issue I found recently.
