### ISSUE TITLE
onZoomEnd error when using touch controls

### ISSUE THREAD

**Issue by Venlious** [naver/billboard.js#2343]
## Description
When you have a line graph with `zoom: { enabled: true, type: 'drag' }` an error will appear in the console if you use touch controls to make a zoom selection (after letting go).

The error that appears:
```js
billboard.js:17456 Uncaught TypeError: Cannot read properties of null (reading 'changedTouches')
    at ChartInternal.onZoomEnd (billboard.js:17456)
    at bt.call (d3.v7.min.js:2)
    at w.emit (d3.v7.min.js:2)
    at w.end (d3.v7.min.js:2)
    at SVGRectElement.<anonymous> (d3.v7.min.js:2)
    at bt.call (d3.v7.min.js:2)
    at u (d3.v7.min.js:2)
    at li (d3.v7.min.js:2)
    at hi (d3.v7.min.js:2)
```

## Steps to check or reproduce
You can use the example on Billboard.js examples: https://naver.github.io/billboard.js/demo/#Axis.XAxisTickTimeseries

To reproduce:
1) Open dev tools
2) Enable mobile view for touch controls if not using a touch display
3) Make a selection using touch controls
4) See console for error

I have tested this with version `3.2.0-next.6` and `3.1.5`.

**Comment by netil** [comment]
Hi @Venlious, thanks for the report. I'll check the issue.
