### ISSUE TITLE
Cannot make solid white area fill

### ISSUE THREAD

**Issue by radiantone** [naver/billboard.js#235]
## Description

When choosing 'area' for a data axis and color #fff or any white "rgb(255,255,255)" bb fails to fill the area in as white and instead makes it just transparent. The background of the chart is also white. 

Trying to emulate this chart, which requires fill area to be actually filled white.
http://jsfiddle.net/ot19Lyt8/23/

**Comment by netil** [comment]
The opacity filled area value for `area` type is based on CSS `.bb-area` rule.
- https://github.com/naver/billboard.js/blob/master/src/scss/area.scss#L3

The default value is `0.2`. If you want to set to not be transparent, just overwrite the value as below.
```css
.bb-area {
    opacity:1;
}
```
And the result will be as follow.
![image](https://user-images.githubusercontent.com/2178435/34928904-0ccbffd6-fa04-11e7-9edc-e76bb6f372d4.png)

Check out the working code:
- https://jsbin.com/pumetok/1/edit?html,css,js,output

**Comment by radiantone** [comment]
Thank you for the info. Then this should work nicely.
