### ISSUE TITLE
Is there any way to use the donut chart as a semicircle?

### ISSUE THREAD

**Issue by jiniC** [naver/billboard.js#2353]
Is there any way to use the donut chart as a semicircle?
I can't find a way to check the [documentation](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.donut), so I'm asking. I want the appearance of the donut chart to be semicircular like the gauge chart.

**Comment by netil** [comment]
Hi @jiniC, if want draw half circler shape, use `gauge` rather than the donut.
- https://naver.github.io/billboard.js/demo/#GaugeChartOptions.GaugeStackData

**Comment by jiniC** [comment]
thank you. It's been a huge help!
