### ISSUE TITLE
Chart mouse is offset when parent has "transform: translate()"

### ISSUE THREAD

**Issue by Venlious** [naver/billboard.js#2365]
## Description
We noticed that for some users the zoom drag didn't work as expected. This was specifically for users using Firefox. The graphs are displayed in a grid layout and in some cases have a `transform: translateX(...)` offset present. The offset appears to match the unexpected gap in dragging.

## Steps to check or reproduce
Try out the zoom dragging in this example https://jsfiddle.net/ws3ndt0h/ on Chrome and Firefox. You will notice that the drag offset doesn't appear to match what you would expect. In this example "Graph 1" has an offset of 100px using `transform: translateX(100px)`.

Offset:
![image](https://user-images.githubusercontent.com/21037710/137138150-589e2de3-dda5-40b9-afb3-d97ff4d1155d.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/21037710/137138553-c635b806-a8a8-4c52-899a-30f90c71e697.png)

Tested with billboard.js 3.2.0

**Comment by jjfrankovich** [comment]
I ran into the same problem with d3 v3 and v7. I recently upgraded to v7 and the d3.transform method was missing so I found some help from this url:
//https://stackoverflow.com/questions/38224875/how-can-d3-transform-be-used-in-d3-v4     

Here is fix that seems to work to get the proper offset for firefox:
function getD3MouseEventPosition(event, element) {
`var targetElement = $(element).closest(".parentWithTransform")[0],
        translateInfo = targetElement && getTransformation(d3.select(targetElement).attr("transform")),
        transformedOffsetX = translateInfo ? translateInfo.translateX : 0,
        transformedOffsetY = translateInfo ? translateInfo.translateY : 0;

      return {
        x: event.offsetX - transformedOffsetX,
        y: event.offsetY - transformedOffsetY
      };
     }

     function getTransformation(transform) {
    if (!transform) {
      return;
    }
    // Create a dummy g for calculation purposes only. This will never
    // be appended to the DOM and will be discarded once this function
    // returns.
    var g = document.createElementNS("http://www.w3.org/2000/svg", "g");

    // Set the transform attribute to the provided string value.
    g.setAttributeNS(null, "transform", transform);

    // consolidate the SVGTransformList containing all transformations
    // to a single SVGTransform of type SVG_TRANSFORM_MATRIX and get
    // its SVGMatrix.
    const matrix = g.transform.baseVal.consolidate().matrix;

    // Below calculations are taken and adapted from the private function
    // transform/decompose.js of D3's module d3-interpolate.
    const { e, f } = matrix;

    return {
      translateX: e,
      translateY: f
    }; 
      `

**Comment by jjfrankovich** [comment]
So I did a bit more research on this and I was able to find two problems and I have potential solutions for both:
Problem 1) Chrome fails because its not using billboard.js's "getPointer" yet in getDataIndexFromEvent. This can potentially be corrected like this:

 getDataIndexFromEvent: function getDataIndexFromEvent(event) {
          const $$ = this,
            $el = $$.$el,
            config = $$.config,
            _$$$state = $$.state,
            hasRadar = _$$$state.hasRadar,
            inputType = _$$$state.inputType,
            _$$$state$eventReceiv = _$$$state.eventReceiver,
            coords = _$$$state$eventReceiv.coords,
            rect = _$$$state$eventReceiv.rect;
          let index;
          if (hasRadar) {
            let target = event.target;

            // in case of multilined axis text
            if (/tspan/i.test(target.tagName)) {
              target = target.parentNode;
            }
            const d = (0,external_commonjs_d3_selection_commonjs2_d3_selection_amd_d3_selection_root_d3_.select)(target).datum();
            index = d && Object.keys(d).length === 1 ? d.index : undefined;
          } else {
            const isRotated = config.axis_rotated,
              scrollPos = getScrollPosition($el.chart.node()),
              e = inputType === "touch" && event.changedTouches ? event.changedTouches[0] : event; // get data based on the mouse coords

            //start customization required v 3.11.3
            let x = e.clientX;
            let y = e.clientY;

            x = getPointer(e, e.target)[0] + rect.left;
            y = getPointer(e, e.target)[1] + rect.top;

            index = findIndex(coords, isRotated ? y + scrollPos.y - rect.top : x + scrollPos.x - rect.left, 0, coords.length - 1, isRotated);
            //end customization required
          }
          return index;
        },
        ...
}

Problem 2) For the tooltip, getPointer needs support for Firefox and Safari for when there are are css transforms involved:

      function getPointer(event, element) {
        var _ref,
          _this5 = this;
        const touches = event && ((_ref = event.touches || event.sourceEvent && event.sourceEvent.touches) == null ? void 0 : _ref[0]);
        let pointer = [0, 0];
        try {
          //pointer = (0,external_commonjs_d3_selection_commonjs2_d3_selection_amd_d3_selection_root_d3_.pointer)(touches || event, element);
          pointer = (0, getD3MouseEventPosition)(touches || event, element); //customization
        } catch (e) {
          window.console.log(e);
        }
        return pointer.map(function (v) {
          _newArrowCheck(this, _this5);
          return isNaN(v) ? 0 : v;
        }.bind(this));
      }

      function getD3MouseEventPosition(event, element) {

        var targetElement = element.closest(".bb-main"),
          translateInfo = targetElement && getTransformation(d3.select(targetElement).attr("transform")),
          transformedOffsetX = translateInfo ? translateInfo.translateX : 0,
          transformedOffsetY = translateInfo ? translateInfo.translateY : 0;

        const x = (event.offsetX - transformedOffsetX);
        const y = (event.offsetY - transformedOffsetY);
        return [
          x,
          y
        ];
      }
      
      
Let me know if you have any questions, or if there are any problems with this solution

**Comment by netil** [comment]
@Venlious @jjfrankovich 
It seems work fine now. Tested on MacOS FF & Safari.

- https://jsfiddle.net/netil/vxuLtpy5/1/
<img src=https://github.com/user-attachments/assets/592bce36-b0c6-4271-8b61-bbf7c26e93c3 width=400>
