### ISSUE TITLE
Need way to add Y grid lines dynamically.

### ISSUE THREAD

**Issue by radiantone** [naver/billboard.js#237]
## Description

When creating a chart, you can specify optional Y grid lines, as seen here.
https://naver.github.io/billboard.js/demo/#Grid.OptionalYGridLines

Based on some searching, an old C3 ticket was created to address the need to add these lines after chart creation (e.g. chart.load({grid: ... })) however, the authors reply to that ticket did not address the original need.

Is there a way to add these lines after chart is created?

**Comment by netil** [comment]
There's `.ygrid()` API to add grids on axis Y.
- https://naver.github.io/billboard.js/release/latest/doc/Chart.html#ygrids

Here is the code to add y grids like example.
```js
// Generate a chart
var chart = bb.generate({
	data: {
		columns: [
			["sample", 30, 200, 100, 400, 150, 250],
			["sample2", 1300, 1200, 1100, 1400, 1500, 1250]
		],
		axes: {
			sample2: "y2"
		}
	},
	axis: {
		y2: {
			show: true
		}
	}
});

// Add y grids
chart.ygrids([
	{
		value: 50,
		text: "Label 50 for y"
	},
	{
		value: 1300,
		text: "Label 1300 for y2",
		axis: "y2",
		position: "start"
	},
	{
		value: 350,
		text: "Label 350 for y",
		position: "middle"
	}
]);
```

**Comment by radiantone** [comment]
Thank you so much for the example!
