### ISSUE TITLE
Cannot autosize chart with parent container that overflows out of the body

### ISSUE THREAD

**Issue by Amiron49** [naver/billboard.js#2374]
## Description
When the parent div for a chart is wider than the body of the page, the chart ignores the parent width and uses the body width instead.

My use-case is that I'm trying to display charts on narrow mobile devices and desktop. On mobile I want the chart to overflow in the x-axis so the mobile user has to scroll (but at least the graph wouldn't be too smushed). And on desktop/large screens the chart should be unrestricted and grow to whatever the device width is. I tried to do that by creating "breakout" divs to act as the parent container of my charts, that have a fixed `width: 900px` on screens smaller than 500px. And on devices wider than 900px they would default to `width: 100%` instead. 

I could in theory dynamically edit the options of the chart depending on the device but the overhead of that seems unnecessarily complex.

I wish there was no smart logic at all that tried to force the chart back into the confines of the body. And instead the chart would be dumb and simply adhere 1:1 to the dimensions of whatever parent container the chart is thrown in. 

## Steps to check or reproduce

the "body" has a border and the red part is a "breakout" div that goes beyond the bounds of the body.

issue with the body: https://stackblitz.com/edit/a7k5ga-wwp1hh?file=index.html

how it works when no body is in the way: https://stackblitz.com/edit/a7k5ga-cgqm5p?file=index.html

**Comment by netil** [comment]
Hi @Amiron49, basically the autoresize will not exceed body's width value.
So, if you need to make some sort of auto resize to exceed body's width, you can implement simple resizer.

```js
const chart = bb.generate({
  ...,
  resize: {
     auto: false  // disable default auto resize
  }
});

// then, implement your own resize functionality
window.addEventListener("resize", function resize() {
	resize.timeout && clearTimeout(resize.timeout);
	resize.timeout = setTimeout(() => {
		chart.resize({
		    width: 500 // specify wrappers' width value
		});
	}, 300);
});

```
