### ISSUE TITLE
in Version 3.2.0 syntax error occurs in IE11

### ISSUE THREAD

**Issue by jiniC** [naver/billboard.js#2375]
I am testing working with latest version of billbard.js using cdn path.
But I found that this doesn't work in ie11.

![1](https://user-images.githubusercontent.com/13125662/137852870-39d84f12-0cc5-42ce-bdf0-1ead375282f1.PNG)

![2](https://user-images.githubusercontent.com/13125662/137852876-b1aeb604-e0c8-4ce5-8da6-2bf075acb7bf.PNG)

Here is my test code:
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>TEST</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/billboard.js/3.2.0/billboard.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/billboard.js/3.2.0/billboard.pkgd.min.js"></script>
</head>

<body>
  <div id="chart"></div>
  <script>
    var chart = bb.generate({
      data: {
        columns: [
          ["data1", 300, 350, 300, 0, 0, 0],
          ["data2", 130, 100, 140, 200, 150, 50]
        ],
        types: {
          data1: "area",
          data2: "area-spline"
        }
      }
    });
  </script>
</body>

</html>
```

<br>

I also found the following error in ie11 when accessing the site(https://naver.github.io/billboard.js/).

![billboard 차트 오류 3](https://user-images.githubusercontent.com/13125662/137851239-032bb18f-3412-4cb2-94c1-b71452599258.PNG)

<br>

ie Browser support is no longer available? Thanks for checking.

**Comment by netil** [comment]
Thanks for the report. I'll check the issue.
