### ISSUE TITLE
Bar chart with dual time custom axis

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2381]
## Description
I am trying to create broken horizontal bar chart with time series on dual y axis. Have some questions:
- is dual axis with date time possible?
I see generally its possible with numbers but didnt find documentation on how to achive this with time series?

- Is it possible to create broken bar chart
I am achieving this by kind of hack where I use stacked bar chart with data1 transparent to get this behavior. Is there any out of box option or better approach than this?

- customize the Y axis ticks like shown in the below drawing (week numbers in one and month in another)
Is there an option to custmize the axis and ticks like shown below?

<img width="787" alt="Screenshot 2021-10-22 at 2 36 25 PM" src="https://user-images.githubusercontent.com/47805716/138426815-9226fc7f-b3e8-4b6b-97d4-a401c78130dd.png">

## Steps to check or reproduce
https://codepen.io/5r1m/pen/OJjbQjy

**Comment by netil** [comment]
HI @5r1m 

> Is it possible to create broken bar chart

can be drawn using `candlestick` type.
```js
 data: {
    columns: [
		["data1", 
			// data format should be:
			// [ start value, start value + data length, ... ]
			[10, 10+130, 10, 10+130],
			[220, 220+230, 220, 220+230],
			[310, 310+470, 310, 310+470],
			[270, 270+500, 270, 270+500]
		]
```

The axis tick value always correlate with the data bound. If wants to display text values where has no direct connection with the data, you need to handle it separately. (via `axis.y.tick.format`)

checkout the example based on you needs as much as possible:
- https://jsfiddle.net/netil/mj47pg3r/

**Comment by 5r1m** [comment]
Thanks @netil for the idea. For custom axis (styling), is it possible to do as shown in picture with config or css? I know it can be done through d3 but want to see if there is option provided for doing this out of box or limited css

**Comment by netil** [comment]
@5r1m, there's no specific option to make display as you want and it can't be provided everything as an option.
for your case, will be better implement it manually adding necessary DOM elements and its styling.

checkout the example
- https://jsfiddle.net/netil/mj47pg3r/3/

**Comment by 5r1m** [comment]
@netil intension was only about enquiring about possibility using option but not asking to provide as option. Anyways thanks for the css option, but this wont work as it is not relative to scale.
