### ISSUE TITLE
Showing tooltip API doesnt work with xs and throws exception in touch mode

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2390]
## Description
I am trying to show tooltip at runtime. How ever there are two issues observed and it doesnt work as documented:
1. show tooltip API doesnt show the tooltip with grouped true/false and with index/x
2. When in touch mode (chrome simulation), it throws below exception:

<img width="1019" alt="Screenshot 2021-10-29 at 11 22 33 AM" src="https://user-images.githubusercontent.com/47805716/139384075-1deec868-7817-465b-9d0b-8fc66b3114ee.png">

## Steps to check or reproduce
https://codepen.io/5r1m/pen/PoKKNRa

**Comment by netil** [comment]
Hi @5r1m,

For `timeseries` type axis, try giving `x` value as Date value. And if you just want to make tooltip to be displayed at the initialization, you can use `tooltip.init.show` option.

```js
chart.tooltip.show({
    data: {
        "value": 2,
      "id": "data2",
      //"index": 0,
      "x": new Date("2021-11-27 00:00")
  }
});
```

**Comment by 5r1m** [comment]
Thanks @netil for looking in to this. I see that this works BUT only for start and end of the data and for no other point. For eg: it works for 27 but not for 28 in the example. Did I again hit any limitation? :( If so, Is there any way to over come this?

**Comment by netil** [comment]
@5r1m, based on the example you shared, there're 2 ticks.

```js
chart.tooltip.show({
    data: {
        "value": 2,
      "id": "data2",
      "x": new Date("2021-11-27 00:00")
      // "x": new Date("2021-12-27 00:00")
  }
});
```
And by calling with different x datetime value, it will display tooltip as below.

![Kapture 2021-11-03 at 11 15 18](https://user-images.githubusercontent.com/2178435/140001391-cf3c2377-4f99-4cb0-b756-2508c01d44ab.gif)

**Comment by 5r1m** [comment]
Yes @netil it works for only the start and end dates but not in between. How ever showTooltip(internal) has the ability to work with tooltip irrespective of start and end data points. Will close this as I guess this might not be supported by line.

**Comment by netil** [comment]
> it works for only the start and end dates but not in between

For tooltip display, basically it works only for data existence ticks. In a between position, needs some customization.
