### ISSUE TITLE
[API] Impossible to unset min/max on axis

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2398]
I'm trying to implement an option which would allow to toggle specific values for the min/max boundaries of the y axis.

### Problem:

It's quite simple to enable min/max limits:
`mychart.axis.range({max: {y: 140}, min:{y:60}});`

But once they are enabled, it's impossible to get rid of them via the API:

1. Setting "undefined", "null" or "false" to the `y: ...` will get filtered by the code, nothing happens.
2. Setting `mychart.axis.range{max: false, min: false}` will reset max and keep min, since both have different algorithms for checking [1] [2]

### Possible solutions:

There is no obvious clean way to solve/implement this.
Giving `undefined` as value doesn't seem right:
`mychart.axis.range({max: {y: undefined}, min:{y: undefined}});`

IMO the best comprise would be to accept `false` instead of a value, and then adjust the code in setMinMax to set "undefined" when a value is matched against `=== false`, so one could unset with:
`mychart.axis.range({max: {y: false}, min:{y: false}});`

If implemented properly, this should keep the ability to change the min/max of individual axes without touching the others, as it's possible at the moment.

And of course, the checks for min() and max() should be harmonized.

### Ref:

[1] https://github.com/naver/billboard.js/blob/master/src/Chart/api/axis.ts#L153
[2] https://github.com/naver/billboard.js/blob/master/src/Chart/api/axis.ts#L128

**Comment by adschm** [comment]
For documentation:

The workaround obviously is just copy-pasting the code using .internal:

```
mychart.internal.config["axis_y_max"] = undefined;
mychart.internal.config["axis_y_min"] = undefined;
mychart.internal.redraw({
			withUpdateOrgXDomain: true,
			withUpdateXDomain: true
		});
```

**Comment by netil** [comment]
The current best way to reset, would be:

```js
chart.config("axis.y.max", null, true);
chart.config("axis.y.min", null, true);
```

It would be reasonable provide some way to reset the range as you suggested. I'll try consider this for next release.  Thanks!

**Comment by adschm** [comment]
> The current best way to reset, would be:
> 
> ```js
> chart.config("axis.y.max", null, true);
> chart.config("axis.y.min", null, true);
> ```
> 
> It would be reasonable provide some way to reset the range as you suggested. I'll try consider this for next release. Thanks!

Since I'm always doing both at once, it's probably better to call redraw only once?

```
chart.config("axis.y.max", null, false);
chart.config("axis.y.min", null, true);
```
