### ISSUE TITLE
`onclick` doesn't work on touch screens ?

### ISSUE THREAD

**Issue by drazik** [naver/billboard.js#24]
Hello,

## Description
I put an `onclick` callback on my chart. It works pretty well when clicking with a mouse on a desktop device. But when touching a point on a touch screen or in chrome and firefox in touch device simulation mode, it doesn't execute my callback.

## Steps to check or reproduce
[Here is a codepen](https://codepen.io/anon/pen/XgRXza) on which you can easily reproduce this, by clicking on a point.

Thanks for you work.

**Comment by netil** [comment]
@drazik thanks reporting.
Confirmed the issue, and will be fixed. We're planning to release the next version in few weeks and this will be fixed on that.
