### ISSUE TITLE
getPointer: Exception when touches are zero

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2409]
## Description
I was trying something and encountered an exception once (couldn't reproduce again) and I traced it back to utils: getPointer. Problem seems to be inside this API, it goes with assumption that when touches is defined, even touches[0] is defined. This will not be true when touches is empty array and results in exception inside d3 selection.

One probable fix would be to check also length.

## Steps to check or reproduce
https://github.com/naver/billboard.js/blob/ab8643980fa1f645699ee84203904324d4c6f2ec/src/module/util.ts#L267

**Comment by netil** [comment]
Hi @5r1m, thanks for sharing. Kinda difficult if the cause or happening isn't reproducible.
Anyway, I'll be updating to prevent this unexpected case.

**Comment by 5r1m** [comment]
Hi @netil , I see that this was not included in last release. Can you please confirm if this is going to be in next release? Thanks.

**Comment by netil** [comment]
The changes has been included in `v3.2.2`.
- https://github.com/naver/billboard.js/blob/3.2.2/src/module/util.ts#L264-L269

If issue continues, it needs a reproducible way for the fix.
Assuming the cause not knowing exactly what is it, will make harder figure out and fix.
