### ISSUE TITLE
Provide theme style using different CSS

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#241]
## Description

Aside of the default CSS style, providing different look based on `theme style` will be useful.
Just changing the load of these files can make chart to render to have different style.

```html
<!-- default css -->
<link rel="stylesheet" href="$YOUR_PATH/billboard.css">

<!-- ex: replace the default to use other theme css file -->
<link rel="stylesheet" href="$YOUR_PATH/theme/lighter.css">
```

**Comment by Hanterdro** [comment]
A much better solution for theming would be the usage of CSS Custom Properties:

https://developer.mozilla.org/en-US/docs/Web/CSS/--*

CSS Custom Properties allows you to theme at the runtime!

Example

```
// global theme
:host {
  --bb-grild-line-stroke: red;
}

// style a spefic chart
.myChart {
  --bb-grild-line-stroke: red;
}
```

Implementation (billboard.css):

```
.bb-grid line {
  stroke: #aaa; //IE11 Fallback
  stroke: var(--bb-grild-line-stroke, #aaa); }
```

Only downside of the solution is that IE11 does not support this kind of theming.

**Comment by netil** [comment]
@Hanterdro thanks for the suggestion.
That will be one of the alternatives, but it should cover IE11 too. It can be considered when IE11 usage degrade on meaningless level.

**Comment by Hanterdro** [comment]
@netil 
I would suggest that you add CSS custom properties to the default theme, additional to the option for a custom theme.css file path as you described above.

In my example you see how to add css custom properties with fallback values for IE11.

If a user of billboard.js don’t need IE11 theming he could use the original theme.css with the custom properties. If he need IE11 theme support he just use the theme path.

Adding CSS custom properties is not much work and brings a  lot of value without any disadvantages.

**Comment by netil** [comment]
# Screenshot of each Themes

- In order of
  default &rarr; insight &rarr; graph &rarr; datalab

## Color patterns
![image](https://user-images.githubusercontent.com/2178435/91416931-06c6a000-e88b-11ea-94b8-8e344217671e.png)

## Axis, Legend & Tooltip
![image](https://user-images.githubusercontent.com/2178435/91417519-e519e880-e88b-11ea-8a51-dbec72be0fb2.png)

## Data Point & Grid
![image](https://user-images.githubusercontent.com/2178435/91418138-b6e8d880-e88c-11ea-8ab1-954970b9bc39.png)

## Pie

![image](https://user-images.githubusercontent.com/2178435/91418445-1e068d00-e88d-11ea-88b6-2bd310b3a1c9.png)

**Comment by msteller-connyun** [comment]
Btw... IE 11 is dead, after there’s now Edge for Win7.

So maybe it’s now time to support CSS Custom Properties ;)
