### ISSUE TITLE
how to change json data to columns?

### ISSUE THREAD

**Issue by cepiloth** [naver/billboard.js#2419]
## Description

Hello. I Have a some questions.
Currently, there is an inconvenience when using billboard.js.
I want to know how to change the parameter to 'columns' format when binding data to chart.

`chart = bb.generate({
      data: {
        columns: [
          ["data1", 30],
          ["data2", 120],
        ],`

//TODO
data: jsontocolums()

I want to use JSON DATA right away, but I don't know how.

**Comment by netil** [comment]
Hi @cepiloth, checkout the examples and documentation.

- Example: https://naver.github.io/billboard.js/demo/#Data.JSONData
- Doc: https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4json

**Comment by cepiloth** [comment]
thank you:)
