### ISSUE TITLE
Candlestick Chart example compile error

### ISSUE THREAD

**Issue by g2developer** [naver/billboard.js#2422]
Enviroment : Typescript, Angular

I was copy and paste in typescript example source from Canclestick Chart page (https://naver.github.io/billboard.js/demo/#)
but occurred compile error.

**Type 'number' is not assignable to type 'string'.(2322)**

This error occurring too in your web page <Code Editor (TS)>

thx

고생이 많으세요. 
웹 검색하다가 빌보드 컴포넌트를 발견해서 사용해보려고 즐거운 마음으로 예제를 복사해서 넣어봤는데 
오류가 발생하고 있네요.
타입오류인 것 같은데 예제 페이지에 코드 에디터(타입스크립트)에서도 발생하고 있네요.

그리고 데이터를 가지고 올 때 백엔드단에서 json 배열 형태로 가지고 오는데 
json배열 형태의 데이터는 캔들차트에 어떻게 적용할 수 있을까요?
아래와 같은 형태입니다.
[
{ datetime:'2021-11-18 11:00:00', open:'1000', high:'1100', low:'900', close:'800', volume:'123' },
{ datetime:'2021-11-18 11:00:00', open:'1000', high:'1100', low:'900', close:'800', volume:'123' },
{ datetime:'2021-11-18 11:00:00', open:'1000', high:'1100', low:'900', close:'800', volume:'123' }
]

**Comment by netil** [comment]
Hi @g2developer, thanks for the type error report. I'll check the issue.
And for JSON data format, you can use with one of below format.

```js
data: {
    // #1
    json: {
        data1: [
            [1327, 1369, 1289, 1348],
            {open:1348, high:1371, low:1271, close:1320},
            ...
        ]
    },
    
    // #2
    json: [
            {
                name: "data1",
                "data": {
                    open:1300, high:1369, low:1200, close:1339, volume:100
                }
            },
            ...
    ],
    keys: {
        value: ["data"]
    },
```
