### ISSUE TITLE
legend.usePoint not working for custom points patterns if there is spaces or special chars in data title

### ISSUE THREAD

**Issue by ugoQ** [naver/billboard.js#2425]
To reproduce this, go here https://naver.github.io/billboard.js/demo/#Legend.usePoint
And rename one of the titles with a custom point pattern associated, for example rename `"data3"` to `"data_3"` or `"data 3"` (same thing happens with slashes, parentheses, brackets...), you will see that the related "point" is not displayed in the legend.

Because the legent point has this `href`
```
<use class="bb-legend-item-point" href="#bb-1637241256550-point-data{3" ...>
```
Whereas the polygon definition has this `id`
```
<polygon id="bb-1637241256550-point-data-3" ...>
```

**Comment by netil** [comment]
Hi @ugoQ, thanks for the report.

**Comment by ugoQ** [comment]
> Hi @ugoQ, thanks for the report.

No problem, thanks for the quick fix and thanks for this amazing library!
