### ISSUE TITLE
Empty space left in graph when hiding y2 with CSS

### ISSUE THREAD

**Issue by netbymatt** [naver/billboard.js#2429]
## Description
I'm plotting data on both y and y2, but I do not want the y2 axis to be drawn on the chart. I have read #894 and #1016 and see that I must set `axis.y2.show = true` for the data to be plotted correctly. I have also added CSS to hide the axis `.bb-axis-y2 { display: none; }` to hide the axis. The axis is hidden, but unlike an html element with display: none which collapse the element and allows other elements to fill the space, when used against the SVG the element is not collapsed and there is a slice of empty white space at the right edge of my plot area.

Is there a way to use y2 without it being drawn and without the empty space generated by the CSS solution?

## Steps to check or reproduce
Fiddle: https://jsfiddle.net/fmr3b47h/
Explanation: Graph-1 and Graph-2 are the same graph. Both have been placed on an (ugly) red background to highlight the size of the graph element. The second graph has the CSS fix `.bb-axis-y2 {display: none}` added to it. Note the extra space blank space at the right of Graph-2. 

I would like a solution that lets Graph-2 expand to fill the space vacated by the y2 axis.

**Comment by netil** [comment]
Hi @netbymatt, use [`padding`](https://naver.github.io/billboard.js/release/latest/doc/plugin-stanford.html#.padding) option as below.

```js
  padding: {
  	right: 0
  },
```

**Comment by netbymatt** [comment]
Thanks for the response. I had missed the entire graph's padding at the top level of the options. For those that come across this later I want to share the following notes. This is all in the documentation as well.

`axis.x.padding` takes either a number that sets both the `left` and `right` values. `left` and `right` determine the distance between the vertical y axis and the first/last point plotted. The default makes for a prettier plot with a little room for each of the points to breathe and setting it to 0 will plot the lowest x value on the y-axis, similar to what you'd see in a scientific setting.

`axis.y.padding` is the same as x, but in the vertical direction.

`padding` takes only an object with `top`, `right`, `bottom`, and `left` this controls the amount of space between the extents of the drawn graph and the actual bounding box of the graph. Note, unlike the axis properties there is no numeric shorthand for this property. This is the option that resolved my issue.
