### ISSUE TITLE
Text is overlapping on x-axis

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#244]
Hi @netil ,
There is some text on x-axis which is overlapping or not visible.
Please refer screenshot.Is there any option to set this properly?
![image](https://user-images.githubusercontent.com/33453608/35207853-39158032-ff6b-11e7-9ada-cf8129c8db3a.png)

**Comment by netil** [comment]
Hi, @Rohit-Parte 
You can try setting the height value of x axis with [axis.x.height](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4height) option.

```js
axis: {
  x: {
    height: 20
  }
}
```
