### ISSUE TITLE
y tick text is clipped on rotated bar chart

### ISSUE THREAD

**Issue by eLarocque** [naver/billboard.js#2444]
## Description
There is a visual bug that is apparent when the y axis's yPosition is changed on a bar chart with rotated axes. The text seems to be cut when there is no reason for it to be.

## Steps to check or reproduce

Can see the issue here:
https://stackblitz.com/edit/zykutw

- Open Stackblitz link
- Click on the "Rotate Axis" button

Here is a non rotated chart example:
![image](https://user-images.githubusercontent.com/8459019/143943708-7129ac33-cbff-4d82-91cb-6b87df79e563.png)

Here you can see the issue:
![image](https://user-images.githubusercontent.com/8459019/143943787-49cb2bfd-1c91-491e-9035-ee3d7ebe8182.png)

As you can see the switched y-axis (which is now the x-axis) text is clipped, like if there isn't enough room in the svg, when it is not the case.

**Comment by netil** [comment]
Hi @eLarocque, try with setting [`axis.y.clipPath=false`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4clipPath) option.

![Kapture 2021-11-30 at 14 13 04](https://user-images.githubusercontent.com/2178435/143989522-2fbbff65-8d53-4007-b921-d4d463c6ca7c.gif)

**Comment by eLarocque** [comment]
This worked, thanks @netil !
closing the issue!
