### ISSUE TITLE
X Axis Tick Fitting: Doc error

### ISSUE THREAD

**Issue by Nicolas469** [naver/billboard.js#2446]
## Description
[Documentation](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4fit) says: _**true**: will i ticks will be positioned nicely to have same intervals_ but a simple look to the [demo](https://naver.github.io/billboard.js/demo/#Axis.XAxisTickFitting) shows exactly the opposite.
For me, it's an error in the doc, not in the code.

**Comment by netil** [comment]
Hi @Nicolas469, thanks for the report.
The description for `axis.x.tick.fit` will be updated as follows:

- As-is:
> true: ticks will be positioned nicely to have same intervals.
> false: ticks will be positioned according to x value of the data points.

- To-be:
> true: ticks will be shown according to x value of the data points.
> false: ticks will be shown as to have same intervals.
