### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#246]
Hi @netil ,
Do we have this kind of graph?
![image](https://user-images.githubusercontent.com/33453608/35258462-b159e5f0-0025-11e8-82c1-7429d75a31c2.png)

**Comment by netil** [comment]
@Rohit-Parte, the image was not fully uploaded.
Could you upload again?

**Comment by Rohit-Parte** [comment]
@netil,
Alright, Combination chart has been worked for me.
Thanks
