### ISSUE TITLE
Cannot read properties of null (reading 'sourceEvent') in device mode

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2477]
## Description
There is uncaught exception when clicking on pie chart in device mode in chrome

## Steps to check or reproduce
- Open the pie chart example in device mode in chrome
- https://naver.github.io/billboard.js/demo/#Chart.PieChart
- Post load completion, click on any chart pie area

<img width="1456" alt="Screenshot 2021-12-28 at 1 31 03 PM" src="https://user-images.githubusercontent.com/47805716/147543646-bd5ee4b3-c5f1-4dc9-9f12-950262c14984.png">

**Comment by 5r1m** [comment]
Problem seems to be in this handler:
https://github.com/naver/billboard.js/blob/65da5a80b383ca22959043d0eb0e25924c919ee6/src/ChartInternal/shape/arc.ts#L798

Unlike in mouse mode, event is not persisted in touch mode and adding below seems to fix the issue:
adding state.event = event;

**Comment by netil** [comment]
Hi @5r1m, thanks for the report. I'll check the issue.
