### ISSUE TITLE
[Feature request] Add an option for culling to also hide ticks, along with tick labels.

### ISSUE THREAD

**Issue by ImADrafter** [naver/billboard.js#2478]
## Description
I have an use case where the chart should handle both large and small datasets. I found that my solution could be use culling, but also, hide ticks along with the tick labels.

For large data sets, if you specify culling, the ticks will end overlapping one with each other.

Other possibilities that I've tried so far:

The configuration specified at [X Axis Tick Timeseries](https://naver.github.io/billboard.js/demo/#Axis.XAxisTickTimeseries), may look good when the dataset is large. But it falls short when you have less entries than the number specified by axis.x.count, because it shows more ticks than data points. This seems OK on area charts, but it feels weird for line charts.

If you change the size of the dataset with previous configuration ({fit: false, count:5}) an strange behavior occurs, ignores the specified count. Please take a look at bellow images.

![image](https://user-images.githubusercontent.com/44379989/147562054-62ff6012-348f-44ff-95d9-934ee3bf7cb3.png)
![image](https://user-images.githubusercontent.com/44379989/147562059-dc984bd4-d92c-4fb5-bbe0-9669739e391c.png)

If fit: false is specified, then the x axis labels will no longer be positioned according to the data, as the documentation indicates.

So, I tried different configuration possibilities. One of them was using culling: { max: 5 }, which works nice, but with large datasets, the x axis looks really bad, since all the ticks are overlapping.

![image](https://user-images.githubusercontent.com/44379989/147562068-8acd227d-7d43-4bc4-9037-485ea5c39b7e.png)

It would be nice to have the option of also, hide the tick along with the label while using culling. Maybe this was the original idea from count? What am I missing here?

Thank you for taking the time to read this issue. Please let me know how should I proceed.

## Steps to check or reproduce

In this [codeSandbox](https://codesandbox.io/s/bb-with-large-dataset-forked-pmnw8) you can change the length of the dataSet and check what I described before.

**Comment by netil** [comment]
> If fit: false is specified, then the x axis labels will no longer be positioned according to the data, as the documentation indicates.

The description for `fit` was described in opposite way, which was fixed now, https://github.com/naver/billboard.js/commit/e504bdd04fff5858d2dec9ec6b0caffa0adc610b

From the latest release with some option combination, you can limit x axis ticks appearance as below.

<img src=https://user-images.githubusercontent.com/2178435/147896200-67cdda52-d073-4244-9791-7fb0e10923cc.png width=500>

I think, with the option `count=5`, will fulfill your needs. But if want to make ticks to be displayed as the last screenshot without tick lines, you can control the visibility by style.

```html
<div id="cullingChart"></div>
```
```css
#cullingChart .bb-axis-x .tick line {
    display: none;
}
```
```js
const chart = bb.generage({
    ...
    axis: {
        x: {
            culling: {
            max: 5,
        }
    },
    bindto: "#cullingChart"
});
```
