### ISSUE TITLE
y-axis doesn't automatically fit after hiding bar chart

### ISSUE THREAD

**Issue by Kedia94** [naver/billboard.js#2501]
Hello.
I'm going to update billboard.js from 1.12.11, and found there is slightly difference feature between `1.12.11` and `2.* and later`.
I want to know if it is a bug or intended change.

## Description

It happens after billboard.js is updated to 2.0.
Chart with line and bar types doesn't change min value of y-axis when hiding bar type.
Specifically, the min value is always 0 or less.

- Above image: data1 is line, and data2 is bar
- Below image: both data are line

### 2.* and later
![image](https://user-images.githubusercontent.com/11289254/149263712-0a6192cb-1826-4766-a3ac-99a807021a74.png)

#### 1.12.11
![image](https://user-images.githubusercontent.com/11289254/149270083-bacf8146-1ab2-4f45-b1f2-c2d79b0d2023.png)

## Steps to check or reproduce

I made it with stackblitz: https://stackblitz.com/edit/ggvqc5?file=index.ts
After 2 seconds, it automatically hides one chart.
It happens when hiding bar, area, area-spline, or area-step.

Thanks.

**Comment by netil** [comment]
If `bar` type is included, y axis will be based from the zero, which means bar shape starts rendering from zero.
Even bar is hidden, the y axis will be stuck from that configuration. If don't want y axis stuck on zero, try setting below option.

```js
  bar: {
    zerobased: false
  },
```
