### ISSUE TITLE
Inverted Y-Axis Does Not Handle Positive Values Correctly

### ISSUE THREAD

**Issue by StrangeWill** [naver/billboard.js#2503]
## Description
When you enable `inverted` on an axis, positive values mess up the chart rendering bars from the bottom of the graph instead of from "zero".

Inverted:
![image](https://user-images.githubusercontent.com/1322565/149366496-341c187a-7d7a-4a8c-ab25-7b6cce61e8e8.png)

Not Inverted:
![image](https://user-images.githubusercontent.com/1322565/149366535-95ae0e86-e279-4fda-99a6-f1a6940426fc.png)

Obviously we basically expect the "not inverted" chart, but mirrored on the x-axis, instead we're getting... whatever is happening on the inverted image (it's drawing "up" from the "max" (now "min") y-value to the value of the series)

## Steps to check or reproduce
Given this example:
https://naver.github.io/billboard.js/demo/#Chart.BarChart

Using the following javascript:
```js
// for ESM environment, need to import modules as:
// import bb, {bar} from "billboard.js"

var chart = bb.generate({
  axis: { y: { inverted: true } },
  data: {
    columns: [
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 100, 140, 200, 150, 50]
    ],
    type: "bar", // for ESM specify as: bar()
  },
  bar: {
    width: {
      ratio: 0.5
    }
  },
  bindto: "#barChart"
});

setTimeout(function() {
	chart.load({
		columns: [
			["data3", 130, -150, 200, 300, -200, 100]
		]
	});
}, 1000);
```

**Comment by netil** [comment]
Hi @StrangeWill, current `inverted` option makes not only axis to be inverted. It changes the way bar to be drawn.
The shape will be drawn from the bottom to the value, not from the zero.

If you checkout the below example, every bar shape ends to the position of given value, and its not starting from the zero.
```js
["data1", 30, 200, -100],
```
<img src=https://user-images.githubusercontent.com/2178435/150067126-945f8368-a7c8-4d2f-8be5-7057b9732925.png width=350>

**Comment by StrangeWill** [comment]
Ah okay, yeah that behavior isn't in line with the documentation which I'd expect to _only_ invert the axis, not change how the data is also drawn: https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4inverted, an inverted chart we'd normally expect should look the same just "flipped" along the inverted axis.

It's also a bit inconsistent, because if you use all negative values it _does_ use zero as a basis (we got thrown off when some numbers end up positive and the chart starts drawing things in an entirely unexpected manner).

I'll have to ponder if there is another way to accomplish an axis inversion only.

**Comment by SaphireLattice** [comment]
Looking at the docs it does seem to imply only touching the direction of the axis, and from that the data. Even if there's not much actually said there. 

The behavior of setting the bar origin to some dynamic value at the bottom of the chart looks rather not intuitive neither for the developer, nor for possible user trying to read the chart. Perhaps this should be its own separate option, something like `dynamicOrigin`, to automatically set the bar's origin line to something different than 0, which this seems to do for some reason?

**Comment by netil** [comment]
@StrangeWill @SaphireLattice, thanks for the comments and you're right.
I eyed previous releases handling on this, and realized since `v1.12.4` the way on drawing has been changed.

I guess some updates mistakenly caused a side-effect where couldn't be noticed until present.
`v1.12.3` seems working correctly.
- https://jsfiddle.net/netil/uts9p02z/1/

**Comment by StrangeWill** [comment]
Oh awesome, thanks for digging into that more! I'll see if we can't roll back to 1.12.3 for the time being (may be a day or two before I can eyeball that on our end)

**Comment by netil** [comment]
@StrangeWill, I'll be trying patch soon and releasing it. Probably within this week.
