### ISSUE TITLE
Q: Is it possible to set a double click event on a bar chart

### ISSUE THREAD

**Issue by alexkzone** [naver/billboard.js#2521]
Hi,

I need to set up a double click on a chart. 
Is it possible?

Thanks,
Alex

**Comment by netil** [comment]
Hi @alexkzone, could be more specific?
Currently there's no option for double click event. If is needed, you need to bind manually.

For e.g., below code will bind a double click event to whole chart area.
```js
	onafterinit: function() {
		this.$.main.on("dblclick", function(e) {
			console.log(e)
		});
	},
```

**Comment by alexkzone** [comment]
Hi @netil 
First of all, thank you for your job and help!
And back to my question: I need the ability to double click on a single bar (similar to "onclick").
I tried your code, but I always get .bb-event-rect rect and not a bar behind. Is it possible to get a single bar?

Thanks,
Alex

**Comment by alexkzone** [comment]
Thanks, @netil!
