### ISSUE TITLE
Browser freezes with onclick option

### ISSUE THREAD

**Issue by alexkzone** [naver/billboard.js#2522]
## Description
Hi,
A browser freezes with the "onclick" option (not sure if the onclick option cause this behavior, but after a lot of testing, I think it does). Not constantly, but if the page still opens, it freezes after a while.
Sometimes it is back, but sometimes it is completely gone.

## Steps to check or reproduce
https://jsfiddle.net/aqkshx8e/

**Comment by netil** [comment]
There's nothing suspicious triggering `onclick` event. 

I'm guessing your example could possible make some break, because
- `onclick` option:
    Loading data dynamically, will make it redraw the chart.  If you're clicking multiple times with very short intervals, it will interrupt the whole chart rendering process, which eventually breaks if the prior loading process hasn't been correctly ended.

    Is it safe to use [`load.done`](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load) to ensure to do some task after data loading ends.
- `zoom` option: 
    If you go through how zoom interaction works, the interaction of starting the zoom is the same as "click".
    This also will affect if some of the "click" interaction happens holding "mousedown", it makes it difficult determine if the user intention is click or wants to start zooming.

```js
  onclick: (e,i) => {data.unload= true;chart.load(data);console.log("done");},
  "zoom": {
    "enabled": true,
    "rescale": true,
    "type": "drag",
    "resetButton": true
  },
```

**Comment by alexkzone** [comment]
It looks like that is the problem. Thanks a lot, @netil!
