### ISSUE TITLE
convertInputType: Incorrect input type returned for Android tablets

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2526]
## Description
For some Android tablets, Input type is returned incorrectly.

## Steps to check or reproduce
Open https://naver.github.io/billboard.js/demo/#Interaction.PreventScrollOnTouch in an Android tablet and set mouse interaction as false. Post this, interaction doesnt work and tooltips are not shown. I could reproduce this in Samsung S6 tablet.

Problem seems to be in convertInputType method
https://github.com/naver/billboard.js/blob/d3cc268ae7a6251539cb205e4223f3b2d55c39d9/src/module/util.ts#L736

Here it checks for 'Mobi' token inside user agent but these tablets doesn't have this token and returns as mouse. How ever the mouse handler binding is not done as mouse input is false by which events are not captured and tooltip/selection doesnt work.

User agent for S6 tablet:
https://user-agents.net/string/mozilla-5-0-linux-android-7-1-2-galaxy-tab-s6-build-n2g48h-wv-applewebkit-537-36-khtml-like-gecko-version-4-0-chrome-66-0-3359-158-mobile-safari-537-36

User agent for Galaxy Tab A:
https://developers.whatismybrowser.com/useragents/explore/operating_platform/galaxy-tab-a-10-1-sm-t585/

One probable fix would be to extend the regex to include 'Android' token as well. Thanks!

**Comment by netil** [comment]
Hi @5r1m, thanks for the report.
The detection mechanism based on `navigator.userAgent` was quite common for long period, but is reaching the end.
> Ref. [Update on User-Agent String Reduction in Chrome](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html)

So, avoiding detection based on `userAgent` info is necessary as describe at:
- [MDN: Avoiding user agent detection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#avoiding_user_agent_detection)
