### ISSUE TITLE
issue with 'subchart.show()' and 'subchart.hide() '

### ISSUE THREAD

**Issue by RuggeroN** [naver/billboard.js#2534]
## Description

Hello Netil, I have a problem with method subchart.show() (and subchart.hide()) in a angular webapp;
in develop mode, with billboard.js v3.2.0, v3.2.1, v3.2.2 all works fine, but in prod mode something goes wrong.
With 3.3.0 and 3.3.1 versions, i have the same problem either in develop and prod mod; 
error is always the same: 
```
TypeError: Cannot read properties of null (reading 'style')
    at SVGGElement.<anonymous> (main-es2015.1444be1b0d3974b6b534.js:31:384786)
    at sn.each (main-es2015.1444be1b0d3974b6b534.js:31:176402)
    at main-es2015.1444be1b0d3974b6b534.js:31:384716
    at Array.forEach (<anonymous>)
    at t.setCulling (main-es2015.1444be1b0d3974b6b534.js:31:384462)
    at t.redrawAxis (main-es2015.1444be1b0d3974b6b534.js:31:384194)
    at t.redraw (main-es2015.1444be1b0d3974b6b534.js:31:306005)
    at t.updateAndRedraw (main-es2015.1444be1b0d3974b6b534.js:31:308816)
    at t.flush (main-es2015.1444be1b0d3974b6b534.js:31:351604)
    at t.hide (main-es2015.1444be1b0d3974b6b534.js:31:428913)
```
from package.json:
```
dependencies
    "@angular/animations": "~11.2.9",
    "@angular/cdk": "~11.2.8",
    "@angular/common": "~11.2.9",
    "@angular/compiler": "~11.2.9",
    "@angular/core": "~11.2.9",
    "@angular/forms": "~11.2.9",
    "@angular/localize": "^11.2.9",
    "@angular/material": "^11.2.8",
    "@angular/platform-browser": "~11.2.9",
    "@angular/platform-browser-dynamic": "~11.2.9",
    "@angular/router": "~11.2.9",

    "@types/d3": "^6.3.0",
    "billboard.js": "^3.3.1",
    "d3": "^6.6.2",
    "d3-voronoi": "^1.1.4",
    "rxjs": "7.4.0",
 ```
## Steps to check or reproduce

simply setting 'subchart.show: true' trigger the error: 
```js
subchart: {
        enabled: subchart(),
        show: true,
        size: {
          height: 15,
        },
        axis: {
          x: {
            show: true,
            tick: {
              show: true,
              text: {
                show: false,
              },
            },
          },
        },
      }, 
```
thanks in advance for your availability and support,
greetings,
Ruggero Nardoni

**Comment by netil** [comment]
Hi @RuggeroN, I'm guessing the error happens handling subchart svg node's style.
I couldn't reproduce the error, but I'll be trying adding some prevention code.

**Comment by RuggeroN** [comment]
Hi Netil,
thank you for support and disponibility; today i've installed and checked v3.3.2, but i found the same issue;
i've tried some other version and found the 3.3.0-next.1 (among 3.3.0-next.2, 3.3.1, 3.3.0, 3.2.2, 3.2.1, 3.2.0) and this one hasn't issue with subchart. Maybe this info is usefull, i hope so.
Thanks in advance for your availability and support,
greetings,
Ruggero Nardoni
