### ISSUE TITLE
Geo chart

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#254]
Hi @netil ,
Is there any geoChart available? Like this
![image](https://user-images.githubusercontent.com/33453608/35373408-40afefd4-01c4-11e8-8b76-36c891b12305.png)

**Comment by netil** [comment]
@Rohit-Parte, unfortunately there's no geo chart support.

**Comment by Rohit-Parte** [comment]
Hi @netil ,
Okay,
Thanks
