### ISSUE TITLE
How can i updata axis.y.tick.values

### ISSUE THREAD

**Issue by wu-kai** [naver/billboard.js#255]
I need to update the y-axis scale after getting the data, but there's no such function in document。

Can you help me?

**Comment by netil** [comment]
Hi @wu-kai,

In most cases, scales are updated automatically according the data bound.
Could be more specific(providing some online code snippet? - like jsfiddle, jsbin, etc.) what is your needs?

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/35374107-78cfd740-01dc-11e8-8621-a192ef4e3745.png)



Here are two charts, 
the first chart axis.y.tick.value I want to set to [0, maxdata],
the first chart axis.y.tick.value I want to set to [0, maxdata/2,maxdata]

Y-axis scale I tried for a long time can not control them well

**Comment by netil** [comment]
@wu-kai, if you know the max data on generating chart, you can use [axis.y.tick.values](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4values) option.

For example, if your max data is 500,

```js
bb.generate({
    ....
    axis: {
        y: {
           tick: {
                values: [0, 500]  // this will display 2 ticks values
                // values: [0, 250, 500]  // this will display 3 ticks
           }
        }
    }
});
```

Also checkout [axis.y.min](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4min) and [axis.y.max](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4max) options to limit the y min and max values respectively.

**Comment by wu-kai** [comment]
@netil  So what do you mean is that I need to regenerate the chart instead of updating the chart?

**Comment by netil** [comment]
nope. I mean during the time when you generate the chart.

**Comment by wu-kai** [comment]
If I get the data on a regular basis（5s）, then I will continue to re-generate the chart......

**Comment by netil** [comment]
Hmm... I don't know what is your using environment, but according your comment, I guess you likely need load data every 5 seconds and rendering it constantly.

Let's say you have first chart generated.
```js
var chart = bb.generate({
  data: {
    columns: [
      ["data1", 130, 140, 130],
      ["data2", 150, 160, 145]
    ]
  },
  axis: {
    y: {
      min: 0,
      max: 200
    }
  }
});
```
You'll load new data and wants change the y axis scale.
In that case you can use [.axis.min()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#axis%25E2%2580%25A4min) or [.axis.max()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#axis%25E2%2580%25A4max)

```js
  // update y max value to 300
  chart.axis.max({
	y: 300
  });

  // and load new data
  chart.load({
	columns:[["data3", 200, 180, 90]]
  });
```

I made a simple demo for that.
- https://jsbin.com/nonola/edit?html,js,output

**Comment by wu-kai** [comment]
https://jsbin.com/voduxivinu/1/edit?html,js,console,output

I modified your data in your demo, there will be a negative case...

**Comment by netil** [comment]
@wu-kai, adding `axis.y.padding=0` will remove the negative tick value.

```js
  axis: {
    y: {
      ...
      padding: 0
    }
  }
```

**Comment by wu-kai** [comment]
@netil   Thank you for your reply, this is very useful to me

**Comment by netil** [comment]
You're welcome, @wu-kai  :)
