### ISSUE TITLE
related to :  issue with 'subchart.show()' and 'subchart.hide() ' #2534 

### ISSUE THREAD

**Issue by RuggeroN** [naver/billboard.js#2556]
Hi Netil,
thank you for support and disponibility; i've installed and checked v3.3.2, but i found the same issue;
i've tried some other version and found the 3.3.0-next.1 (among 3.3.0-next.2, 3.3.1, 3.3.0, 3.2.2, 3.2.1, 3.2.0) and this one hasn't issue with subchart. Maybe this info is usefull, i hope so.
Thanks in advance for your availability and support,
greetings,
Ruggero Nardoni

## Steps to check or reproduce
```js
subchart: {
        enabled: subchart(),
        show: true,
        size: {
          height: 15,
        },
        axis: {
          x: {
            show: true,
            tick: {
              show: true,
              text: {
                show: false,
              },
            },
          },
        },
      }, 
```

**Comment by netil** [comment]
Following the error call stack, it seems happening from the https://github.com/naver/billboard.js/commit/aad8c4573641cb4d444c61d5b7a89b78e6b54e2e changes.

https://github.com/naver/billboard.js/blob/6f71992b401184d6b86612aca2038ed9102e6dbc/src/ChartInternal/Axis/Axis.ts#L976

I couldn't reproduce the issue with the given option, so I'll be adding some prevention code on handling `.style()`.

**Comment by netil** [comment]
I could reproduce the issue by following options.

```js
{
  data: {
    columns: [
        ["data1", 30, 500, 60]
    ]
  },
  axis: {
    x: {
      tick: {
        culling: {
          max: 3
        }
      }
    }
},
subchart: {
  show: true,
  axis: {
    x: {
      tick: {
        text: {
            show: false
          }
        }
      }
    }
  }
}
```
