### ISSUE TITLE
Sub chart data fetch

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#256]
Hi @netil ,
Can we get selected data from subchart selection?

**Comment by netil** [comment]
Actually there's no API for that purposes, but you can make a function to accomplish that.

I made an example function, which is returning the selected area data point index.
```js
// Will get the index value of the subchart selection
function getSubChartSelectionIndex() {
	const chartWidth = +chart.element.querySelector("svg").getAttribute("width");
	const selectedIndex = [];
	
	d3.selectAll(".bb-event-rects rect").each(function() {
		const rect = d3.select(this);
		const x = +rect.attr("x");
		const width = +rect.attr("width");
	
                // check if <rect> elements within visible area
		if (x >= 0 && x+width <= chartWidth) {
			selectedIndex.push(+rect.attr("class").replace(/.*(\d+)/, "$1"));
		}
	});
	
	return selectedIndex;
}
```
![subchart](https://user-images.githubusercontent.com/2178435/35423215-1487be74-0290-11e8-91bc-1dd1ae74e234.gif)

With this function, you can get selected area index value, which can be used to get the data from that.
Check out the working example from below fiddle.
- https://jsbin.com/zejasiy/edit?html,js,output

**Comment by Rohit-Parte** [comment]
Hi @netil ,

That has been worked. 

Thank you very much.

Your support appriciated.
