### ISSUE TITLE
Control bubble select/focus/sensitivity based on the radius

### ISSUE THREAD

**Issue by eamodio** [naver/billboard.js#2568]
Currently there doesn't seem to be a way to control the size of the select, focus, and sensitivity options for the bubble chart. There are defaults, that are based on multiples of the bubble's size, but those multiples don't seem to be configurable (and sensitivity isn't a multiple).

Is this available?

**Comment by eamodio** [comment]
Here is a screenshot of the visualizationI'm working on

![image](https://user-images.githubusercontent.com/641685/155368035-d64a3942-748f-400d-9a8c-243545d3dd93.png)

**Comment by netil** [comment]
Hi @eamodio, for bubble type all the configurable options are described from the API doc.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.bubble

If needs to draw a configurable radius bubble, you can try giving `z` values.
- https://naver.github.io/billboard.js/demo/#Chart.BubbleDimensionChart

**Comment by eamodio** [comment]
@netil Thanks for the awesome library! I am currently using the `z` value, but I'm looking for more control over the selection of the bubbles (sensitivity) and their selection and focus radius. Since those options don't currently seem to be available, please consider this a feature request.

Thank you!

**Comment by netil** [comment]
@eamodio, I'll be trying enhance by adding some configurable options. Thanks for the suggestion!

**Comment by netil** [comment]
@eamodio, I forgot mentioning that sensitivity and focus radius can be configured via `point` options.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.point

**Comment by eamodio** [comment]
@netil yeah, but those options seem to only accept absolute values, not a function or multiplier, so they don't work very well for different sized bubbles.
