### ISSUE TITLE
3.3.1 breaks rescaling with hidden y axis on data load

### ISSUE THREAD

**Issue by ebencollins** [naver/billboard.js#2571]
## Description
Line charts with hidden y axis do not rescale when new data is loaded with 3.3.1 or later.
Reverting a697b69 fixed the issue for me.

![](https://i.imgur.com/tCHJF09.gif)

Expected behavior (prior to 3.3.1, or with `axis.y.show = true`)
![](https://i.imgur.com/WKL3ccO.gif)

## Steps to check or reproduce

Expected behavior (3.3.0): https://stackblitz.com/edit/paqe4q
No rescale (3.3.1): https://stackblitz.com/edit/t9s8uu

Set `axis.y.show = false` with 3.3.1 or later, then load data that is on a significantly different scale (eg 10x the original values)
```js
var chart = bb.generate({
  data: {
    columns: [
      ['data1', 30, 200, 100, 400, 150, 250],
      ['data2', 130, 100, 140, 200, 150, 50],
    ],
    type: 'area-spline',
  },
  bindto: '#splineChart',
  axis: {
    y: {
      show: false, // setting this to false causes the chart to not rescale when new data is loaded
    },
  },
});

setTimeout(function () {
  chart.load({
    columns: [
      ['data1', 500, 600, 500, 4000, 750, 2000],
      ['data2', 123, 444, 555, 112, 3321, 232],
    ],
  });
}, 5000);

```

**Comment by netil** [comment]
Hi @ebencollins, thanks for the report.
It seems side effect caused by the commit (the conditional checking the visibility of the axis) you mentioned.
