### ISSUE TITLE
x axis labels are not reorganized with culling max set when using load()

### ISSUE THREAD

**Issue by heppa** [naver/billboard.js#2582]
## Description
When setting a culling max value for the x axis label to only show a maximum number of labels and then using the load API method to have more data displayed and then using load again with fewer data, the x axis labels are not reset again => eventually when using load more often to update data (eg. via a time periods slider), this leads to having no periods displayed on the x axis at all.

In the example jsFiddle, by pressing the "Get more data" button first and then the "Get back again" button demonstrates this behaviour.

## Steps to check or reproduce
(https://codepen.io/alexhepp/pen/YzEMeBL)

**Comment by netil** [comment]
Hi @heppa, confirmed and I'll check the issue. Thanks!

**Comment by heppa** [comment]
Many thanks for fixing this issue so quickly and also for the awesome library!!! Amazing support!
