### ISSUE TITLE
Impossible to create two unrelated data series without a visible y2

### ISSUE THREAD

**Issue by pablodalloglio** [naver/billboard.js#2586]
## Description
Hi,

As user of C3 during years I'm migrating to BB now and I realize the following:
I need to show two unrelated data series. The 'data1' numbers are much bigger than 'data1'.
I know that if I didn't turn on an additional Y2, the 'data2' will be "smashed", ending being just a line in the base of chart.
In C3, I just used to add a second Y2, and it didn't required Y2 to be visible in order to allow the series to be apart.
In BB, if Y2 is not visible, the series are not apart, and 'data2' end being a smashed line in the base of chart.
If you switch the "show: false" between true and false, you'll realize this behavior.
I think the correct behavior would be the same presentation of lines, despite having Y2 visible or not.

## Steps to check or reproduce
<pre>
var chart = bb.generate({
    bindto:'#multiAxes_1',
    data: {
        columns: [
            ['data1', 3000, 2000, 1000, 4000, 1500, 2500],
            ['data2', 50, 20, 10, 40, 15, 25]
        ],
        axes: {
            data1: 'y',
            data2: 'y2'
        }
    },
    axis: {
        y2: {
            show: false
        }
    }
});
</pre>

**Comment by pablodalloglio** [comment]
I know I can hide the axis via Javascript:
$('#' + this.containerId).find('.bb-axis.bb-axis-y2').hide();

But using this strategy, the chart doesn't fill all width.

**Comment by netil** [comment]
Hi @pablodalloglio. Is because during the generation process, if the axis is set to hidden, it isn't necessary to go through any relation work for that axis. If axis.y2.show=false, it doesn't generate y2 scales and its related work.

Even so, you can achieve your needs by:
```css
/* hide the y2 axis */
.bb-axis.bb-axis-y2 {
    visibility: hidden;
}
```
```js
bb.generate({
    data: {
        columns: [
            ['data1', 3000, 2000, 1000, 4000, 1500, 2500],
            ['data2', 50, 20, 10, 40, 15, 25]
        ],
        axes: {
            data1: 'y',
            data2: 'y2'
        }
    },
    padding: {
        right: 0  // remove the padding occupied by y2
    },
    axis: {
        y2: {
            show: true  // turn on y2 visibility, to make go through necessary tasks
        }
    }
});
```

I'll be considering to add some new option for this use cases, like hiding axis, but want dataset rely on the hidden axis.

**Comment by pablodalloglio** [comment]
Thank you @netil! 

I didn't realize the right padding could fix this. I didn't even tried this solution, because I thought the SVG was already created with fixed widths and taking off the visibility in CSS level would not take the padding into consideration.

Excuse by taking your time with this simple question. Thanks a lot by provinding us with a such high quality project!

Sincerily,
Pablo
