### ISSUE TITLE
[Feature Request] On axis click

### ISSUE THREAD

**Issue by pedrorfernandes** [naver/billboard.js#2587]
## Description
I have a use case for displaying a time series stacked bar chart, in which clicking a specific point on the X (time) axis should update an html video to the timestamp that was clicked (i.e. use the chart as a video scrubber)

The issue is that onclick processing is only done with associated data ([x,y] point), but for my scenario, every second does not necessarily have a data point associated (only x, no y value). It doesn't make sense to add a y value for each second of the video, as this pollutes the chart and the interpolated Y values are good enough.

## Desired output
The solution I found [was through this change](https://github.com/pedrorfernandes/billboard.js/commit/b81f0c1fe1473d7acd2f8a4f4f62c951886a1ab2), basically adding a `axis_onclick` called inside `clickHandlerForSingleX()`

Is there a better way to handle this requirement? Does it make sense to have an axis onClick?

**Comment by netil** [comment]
> which clicking a specific point on the X (time) axis

This means clicking axis area or shape(where the bar, line renders) area?
`.clickHandlerForSingleX()` is called on shape area's event, not for axis.

**Comment by pedrorfernandes** [comment]
Ok then it's working for me because I've used a stacked area chart that covers 100% of the axis

Still, it would be useful for a click handler for anywhere in the chart region with just the mapped [X,Y] coordinates of the click, without associated data
