### ISSUE TITLE
[bug] Normal zoom gets stuck on edges

### ISSUE THREAD

**Issue by ebencollins** [naver/billboard.js#2588]
## Description
Zooming/dragging past the edge of the chart makes it feel "stuck" and requires additional dragging with no movement to return to the center.
Expected behavior: No matter how far dragged to the left/right the chart is, it should immediately start moving when dragged towards center.

![](https://i.imgur.com/ENn209l.gif)
\* Note that all the left/right movement in the gif is dragging with a release on the right side before switching directions

## Steps to check or reproduce
1. Open zoom example
2. Zoom in and drag to the min/max, then continue dragging towards the edge
3.  Try to drag back towards the center
4. Observe that potentially lots of dragging is required before the chart starts to move again

**Comment by netil** [comment]
Hi @ebencollins, thanks for the report. I'll look into.
