### ISSUE TITLE
Can we set the selection of a subchart?

### ISSUE THREAD

**Issue by dionverbeke** [naver/billboard.js#260]
I would like to set the selection of the subchart to 1 one month (while still keeping 12 months om the chart).
Is that possible?

**Comment by netil** [comment]
I'm not sure what is your needs exactly, but selecting subchart area programmatically can be done using `.zoom()`.

Let's say a timeseries chart showing data of each months. If you want to select subchart area just call:
```js
chart.zoom([new Date("2018-02-01 00:00"), new Date("2018-03-01 00:00")]);
```
![subchart01](https://user-images.githubusercontent.com/2178435/35601703-c4e52a0a-0677-11e8-9b2d-ffc39ea1699c.gif)

The full example code is:
```js
const chart = bb.generate({
	data: {
		x: "x",
		columns: [
			["x", "2018-01-01", "2018-02-01", "2018-03-01", "2018-04-01", "2018-05-01"],
			["data1", 30, 200, 100, 400, 150]
		]
	},
	axis: {
		x: {
			type: "timeseries"
	    	}
	},
	subchart: {
		show: true
	}
});

// this will select 2018/02 ~ 2018/03
chart.zoom([new Date("2018-02-01 00:00"), new Date("2018-03-01 00:00")]);
```

**Comment by dionverbeke** [comment]
Hi, Thanks but it does not work. Here part of my code:

  // generate the chart
                var chart = bb.generate({
                    bindto: "#myChart",
                    
                    regions: [
                        {
                            axis: "y",
                            start: 0,
                            end: 50000,
                            class: "fill_green"
                        }
                       
                    ],
                    data: {
                        x: "x",
                        type: "spline",
                        url: "php/solar.php",

                    },
                 
                    axis: {
                        x: {
                            type: "timeseries",
                          
                            tick: {
                                format: "%Y%m"
                            }
                        }
                    },
                    subchart: {
                        show: true
                    },
                    zoom: {
                        enabled: true
                    }
            });


          
            // this will select 2018/02 ~ 2018/03
            chart.zoom([new Date("01/01/2018"), new Date("01/02/2018")]);

**Comment by netil** [comment]
@dionverbeke, could you provide the sample of the returning of the `php/solar.php`?

**Comment by dionverbeke** [comment]
Thanks finally got it to work with columns data

 var chart = bb.generate({
                    bindto: "#myChart",
                    
                    regions: [
                        {
                            axis: "y",
                            start: 0,
                            end: 50000,
                            class: "fill_green"
                        }
                       
                    ],

                    data: {
                        x: "x",
                        columns: [
                            ["x", "2017-10-28", "2017-10-29", "2017-10-30", "2017-11-01", "2017-11-02", "2017-11-03", "2017-11-04", "2017-11-05", "2017-11-06", "2017-11-07", "2017-11-08", "2017-11-09", "2017-11-10", "2017-11-11", "2017-11-12", "2017-11-13", "2017-11-14", "2017-11-15", "2017-11-16", "2017-11-17", "2017-11-18", "2017-11-19", "2017-11-20", "2017-11-21", "2017-11-22", "2017-11-23", "2017-11-24", "2017-11-25", "2017-11-26", "2017-11-27", "2017-11-28", "2017-11-29", "2017-11-30", "2017-12-01", "2017-12-02", "2017-12-03", "2017-12-04", "2017-12-05", "2017-12-06", "2017-12-07", "2017-12-08", "2017-12-09", "2017-12-10", "2017-12-11", "2017-12-12", "2017-12-13", "2017-12-14", "2017-12-15", "2017-12-16", "2017-12-17", "2017-12-18", "2017-12-19", "2017-12-20", "2017-12-21", "2017-12-22", "2017-12-23", "2017-12-24", "2017-12-25", "2017-12-26", "2017-12-27", "2017-12-28", "2017-12-29", "2017-12-30", "2017-12-31", "2018-01-01", "2018-01-02", "2018-01-03", "2018-01-04", "2018-01-05", "2018-01-06", "2018-01-07", "2018-01-08", "2018-01-09", "2018-01-10", "2018-01-11", "2018-01-12", "2018-01-13", "2018-01-14", "2018-01-15", "2018-01-16", "2018-01-17", "2018-01-18", "2018-01-19", "2018-01-20", "2018-01-21", "2018-01-22", "2018-01-23", "2018-01-24", "2018-01-25", "2018-01-26", "2018-01-27", "2018-01-28", "2018-01-29", "2018-01-30", "2018-01-31", "2018-02-01", "2018-02-02", "2018-02-03", "2018-02-04", "2018-02-05"] ,
                            ["d", 6987, 26236, 1701, 27759, 16584, 11492, 20513, 20861, 26418, 27804, 1764, 8785, 4239, 3114, 9162, 20251, 11958, 3854, 3836, 21158, 5844, 11931, 1101, 2508, 16815, 5590, 11289, 10958, 19343, 1302, 20065, 3097, 4080, 2854, 2537, 605, 6147, 683, 2049, 1605, 7824, 4260, 188, 19, 2652, 859, 4786, 3648, 8146, 16777, 4808, 6342, 1293, 744, 1142, 987, 1106, 1264, 10304, 9370, 16180, 1455, 2890, 3643, 10361, 7130, 2543, 1583, 5077, 2326, 4020, 1928, 4062, 2688, 4651, 1359, 3287, 18818, 1947, 8777, 4792, 7397, 20835, 1531, 12756, 6220, 12731, 3253, 3780, 9129, 9366, 7482, 2126, 25901, 1174, 7611, 6029, 3501, 11491, 26278],
                        ],
                        type: "spline"
                    },
                    subchart: {
                        show: true
                    },
                    axis: {
                        x: {
                            type: "timeseries",
                            tick: {
                                format: "%Y-%m-%d"
                            }
                        }
                    }
                  });



            // this will select 2018/02 ~ 2018/03
                chart.zoom([new Date("2018-01-15 00:00"), new Date("2018-02-01 00:00")]);
            //chart.zoom([new Date("2018-01-01"), new Date("2018-01-02")]);
