### ISSUE TITLE
Loop function in generateWait (generator.ts) never ends

### ISSUE THREAD

**Issue by tomaszkunicki** [naver/billboard.js#2606]
## Description
When transition is processed (loop) the local variable (done) is not incremented in result `loop` function never ends.

## Steps to check or reproduce
Check in the debugger. The line with callback is not executed.

**Comment by netil** [comment]
Hi @tomaszkunicki, could you provide precise reproducible example?

In a simple legend toggle transition, it works.
![Kapture 2022-03-24 at 11 05 41](https://user-images.githubusercontent.com/2178435/159827626-621083d9-80b6-4833-b697-52743d11d6b3.gif)

**Comment by tomaszkunicki** [comment]
I think this is the case when tab is not visible. I think the assumption was the transition should be emptied but if is called when tab is not visible it stucks forever. It seems the function is being called despite tab is not visible.
So it works in regular condition but when we lock desktop (tabs are hidden then) and code calls periodically to refresh chart it falls apart.

**Comment by tomaszkunicki** [comment]
I'm still investigating the issue. All I see that after a while I can get 100% utilization and 5 million of d3 timer tasks.

It seems that this fix works for me.

https://github.com/adremsoft/billboard.js/commit/21d98b29da82e0ecd45529cb27394050a167545b

**Comment by netil** [comment]
> I think this is the case when the tab is not visible. I think the assumption was the transition should be emptied.

Tested triggering some API to simulate, but even tab is hidden the callback called.
To prevent any situation, where the loop never ends, adding bulletproof code will prevent or mitigate.
