### ISSUE TITLE
Hide data for type scatter does not work

### ISSUE THREAD

**Issue by leobr29** [naver/billboard.js#2609]
Hi everyone and thanks for this great library.

## Description
It seems that we cannot hide scatter data. The legend state seems to be hidden and tooltips do not open but the point are still drawn.

## Steps to check or reproduce
To reproduce it, I use next example by adding `hide: true`.
https://naver.github.io/billboard.js/demo/#LineChartOptions.LinePoint

exact code : 
```javascript
var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 50, 20, 10, 40, 15, 25],
	["data3", 170, 250, 210, 190, 175, 225],
	["data4", 283, 170, 275, 143, 220, 255]
    ],
    hide: true,
    type: "line", // for ESM specify as: line()
    types: {
      data2: "scatter", // for ESM specify as: scatter()
    }
  },
  line: {
    point: [
      "data1",
      "data3"
    ]
  },
  bindto: "#linePoint"
});
```

King regards,
Leo.

**Comment by netil** [comment]
Hi @leobr29, confirmed the issue. Thanks for the report!
I'll dig into.
