### ISSUE TITLE
Billboard fails to load as an ES6 module

### ISSUE THREAD

**Issue by qsiebers** [naver/billboard.js#2616]
## Description
I'm trying to use billboard as a dependency in a dynamically loaded module, which tries to load billboard with:

```js
import './billboard.js';
```

But this fails with the error `TypeError: Cannot read properties of undefined (reading 'd3')`. Debugging tells me that the issue is due to `this` being undefined in a module. The `this` usage at billboard.js 3.3.3 line 16 seems to be meant to be the window object. 

As the module doing the import is dynamically loaded, I cannot add the billboard script tag to the html. 

I've also tried the `billboard.pkgd.js` script, resulting in `TypeError: Cannot set properties of undefined (setting 'bb')`. Debugging shows a similar setup as in the `billboard.js` script, trying to use `this` as the `window` object.

Is there a way to use billboard as an import in this way? Or can you modify the script to use the `window` object?

## Steps to check or reproduce
```html
<script type="module" src="some-module.js"></script>
```

```js
// some-module.js
import './d3.min.js';
import './billboard.js'; // fails

// do something with billboard
```

**Comment by netil** [comment]
Hi @qsiebers, from the billboard.js npm package distribution, it provides different modules types to be consumed: UMD or ESM. In general circumstances, based on your dev environment, it will pick up the right module (module resolution) types.
- https://github.com/naver/billboard.js/blob/master/package.json#L10

But if you're loading it directly(not by package resolution) as ESM, try using the distribution from `dist-esm` folder.
- https://unpkg.com/browse/billboard.js@3.3.3/

The `dist` folder contains UMD type and `dist-esm` contains native ESM type.

**Comment by qsiebers** [comment]
> But if you're loading it directly(not by package resolution) as ESM, try using the distribution from dist-esm folder.

Ah, I saw that there were different dists, but I've seem to have missed the dist-esm folder. 

Unfortunately this version also does not work as-is in the browser. The imports at line [10-21](https://unpkg.com/browse/billboard.js@3.3.3/dist-esm/billboard.js#L10) are not valid in the browser: 

```
Uncaught TypeError: Failed to resolve module specifier "d3-time-format". Relative references must start with either "/", "./", or "../". 
```

For the browser they have to be relative, and have to actually resolve to a file so an extension is also required. You can see this error in this pen:

https://codepen.io/qsiebers/pen/oNpeXvB?editors=1111

> ... based on your dev environment ...

This is where my difficulty lies. I'm trying to use billboard as an import directly from the dist into the browser via webjars. There is no npm/bower/yarn/... nor webpack to resolve and bundle things for me, as it would require my entire framework front-end to be overhauled. Eventually that might happen, but not today.

**Comment by netil** [comment]
The ESM distribution's dependencies imports are pointed as "module-name".
When you check the billboard.js' ESM dist file, all the necessary dependencies imports are defined at the top as:

```js
import { timeParse, utcParse, timeFormat, utcFormat } from 'd3-time-format';
import { pointer, select, namespaces, selectAll } from 'd3-selection';
...
```

So, to execute it needs those imports first. As you pointed, to be imported directly to the browser (w/o transpilation), the "module-name" should be relative or some origin where browser could identify.
If you aren't aware on browser compatibility, you can use [import maps](https://caniuse.com/import-maps) to fix that.

```html
<!-- specify importmaps to mapping dependencies modules and its location --->
<script type="importmap"> 
    {
      "imports": {
        "d3-time-format": "https://cdn.skypack.dev/d3-time-format",
        "d3-selection": "https://cdn.skypack.dev/d3-selection",
        "d3-brush": "https://cdn.skypack.dev/d3-brush",
        "d3-dsv": "https://cdn.skypack.dev/d3-dsv",
        "d3-drag": "https://cdn.skypack.dev/d3-drag",
        "d3-scale": "https://cdn.skypack.dev/d3-scale",
        "d3-transition": "https://cdn.skypack.dev/d3-transition",
        "d3-axis": "https://cdn.skypack.dev/d3-axis",
        "d3-ease": "https://cdn.skypack.dev/d3-ease",
        "d3-interpolate": "https://cdn.skypack.dev/d3-interpolate",
        "d3-shape": "https://cdn.skypack.dev/d3-shape",
        "d3-zoom": "https://cdn.skypack.dev/d3-zoom"
      }
    }
</script>
<script type="module">
import bb, {area, line} from "https://unpkg.com/billboard.js/dist-esm/billboard.js";

bb.generate( ... );
</script>

````

And here's working demo: 
- https://codepen.io/netil/pen/NWXvJrW
