### ISSUE TITLE
3.4.0 version does not work in IE.

### ISSUE THREAD

**Issue by jiniC** [naver/billboard.js#2637]
Hello! As the [supported browser](https://github.com/naver/billboard.js#supported-browsers) says ie 9+, I report an issue.

I can't know the exact cause by checking the edge browser ie mode view in the window 11 environment,
but the billboard doesn't seem to work in ie.

All charts on the [demo site](https://naver.github.io/billboard.js/demo/ ) are not exposed, and the error appears even in the environment I'm working on. There are few ie users, but I think there will be users or developers with the same error as me before ie support ends on June 25, 22.

If billboard.js no longer supports the ie environment, it seems that the written description needs to be updated.
Please confirm.

**Comment by netil** [comment]
Hi @jiniC, billboard.js has supported legacy browsers for a long period, but as the whole ecosystem and even MS announced the EOL of IE as you mentioned.
Basically, our direction is to provide as broad compatibility as we can, but it isn't an easy task.

We'll provide a fix for this for now, but consider that in a near future dropping the support for legacy browser is inevitable.

**Comment by jiniC** [comment]
Thank you for your confirmation!
