### ISSUE TITLE
Can't find variable bb

### ISSUE THREAD

**Issue by musicianZem** [naver/billboard.js#2656]
## Description
billboard.js v1.12.11 버전을 로컬로 사용중입니다.
billboard.js v.1.12.11 with download file.

간혹, 스크립트에서 오류가 발생해, 페이지 전체가 로딩되기 전 멈추는 현상이 있다고 전달받았습니다.
I got a report recently that sometimes main page is stop before initialization.

원인을 분석하기 위해 초기화하는 코드에 `try-catch` 를 이용해 오류메세지를 웹훅으로 확인해 본 결과, 아래 두 오류메세지가 대부분이었습니다.
To analyze this issue, I used `try-catch` in the initialization code which send error message to slack channel(web hook). And most of the results are shown below.

```
ReferenceError: bb is not defined
ReferenceError: Can't find variable: bb
```

우선 오류가 발생할 수 있다는 것을 감안하여 프로젝트를 유지하고 있습니다.
I'm keeping this project even if billboard cause error.

도움이 되지 않을까 하여 제보드리는 바 입니다.
I hope my case can be helpful to your project.

## Environment
* Node.js + express + ejs
* Android : WebView
* iOS : Webkitwebview

## Error Message
우선, 금일 발견 된 error의 stack을 첨부드립니다.
First of all, I attach error message occured today.
```
initParams@https://xxx.xxx.com/.../billboard.js:1885:483
init@https://xxx.xxx.com/.../billboard.js:1842:38
Chart@https://xxx.xxx.com/.../billboard.js:2586:109
generate@https://xxx.xxx.com/.../billboard.js:14976:51
```

오류메세지를 확인하게 된 수도코드는 아래와 같습니다.
Under code is how error message generated.

```javascript
try {
  // something init page
  bb.generate({ ... });
} catch(e) {
  send_slack_webhook(e.stack);
}
```

## Additional
2~3일 정도 지켜본 후, 어떤 플랫폼(Android/iOS)에서 주로 오류가 발생하는지 현상 파악 예정입니다.
I'll watching it over the next few days to know which platform cause this issue.

특정 휴대폰 기종에서 발생하는 경우 추가 제보 드리도록 하겠습니다.
I'll report more if this issue occur only single platform.

**Comment by netil** [comment]
Hi @musicianZem, the reference error usually happens when the call of global namespace `bb` happens before the namespace has been loaded completely. And as of `v1.x` is an old version which we recommend to upgrade to the latest version which might fix any possible bug from the old version.

Also from the info provided, can't reproduce or figure out the issue. Please provide a reproducible example for checking.
