### ISSUE TITLE
Stanford charts popup labels missing

### ISSUE THREAD

**Issue by leobr29** [naver/billboard.js#2657]
Hi everyone,

## Description
I'm working with stanford chart plugin to show data in function of pressure and time.

But it seems that when x axis is declared as a **timeserie** labels are not set in the popup.

![PRstanford_5906763_PF_30-28](https://user-images.githubusercontent.com/5701109/165273299-b221bf9a-7c8d-461e-a359-83eb29ada6af.png)

Please can you tell me if it's a bug or if I just missing something ?

## Steps to check or reproduce
Here is an example where I reproduce the problem : https://stackblitz.com/edit/stanford-popup-example?file=index.ts

Now if you remove attributs **type** and **format** from **x axis** it seems to work :
```json
  axis: {
    x: {
      label: 'Datetime',
      tick: {
        fit: true,
        count: 30,
        culling: {
          max: 6,
        },
      },
    },
```

King regards,
Leo.

**Comment by netil** [comment]
Hi @leobr29, thanks for the report. Will check the issue.
