### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'axis.subX.tickOffset')

### ISSUE THREAD

**Issue by niksite** [naver/billboard.js#2669]
## Description

When I reset out a zoom and then try to set some regions, I am getting `TypeError: undefined is not an object (evaluating 'axis.subX.tickOffset')` error. 

## Steps to check or reproduce

1. render a time series chart with x ticks enabled (by default)
2. drag zoom in
3. click zoom reset button
4. render a region (`chart.regions([{ start, end }])`) <- got `TypeError: undefined is not an object (evaluating 'axis.subX.tickOffset')`

https://stackblitz.com/edit/zyjb8b-as58p3?file=index.js

ticks disable fixes issue

**Comment by netil** [comment]
Hi @niksite, confirmed the issue. Thanks for the report.
