### ISSUE TITLE
[question] How to display only integers on Y axis instead of real numbers?

### ISSUE THREAD

**Issue by Blaumaus** [naver/billboard.js#2690]
On the charts below I want only integers to be displayed on the Y axis.
Could anyone answer me which parameter can I use to enforce such behaviour?

![Screenshot from 2022-05-18 00-16-45](https://user-images.githubusercontent.com/35810911/168911737-fdbe2f26-55fd-44da-80df-7292cf3987aa.png)
![Screenshot from 2022-05-18 00-16-36](https://user-images.githubusercontent.com/35810911/168911742-7494eb0b-93e5-474c-9049-9603958ca1b8.png)

**Comment by netil** [comment]
Hi @Blaumaus, there're several ways to do that. Checkout one of the below options.

- [axis.y.tick.culling](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4culling)
- [y.tick.values](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4values)
