### ISSUE TITLE
data label placement with inverted y/y2 axis

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#2700]
### Current data label placement with not inverted y/y2 axis
- data labels for `values >== 0` are placed **above** the data point (**above** the zero line)
- data labels for `values < 0` are placed **below** the data point (**below** the zero line)
- Exception Candlestick Chart
  - data labels for **Low** are placed **at the bottom** of the candle
  - data labels for **High** are placed **at the top** of the candle
- Line Chart
![03 current_not_inverted_y_axis_label_placement](https://user-images.githubusercontent.com/42860868/170231922-5747c947-5aee-4ab6-be44-b7b7004e2c31.png)
- Bar Chart
![06 current_not_inverted_y_axis_label_placement_bar](https://user-images.githubusercontent.com/42860868/170235947-d5c1d374-a804-494d-aac8-ef5cd3c507b7.png)
- Candlestick Chart
![09 current_not_inverted_y_axis_label_placement_candle](https://user-images.githubusercontent.com/42860868/170242628-ad01ba6a-ea46-4532-aebe-f23714a54b44.png)

### Current data label placement with inverted y/y2 axis
- data labels for `values >== 0` are placed **above** the data point (**below** the zero line)
- data labels for `values < 0` are placed **below** the data point (**above** the zero line)
- Exception Candlestick Chart
  - data labels for **Low** are placed **at the bottom** of the candle
  - data labels for **High** are placed **at the top** of the candle
- Line Chart
![01 current_inverted_y_axis_label_placement](https://user-images.githubusercontent.com/42860868/170231941-f5e63f1f-3464-49a7-9296-8fa45100ab00.png)
- Bar Chart
![04 current_inverted_y_axis_label_placement_bar](https://user-images.githubusercontent.com/42860868/170236288-5e44fdf7-54fe-43f7-a551-c6f9b239b84a.png)
- Candlestick Chart
![07 current_inverted_y_axis_label_placement_candle](https://user-images.githubusercontent.com/42860868/170242660-390783a4-308c-41e1-b91c-418c6659cca8.png)

### Expected data label placement with inverted y/y2 axis
- data labels for `values >== 0` are placed **below** the data point (**below** the zero line)
- data labels for `values < 0` are placed **above** the data point (**above** the zero line)
- Exception Candlestick Chart
  - data labels for **Low** are placed **at the top** of the candle
  - data labels for **High** are placed **at the bottom** of the candle
- Line Chart
![02 fixed_inverted_y_axis_label_placement](https://user-images.githubusercontent.com/42860868/170234453-ec32c6a5-91c1-4eca-acb6-78a7a4ceb2f7.png)
- Bar Chart
![05 fixed_inverted_y_axis_label_placement_bar](https://user-images.githubusercontent.com/42860868/170236311-cc4524c7-c788-4188-9b43-35c8cb12060d.png)
- Candlestick Chart
![08 fixed_inverted_y_axis_label_placement_candle](https://user-images.githubusercontent.com/42860868/170242707-90c72fd3-a4b5-48c6-b521-3289cd395998.png)

In the end you can say that **all data labels** that are **above** the zero line should be placed **above** the data point and **all data labels** that are **below** the zero line should be placed **below** the data point. 
Exception is the Candlestick Chart where the data labels are placed depending on High/Low.

## Steps to check or reproduce
https://jsfiddle.net/michkami/oe9cLwhn/

**Comment by netil** [comment]
Seems having inconsistency on inverted axis.
