### ISSUE TITLE
chart object does not have a tooltip property.

### ISSUE THREAD

**Issue by nigayo** [naver/billboard.js#271]
## Description
I want to remove tooltip ui, but i found chart.tooltip is not defined.
Instead, it could be implemented as follows.
```javascript
		tooltip : {
			show:false
		},
```

## Steps to check or reproduce
var chart = bb.generate({...});
chart.tooltip.hide() //not working

**Comment by netil** [comment]
Hi @nigayo, there's already an option to handle that.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip

```js
bb.generate({
    ...
    tooltip: {
        show: false
    }
});
```
Check out the example:
- https://naver.github.io/billboard.js/demo/#Tooltip.HideTooltip

**Comment by nigayo** [comment]
Thanks !
