### ISSUE TITLE
Display negative float values

### ISSUE THREAD

**Issue by leobr29** [naver/billboard.js#2714]
Hi everyone,

## Description
I have trouble to share negative float values on charts. Do I have to configure something or not it is not managed ? On the screen below I don't see decimal value for all values under 0 (**popup** and **axis**).

![linear_84471594_68-28](https://user-images.githubusercontent.com/5701109/171816202-7383aad0-32fb-45ba-8b0a-64d0dfab1db4.png)

## Steps to check or reproduce
I reproduced it in next example by replacing the code by following example.
https://naver.github.io/billboard.js/demo/#Chart.ScatterPlot

exact code : 
```javascript
var chart = bb.generate({
  data: {
    xs: {
      setosa: "setosa_x",
      versicolor: "versicolor_x"
    },
    columns: [
	["setosa_x", -3.5, -3, -3.252, -3.145, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3, 3, 4, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3, 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3, 3.8, 3.2, 3.7, 3.3],
	["versicolor_x", 3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2, 3, 2.2, 2.9, 2.9, 3.1, 3, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3, 2.8, 3, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3, 3.4, 3.1, 2.3, 3, 2.5, 2.6, 3, 2.6, 2.3, 2.7, 3, 2.9, 2.9, 2.5, 2.8],
	["setosa", 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2],
	["versicolor", 1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1, 1.3, 1.4, 1, 1.5, 1, 1.4, 1.3, 1.4, 1.5, 1, 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1, 1.1, 1, 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1, 1.3, 1.2, 1.3, 1.3, 1.1, 1.3]
    ],
    type: "scatter", // for ESM specify as: scatter()
  },
  axis: {
    x: {
      label: "Sepal.Width",
      tick: {
        fit: false
      }
    },
    y: {
      label: "Petal.Width"
    }
  },
  bindto: "#scatterPlot"
});
```

King regards,
Leo.

**Comment by netil** [comment]
Hi @leobr29, I'm not sure if you want to make tooltip's value to be displayed as is try with the below option.

```js
  tooltip: {
    format: {
      title: x => x
    }
  },
```

<img width="359" alt="image" src="https://user-images.githubusercontent.com/2178435/171871630-191ed191-b29c-4fee-bb05-eaaf2905e6c0.png">

**Comment by leobr29** [comment]
Hi @netil,
Ok thanks it solved my problem for negative values in tooltip
I also added this to have one digit on axis for negative values :

```json
tick: { 
  format: d3.format('.1f') 
};
```
Many thanks for your help,
Leo.
