### ISSUE TITLE
Clipped data labels (line charts)

### ISSUE THREAD

**Issue by allthesignals** [naver/billboard.js#2734]
## Description
Hi there, I'm struggling a bit with data labels being clipped:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/5004319/173445309-cbe8ca14-96a5-4003-ac11-2b5e0e6520b3.png">

I've seen this on a few iterations of this chart. Is there any way to just ask it to pad the top so my labels aren't clipped?

```javascript
bb.generate({
      data: {
        columns: [
          this.args.data,
        ],
        type: 'line',
        labels: {
          format: {
            'Population': (x, id, i, texts) => x.toLocaleString(),
          },
        },
      },
      axis: {
        x: {
          show: false,
          padding: 0.1,
          type: 'category',
          categories: CATEGORIES,
        },
        y: {
          show: false,
          axes: [{domain: [0, 6000]}],
        },
      },
      legend: {
        show: false,
      },
      bindto: "#line"
    });
```

Some ideas:

1. Maybe set the domain manually? I can't seem to get that to work:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/5004319/173445267-6457ab33-8951-462f-b2e1-a13a9147b6a1.png">

2. Setting the padding seems to worsen the problem.

Thank you!

**Comment by allthesignals** [comment]
```javascript
        y: {
          show: false,
          padding: 20,
        },
```

Setting the padding on the y axis fixes my problem. Thanks for 🦆 !

**Comment by netil** [comment]
@allthesignals, checkout [clipPath](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.clipPath) option also.
