### ISSUE TITLE
Question - Select range on main chart

### ISSUE THREAD

**Issue by tamascsaba** [naver/billboard.js#277]
I want to select a range with mouse in chart (timeseries barchart), and I want to get back the first and last data point my selection, like you can select a range in subchart, but I can't found any possibility to select range with mouse in the main chart.

I'm not sure I'm completely understandable, so I was looking for an example
https://www.highcharts.com/demo/arearange (without zoom)

**Comment by netil** [comment]
Hi @tamascsaba, unfortunately there's no functionality implemented right now.
I think is one of the feature to be considered to provide an additional usability.

We will take this in consideration. :)

**Comment by rshingleton** [comment]
I'm sure there are many people who could use this functionality, I know I can. I've seen requested help for this on C3 posts as well.

Here is one example of a D3 plugin that might be useful in implementing this feature:
[D3-Area-Range-Line-Plugin](https://github.com/JunctionTV/D3-Area-Range-Line-Plugin)

There are also some workarounds to simulate this using 2 area lines:

[C3js Area Range chart](https://stackoverflow.com/questions/30042060/c3js-area-range-chart)
[C3js Area Range chart - fiddle example](http://jsfiddle.net/ot19Lyt8/23/)

**Comment by netil** [comment]
@rshingleton, thanks for the suggestion.

I think you and @tamascsaba's requests are different.
- @tamascsaba 
   A functionality to select a range with user's interaction(ex. mouse) and get selected range's data
- @rshingleton 
   Provide an `Area Range Chart`, having a range rendered 

Of course, both are definitely worth to be considered!

**Comment by rshingleton** [comment]
@netil 

Perhaps. The link @tamascsaba suggested the area range with outside lines/points, the one I was referring to has a median line with surrounding areas. I use this in a current highcharts implementation to show standard deviations +/- on a timeline with host/application metrics.

The second example given in highcharts is [Area range and line](https://www.highcharts.com/demo/arearange-line), which is more like the demo that I suggested. 

I would be happy to open another feature request for this specifically if needed.

**Comment by tamascsaba** [comment]
hi @netil, @rshingleton 

My suggestion workaround (with typescript) :)

```
    const region: {axis: string; start?: Date; end?: Date} = {axis: 'x'};
    const chartMain = chart.internal.main;
    let startPosition: Date;

    const mousemove = (...args) => {
      const [xCoord] = mouse(args[2][0]);
      const end: Date = chart.internal.x.invert(xCoord);

      if (end < startPosition) {
        region.start = end;
        region.end = startPosition;
      } else {
        region.end = end;
      }

      chart.internal.redrawRegion();
    };

    const mousedown = (...args) => {
      const [xCoord] = mouse(args[2][0]);
      const start = chart.internal.x.invert(xCoord);
      startPosition = start;
      region.start = start;
      region.end = start;

      chart.regions([region]);
      chartMain
        .on('mousemove', mousemove)
        .classed('hide-tooltip-line', true);
    };

    const mouseup = () => {
      console.log('yep yep yep')
      // Call some business logic
      ......

      // Force hide the region, when i only call regions.remove() sometimes it doesn't work
      region.start = new Date(0);
      region.end = new Date(0);
      chart.regions.remove();
      
      chartMain.on('mousemove', null);
    };

    const mouseleave = () => {
      chart.regions.remove();
      chartMain
        .on('mousemove', null)
        .classed('hide-tooltip-line', false);
    };

    chartMain
      .on('mousedown', mousedown)
      .on('mouseup', mouseup)
      .on('mouseleave', mouseleave);
```

**Comment by netil** [comment]
@tamascsaba, how about integrate as an option? It'll be great send a PR.

**Comment by tamascsaba** [comment]
@netil unfortunately it is only a workaround. It could have some problems, yet. I don't handle the fast left-right region selection :(

**Comment by netil** [comment]
The dragging selection zooming feature was implemented.
Checkout the issue #513 for the details.

**Comment by tamascsaba** [comment]
https://naver.github.io/billboard.js/demo/#Data.DataSelection solve this question, not perfecly, becouse no event on mouseup/dragend, but it can be easily workaround.
