### ISSUE TITLE
Question, Bar chart total count division

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#278]
Hi @netil ,
Do we have or can create this type of graph.
In this graph whole bar is showing total and two stacks are showing out of total count.
![img_20180207_131235431](https://user-images.githubusercontent.com/33453608/35906599-2465a59c-0c11-11e8-8607-7fcda350ff8c.jpg)

**Comment by Rohit-Parte** [comment]
Divide total into sub.

**Comment by netil** [comment]
You can generate stacked bar using '[data.groups](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4groups)' option.
Check out the example:
- https://naver.github.io/billboard.js/demo/#Chart.StackedBarChart
