### ISSUE TITLE
Cannot read properties of undefined (reading 'length') atxisRenderer.getGeneratedTicks

### ISSUE THREAD

**Issue by risingphoenix** [naver/billboard.js#2786]
## Description

since version 3.5.1 I'm getting the error in title:
"Cannot read properties of undefined (reading 'length') atxisRenderer.getGeneratedTicks"

it happens when I set parameters for handle/display tick axis, then hide the axis itself

## Steps to check or reproduce

Error Example with v. 3.5.1
https://jsfiddle.net/marcosgorbati/ex7dpa61/15/
the area chart is empty and is visible only x axis - no y grids - no chart

Same Data but with v. 3.4.1
https://jsfiddle.net/marcosgorbati/n1oa5vLg/1/
correct with chart, ticks and grids

I hope it can help you
Many Thanks for all the support

**Comment by netil** [comment]
Hi @risingphoenix, thanks for the report.
Seems side effect caused by #2715
