### ISSUE TITLE
Question,

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#279]
Hi @netil ,
I want to hide bar but need to show that bar data in tooltip.Is there any way to do this?

**Comment by netil** [comment]
You can approach directly handling the visibility of the bar element.
For example, if you have a chart  generated with below options,
```js
var chart = bb.generate({
	data: {
		columns: [
			['Max', 300, 350, 300, 290, 225, 220],
			['Score', 250, 320, 280, 250, 170, 180],
			['Min', 230, 300, 240, 200, 150, 150]
		],
		type: "bar",
		colors: {
			Max: 'rgb(215, 232, 248)',
			Score: 'rgb(120, 178, 235)',
			Min: 'red'
		}
	}
});
```
then, if you need to hide `Min` data only from the chart, just change the opacity of that bar element.
```css
.bb-shapes.bb-bars-Min {
  opacity: 0;
}
```

Check out the working example:
- https://jsbin.com/pumetok/edit?html,css,js,output

**Comment by Rohit-Parte** [comment]
Hi @netil ,
Thanks, 
It has been worked.
