### ISSUE TITLE
Issue - Scatter tooltip position

### ISSUE THREAD

**Issue by ghost** [naver/billboard.js#281]
Hey,

There seems to be a problem when I try to zoom on a scatter.
The coordinates for the tooltip doesn't get updated correctly.
Causing the targeted point and the location of the tooltip to misalign.
```
{
    "data": {
        "columns": [
            ["data1", 30, -200, 100, 400, 150],
            ["data2", 50, 20, 10, 40, 15],
            ["data3", 50, 20, 10, 40, 15],
            ["data4", 30, 200, 130, 400, 30],
            ["data5", 50, 20, 10, 40, 415]
        ],
        "type": "scatter"
    },
    "zoom": {
        "enabled": true,
        "rescale": true
    }
}
```

**Comment by BrattPurrie** [comment]
[https://github.com/naver/billboard.js/issues/209](https://github.com/naver/billboard.js/issues/177)
Seems related
