### ISSUE TITLE
position of 0 values with grouped data and positive and negative values

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#2813]
## Description
I was working with grouped data in the last days and I noticed something weird.

![grafik](https://user-images.githubusercontent.com/42860868/183089772-7dbe296e-380f-4b16-919e-2320540dd21f.png)

In this chart I use `data.order: null` to keep the order of the data as I ordered it manually.

When you look at the image above, I would expect the **0** on the left side to be positioned below the **-11** to match the data order.
The **-1** on the right side is placed below **-11** (at **-12**) which is what I expect because we cumulate the values below the zero line up to the **-1** when they are grouped.
It seems that if there are positive and negative and the value is zero it doesn't cumulate the values below the zero line up to **0** but it cumulates all values (positive and negatives) and that's why the **0** is positioned at **-8** instead of the correct accumulated value (**-12**) on the left side.

Is this the right behaviour or is it a bug?

## Steps to check or reproduce
https://jsfiddle.net/michkami/7jn9wq2b/

**Comment by netil** [comment]
>  I would expect the 0 on the left side to be positioned below the -11 to match the data order.

IMO, `series 3` should stay at the top if `data.order=null` is specified.

**Comment by netil** [comment]
@michkami, after doing some approach, doubt on how `zero` should be represented?

In a scenario, where the example you provided, the `series3` value goes from `0 to -1`. Looks reasonable the coordinate of 0 staying at the bottom(near -11 at y Axis) as you said, but what if value goes from `0 to 1`?

<img width="236" alt="image" src="https://user-images.githubusercontent.com/2178435/183605474-735550b1-e39d-4cb2-bbab-1eec3bf59517.png">

In this case, implicitly put 0 as negative value. So, having this in mind, when value goes from `0 to 1`, it will be drawing from the bottom to the top.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/2178435/183606032-d178d189-a139-4904-95ca-ec3e5a6cc872.png">

What I want to explain here is, the 0 can be negative or positive. Look nicer if 0 treated as "negative" when value flows to negative, but is awkward, if flows to positive and vice versa.

When 0 is treated as "positive" value, representing `0 to 1`:

Look nicer if value flows to positive value,
<img width="244" alt="image" src="https://user-images.githubusercontent.com/2178435/183607050-5fa207ba-9738-4a69-8746-495bd04b5c6d.png">

But, looks awkward if value flows to negative value.
<img width="215" alt="image" src="https://user-images.githubusercontent.com/2178435/183607260-ca4b5cd3-3372-40bc-a883-b77949c3128c.png">


So, my idea is this can't be handle automatically. Providing some option to implicitly determine, how 0 will be treated.
- treat as `absolute 0`
  zero won't be stacked, and will correlated with y axis 0.
  - left: 0 to 1 / right: 0 to -1
  <img width="254" alt="image" src="https://user-images.githubusercontent.com/2178435/183609179-de1a2bbd-f883-42ec-aa64-6723bf35c37b.png"> <img width="250" alt="image" src="https://user-images.githubusercontent.com/2178435/183609298-4ac13596-8f82-403c-9288-169120e2d869.png">



- treat as `negative 0`
- treat as `positive 0`
