### ISSUE TITLE
[Question] Can I highlight axis text and change chart polygon color? (radar chart)

### ISSUE THREAD

**Issue by natonato** [naver/billboard.js#2817]
I'm using radar chart, and I want to highlight most highest axis's text

![스크린샷 2022-08-10 오후 7 26 10](https://user-images.githubusercontent.com/19733033/183879767-ec42eeba-7c7d-4e4b-9bcf-7bd882f93a6d.png)

In this chart, I want to show 'axis3' as blue color, bold text, etc...
Is there way to apply css style or something to highlight axis label?

![스크린샷 2022-08-10 오후 7 47 18](https://user-images.githubusercontent.com/19733033/183883184-b77e2a2a-1f98-467d-8446-a2d0f1b14fc7.png)
And when I set color to chart frame polygon, it hide smaller one cause polygon draw from smaller one to big one

![스크린샷 2022-08-10 오후 7 49 56](https://user-images.githubusercontent.com/19733033/183883682-72abf525-a0b7-4c6d-9eb5-703821fe391a.png)
This is the shape I want. Is there option to do this?

**Comment by netil** [comment]
Hi @natonato,

> In this chart, I want to show 'axis3' as blue color, bold text, etc...
> Is there way to apply css style or something to highlight axis label?

It seems want to highlight the highest value's position axis label.
In this case can use [`data.onmax`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4onmax) callback option.

```js
bb.generate({
  data: {
    x: "x",
    columns: [
      ["x", "Data A", "Data B", "Data C", "Data D", "Data E"],
      ["data", 5, 5, 7, 3, 2],
    ],
    type: "radar",
    onmax: function(data) {
       data.forEach(v => this.$.main.select(`.bb-axis-${v.index} text`)
          .style("font-weight", "bold").style("fill", "red"));
    }
  }
});
```

<img width="367" alt="image" src="https://user-images.githubusercontent.com/2178435/184084611-f3a9729b-7b88-4eef-8036-8507c2eafa88.png">

> And when I set color to chart frame polygon, it hide smaller one cause polygon draw from smaller one to big one

If you loaded correctly the dist css file, every radar's polygon shape will apply `fill-opacity` property.
If don't, try setup below css rule to apply opacity.

```css
.bb-chart-radars .bb-shapes polygon {
    fill-opacity: .2;
}
```
