### ISSUE TITLE
Console error with combination line/area chart, when any data starts with null

### ISSUE THREAD

**Issue by grantcox** [naver/billboard.js#2826]
## Description
When I have a combination area and line chart, and any of the data series start with `null` (as this series has no data until later in the chart), an error is printed to the browser console like:
```
d3.v7.min.js:2 Error: <path> attribute d: Expected number, "M 9 undefined".
```

If there is no area chart (all just lines), then the error does not occur.
If there are no data series starting with null (eg if it starts with 0, then has a bunch of null values after that), the error does not occur.

## Steps to check or reproduce
- open the dev tools console
- go to https://jsfiddle.net/gcok836n/1/

**Comment by netil** [comment]
Hi @grantcox, thanks for the report. I'll dig into.

**Comment by grantcox** [comment]
Wow, fast work!  Thank you @netil !
