### ISSUE TITLE
BUG: In 3.5.1 grid.y.show = true breaks if there is a y2 axis but no y axis

### ISSUE THREAD

**Issue by m-gallesio** [naver/billboard.js#2836]
## Description
In version 3.5.1, when a chart:
- has a y2 axis
- does NOT have a y axis
- has `grid.y.show = true`

the generation breaks after drawing the axes:

![immagine](https://user-images.githubusercontent.com/46478501/186610711-7c0a6d37-229e-4779-a982-80c5b983d7a0.png)

Conceptually this makes sense, but it **did NOT happen in version 3.4.1**.

## Steps to check or reproduce
The following chart configuration produces the bug:

```javascript
{
  "bindto": "#lineChart", 

  "data": {
    "rows": [
      [ "Bar", "Line_1", "Line_2" ],
      [ 0.5, 2, 1 ],
      [ 3, 1, 2 ],
      [ 2, 1, 3 ],
      [ 1, 2.5, 0.5 ],
      [ 2, 1, 0 ],
      [ 1.5, 2, 1 ],
      [ 0, 2, 1 ],
      [ 0.5, 1, 3 ],
      [ 1, 1, 2 ],
      [ 2, 1, 1 ],
      [ 0.5, 1, 2 ],
      [ 1, 0.5, 3 ]
    ],
    "types": {
      "Line_1": "line",
      "Line_2": "line",
    },
    "type": "bar",
    "axes": {
      "Bar": "y2",
      "Line_1": "y2",
      "Line_2": "y2"
    }
  },
  "axis": {
    "x": {
      "type": "category",
      "categories": [ "gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic" ],
      "clipPath": false
    },
    "y": {
      "show": false
    },
    "y2": {
      "show": true,
      "padding": { "bottom": 0 },
      "min": 0,
      "max": 3
    }
  },
  "grid": {
    "y": {
      "show": true // this breaks the chart
    }
  }
}
```

**Comment by m-gallesio** [comment]
This seems related to https://github.com/naver/billboard.js/issues/2786.

**Comment by netil** [comment]
Hi @m-gallesio, it seems duplicated and already fixed(with the issue you mentioned).
From the latest build from the master, it renders without issue.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/2178435/186851870-0b9a0b0e-5479-4560-8c0d-fbf0da01a161.png">

Try with the `nightly` build
- https://github.com/naver/billboard.js#nightly-version

**Comment by m-gallesio** [comment]
It looked like a different problem but it indeed is a duplicate. I apologize for the inconvenience.
I can confirm this is fixed in the nightly build.

**Comment by netil** [comment]
@m-gallesio no worries!

**Comment by netil** [comment]
Next release will out on this month.
