### ISSUE TITLE
Labels in combination charts overlapping values

### ISSUE THREAD

**Issue by heinickk** [naver/billboard.js#2837]
## Description
Is there a way to prevent the chart labels from being rendered  on top of each other when combining visualizations within a chart - ie. Line chart with bar chart?

## Steps to check or reproduce

![OverLapping_labels](https://user-images.githubusercontent.com/827374/186931763-7b99cb53-9564-4ab4-b453-99be2c57f0db.PNG)

**Comment by heinickk** [comment]
I also want to mention adjusting the position values will not help because:
- The position value is global for each element in the chart - so at some point the line label will collid with the bar lable
- I have not found a way to individually identify the collision and change a specific data labels position while leaving the others alone.

**Comment by netil** [comment]
Hi @heinickk, did you tried [TextOverlap](https://naver.github.io/billboard.js/demo/#Plugins.TextOverlap) plugin?
