### ISSUE TITLE
How to use different values for the x-axis and 'pop-over' title?

### ISSUE THREAD

**Issue by MartijnHarmenzon** [naver/billboard.js#284]
I want to create a timeseries graph with billboard.js. The data consists of multiple datetime entries.

I would like the x bar to only show the time of the entrie. But when you click on the point in the graph I want the info to show the date and time.

So the format of the x-axis will be %H:%M and the format shown in the info 'pop-up' contains %Y-%m-%d %H:%M:%S. Is this possible?

Below the code I have so far.

```js
{
  data: {
    x: "x",
    xFormat: '%Y-%m-%d %H:%M:%S',  
    columns: [
      ["x", "2018-02-08 22:00:00", "2018-02-08 23:00:00", "2018-02-09 00:00:00", "2018-02-09 01:00:00"],
      ["data1", 2, -1, -2, -3]
    ]
  },
  axis: {
    x: {
      type: "timeseries",
      tick: {
        format: "%H:%M"
      }
    }
  }
}
```

**Comment by netil** [comment]
@MartijnHarmenzon, I'm not sure if I understood correctly your question, what I understood was you need to display x Axis with `%H:%M` format and for the tooltip('pop-up' from your description) title, displaying with `%Y-%m-%d %H:%M:%S` format.

If so, set [tooltip.format.title](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option as below.
```js
tooltip: {
	format: {
		title: function(x) {
			return d3.timeFormat("%Y-%m-%d %H:%M:%S")(x);
		}
	}
}
```

![image](https://user-images.githubusercontent.com/2178435/36085569-e9a603fa-1009-11e8-9704-b5a710a546ae.png)

**Comment by MartijnHarmenzon** [comment]
@netil Thank you. This was exactly what I was looking for.
