### ISSUE TITLE
How to add labels to line chart for null values

### ISSUE THREAD

**Issue by heinickk** [naver/billboard.js#2847]
## Description
I am working on a line chart that may or may/not have null values within the data series. We are replacing our current charting software with billboard and it currently displays "N/A" for a null value and does not render the point or the lines. I have not successfully been able to find a way to achieve this. Is this possible within the billboard.js architecture?

## Steps to check or reproduce
This is the desired effect. 
![Line with NA](https://user-images.githubusercontent.com/827374/187982962-14c46801-72c8-4e8d-885f-4cb4f20e7b34.PNG)

**Comment by netil** [comment]
Hi @heinickk, unfortunately there's no direct option to achieve this.
It needs to implement this manually as appending text nodes for nullish data values.

checkout the working demo:
- https://jsfiddle.net/netil/c4khx20o/

```js
bb.generate({
  ...
  onrendered: function() {    
    const {x, y} = this.internal.scale;
    const id = "data1";
    const label =  "N/A";

    // filter nullish value
    const pos = this.data.values(id)
      .map((v, i) => v === null ? i : false)
      .filter(Boolean);

    const text = this.$.text.texts.node();
    const parent = text.parentNode;
    const yDomain = y.domain();
    const yCenter = yDomain.reduce((p, c) => c - p) / 2 + yDomain[0];
      
    pos.forEach(v => {
      const t = text.cloneNode(true);

      t.setAttribute("x", x(v));
      t.setAttribute("y", y(yCenter));
      t.textContent = label;
      
      parent.appendChild(t);        
    })
  }
});
```
