### ISSUE TITLE
Import only really required modules from D3 

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#285]
## Description

I was analyzing my webpack build, and found some non used modules imports.

I can't find any usage of d3-geo in charts, but it adds 90KB of bloat.

![image](https://user-images.githubusercontent.com/910967/36074083-4a64b4ae-0f3b-11e8-9498-8b0bd97984b3.png)

And I'm not sure about the rest of them, so, I think [d3 imports](https://github.com/naver/billboard.js/blob/5cc34423440d5aef99e71a019e1029055145d1ee/src/core.js#L5) should be reviewed, or better **removed completely** from root, as why do we need to [reexport **whole** d3](https://github.com/naver/billboard.js/blob/5cc34423440d5aef99e71a019e1029055145d1ee/src/core.js#L122) library at all?

All of these are not used, but are built in the final bundle

d3-geo
d3-voronoi
d3-force
d3-hierarchy
d3-request
d3-dsv
d3-chord
d3-polygon
d3-quadtree
  

## Steps to check or reproduce

Just add a [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) plugin to your webpack build, and see the build report for details.

**Comment by netil** [comment]
@creage thanks for the suggestion.
It should be three-shaking as you said.

It was importing all and re-exporting for the packed bulid dist file, which to exposing `d3` on global usage.

**Comment by creage** [comment]
@netil well, I'm sure you should not reexport such things. If I would need some part of d3, I'd set it as my project dependency, and import it explicitly, and not rely on something a third-party library exposes.

For now I'm "shaking the tree" manually, using webpack plugin

```javascript
// ignore non-used d3 modules for billboard.js
new webpack.NormalModuleReplacementPlugin(/d3-*/, function (resource) {

    if (resource.userRequest) {

	const map = {
	    find: /client\\node_modules\\(d3-geo|d3-voronoi|d3-force|d3-hierarchy|d3-request|d3-dsv|d3-chord|d3-polygon|d3-quadtree)+\\index/,
	    replace: 'client\\webpack\\empty-module-placeholder'
	};

	resource.request = resource.request.replace(map.find, map.replace);
	resource.userRequest = resource.userRequest.replace(map.find, map.replace);
	resource.resource = resource.resource.replace(map.find, map.replace);
    }
})
```

**Comment by creage** [comment]
Well, that looks better now, but, still, why do we have/need [this config](https://github.com/naver/billboard.js/blob/67c8305088f3379b30da24e5830cf2e7d9fba842/webpack.config.js#L18) still?

I see too many redundant d3 modules imported with no usage, which should be caused by the setting above, which forces webpack to inject the code below
```javascript
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("d3"));
	else if(typeof define === 'function' && define.amd)
		define(["d3"], factory);
	else {
		var a = typeof exports === 'object' ? factory(require("d3")) : factory(root["d3"]);
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(typeof self !== 'undefined' ? self : this, function(__WEBPACK_EXTERNAL_MODULE_1__) {
```

If we import all of deps explicitly, there is no need for such hook anymore, I believe.

**Comment by creage** [comment]
OK, I'm trying importing not the compiled version, but the one from sources ```src/core.js```. It looks fine, and works, but webpack fires a warning
```
WARNING in ..../node_modules/billboard.js/src/internals/color.js
46:41-59 "export 'schemeCategory10' (imported as 'd3SchemeCategory10') was not found in 'd3-scale'
 @ ..../node_modules/billboard.js/src/internals/color.js
 @ ..../node_modules/billboard.js/src/core.js
```

**Comment by netil** [comment]
It's because from d3 v5, the `schemeCategory10` was moved from d3-scale to d3-scale-chromatic.
I'll releasing patch about tomorrow fixing that.
