### ISSUE TITLE
Logarithmic scale does not render correctly

### ISSUE THREAD

**Issue by andrewbdfisher** [naver/billboard.js#2854]
## Description
When using a logarithmic scale on the y axis, the rendered spacing of the log periods are not equal. This seems to be an issue only below 10. 

## Steps to check or reproduce

The graph in this example should be a straight line, with equal rendered spacing of 0.01, 0.1, 1, 10, 100, 1000.
https://jsfiddle.net/nk17wtd6/1/

**Comment by netil** [comment]
Hi @andrewbdfisher. For `log` scale, billboard.js uses d3.js' [Symlog Scales](https://github.com/d3/d3-scale#symlog-scales) and for the dataseries `[0.01, 0.1, 1, 10, 100, 1000]` it renders as the example you shared.
- https://jsfiddle.net/netil/f4qy3xn6/
