### ISSUE TITLE
How to show only the full 24h values on the x-axis in a timeseries chart?

### ISSUE THREAD

**Issue by MartijnHarmenzon** [naver/billboard.js#286]
I would like to create a timeseries chart form a data set containing hourly values for the the duration of 1 year. The exact time of the hourly values is never on the full hour, it can be anything. 
But I would like the values showed on the x-axis to be on the full hour for periods of 24h. So 00:00, 01:00 ... 22:00, 23:00.  How to achieve this?

I know I can set the x-values as an array, as shown in the code below. But is there not a function to do this instead of having to manually code all the values for a year?  

```
{
  data: {
    x: "x",
    xFormat: '%Y-%m-%d %H:%M:%S',  
    columns: [
      ["x", "2018-02-08 22:05:00", "2018-02-08 23:12:00", "2018-02-09 00:09:00", "2018-02-09 01:21:00"],
      ["data1", 2, -1, -2, -3]
    ]
  },
  axis: {
    x: {
      type: "timeseries",
      tick: {
        format: "%H:%M",
        values: [
          "2018-02-08 22:00:00",
          "2018-02-08 23:00:00",
          "2018-02-09 00:00:00",
          "2018-02-09 01:00:00"
        ]
      }
    }
  }
}
```

**Comment by netil** [comment]
@MartijnHarmenzon, you need to handle this making some helper function and this could be achieved in many different ways.

One of the approach is separate the data and get tick value string from it.
```js
// separated the data to get transformed tick values
var data = [
    ["x", "2018-02-08 22:05:00", "2018-02-08 23:12:00", "2018-02-09 00:09:00", "2018-02-09 01:21:00"],
    ["data1", 2, -1, -2, -3]
];

var chart = bb.generate({
	data: {
		x: "x",
		xFormat: '%Y-%m-%d %H:%M:%S',
		columns: data
	},
	axis: {
		x: {
			type: "timeseries",
			tick: {
			    format: "%H:%M",
		            values: data[0].concat().splice(1).map(function(v) {
                		return v.replace(/(:\d{2}){2}$/, ":00:00");
		            })
		    }
		}
	}
});
```

**Comment by MartijnHarmenzon** [comment]
@netil Thanks again. This was very helpfull.
