### ISSUE TITLE
Get Config from a rendered chart icon

### ISSUE THREAD

**Issue by norbertbede** [naver/billboard.js#2864]
## Description
I would like to copy chart config - data, - full json for additional analysis. This can be done by extra icon or special config - permission sent by hosting environment.

This would help to validate and play with config in your "playground" - embedded visual code editor.

Norbert

**Comment by netil** [comment]
Hi @norbertbede, thanks for the idea. I think providing an API returning generation option used at the initialized time will be useful. I'll try implement this for next release.
