### ISSUE TITLE
Tableview only

### ISSUE THREAD

**Issue by norbertbede** [naver/billboard.js#2884]
## Description
i analyse some other chart-libs, and, they are support table views - i mean let say table=chart - so chart is not rendered but table itselft i a chart.

Does this something you plan implement it ?

Thanks
Norbert

**Comment by netil** [comment]
Hi @norbertbede, I don't get it the necessity of `tableview` only. If need display table based list, making it without using chart implementation is much better in all circumstances.

Anyway, `tableview` only can be implemented by adjusting the chart size & its container.
Checkout the example: 
- https://jsfiddle.net/netil/osnfh954/

**Comment by norbertbede** [comment]
thanks for example and suggestion. n
