### ISSUE TITLE
Export doesn't consider font family

### ISSUE THREAD

**Issue by alebx** [naver/billboard.js#2892]
## Description
If a specific font family is set, the font family isn't applied in the export.

## Steps to check or reproduce

1. set a font family for `.bb svg`
2. export the chart

https://zfbya9.stackblitz.io

**Comment by netil** [comment]
Hi @alebx, thanks for the report. I'll dig into.

**Comment by netil** [comment]
To reflect custom style font need to make font's data embeddable. 
The current conversion pipeline goes generating a svg node embedding all the styles used from the page.
And then from the generated `svg + styles` trees, use canvas' API to generate image.

Unfortunately, to generate image from svg node, svg should contain all the styles needed. So the web font too.

There're two possible approaches:
- Option 1: Embed all web font's data as inlined.
   - This need to convert font's binary data to dataURI. (online [data: URI Generator](https://dopiaza.org/tools/datauri) might help)
   - working example: https://stackblitz.com/edit/zfbya9-8nf9nn?file=index.html
- Option 2: Or, billboard.js handle it
  - In this case, all the text nodes need to be handle separately to reflect proper styles by drawing texts separately.

The best for user, obviously will be the second one. But the implementing it will take time.
I'll be considering to enhance this for the next release.

**Comment by alebx** [comment]
@netil Thanks for the quick fix!
