### ISSUE TITLE
Data onover / onout not reliably called when moving between different series with same x-value

### ISSUE THREAD

**Issue by grantcox** [naver/billboard.js#2901]
## Description
I want to show some information based on which datapoint is currently highlighted - much like a tooltip.  This additional data involves template rendering so is a little expensive to generate, so I'd like to update it only when the highlighted data point actually changes.

Using `data.onover`, `data.onout` and `tooltip.grouped = false` almost achieves what I want, the only problem is that the `onout` for a series is only called when highlighting a completely separate x-axis value, not when highlighting another series value at the same x-axis value.  This means that trying to compare two series at the same point in time works "one way" (as each `onover` is called in turn), but then stops updating.
![data-onover](https://user-images.githubusercontent.com/186808/195143356-b00d07ce-5775-43cd-a60b-0c3063367420.gif)

I can get the desired behavior to work by using the `tooltip.onshow` and `tooltip.onhide`, but both of these callbacks are executed for every mouse movement even when there has been no significant change - there's no definitive "tooltip is no longer being shown" callback (afaict).  To avoid expensive template re-rendering I'd need to debounce these calls and see if there was a net change over time.
![tooltip-onshow](https://user-images.githubusercontent.com/186808/195141856-15a34c77-d367-4f19-9681-5b90fbf2c0d1.gif)

Is this the intended behavior?  The `setOverOut` implementation (and cache usage), looks like it was intended to call `data.onout` for each datapoint as soon as the cursor moves outside the shape bounds - potentially multiple points could be "over" concurrently, but once moving outside the shape bounds the respective `onout` should run immediately, rather than "once all shapes are out".

## Steps to check or reproduce
Here is a JSFiddle demonstrating these two cases: https://jsfiddle.net/6m9ay5Lh/4/

**Comment by netil** [comment]
@grantcox, released the [3.6.1](https://github.com/naver/billboard.js/releases/tag/3.6.1) with the fix.

**Comment by grantcox** [comment]
Thank you @netil , both for the changes to `data.onover/out` and for the suggestion about the bar sensitivity.  I was out of the office last week and I won't have a chance to test / integrate these changes in the coming week, but I really appreciate your efforts and responsiveness.  Thank you!
