### ISSUE TITLE
Improve Stacked Bar/Area Tooltip with ratio

### ISSUE THREAD

**Issue by igorpojzl** [naver/billboard.js#2921]
## Description
According to documentation #tooltip.format.value - Specified function receives name, ratio, id and index of the data point to show. ratio will be undefined if the chart is not donut/pie/gauge. If undefined returned, the row of that value will be skipped.

We would like to show percent of total in stacked Bar Chart Tooltip.

Use Case: Stacked Bar Chart with Timeseries
x = 1.1.2022, Values 100k By 20k (A), 30k (B), 50k (C) -> In Tooltip we want to show ratio for each Group

https://stackblitz.com/edit/cl47bu?file=index.ts

**Comment by netil** [comment]
Hi @igorpojzl, thanks for the suggestion.
Improved to pass `ratio` for area/bar stacked data. The change will be released in next release.
