### ISSUE TITLE
Round corners on Gauge & Donut - Feature Request

### ISSUE THREAD

**Issue by adamfagerstrom** [naver/billboard.js#2936]
## Description
It might be a nice addition if the gauge chart could be set to use rounded corners, kind of like the `bar_radius` option for the bar-chart. And also something similar for the donut chart, i guess that's also includes adding padding as an option between all slices aswell.

I can't find any options to set this as for now, or a similar request in previous issues. If i missed something please just close.

## Example
Some rough sketches to give an idea what my request is about
### Gauge
![gauge](https://user-images.githubusercontent.com/76154776/199185001-adc3a766-83c4-4f47-b777-6426b1079ec4.jpg)
### Donut
![donut](https://user-images.githubusercontent.com/76154776/199185874-7363574f-f9c4-439c-9411-0dfda4887d1a.jpg)

**Comment by netil** [comment]
Hi @adamfagerstrom, thanks for the suggestion.
I'll consider for the next release.
