### ISSUE TITLE
Transition setting is ignored

### ISSUE THREAD

**Issue by joedwy** [naver/billboard.js#294]
## Description
I am trying to stop the rendering animation entirely. No matter what I set the transition duration to, the duration is consistent (about the 350ms described in the documentation). 

## Steps to check or reproduce
This is the code I'm using to generate the chart: 

`streamChart = bb.generate({
			    bindto: '#algoChart',
			    data: {
				    columns: chartColumns,
					colors: {
				    	buy: 'green',
				    	price: 'blue',
				    	sell: 'red'
				    }
			    },
			    transition: { 
			    	duration: 0 
			    }
			});`

I've tried it with `null` and `0`.  I also tried large and small numbers to see if I was being stupid. Heck, I've even tried going into the Billboard source JS files and manually setting the transition_duration to `0`. 

I observed the created object in the javascript console and noted that while most other settings show up as object properties, `transition` is not one of the object's properties.

**Comment by netil** [comment]
Hi @joedwy, can you describe more in detail about your use case?

Take in consideration with the below [example](https://naver.github.io/billboard.js/demo/#Chart.LineChart), how the `transtion.duration` option works.

- Default transition
<img src=https://user-images.githubusercontent.com/2178435/36368207-88bf2a5e-1599-11e8-821e-b5c309c5c9d1.gif width=500>

- When set `transition.duration=0`
<img src=https://user-images.githubusercontent.com/2178435/36368213-8d7dc712-1599-11e8-9fcb-87c52d37027c.gif width=500>

**Comment by NeomMob** [comment]
I am encountering the same issue but for the initial transition, just after the graph has loaded. No probelm after. Only the initial one stays at 350ms

**Comment by netil** [comment]
Fixed from #2232
