### ISSUE TITLE
Type for gauge.label.format does not match the specification

### ISSUE THREAD

**Issue by m-gallesio** [naver/billboard.js#2946]
The typing for the `ChartOptions.gauge.label.format` is incomplete and does not fully match its specification.

Accordig to the [documentation](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.gauge) it accepts an `id` parameter with the name of the series,
however this `id` is not declared in the interface:
https://github.com/naver/billboard.js/blob/e8e41c8dc3832c38f81d30bb2dab97060c50c9c3/types/options.shape.d.ts#L261

Specifying an `id` parameter works correctly at runtime, so it is simply a typing problem.

**Comment by netil** [comment]
Hi @m-gallesio, thanks for the report. Fixed the issue.
