### ISSUE TITLE
Question : Tootip order 

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#295]
Hi @netil ,
How to set custom order in tooltip and order set to be fixed.
like 1. total call 
       2. hardware calls
       3.Software calls

**Comment by netil** [comment]
There's [tooltip.order](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option to sort tooltip's data.

Also check out the example:
- https://naver.github.io/billboard.js/demo/#Tooltip.TooltipOrder

**Comment by Rohit-Parte** [comment]
Hi @netil ,
Done,
Thanks
