### ISSUE TITLE
data.regions not rendered correctly

### ISSUE THREAD

**Issue by alebx** [naver/billboard.js#2950]
## Description
When adding `data.regions` the line isn't rendered correctly anymore, somehow an offset is added to the dashed lines.

## Steps to check or reproduce
Example:
https://stackblitz.com/edit/data-regions?file=index.ts

**Comment by netil** [comment]
HI @alebx, confirmed the issue.
It happens for `category` type axis only. I'll dig into.

**Comment by alebx** [comment]
@netil Thanks for the quick reply!
