### ISSUE TITLE
Missing d3 types referenced from types.d.ts: @types/d3-selection @types/d3-transition

### ISSUE THREAD

**Issue by josundt** [naver/billboard.js#2954]
## Description

* When compiling a TypeScript project that depends on the billboard.js package, compilation fails because of missing d3 types.

### TypeScript compilation error message ###
```
node_modules/billboard.js/types/types.d.ts:5:25 - error TS7016: Could not find a declaration file for module 'd3-selection'. '/repos/sample-project/node_modules/d3-selection/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/d3-selection` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3-selection';`

5 import {Selection} from "d3-selection";
                          ~~~~~~~~~~~~~~

node_modules/billboard.js/types/types.d.ts:6:26 - error TS7016: Could not find a declaration file for module 'd3-transition'. '/repos/sample-project/node_modules/d3-transition/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/d3-transition` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3-transition';`

6 import {Transition} from "d3-transition";
                           ~~~~~~~~~~~~~~~
```

### From `billboard.js/types/types.d.ts`: ###
```typescript
import {Selection} from "d3-selection";
import {Transition} from "d3-transition";

// ...
```

### Reason: ###
In the `billboard.js` package, `@types/d3` is a `devDependency`.
Since it is not `dependency`, this types package is not installed in a project that consumes the `billboard.js` package.
Still the `billboard.js` exported types has references/dependencies to `d3` types packages (as shown in the previous paragraph).

### Temporary workaround for TypeScript projects that uses `billlboard.js`: ###
Add `skipLibCheck: true` to TypeScript compiler options in project that consumes the `billboard.js` package.
> _It is of course not desirable to do this, since it will suppress type errors from all packages._

### Resolution alternatives: ###
1. Make the full `@types/d3` bundle package a _`dependency`_ instead of a _`devDependency`_. This is the quickest fix, but it will expose the full d3 type bundle to projects that consume billboard.js. This will expose a lot more d3 types packages than required.  

2. Add only `@types/d3-selection` and `@types/d3-transition` packages as `dependencies`. This is all that's required for TypeScript compilation to work, and in my opinion the best option.

3. Remove references to `d3` types entirely; use only "local" interfaces (copy type definitions from d3).

**Comment by boris-petrov** [comment]
The same started happening again in version 3.11.0 upgrading from 3.10.3.

cc @netil

**Comment by josundt** [comment]
@netil Waiting for the release for this fix.
