### ISSUE TITLE
Question: Line chart with regions

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#296]
Hi @netil ,
How to set  "Line chart with regions" ,region start value in category axis.

**Comment by netil** [comment]
Check out the [regions](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.regions) option for that.

There's also an example of regions setting:
- https://naver.github.io/billboard.js/demo/#Region.Region

**Comment by Rohit-Parte** [comment]
Hi @netil ,
Yes, I already did it. 
Working fine.
Thanks,
