### ISSUE TITLE
Bars rendered in an unexpected position

### ISSUE THREAD

**Issue by web-party** [naver/billboard.js#2962]
## Description
In a bar chart, if all column values are identical (low integers, equal/less than 7 or so) and the y axis max value is configured to be the same as column value, bars are placed too far away from the x axis.

## Steps to check or reproduce
https://stackblitz.com/edit/8fjgej

**Comment by netil** [comment]
Hi @web-party, thanks for the report.
For workaround set `axis.y` option as below:

```js
  axis: {
    y: { 
      max: 5,
      tick: {
        values: [1, 3, 5]
      },
      min: 0,
      padding: {
        bottom: 0
      }
    }
  }
```
