### ISSUE TITLE
rendering area behind bar

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#2965]
## Description
When we create a chart with 2 data rows, `data1` being `area-spline`, and `data2` being a `bar`, the bars will be rendered behind the area, not considering the columns order of the data.
This makes the parts, where the area overlapps the bars look blueish:
![01  current order](https://user-images.githubusercontent.com/42860868/203092504-8a858564-c8f4-4bb1-bcf0-f58c4b5ac58d.png)

The unwanted effect here is that the area will always change the color of the overlapped bar as it was decided to always render the bars first:
![grafik](https://user-images.githubusercontent.com/42860868/203093694-11fa38e0-0a46-4609-a218-9000a6641b8b.png)

The wanted result is **only** the area being rendered behind the bars, and the line and points still being rendered in front of the bars like this:
![03  area between bar](https://user-images.githubusercontent.com/42860868/203094610-30391a65-a4c3-4c5c-a0a5-85ea9b32bef3.png)

Is there any way to achieve this without changing the way the data types are rendered in billboard?

There was also similar issue created in c3 in 2015 which I will also link here: https://github.com/c3js/c3/issues/1446

**Comment by netil** [comment]
Hi @michkami, this happens because line types(including area) nodes area generated and controlled as a group, and they're rendered after bar node in DOM hierarchy order.

The simple workaround is manipulate area node hierarchy order to stay before the bar node element as:

```js
  onafterinit: function() {
    const bars = this.$.main.select(".bb-chart-bars").node();
    const areas = this.$.main.selectAll(".bb-areas").nodes();

    areas.forEach(v => {
      bars.insertAdjacentElement("beforebegin", v);
    });
  }
```

I'm not sure how this functionality is needed, but I'll be considering for the next release.
