### ISSUE TITLE
How access a chart already generate to hide/show data label:question 

### ISSUE THREAD

**Issue by patbourgoin** [naver/billboard.js#297]
##  #Description
Hi, I got a question.
Once I generated the chart, how can I access the object, the chart, to hide/show some data?

Thanks
Patrick

**Comment by netil** [comment]
Hi @patbourgoin, there're 3 types of methods to handle the visibility of the data.
- [.show()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#show)
- [.hide()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#hide)
- [.toggle()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#toggle)

The basic usage examples are
```js
var chart = bb.generate({ ... });

chart.hide("data1");  // or chart.hide(["data1", "data3"]);
chart.show("data1");  // or chart.show(["data1", "data3"]);

// when data is visible, it will hide, when data is invisible, it will show
chart.toggle("data1");
chart.toggle(["data1", "data2"]);
```
