### ISSUE TITLE
stanford scale breaks on min: 0

### ISSUE THREAD

**Issue by dastrobu** [naver/billboard.js#2999]
## Description
When setting the scale to start from 0, it breaks. 

```
scale: {
          min: 0,
          max: 10
     },
```

## Steps to check or reproduce

1. Open https://naver.github.io/billboard.js/demo/#Plugins.StanfordDiagram
2. edit the scale and set to: 
   ```
        scale: {
          min: 0,
          max: 10000
     }
   ```

Actual:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/1847260/207834092-21701ee2-8497-4735-ad2d-28d5f34d31a0.png">

Scale has no ticks anymore, and all points are green (no color coding anymore)

**Comment by netil** [comment]
Hi @dastrobu, thanks for the report and it was reproducible.
I'll be checking the issue.

**Comment by habibi03336** [comment]
Can I investigate this issue?
