### ISSUE TITLE
Change color based on graph value

### ISSUE THREAD

**Issue by sibliss** [naver/billboard.js#30]
## Description
Hello there, coming from a D3 background I used to write code like this:
`const opacity = d3.scaleLinear().domain([0, max]).range(["#efffff", this.computedType]);`

(`this.computedType` was simply a different color based on the type of the graph.)
to obtain the effect of changing the color based on the single bar value: the higher the value, the stronger the color.

How can I obtain the same effect on Billboard? I saw in the doc that there is a color:pattern property but it's not really clear how it works!

**Comment by netil** [comment]
Take a look [data.color](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data:color) option for that.
Not fully, but you can handle some point to change the color.

```js
color: function(color, d) {
        // define your color scale
	var colorRange = d3.scaleLinear()
		.domain([0, 20])
		.range(["white", "orange", "red"]);

	if (typeof d === "object") {
		// for data point
		if (d.value) {
			return colorRange(d.value);
	
	    	// for data type (ex. line, bar)
	    	} else {
			return color;
	    	}
	
	// for label
	} else {
	    return color;
	}
}
```
I made a simple demo, which bar color differ according it's data value.
- http://jsbin.com/witeduq/edit?html,js,output

**Comment by netil** [comment]
Closing for now.
@sibliss If you haven't achieved your needs or have other question, plz open new issue for that.
