### ISSUE TITLE
padAngle in pie chart

### ISSUE THREAD

**Issue by julien** [naver/billboard.js#301]
## Description
This is not an issue, but rather a question.
Currently, when using the `pie.padAngle` option, the chart is rendered like in the image bellow

<img width="293" alt="pad_angle_01" src="https://user-images.githubusercontent.com/5572/36417538-885084d0-162c-11e8-879d-2c930ce62800.png">

What would you think if it was also possible to be renderer like this?

<img width="359" alt="pad_angle_02" src="https://user-images.githubusercontent.com/5572/36417785-23927d5e-162d-11e8-94f3-54ddaa0bd11e.png">

I was thinking that we could of add another option so that the "two" behaviours can be supported.
Tell me what you think, I'd be happy to implement this.

**[This](https://bl.ocks.org/mbostock/3e961b4c97a1b543fff2)** might be worth reading as well, since it's somewhat related.

Thanks!

**Comment by netil** [comment]
Sure @julien, giving different alternative will be really useful :)
