### ISSUE TITLE
Question about the problem using subchart with init range and timeseries

### ISSUE THREAD

**Issue by minjooo96** [naver/billboard.js#3010]
안녕하세요! 저는 billboard.js를 처음 사용해보는 사용자입니다.
우선 아주 좋은 차트 라이브러리를 사용할 수 있게 만들어주셔서 감사합니다.
2가지의 질문이 있습니다!

1. subchart의 init.range를 사용할때, 가장 처음과 가장 마지막을 선택할 경우 subchart가 꽉 차지 않아 원래의 차트가 잘리는 문제가 있습니다. 어떻게 해야 해결할 수 있을지 답변 부탁드립니다!

** init.range를 사용했을 때의 화면
![image](https://user-images.githubusercontent.com/47136112/209892417-78d1054c-d97a-40a5-9689-452fcc72f15d.png)

** 제가 의도하고 싶은 화면
![image](https://user-images.githubusercontent.com/47136112/209892171-1d25d57f-d8f1-455b-9d10-4a69fd231552.png)

2. x축의 type을 timeseries로 선언했는데, zoom을 안했을 경우 정상적으로 tick들이 보입니다. 하지만 zoom을 했을 경우에 제가 선언하지 않은 날짜의 tick들이 보입니다.  저는 각 월의 1일만 보이게끔 하고 싶은데, 방법이 있을까요?
(빨간색 박스의 tick만 제가 보이게 하고 싶은 날짜들입니다.)

![image](https://user-images.githubusercontent.com/47136112/209892275-3a5521fb-196e-4845-a614-bf146fdf92a2.png)

2가지의 경우 모두 구글링을 해보아도 해답을 찾지 못해 이렇게 문의를 남깁니다.
혹시 몰라 코드펜 링크 남겨드립니다!!
https://codepen.io/minjooo/pen/vYaLjRE

확인부탁드립니다. 감사합니다!

**Comment by minjooo96** [comment]
자문자답입니다..... 
1번은 스스로 해결할 수 있었습니다. :-)!!
차트와 x축의 padding을 조절하니 모든 축이 노출이 됩니다.

하지만 2번의 답은 아직 찾지 못했습니다 :( ..

**Comment by netil** [comment]
@minjooo96, try setting `axis.x.tick.fit=true` and the ticks will stay same during the zoom interaction.

![Dec-29-2022 22-12-14](https://user-images.githubusercontent.com/2178435/209955925-b4fae2f2-e7c3-43f8-8404-91102c8993c2.gif)

If set to `false` will make appear ticks according on zoom range. Checkout the below example by drag zoom-in and will see ticks data adjusting & appearing relatively the given zoomed range.
- https://naver.github.io/billboard.js/demo/#Axis.XAxisTickTimeseries

**Comment by minjooo96** [comment]
헉 답변 감사드립니다! 알려주신 방법으로 잘 해결 되었습니다.
새해 복 많이 받으시고 좋은 하루 보내시길 바라겠습니다~ :-)
