### ISSUE TITLE
Missing axis ticks on bar chart

### ISSUE THREAD

**Issue by Alex-Dettinger** [naver/billboard.js#3020]
### Description
I've migrated our project from c3 to the latest version of billboard.js. All charts are worked as previously except that there are not tick marks on the axes of our bar chart

### Steps to reproduce
Our bar chart is detailed below. I've also needed to make some changes to our scss to adjust the axes thickness. 
<pre>
this.chart = bb.generate({
                bindto: '#chart-container',
                size: {
                    height: 350,
                    width: 600,
                },
                legend: {
                    show: false,
                },
                tooltip: {
                    show: false,
                },
                data: {
                    type: bar(),
                    json: this.state.data,
                    keys: {
                        x: 'letter_grade',
                        value: ['num_learners'],
                    },
                },
                axis: {
                    x: {
                        type: 'category',
                    },
                    y: {
                        padding: {
                            top: 120,
                        },
                        tick: {
                            format: d3.format("d"),
                        },
                    },
                },
            });
</pre>
<pre>
.bb-axis.bb-axis-y path {
  stroke-width: 1px;
  stroke: #000;
  fill: none;
}

.bb-axis.bb-axis-x path {
  stroke-width: 1px;
  stroke: #000;
  fill: none;
}
</pre>
Old Chart:
![Screen Shot 2023-01-06 at 2 50 50 PM](https://user-images.githubusercontent.com/86626632/211097776-2e74531d-b0d8-42ea-b8bc-8722dd1e55bf.png)

New Chart:
![Screen Shot 2023-01-06 at 2 50 59 PM](https://user-images.githubusercontent.com/86626632/211097822-9149aa63-5bfa-45c7-ba27-d6659a267700.png)

**Comment by netil** [comment]
Hi @Alex-Dettinger, I made an online working example based on your generation code I couldn't find any issues.
- https://jsfiddle.net/netil/84vbfL27/

Ticks display can be handle by [`axis.x.tick.show` ](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4show) option, which the default is set to display.
