### ISSUE TITLE
Setting pie.padAngle renders incorect values

### ISSUE THREAD

**Issue by julien** [naver/billboard.js#303]
## Description

When creating a pie chart and using the `pie.padAngle` option, the values displayed in pie chart are incorect

## Steps to check or reproduce

Create a pie chart with the following snippet

```javascript
var chart = bb.generate({
  data: {
    columns: [
      ['data1', 20],
      ['data2', 10],
      ['data3', 40],
      ['data4', 30]
    ],
    type: 'pie',
   },
   pie: {
     padAngle: 0.02
  },
  bindto: '#chart'
});
```

### Current result

<img width="325" alt="pad_angle_00" src="https://user-images.githubusercontent.com/5572/36484343-40a8624a-1719-11e8-8f06-ed827cdd8cbf.png">

### Expected result (or what I would expect) 

<img width="325" alt="pad_angle_02" src="https://user-images.githubusercontent.com/5572/36484087-6ba14dc8-1718-11e8-8c47-70c548625a87.png">

### More information and proposed solution

After looking at the [`defaultArcValueFormat `](https://github.com/naver/billboard.js/blob/master/src/internals/format.js#L48-L50) it seems that the text that is renderer is not the actual value of the datum, but the `ratio` passed to the function.

Maybe the function could just return the percentage of the datum's value concatenated with the `%` sign

**Comment by netil** [comment]
Yeap, it seems a bug. I guess the value is affected by `padAngle` which shouldn't be.
