### ISSUE TITLE
t.initClip is not a function error in 3.7.0

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#3035]
## Description
When rendering a chart using a tree-shaken build, we get a `t.initClip is not a function` error in `t.initParams` in the chart internals.

## Steps to check or reproduce
Use the ESM tree-shaken build
Render a donut chart (or any other type of chart that does not have axis)

**Comment by netil** [comment]
Thanks for the report. Caused as a side-effect of the treemap type implementation.
