### ISSUE TITLE
rotated bars not drawing when y axis inverted

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3049]
## Description
When you create a simple bar chart like this:
![grafik](https://user-images.githubusercontent.com/42860868/212841429-e4e9e644-8e38-4182-86be-15b84c416d4a.png)

you can set `axis.rotated: true`, and will get the following chart:
![grafik](https://user-images.githubusercontent.com/42860868/212844963-a9c78d1f-cfba-43a6-a21b-665a7984fa92.png)

When you invert the y axis in the first chart, it will look like this:
![grafik](https://user-images.githubusercontent.com/42860868/212845167-8ffe78e2-8457-4e9a-8e9c-985fc5c66066.png)

but when you invert the y axis on the rotated chart, it won't draw the bars anymore:
![grafik](https://user-images.githubusercontent.com/42860868/212845282-39359c73-4ab2-4db5-905b-13f7c196000e.png)

## Steps to check or reproduce
https://stackblitz.com/edit/eventrect-6x51aw?file=index.ts

**Comment by netil** [comment]
Hi @michkami, thanks for the report. I'll fix that.
