### ISSUE TITLE
The distribution sets __esModule on window

### ISSUE THREAD

**Issue by boris-petrov** [naver/billboard.js#305]
This code from `node_modules/billboard.js/dist/billboard.js`:

```javascript
var a = typeof exports === 'object' ? factory(require("d3")) : factory(root["d3"]);
for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
```

The variable `a` contains:

```javascript
{
  bb: {version: "1.2.0", generate: ƒ, chart: {…}},
  d3: {event: null, format: ƒ, formatPrefix: ƒ, timeFormat: ƒ, timeParse: ƒ, …},
  __esModule: true
}
```

And then the `for` loop sets all keys in `window`. This breaks other libraries which I've required after `billboard` (because of `__esModule` which should not be in `window`). Am I doing something wrong or is this a bug?

**Comment by netil** [comment]
Hi @boris-petrov, what's your build environment?

billboard.js is distributed to targeted as UMD. If you're including as normal script loading(`<script src...>`), will be exposed in global context.

But, if you're dealing with as ESM import, will not be exposing it.
```js
import {bb} from "billboard.js";
```

**Comment by boris-petrov** [comment]
@netil - thanks for the answer. I'm using it with Ember CLI - there I use `app.import('node_modules/billboard.js/dist/billboard.js');` which pretty much just appends the source code to a big JS file which is then put in a script tag.

**Comment by netil** [comment]
I'm seeing, below difference from 1.2.0, which wasn't present.
Would you mind test commenting them?
I'll try to look for that.

```js
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
```

**Comment by boris-petrov** [comment]
Hi, thanks for the answer! Actually, `__esModule` was set even before `1.2.0` - I first started using billboard.js from version `1.1.0` and that's when I opened the issue. I think it happens because of the code that I mentioned in the first post.

Otherwise - commenting out that code didn't fix neither this issue here, nor the [other one](https://github.com/naver/billboard.js/issues/334). :(

**Comment by netil** [comment]
Hmm... weird, because since the first release `__esModule` was set true.

As you mentioned from the #334, if not started working from 1.3.0, it should be caused from the changes happened from that.

Let me dig more on this.

**Comment by boris-petrov** [comment]
Thanks a lot for taking the time to check this! Be sure to play with the [reproduction project](https://github.com/boris-petrov/billboard.js-bug), it should help you narrow down the issue I hope!

**Comment by boris-petrov** [comment]
I believe this is no longer relevant.
