### ISSUE TITLE
Bug in Stacked Serialized Bars

### ISSUE THREAD

**Issue by Tomas-Henriques** [naver/billboard.js#3055]
## Description

When I click on 'today'
![image](https://user-images.githubusercontent.com/123361595/213999364-5f51cfd6-acf1-49db-af01-a1c7286d7a6f.png)
Everything works like its supposed too.
![image](https://user-images.githubusercontent.com/123361595/213999469-825df620-3de2-4292-9f07-96e8d00513e8.png)
But when I click again.
![image](https://user-images.githubusercontent.com/123361595/213999726-b37497e0-8afa-4036-b39f-c479e40c9b8d.png)
These 3 labels go all the way to the left.
I thinks it might be a bug.

**Comment by netil** [comment]
Hi @Tomas-Henriques, thanks for the report.
