### ISSUE TITLE
Gauge and donut charts don't render empty label text in v2.2.6

### ISSUE THREAD

**Issue by lrdiv** [naver/billboard.js#3066]
## Description

I'm on d3 version 5.0.0 attempting to migrate from c3.js to billboard.js

Most charts looks great after following the migration instructions linked in the README. However, both donut and gauge chart types are having different issues displaying the empty label text.

**Gauge**: When an empty array is passed as `data.columns`, an exception is thrown that says `Reduce of empty array with no initial value` which seems to be caused by trying to calculate the gauge chart's max value on an empty dataset.

**Donut**: When an empty array is passed as `data.columns`, no text is rendered.

Are there any known workarounds for this?

## Steps to check or reproduce

I've reproduced both of these with the most basic implementation possible on Stackblitz: https://stackblitz.com/edit/typescript-kwgtun?file=index.ts

Edit: to see the issue with donut charts in the above Stackblitz, the gauge chart code must be commented out first

**Comment by netil** [comment]
Hi @lrdiv, thanks for the report.
It was a bug regardless the version and I'll be looking how to fix for `2.x`

**Comment by netil** [comment]
@lrdiv, released  `v2.2.7` as the patch version.  
Try by installing,

```
$ npm install billboard.js@2.2.7
```
