### ISSUE TITLE
Getting references to all charts on one page

### ISSUE THREAD

**Issue by rshingleton** [naver/billboard.js#308]
Question:

Is there a way to get a reference to all chart instances on a page?

Use case:

- Need to resize all charts on a given page
- Interact with multiple timeseries charts on a given page
  - hover a point on one chart and show a hover line on other charts with matching datapoints

**Comment by rshingleton** [comment]
There are implementations outside the api, just pushing them into an array or hash is easy enough. Highcharts for instance maintains a charts array when a new chart is generated:
[<static> charts :Array.<Highcharts.Chart>](https://api.highcharts.com/class-reference/Highcharts#.charts)

I thought there might be something similar. No big deal, I might work on an extension for this.

**Comment by netil** [comment]
well, maybe it's good idea having this feature.
