### ISSUE TITLE
X-axis of timeseries-based-chart changes by the chart type

### ISSUE THREAD

**Issue by jsong0605** [naver/billboard.js#31]
## Description

Like I mentioned on the title, X-axis of timeseries-based-chart changes by the chart type
and I’d like to get timeseries charts w/ same x-axis .

On the bar chart example(check the bar chart below), there are some scratch areas on the very left and right side, which were generated automatically.
The thing is… on the line chart example, the scratch area doesn’t exit and the x-axis is differ from that of bar chart. (Even though they were rendered based on the totally same data)

I am getting through this problem by manipulating some padding.left & padding.right (or axis.x.padding.left, axis.x.padding.right).

As you may guess, sometimes, synchronizing each chart's x-axis is a huge deal.

It will be a big help for me, if you guys are willing to provide an way to get charts w/ same x-axis.
There must be someone who needs your solution on this matter as like I do.

Thanks, in advance. :)

## Steps to check or reproduce
<a class="jsbin-embed" href="http://jsbin.com/zuqofuh/4/embed?html,js,output">JS Bin on jsbin.com</a>

![issue3](https://user-images.githubusercontent.com/25364015/27373382-03b2ae40-56a3-11e7-9fa6-bde35b79f492.png)

**Comment by kjhwee91** [comment]
@jsong0605 you can use [axis.x.padding](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis:x:padding) option to solve your issue. please check [solved example](http://jsbin.com/ziroxiv/1/edit?html,js,output) and this code.
```
var lineChart = bb.generate({
  // ...
  axis: {
    x: {
      padding : { // add this config
        left : 0,
        right : 0
      },
      type: "timeseries",
      min:  "2017-02-15",
      max:  "2017-07-15"
    },
    // ...
});
```
If you not setting "axis.x.padding" option, billboard.js reflect max data count to make xAxis. but this logic is only applied when generate bar chart. so line chart and bar chart has different xGrid result.

try this solution and if you faced another issue, please add comment.

**Comment by netil** [comment]
Closing the issue.
If not solved with above comment, plz reopen it.
