### ISSUE TITLE
The requested module 'd3-shape' does not provide an export named 'arc' (at billboard.js:17:321)

### ISSUE THREAD

**Issue by mlcarrington** [naver/billboard.js#3115]
## Description

I'm trying to use billboard.js via npm install and an importmap from a browser without using any bundling. I've hit the above problem with the import of arc from d3-shape in billboard.js. Have a missed a version or dependency issue ? Or is this just not the right way to do this ?

npm install billboard.js
npm install d3

Then in the browser ...
## Steps to check or reproduce

    <script type="importmap"> 
    {
	"imports": {
	    "d3-axis": "/node_modules/d3-axis/dist/d3-axis.min.js",
	    "d3-brush": "/node_modules/d3-brush/dist/d3-brush.min.js",
	    "d3-drag": "/node_modules/d3-drag/dist/d3-drag.min.js",
	    "d3-dsv": "/node_modules/d3-dsv/dist/d3-dsv.min.js",
	    "d3-ease": "/node_modules/d3-ease/dist/d3-ease.min.js",
	    "d3-hierarchy": "/node_modules/d3-hierarchy/dist/d3-hierarchy.min.js",
	    "d3-interpolate": "/node_modules/d3-interpolate/dist/d3-interpolate.min.js",
	    "d3-scale": "/node_modules/d3-scale/dist/d3-scale.min.js",
	    "d3-selection": "/node_modules/d3-selection/dist/d3-selection.min.js",
	    "d3-shape": "/node_modules/d3-shape/dist/d3-shape.min.js",
	    "d3-time-format": "/node_modules/d3-time-format/dist/d3-time-format.min.js",
	    "d3-transition": "/node_modules/d3-transition/dist/d3-transition.min.js",
	    "d3-zoom": "/node_modules/d3-zoom/dist/d3-zoom.min.js",
        "billboard": "/node_modules/billboard.js/dist-esm/billboard.js"	    
	}
    }
    </script>
    <script type="module">
      import bb, {area, line} from "billboard";
      console.log(bb);
    </script>

**Comment by netil** [comment]
@mlcarrington have you checked the related doc?
- https://github.com/naver/billboard.js/wiki/How-to-load-as-ESM-directly-from-the-browser%3F

also checkout the working online demo:
- https://codepen.io/netil/pen/NWXvJrW

**Comment by mlcarrington** [comment]
Thanks for the links. I actually used them for my start point but if I don't specify the full path on each entry I just get a 404 for each one.

**Comment by mlcarrington** [comment]
Tried installing an older version of d3 to see if that made any difference ...

npm install d3@^6

... same result.

**Comment by lrdiv** [comment]
Is it possible to achieve this in webpack?

**Comment by mlcarrington** [comment]
Thanks for the suggestion. Yes, it is possible to do it with webpack or one of the many other bundling solutions but I was after a completely static solution with the least amount of extra baggage. 

It looks like it should work without any problem at all. After all it's very simple but it doesn't and I'd really like to understand why that is.

**Comment by netil** [comment]
@mlcarrington, basically this isn't billboard.js' issue. Is about how to load(import) locally installed module and run.

To do that, follow below steps.

### Step 1

```
## don't need to install other packages
$ npm i billboard.js
```

### Step 2

Specify and maps all necessary modules.

```html
<script type="importmap"> 
  {
    "imports": {
        "d3-array": "./node_modules/d3-array/src/index.js",
        "d3-axis": "./node_modules/d3-axis/src/index.js",
        "d3-brush": "./node_modules/d3-brush/src/index.js",
        "d3-color": "./node_modules/d3-color/src/index.js",
        "d3-dispatch": "./node_modules/d3-dispatch/src/index.js",
        "d3-drag": "./node_modules/d3-drag/src/index.js",
        "d3-dsv": "./node_modules/d3-dsv/src/index.js",
        "d3-ease": "./node_modules/d3-ease/src/index.js",
        "d3-format": "./node_modules/d3-format/src/index.js",
        "d3-hierarchy": "./node_modules/d3-hierarchy/src/index.js",
        "d3-interpolate": "./node_modules/d3-interpolate/src/index.js",
        "d3-path": "./node_modules/d3-path/src/index.js",
        "d3-scale": "./node_modules/d3-scale/src/index.js",
        "d3-selection": "./node_modules/d3-selection/src/index.js",
        "d3-shape": "./node_modules/d3-shape/src/index.js",
        "d3-time": "./node_modules/d3-time/src/index.js",
        "d3-time-format": "./node_modules/d3-time-format/src/index.js",
        "d3-timer": "./node_modules/d3-timer/src/index.js",
        "d3-transition": "./node_modules/d3-transition/src/index.js",
        "d3-zoom": "./node_modules/d3-zoom/src/index.js",
        "internmap": "./node_modules/internmap/src/index.js",
        "billboard.js": "./node_modules/billboard.js/dist-esm/billboard.js"
    }
  }
</script>
```

### Step 3

Place generation code

```html
<script type="module">
import bb, {area, line} from "billboard.js";

bb.generate({
    data: {
        columns: [
            ["data1", 300, 350, 300, 0, 0, 0],
            ["data2", 130, 100, 140, 200, 150, 50]
        ],
        types: {
            data1: area(),
            data2: line()
        }
    }
});
</script>
```

Tested on latest chrome and worked without issue.

For convenience, here's the whole HTML code.

```
<html>
<head>
<title>billboard.js</title>
<link rel="stylesheet" href="./node_modules/billboard.js/dist/billboard.css">
<body>
<div id="chart"></div>
<script type="importmap"> 
  {
    "imports": {
        "d3-array": "./node_modules/d3-array/src/index.js",
        "d3-axis": "./node_modules/d3-axis/src/index.js",
        "d3-brush": "./node_modules/d3-brush/src/index.js",
        "d3-color": "./node_modules/d3-color/src/index.js",
        "d3-dispatch": "./node_modules/d3-dispatch/src/index.js",
        "d3-drag": "./node_modules/d3-drag/src/index.js",
        "d3-dsv": "./node_modules/d3-dsv/src/index.js",
        "d3-ease": "./node_modules/d3-ease/src/index.js",
        "d3-format": "./node_modules/d3-format/src/index.js",
        "d3-hierarchy": "./node_modules/d3-hierarchy/src/index.js",
        "d3-interpolate": "./node_modules/d3-interpolate/src/index.js",
        "d3-path": "./node_modules/d3-path/src/index.js",
        "d3-scale": "./node_modules/d3-scale/src/index.js",
        "d3-selection": "./node_modules/d3-selection/src/index.js",
        "d3-shape": "./node_modules/d3-shape/src/index.js",
        "d3-time": "./node_modules/d3-time/src/index.js",
        "d3-time-format": "./node_modules/d3-time-format/src/index.js",
        "d3-timer": "./node_modules/d3-timer/src/index.js",
        "d3-transition": "./node_modules/d3-transition/src/index.js",
        "d3-zoom": "./node_modules/d3-zoom/src/index.js",
        "internmap": "./node_modules/internmap/src/index.js",
        "billboard.js": "./node_modules/billboard.js/dist-esm/billboard.js"
    }
  }
</script>
<script type="module">
import bb, {area, line} from "billboard.js";

bb.generate({
    data: {
        columns: [
            ["data1", 300, 350, 300, 0, 0, 0],
            ["data2", 130, 100, 140, 200, 150, 50]
        ],
        types: {
            data1: area(),
            data2: line()
        }
    }
});
</script>
</body>
</html>
```

**Comment by netil** [comment]
Also added to wiki page:

*   https://github.com/naver/billboard.js/wiki/How-to-load-as-ESM-directly-from-the-browser%3F#option-2-from-local-installation
