### ISSUE TITLE
v2.2.7 breaks package build

### ISSUE THREAD

**Issue by lrdiv** [naver/billboard.js#3123]
## Description
Once upgrading to 2.2.7 I am getting the following error:

> ERROR in ./node_modules/billboard.js/dist/billboard.esm.js 9:2
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (9:2)

This was not an issue in 2.2.6

**Comment by lrdiv** [comment]
I will try to put together a stackblitz to reproduce this

**Comment by lrdiv** [comment]
Here is a link to a repl.it with a bare minimum webpack config using babel-loader that shows this issue:

https://replit.com/join/bsyczcilmv-lrdiv

To reproduce:

1. Click the "Shell" tab on the right half of the screen
2. Run `npm install`
3. Run `npm start`

**Comment by lrdiv** [comment]
I should note that webpack will run successfully if the import is changed to:

```typescript
import bb, { ChartOptions } from 'billboard.js/dist/billboard';
```

but this causes me to lose all typings

**Comment by netil** [comment]
We adopted [Conditional exports](https://nodejs.org/api/packages.html#conditional-exports) starting from [3.2.0](https://github.com/naver/billboard.js/releases/tag/3.2.0) release. And to handle this issue, is highly recommended to use latest version, which applies the adoption of the latest updates of the ecosystem.

From the [Node.js doc](https://nodejs.org/api/packages.html#type), 

> If the nearest parent `package.json` lacks a `"type"` field, or contains `"type": "commonjs"`, `.js` files are treated as [CommonJS](https://nodejs.org/api/modules.html). If the volume root is reached and no `package.json` is found, `.js` files are treated as [CommonJS](https://nodejs.org/api/modules.html).

2.2.7's package.json has no `type` filed, so according the above definition, ESM dist file(`dist/billboard.esm.js`) will be treated as CJS and to force as ESM need to update dist file's extenstion to `.mjs`.

Will release 2.2.8 providing ESM dist file as `dist/billboard.esm.mjs`. And usually we don't provide patch for older version unless having some severe urgency to do that, so preferably consider moving to latest version.
