### ISSUE TITLE
Setting falsy `type` for data serie renders data serie twice when chart type is set.

### ISSUE THREAD

**Issue by bj00rn** [naver/billboard.js#3125]
## Description

Setting falsy `type` for data serie renders data serie twice when chart type is set.

In C3 data serie type would fall back to `line`

**Billboard behaviour**
![image](https://user-images.githubusercontent.com/10961167/223688898-b6278f05-a968-49a9-b2e8-3fcde0cf60d7.png)

**C3 behaviour**
![image](https://user-images.githubusercontent.com/10961167/223688646-2d4aef50-88ec-492f-a3bf-b0b15c1510a5.png)

## Steps to check or reproduce

```javascript
// for ESM environment, need to import modules as:
// import bb, {bar, spline, line, area, step} from "billboard.js";

var chart = bb.generate({
  data: {
    type: "bar",
    columns: [
	["data1", 30, 20, 50, 40, 60, 50],
	["data2", 200, 130, 90, 240, 130, 220],
    ],
    types: {
      data2: undefined, // "", null
    },
  },
  bindto: "#combinationChart"
});
```

**Comment by netil** [comment]
@bj00rn, thanks for reporting issue.
The way handling for cases specifying falsy value for `data.types` will not behave same way as c3.js case.

When `data.types` has falsy value, then will follow the `data.type` value, which is "parent & general concept" for types.
So, hierarchically will have below relationship.

```
data.type
└-- data.types
```

Following this definition, from the above example, `data2` type will be rendered as `bar`.
