### ISSUE TITLE
highest tick text on rotated y axis is not fully shown

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3136]
## Description
When the axis is rotated, the last tick text on the right side is being cut:
![grafik](https://user-images.githubusercontent.com/42860868/225359597-73cb38fa-d0e3-4472-9de0-b9d552eec9cd.png)

If the axis is not rotated, and there is a very long column name on the x axis, an overflow padding right is being calculated so that the text still can be fully seen:
![grafik](https://user-images.githubusercontent.com/42860868/225360229-6df8dc57-a310-41c6-9180-c0ca70886e61.png)

I would expect that the tick texts on rotated y axis behave the same way to avoid this kind of behaviour.

## Steps to check or reproduce
https://jsfiddle.net/michkami/zhfwneps/
(switch between `axis.rotated: true/false`

**Comment by netil** [comment]
@michkami, i couldn't reproduce the issue.
checkout the demo generating switching axis rotateion.
- https://jsfiddle.net/netil/3n8sdhry/

![Mar-17-2023 15-17-05](https://user-images.githubusercontent.com/2178435/225827528-8bcf4067-89ab-46f3-9be8-9e7b81649906.gif)

**Comment by michkami** [comment]
I meant the last tick on the y axis when rotated=true 
![grafik](https://user-images.githubusercontent.com/42860868/225842907-23f7f70b-9317-42d5-a168-16fda0ace477.png)

It should show "110000000" instead "110000" which is not the case because there is no overflow calculated for rotated y axis as it is for not rotated x axis.

**Comment by netil** [comment]
when calculating the size for x axis(when rotated y axis), the baseline for the dimension is the axis' line, not the tick text.
So, in this case need adjust by giving some space with padding option.
- https://jsfiddle.net/netil/3n8sdhry/8/

**Comment by michkami** [comment]
Oh, now I see what I missed when trying to add the padding. Completely forgot about using "clipPath = false" for the y axis.
Thanks for the quick answer though!
