### ISSUE TITLE
Rotated Chart: Long x-axis label issue

### ISSUE THREAD

**Issue by supriyaKadam1994** [naver/billboard.js#3138]
With Rotated chart, when a-axis labels are long chart is shifting to right side by taking remaining width.
![image](https://user-images.githubusercontent.com/128149819/225918638-514203d0-9389-4bb4-8e1e-c04704b04c4e.png)

Tried with tick.multiline=true property 
this also not usefull
![image](https://user-images.githubusercontent.com/128149819/225918911-360e8695-4f0b-4033-9559-6df6a0c3ea79.png)

to replicate issue,
https://naver.github.io/billboard.js/demo/#Axis.XAxisTickPosition
- increase x-label length

**Comment by netil** [comment]
Hi @supriyaKadam1994, you can adjust with `text-anchor` css property with axis tick text x coordinate.

Checkout the below example
- https://jsfiddle.net/netil/sgm0fqzL/

<img width="826" alt="image" src="https://user-images.githubusercontent.com/2178435/226266788-276eef00-946a-4fd4-9469-7f8e89ae6833.png">

**Comment by netil** [comment]
@SK4492, remove left padding

```
padding: {
	left: 0
}
```

*   https://jsfiddle.net/netil/sgm0fqzL/2/

**Comment by supriyaKadam1994** [comment]
Thank you @netil,
This worked.
