### ISSUE TITLE
BUG `data.labels.format(...)` initially get's called with undefined arguments when rendering chart

### ISSUE THREAD

**Issue by bj00rn** [naver/billboard.js#3148]
## Description

`data.labels.format(...)` initially get's called with undefined arguments when rendering chart

Is there a reason behind this or is this a bug?

![image](https://user-images.githubusercontent.com/10961167/227149807-1ffc89f7-5a54-4a3e-94c6-508aa6678a96.png)

## Steps to check or reproduce

```javascript
// base css
import 'billboard.js/dist/theme/insight.css';
import bb from 'billboard.js';

// for ESM environment, need to import modules as:
// import bb, {area, areaSpline} from "billboard.js";

var chart = bb.generate({
  data: {
    labels: true, // or set specific options,

    labels: {
      format: function (v, id, i, j) {
        console.log('v was: ' + v);
        console.log('id was: ' + id);
        console.log('i was: ' + i);
        console.log('j was: ' + j);

        return v + ' (' + id + ')';
      },
    },
    columns: [
      ['data1', 300, 350, 300, 0, 0, 0],
      ['data2', 130, 100, 140, 200, 150, 50],
    ],
    types: {
      data1: 'area', // for ESM specify as: area()
      data2: 'area-spline', // for ESM specify as: areaSpline()
    },
  },
  bindto: '#areaChart',
});


<!-- Text description or code example (written code / JSFiddle link / etc.) -->

**Comment by netil** [comment]
Hi @bj00rn, isn't a bug. 
Called from below line and it's for to determine label text's width.
https://github.com/naver/billboard.js/blob/master/src/ChartInternal/data/data.ts#L691

When customized format function is set, there's a possibility which text length can be modified according its execution.

**Comment by bj00rn** [comment]
Thanks for the answear! Might be worth mentioning in the docs.
