### ISSUE TITLE
requestIdleCallback override for Safari breaks other libraries

### ISSUE THREAD

**Issue by KenjiTakahashi** [naver/billboard.js#3159]
Especially since it doesn't override the other part: `cancelIdleCallback`.
For example, [this code](https://github.com/KingSora/OverlayScrollbars/blob/fe05099b45ae3b73b1120ff514369fb713b174f1/packages/overlayscrollbars-react/src/useOverlayScrollbars.ts#L42) expects the support to either be there (properly) or not. Which I think is reasonable.

Perhaps consider not messing with the global browser state and have a wrapper instead ;-)?

**Comment by netil** [comment]
Hi @KenjiTakahashi, thanks for the comment.
