### ISSUE TITLE
Y axis ticks truncated when fixed tick values provided

### ISSUE THREAD

**Issue by SK4492** [naver/billboard.js#3170]
Y Axis Tick Texts are truncating for fixed tick values 
top most tick value i.e. 400 has truncated.
![image](https://user-images.githubusercontent.com/85274547/230056631-ebb7b9f6-af16-4562-9cbe-37491fa2c184.png)

Tried by adding axis.tick.count & padding.top but not worked.
I want axis values with these fixed rounded values not randomly generated values.

Code to reproduce:
```js
import "billboard.js/dist/theme/insight.css";
import bb from "billboard.js";

var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 200, 100, 358, 150, 250],
	["data2", 130, 100, 140, 200, 150, 50]
    ],
    type: "bar", 
  },
  axis :{
    y :{
      tick :{
        values : [100,200,300,400]
      }
    }
  },
  bindto: "#barChart_1"
});
```

**Comment by netil** [comment]
Hi @SK4492, give some padding to y axis.

```js
axis :{
  y :{
    padding: {
       top: 50
    }
```

checkout online working demo:
- https://jsfiddle.net/netil/1xuopbwf/

**Comment by SK4492** [comment]
@netil, Thanks for the quick help.
Still top padding not resolving issue.
In above sample code if made any one data item value as 330
![image](https://user-images.githubusercontent.com/85274547/230356389-cf28a3a9-ecf0-4a08-94eb-e0279c06d99e.png)

So padding also need to adjusted with data items and that won't possible with dynamic data right?

**Comment by watnab** [comment]
> Still top padding not resolving issue.

It seems "chart title" can be a workaround if you can use it in your case.
https://naver.github.io/billboard.js/release/latest/doc/Options.html#.title

**Comment by netil** [comment]
@SK4492, the y axis scales according the dataseries values currently shown. If want specify fixed y tick values and the highest data values' range isn't reaching 400(from the option you set), it will scale lower than that.

if only care about truncated text, you can set [padding](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.padding) value. 

```js
padding: {
    top: 5
}
```
- https://jsfiddle.net/netil/1xuopbwf/17/

Try out adjusting axis.y.padding and padding option value to get how they're differently react.

**Comment by SK4492** [comment]
Thank you for the update guys,
@netil , padding won't work for me since data is dynamic and these padding we have to change depends on max data value.

As @watnab has mentioned hidden title works for me.
