### ISSUE TITLE
Hatched bar graph

### ISSUE THREAD

**Issue by maheshrd999** [naver/billboard.js#3174]
## Description
Bar graph design:

I am using billboardjs(for Angular) bar graph to display some analytics. Now my requirement is to show the bars for comparision. One bar should be in dark color and another should be with hatched coloring. Attaching the image of the required graph I want to achieve. 
![image](https://user-images.githubusercontent.com/37367574/230856486-bcb3d15f-3afd-40df-9c2a-c592f937ca3c.png)

Now I am able to achieve the hatched graph but both the bars are hatched. But what I need is one graph should be dark blue and other should be hatched(alternate bar to be hatched) Following is the image of graph what i have achieved now 
![image](https://user-images.githubusercontent.com/37367574/230856601-1be10261-2225-43fc-9c1a-26ffb93ca4f9.png)

Following is the code block I have used.

I only need alternate bar to be hatched. How to achieve. Any suggestions/solutions are of greater help.

```
// base css
import 'billboard.js/dist/theme/insight.css';
import bb from 'billboard.js';
import * as d3 from 'd3';

// for ESM environment, need to import modules as:
// import bb, {areaSpline, bar, bubble} from "billboard.js";
var chart = bb.generate({
  data: {
    json: {
      data1: [15, 23],
    },
    types: {
      data1: 'bar',
    },
  },
  bar: {
    padding: 50,
  },
  color: {
    pattern: ['#002781'],
    tiles: function () {
      var pattern = d3
        .select(document.createElementNS(d3.namespaces.svg, 'pattern'))
        .attr('patternUnits', 'userSpaceOnUse')
        .attr('width', '10')
        .attr('height', '10');

      var g = pattern
        .append('g')
        .attr('fill-rule', 'evenodd')
        .attr('stroke-width', 100)
        .append('g')
        .attr('fill', 'rgb(155, 169, 206)');

      g.append('polygon').attr('points', '6 0 10 0 0 10 0 6');
      g.append('polygon').attr('points', '10 6 10 10 6 10');
      return [pattern.node()];
    },
  },
  bindto: '#colorTiles2',
});
```
`<div id='colorTiles2'></div>`

## Detailed question added in stackoverflow.
https://stackoverflow.com/questions/75884993/billboardjs-hatched-bar-graph

**Comment by netil** [comment]
Hi @maheshrd999 

Specify which index will be applying or not the pattern by [data.color](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4color) option.

```javascript
bb.generate({
  data: {
     ...
     color: function (color, d) {
        return d.index === 0 ? "#002781" : color;
     }
```

checkout the working demo from the stackoverflow's comment.

**Comment by maheshrd999** [comment]
Thanks @netil for quick response.
