### ISSUE TITLE
tooltip.show() not working in all cases

### ISSUE THREAD

**Issue by Patrick-Keenan** [naver/billboard.js#3187]
## Description
I am having a problem where tooltip.show() doesn't always show the tooltip although the proper data is passed per the documentation. Additionally when a user zooms in on the chart the correct tooltip is never shown.

The chart I have made is a connected scatter plot made out of lines that have a start and end x point which have the same y value.

## Steps to check or reproduce
https://jsfiddle.net/j7q8hwfg/
This jsfiddle contains the code to reproduce

I have made a custom plugin that makes additional 'path' elements for each 'path' in order to create an outline for each line to make the chart look better when the lines are close or overlapping.
The plugin also adds a 'mouseover' listener to the parent of each line to programmatically show the tooltip for the corresponding line.
Although I appear to pass the correct data in the tooltip.show function the tooltip doesnt show for every point. See first video

https://user-images.githubusercontent.com/87655487/232877154-e52da41f-0c6b-475d-94b2-e62de5b85020.mov

Additionally when I zoom in on the chart the tooltip almost never shows but when it does it is an entirely different tooltip than what is desired. See second video

https://user-images.githubusercontent.com/87655487/232877591-028b54dc-2d4f-4c0d-83a4-d73771e479a4.mov

**Comment by netil** [comment]
Hi @Patrick-Keenan, thanks for the report.

Found 2 issues, which one is from your generation option, where `point.sensitivity=1` makes harder to trigger  event for `.tooltip.show()`

And the other is a bug, where when `xs` option is used, not reflecting zoom state.

You can check the working example from below screenshot. The only changes was setting `point.sensitivity=2` and fixing the second bug to reflect zoomed status.

![](https://user-images.githubusercontent.com/2178435/235827883-54f48be7-c65f-48b2-a53c-f05c86590b49.gif)
