### ISSUE TITLE
Bug: Hover functionality breaks when loading data containing `xs` without prior `xs` information.

### ISSUE THREAD

**Issue by Tmktahu** [naver/billboard.js#3194]
## Description
For context, in my system I init the graph for display before I receive data from my back end. It takes a few seconds to have the data ready to load into the graph.

The data I am working with requires the use of `xs` to define axis relationships for multiple data sets.

If a graph is initialized without a dummy value for `xs` and then I attempt to load data into the graph that contains `xs` information, the hover functionality and tooltips break.

My best guess for why this happens is that hover/tooltip logic is handled differently for `xs` mode vs 'normal' mode. And if `xs` isn't present when the graph is generated, it defaults to the 'normal' mode and stays that way... despite the graph being set to `xs` mode when new data is loaded in.

## Steps to check or reproduce
1. Create a chart containing points with empty columns. Do not define `xs`.
2. Load in a data set after a delay that includes definitions for `xs` and axis relations.
3. Note that the point hover states and tooltips do not work.

Code example below is an edited version of https://naver.github.io/billboard.js/demo/#Chart.AreaChart
You can paste it in that demo and see the bug.

```js
var chart = bb.generate({
  data: {
    columns: [],
    type: "area",
  },
  bindto: "#areaChart"
});

setTimeout(() => {
  chart.load({
    xs: {
	data: 'dataX'
    },
    columns: [
	["data", 300, 350, 300, 200, 50, 300],
	["dataX", 1, 2, 3, 4, 5, 6],
    ],
  });
}, 5000);
```

Initializing the `xs` value when the chart is generated seems to fix the problem, but then you've got an unused dummy pairing in there which feels messy.

```js
var chart = bb.generate({
  data: {
    xs: {
	dummyUnusedValue: 'dummyUnusedValue2'
    },
    columns: [],
    type: "area",
  },
  bindto: "#areaChart"
});

setTimeout(() => {
  chart.load({
    xs: {
	data: 'dataX'
    },
    columns: [
	["data", 300, 350, 300, 200, 50, 300],
	["dataX", 1, 2, 3, 4, 5, 6],
    ],
  });
}, 5000);
```

**Comment by netil** [comment]
Hi @Tmktahu, thanks for the report.
