### ISSUE TITLE
Question - "Unload" option in instance.load() method maybe not working as intended

### ISSUE THREAD

**Issue by miguelCT** [naver/billboard.js#321]
## Description
I was wondering if the "unload" option in [**instance.load()**](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load) method is working as intended when receiving a *false* value.

I made de assumption that if the "unload" option is set to *false* then the chart would not unload the data before loading the new data. But it seems it's working in the same way it does when the option is set to *true*.

Can you confirm if it's working as intended?
Thank you in advance.

## Steps to check or reproduce
Codepen using the **instance.load()** method with "unload=false"
https://codepen.io/miguelCT/pen/xYNppd/

**Comment by netil** [comment]
Hi @miguelCT, `false` isn't valid for unload option.

The possible values for `unload` are:
- true: It means unload all data before load.
- Array or String: will unload specified data before load.

From API doc:
> Specify the data will be unloaded before loading new data. If true given, all of data will be unloaded. If target ids given as String or Array, specified targets will be unloaded.

**Comment by miguelCT** [comment]
Thanks for the quick answer and the clarification @netil. 

It was just *strange* for me that true is a valid option but false isn't. 
I don't mean that it should be changed, I was just wondering if I understood well the api.

Thanks again.

**Comment by planttheidea** [comment]
I would agree with @miguelCT here, very strange indeed, but also eliminating an implementation convenience because setting / toggling that seeing from true to false is much simpler than setting / toggling from true to removing the property.

Since you don't consider this a bug, would you consider this an enhancement? I can't imagine this code change for this being wild.
