### ISSUE TITLE
graph theme has black background in Firefox

### ISSUE THREAD

**Issue by matwey** [naver/billboard.js#3218]
## Description
Hello, I am using billboard.js 3.8.1 with two different themes: default and graph. I've created a minimal reproducible example mentioned before. My Firefix version is 102.11.

When default theme is used the plot looks like the following:
![изображение](https://github.com/naver/billboard.js/assets/156627/73c4afc6-57c0-46ab-9f4e-aa3fc4ef06ed)

When `graph` theme the plot looks like the following:
![изображение](https://github.com/naver/billboard.js/assets/156627/77db38ac-bbd0-49a8-9169-79aea3cf7282)

`background.color` is ignored in the latter case.

## Steps to check or reproduce
The code snipped is the following:
```javascript
var chart = bb.generate({
    data: {
      type: "line",
      columns: [],
    },
    background: {
        color: "white"
    },
    bindto: "#lineChart"
});

var values = [["x", "y"], [1, 2], [3, 4]];
chart.load({
    rows: values,
});
```

**Comment by netil** [comment]
Tested on Firefox 113.0.1 and it showing without issue.

- https://jsfiddle.net/netil/h3gmp6y2/
<img width="616" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/f78f4725-fe61-4e4a-88a2-7071e186e788">

**Comment by ramirezcgn** [comment]
Hi, I'm having the same issue and I guess is related to this line of the code:

https://github.com/naver/billboard.js/blob/111a5f63133541053800ab3d9608a043731863fc/src/ChartInternal/interactions/eventrect.ts#L14 (line 68)

```
// when initilazed with empty data and data loaded later, need to update eventRect
state.rendered && $$.updateEventRect($el.eventRect, true);
```

Regards

**Comment by netil** [comment]
@ramirezcgn thanks for the comment.
Confirmed the issue and is the side effect caused by #3203
