### ISSUE TITLE
Tooltip scrollbar issue

### ISSUE THREAD

**Issue by SK4492** [naver/billboard.js#3274]
## Description
Not able to do scroll-down for tooltip
Basically when tool-tip content going longer that the parent-graph component height, observed the scrollbar will get visible and mouse-down key will scroll down to saw all tooltip content 
![image](https://github.com/naver/billboard.js/assets/85274547/24d22c29-b8cd-4316-baaa-396d47fc5e86)

Its working in mentioned example but inside my code the scrollbar is visible but not able to scroll-down with mouse-up&down key.
What should I do to work this in my code.

## Steps to check or reproduce
```js
const chart = bb.generate({
		size: {
    	height: 300
    },
    data: {
		columns: [
			["data1", 10, 100, 1000, 2000, 2000, 1000],
			["data2", -100, -10, -2000, -1000, -2000, -1000],
      ["data3", 10, 100, 1000, 2000, 2000, 1000],
			["data4", -100, -10, -2000, -1000, -2000, -1000],
      ["data5", 10, 100, 1000, 2000, 2000, 1000],
			["data6", -100, -10, -2000, -1000, -2000, -1000],
      ["data7", 10, 100, 1000, 2000, 2000, 1000],
			["data8", -100, -10, -2000, -1000, -2000, -1000],
      ["data9", 10, 100, 1000, 2000, 2000, 1000],
			["data10", -100, -10, -2000, -1000, -2000, -1000],
      ["data12", 10, 100, 1000, 2000, 2000, 1000],
			["data13", -100, -10, -2000, -1000, -2000, -1000],
      ["data14", 10, 100, 1000, 2000, 2000, 1000],
			["data15", -100, -10, -2000, -1000, -2000, -1000],
      ["data16", -100, -10, -2000, -1000, -2000, -1000],
      ["data17", 10, 100, 1000, 2000, 2000, 1000],
			["data18", -100, -10, -2000, -1000, -2000, -1000],
      ["data19", 10, 100, 1000, 2000, 2000, 1000],
			["data20", -100, -10, -2000, -1000, -2000, -1000]
		],
    	type: "bar"
	},
});
```

**Comment by watnab** [comment]
It seems:
* mouse wheel-up/down will work.
* page-up/down key won't work. The tooltip will disappear when the key is pressed.

**Comment by watnab** [comment]
I couldn't see what this issue means clearly.

----

By the way, I think it may be good if a feature exists which make the tooltip sticky.

When the feature off:
The tooltip will show/hide automatically when the mouse pointer overs/outs.

When the feature on:
The tooltip will show when the mouse pointer overs.
It will get sticky when the point in the chart is clicked.
It won't hide automatically when it is sticky even if the pointer outs.
It will be released when the same point is re-clicked.
When the other point is clicked the tooltip will move for the point.
