### ISSUE TITLE
Export method doesn't work on Edge browser

### ISSUE THREAD

**Issue by fedegiamporcaro** [naver/billboard.js#328]
Hi,

i have some problems with the export function: it doesn't work with edge browser.
Also the example section (https://naver.github.io/billboard.js/demo/#API.Export), if opened on Edge, returns an error "SCRIPT438: Object doesn't support property or method 'toBlob'".
With Chrome there aren't problems.

My goal is create a PDF (by jsPDF library) with a chart. I would like to export the chart as image and encoding into the PDF. In case, there is an alternative way?
Thanks

**Comment by netil** [comment]
Hi @dongigi92, the `.export()` should be developed more to cover the cross compatibility.
Before that, maybe you can try with other library like:
- https://github.com/tsayen/dom-to-image

**Comment by dongigi92** [comment]
Thanks for the answer @netil 

I started to use dom-to-image, but also it work only on Firefox and Chrome.
Not bad, i wait the future releases....i hope the `.export()` on billboard will be improve.

**Comment by dongigi92** [comment]
Thanks for the answer @netil

I started to use dom-to-image, but works only on Firefox and Chrome too.
Not bad, i wait the future releases....i hope the `.export()` on billboard will be improve.

**Comment by netil** [comment]
Since the MS Edge forked chromium, there's no issue anymore.
