### ISSUE TITLE
Grouped tooltip does not follow mouse pointer in bar charts

### ISSUE THREAD

**Issue by jsynacek** [naver/billboard.js#3291]
## Description
Grouped tooltip does not follow mouse pointer in bar charts. It used to work in `c3`, even though it was only on the y-axis. Is that by design or is that a bug? If it's by design, can there be an additional tooltip option to make the grouped tooltip follow the mouse pointer? It works when `grouped: false`.

## Steps to check or reproduce
Check out the main page for an example: https://naver.github.io/billboard.js/ The bar chart there does exactly what's in the description above.

**Comment by watnab** [comment]
I couldn't see:
> Is that by design or is that a bug?

----

It seems to have something to do with:
https://github.com/naver/billboard.js/blob/249e7bb9cf2bea2be81dce9a96cd28cb70fe0e3b/src/ChartInternal/interactions/eventrect.ts#L448-L453
https://github.com/naver/billboard.js/commit/97df63a38cb1dff5e1b43b1792a4195c2beb9a1f#diff-78484f3c38e5f89fa14e67be54ebe6c3143fb85a07ded5fc89ae6eae99d84d18R381

**Comment by jsynacek** [comment]
Thanks for the quick fix and release! Just to point out the obvious, the grouped tooltip on the project's main page now works:)
