### ISSUE TITLE
Rendering line stroke-width with decimals in "step" and "area-step"

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3295]
## Description
I have a use case where I use a custom line thickness for styling the lines. The values are 0.8, 1.6, 3.2 and 6.4.
In this case the line rendering in type `step` and `area-step` seems to not work properly. If you use rounded values, it seems to render the lines properly. 
The reason for this seems to be the CSS `shape-rendering: crispEdges` that is being set for step type in `updateLine()` in `line.js`.

Would you consider this as correct behavior or as a possible bug? And any idea how to deal with this properly apart from rounding the values?
I found out that this specific code line was already added in c3.js ([Issue](https://github.com/c3js/c3/issues/617)).

EDIT: can probably be referenced to #3222 

## Steps to check or reproduce
https://jsfiddle.net/michkami/q7huLzn5/33/

**Comment by netil** [comment]
Hi @michkami 
> Would you consider this as correct behavior or as a possible bug?
> ... I found out that this specific code line was already added in c3.js (https://github.com/c3js/c3/issues/617).

The behavior followed from the fork.

It seems not happening on Mac OS(but it will on Windows)
![Jul-19-2023 15-13-07](https://github.com/naver/billboard.js/assets/2178435/a9c0e222-050e-4ff9-8478-47ae70dd5ed9)

I'll check if the setting of `shape-rendering:crispEdges` prop for steps can be removed.

**Comment by netil** [comment]
Tried on Windows chrome and with the `shape-rendering:crispEdges`, updating stroke-width's value in decimals, looks weird getting thicker only some parts of the line.
![rendering](https://github.com/naver/billboard.js/assets/2178435/a1732bb4-1f6f-4aa9-a932-eec66f580aaa)

Removing `shape-rendering:crispEdges` works fine.
