### ISSUE TITLE
Tooltip disappears on chart update

### ISSUE THREAD

**Issue by CmShepard** [naver/billboard.js#3305]
## Description
Tooltip disappears on chart load with updated data.

## Steps to check or reproduce
1) Hover on data point
2) Wait for the chart to update
3) Tooltip disappears even if the corresponding datapoint was not changed or updated
https://jsfiddle.net/bqm9skv7/7/

It seems that it is a regression, in the version 3.6.0 the bug was not present.

**Comment by netil** [comment]
Hi @CmShepard, from the example you provided, it seems reasonable maintain tooltip display and update its contents when data is updated.

But, the dynamic data loads not always done maintaining same x Axis values.

For example, when the loaded data can have different x Axis intervals and the current mouse position have to reflect corresponding x Axis updated. And there will be several more cases which need to be handle to make tooltip not disappear.

I'm not sure if this needed to be updated for now. I'll be considering how to handle in this scenario.

Anyway, thanks for the report.

**Comment by CmShepard** [comment]
Hi @netil, thank you for your answer! Sure it makes sense. It would be great to have maybe some sort of boolean flag `keepTooltip`, that would prevent the tooltip from hiding on chart load.

For your understanding, my usecase is the chart with fixed timescale x-axis, where real-time data is updated every second. Tooltip hides even if the "old" value is hovered. That makes tooltip practically unusable in my case.
