### ISSUE TITLE
specifying "low" and "high" in candlestick optional

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3311]
## Description
I was playing around with the Candlestick chart and saw that you must specify the **low** and **high** too. 
In my case I would like to use the Candlestick chart as Waterfall chart, which doesn't show the "sticks" which are drawn by specifying the **low** and **high** values.
Technically you can just use the same values for **open/low** and **close/high** to make it look like a Waterfall chart: 
![grafik](https://github.com/naver/billboard.js/assets/42860868/5af2ffe2-bd6b-4407-a6ee-9ae958b7b104)

The problem here is that in the tooltip the lows and highs are still shown, as it is [hard coded](https://github.com/naver/billboard.js/blob/8d7587026a3ea3a04c2a71254d09111ae6f2197c/src/ChartInternal/internals/tooltip.ts#L205C10-L205C10):
![grafik](https://github.com/naver/billboard.js/assets/42860868/cd21bbe6-b68d-4401-b9d0-87529bbd6800)

That's why it would be nice to make the "low" and "high" also optional.

In addition to this it would be also nice to be able to change the display name for "open", "high", "low", "close" and "volume" in the candlestick config for usage with different languages.

## Steps to check or reproduce
https://jsfiddle.net/michkami/ajyu2v63/

**Comment by netil** [comment]
@michkami 

if you don't need "stick" to be rendered or want to use candlestick as "waterfall" as you mentioned, there's no need to use candlestick. In this case you can use bar type with ranged data.

*   [https://jsfiddle.net/netil/jmpngatb/](https://jsfiddle.net/netil/jmpngatb/)

And also when you need to modify some of the tooltip's content, there's `tooltip.contents` option for that.
