### ISSUE TITLE
onclick does not work as field of data object for bar charts

### ISSUE THREAD

**Issue by therandshow** [naver/billboard.js#3312]
Using onclick as a subfield of data in the configuration object does not work for the simple bar chart example given on the website, see here:
https://jsfiddle.net/therandshow/75vfs28k/

If I use onclick as a top-level field of the configuration object, onclick works, but the arguments provided to the onclick handler make it difficult to use, the first argument is always undefined, the second argument seems to be always 0, and the third argument seems to be the overall SVG object.

https://jsfiddle.net/therandshow/5vkLde7f/

What I would like to be able to do is click on a bar in the bar chart and use that to go to a specific link based on what has been clicked. If I could use an event handler that provided the index of the data used that would be sufficient for my immediate needs.

It's worth noting that this behavior is very different than the documentation describes here:

https://naver.github.io/billboard.js/release/latest/doc/Options.html

**Comment by watnab** [comment]
The code seems to work when I copy it
from https://jsfiddle.net/therandshow/75vfs28k/
to https://naver.github.io/billboard.js/demo/#Chart.BarChart .

**Comment by netil** [comment]
Hi @therandshow, the fiddle provided seems having some issue.  
checkout the example I made, works fine

*   https://jsfiddle.net/netil/uvanybwj/
