### ISSUE TITLE
Subcharts - how to call a function to change the range and get the range?

### ISSUE THREAD

**Issue by Meffesino** [naver/billboard.js#3342]
## Description
I would like to change the range of a subchart. I am aware of the `subchart: { init: { range: [ xxxx, xxxxx]}}`, which is fine. But when I use `chart.load()` to update (and in this case further extends) the chart, I would like to call a function to change the range. I am aware of the `chart.zoom()` function, but this is not working with subcharts...

Is there any possibility to modify the range after generation of the chart by code?
And is there a possibility to get the current range?

**Comment by netil** [comment]
Hi @Meffesino, currently there's no API to control the subchart range. I'll be considering to implement for next release.
Meanwhile, you can use some helper function.

checkout the working demo:
- https://jsfiddle.net/netil/dLy4hm86/

```js
function moveSubchart(chart, range) {
	const {brush, scale: {x}} = chart.internal;
	
	brush.move(
		brush.getSelection(),
		range.map(x)
	);
}

const chart = bb.generate({ ... });

// update the subchart range
moveSubchart(chart, [1,3]);
```
