### ISSUE TITLE
How to vary width of bars instead of whitespace gaps in between?

### ISSUE THREAD

**Issue by JanDW** [naver/billboard.js#335]
## Description
How can I vary the bar width (dependant on number of bars) and have a, say 1px, gap between the bars? 

I googled around for a while but was surprised I couldn't dig up the solution, so I hope it's okay for me to ask here.

## Steps to check or reproduce
N/A

**Comment by netil** [comment]
Do you mean something like each bars has different width and having some gap?

![image](https://user-images.githubusercontent.com/2178435/37552531-b46c0710-29fa-11e8-85f2-faba1f274a46.png)

**Comment by JanDW** [comment]
No, sorry, let me try to clarify. I'm talking about preserving exact spacing between bars (e.g. 1px) and varying the width of the  bars to fill the available space; to accommodate whatever number of data points. Like in the image below. Graphs have same width available, but different number of data points, gap is consistent, bar width varies.

![image](https://user-images.githubusercontent.com/191317/37557150-bb58f17e-29d6-11e8-89ef-70aca01c16f1.png)

Another requirement is for it to be fluid when resizing the browser. E.g. like the image below, the _same graph_ at different widths. It should vary the width of the bars  but preserve the 1px gap:

![image](https://user-images.githubusercontent.com/191317/37557210-b5535516-29d7-11e8-9e79-8a0e1cba7c82.png)

Hope that's clear?

**Comment by netil** [comment]
It'll be good provide as an option.

```js
bar: {
    padding: 1
}
```

**Comment by JanDW** [comment]
Excellent, thanks a lot!

**Comment by netil** [comment]
@JanDW, checkout the new 1.4.0 release.
This was implemented as an option and you can easily set padding between each bars. :smiley:

**Comment by JanDW** [comment]
@netil Great, thank you. Though... what am I missing here: the [padding doesn't seem to come into effect](https://jsbin.com/tudexizoqu/edit?html,js,output).

**Comment by netil** [comment]
well, bar option should declared not within data.

But in your case, the padding isn't effective. `padding` option is for multiple bar elements showed in each x axis value.

**Comment by JanDW** [comment]
Ah okay, [got it](https://jsbin.com/wowazevuse/edit?html,js,output), thanks again. Any reason why you think it shouldn't be set for a single array of bars?

**Comment by JanDW** [comment]
Just [found this](http://d3plus.org/examples/d3plus-plot/bar-chart-padding/) seems like you've implemented `groupPadding` but I was after `barPadding`  :smile:

**Comment by soyeondev** [comment]
@JanDW Can you tell me how you solved it?
I faced the same situation, but the link you posted doesn't work.

**Comment by JanDW** [comment]
@soyeondev Hey—the post is accessible on archive.org 
https://web.archive.org/web/20210730033047/https://d3plus.org/examples/d3plus-plot/bar-chart-padding/
