### ISSUE TITLE
Append new data to chart #question

### ISSUE THREAD

**Issue by patbourgoin** [naver/billboard.js#336]
## Description
Hi,
Is it possible to append new data after the chart was generated?

I found this in the documentation, but nothing about set ou append data.
chart.data("data1");   // Get only data1 data

Thanks,
Patrick

**Comment by netil** [comment]
Hi @patbourgoin.
You can load data using [.load()](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load) method.

Check out the exmple:
- https://naver.github.io/billboard.js/demo/#Data.LoadData
