### ISSUE TITLE
formatting tooltip value for ranged bars

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3371]
## Description
When using ranged bars, the value format function for tooltip gets called 3 times:
1. In the first call the callback receives the value array, ratio, data name and the x axis index:
![grafik](https://github.com/naver/billboard.js/assets/42860868/3581eeec-d2d5-4110-abf2-ec113d937c76)
2. In the second call the callback **only** receives the **start value**:
![grafik](https://github.com/naver/billboard.js/assets/42860868/1d2f763b-9074-4298-b0c2-6295fd5671ab)
3. In the third call the callback **only** receives the **end value**:
![grafik](https://github.com/naver/billboard.js/assets/42860868/f077b6bf-4592-4d17-bdf4-0092712e9ba7)

In my case I use specific value formattings that depend on the additional information that i get in the first call: **data name** and **x axis index**
Is there any specific reason why the additional informations isn't passed to the callback in `internals/tooltip.ts` or can you fix this easily?
![grafik](https://github.com/naver/billboard.js/assets/42860868/b2b6ea77-15f4-464d-8ef4-9dff0ad47418)

In some callbacks the values are specified as `number`, but it doesn't consider using ranged bars where the value can also be an array of numbers:
- `tooltip.format.value`
- `data.labels.format`
- `data.labels.position`
- maybe more types?

Btw. ranged bars work very well for the waterfall chart, thanks for the hint (didn't want to reopen the issue to say thank you ^^)

## Steps to check or reproduce
1. Open https://jsfiddle.net/michkami/mgka1n38/
2. Hover over any bar.
3. Check console: 
![grafik](https://github.com/naver/billboard.js/assets/42860868/881dc0f4-1acd-48e9-9422-bbf47abec5d4)

**Comment by netil** [comment]
@michkami, usually "formatter" function can be called multiple times due to the dimension calculation at the initialization.
There's no way to get the text returned from the formatter without executing it.

BTW, I'll be checking your case. Thanks for the report.

**Comment by netil** [comment]
After reviewing the code, found inconsistency on call of `tooltip.format.value` callback.

> Is there any specific reason why the additional informations isn't passed to the callback in internals/tooltip.ts or can you fix this easily?

As you mention, on that call it should call format function with `id` & `index` value parameters.
To make consistent on value formatter call, will be fixed as:
- formatter function will be called on every value unit.
  - this means, when is ranged data(as the above example), formatter will be called on each value.
  - So when ranged data is array(ex. [100, 250]), formatter will be called twice with each value as `value` parameter for formatter.
  ```js
  // for ranged value: [100, 250]
  tooltip.format.value = function(value, ratio, id, index) {
      // first call with arguments: 100 undefined 'data1' 1
      // second call with arguments: 250 undefined 'data1' 1
     return value;
  }
  ```
  <img width="278" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/bfb17a3c-2f37-4e54-b4a2-8aa2e9a8ee8b">
