### ISSUE TITLE
stacked bar doesn't stack for multiple xs

### ISSUE THREAD

**Issue by mattraydub** [naver/billboard.js#3372]
## Description
Trying to generate a stacked bar chart with multiple xs keys (timeseries). Using the data.group does not stack the bars as it does when there is only one data set for X axes.

Before today, I was on v3.8.2, so I just upgraded to v3.9.3 to see it had been fixed, but the issue exists in both of these versions.

## Steps to check or reproduce
Copied bb.generate logic from a previous comment by @netil at https://github.com/naver/billboard.js/issues/685#issuecomment-444052202, however it does not produce the same chart as shown back then.

```js
bb.generate({
    data: {
        xs: { "Buy": "xBuy", "Sell": "xSell" },
        columns: [
            ["xBuy", "2018-07-05", "2018-07-11"],
            ["xSell","2018-07-02","2018-07-05"],
            ["Buy", 33, 3],
            ["Sell", 7, 33]
        ],
        type: "bar", 
        groups: [[ "Buy", "Sell"]]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%d/%m/%y'
            }
        }
    },
    bar: {
        width: 30
    }
});
```

Generates this chart, where the values on 05/07/18 are on top of each other so one is hidden:

<img width="598" alt="image" src="https://github.com/naver/billboard.js/assets/6732051/ead04293-acf7-4182-9f3a-67274ab28b91">

However, if I tweak the code to use one X dataset, and inject nulls on the multiple Y datasets where data is not present...
```js
bb.generate({
  bindto: `#${element.id}`,
  data: {
    x: "dates",
    columns: [
      ["dates","2018-07-02","2018-07-05", "2018-07-11"],
      ["Buy", null, 33, 3],
      ["Sell", 7, 33, null]
    ],
    type: "bar",
    groups: [[ "Buy", "Sell"]]
  },
  axis: {
    x: {
      type: 'timeseries',
      tick: {
        format: '%d/%m/%y'
      }
    }
  },
  bar: {
    width: 30
  }
});
```
Then I get the chart that I would expect to see below:

<img width="600" alt="image" src="https://github.com/naver/billboard.js/assets/6732051/a3e91d50-175c-443f-a5c2-e45e6925529c">

I've also tried defining the type on the `data.types` object `types: { "Buy": "bar", "Sell": "bar"}`, which also does not work correctly.

**Comment by netil** [comment]
Hi @mattraydub, I'll check the issue. Thanks for the report.

**Comment by netil** [comment]
it started not working since `1.11.0`.
