### ISSUE TITLE
Sortable bar chart

### ISSUE THREAD

**Issue by joao** [naver/billboard.js#338]
Is there a way to sort a bar chart when updating values?
Kind of like this: https://bl.ocks.org/mbostock/3885705
I have built it before in plain D3, but billboard.js as been really great to use in other projects and would like to be able to replicate it.

The load() function works well to load data and update in place, but kind find a way to resort it.
When I try to use my own sort function, when loading data, I have to unload the current data, so I loose the bar chart position.

`chart.load({
    unload: true,
    columns: sortData(data2),
  });
` 

Any idea on how I can just use the load() with new values and then sort them by value, after load?

Demo:
[http://box.wolan.net/billboard_debug_01/](http://box.wolan.net/billboard_debug_01/)
Refreshing after 2500ms with new values, unloading the previous ones

**Comment by netil** [comment]
Hi @joao, sorry to be late on this.

Actually there's no targeted functionality on sorting, but as you mentioned it can be simulated via `.load()`, but you need to unload all before loading new sorted data.

**Comment by joao** [comment]
Hi @netil,

No need to apologize, I'm the one who needs to thank you for all the work you do on this charting library.

I ended up using the method you described, though it doesn't swap in place the x axis order in the chart, needing to unload it. Something like this when loading and then unloading:
`columns: sortData([...])`

That's why I ended up closing the ticket! ;)
Thank you for replying!
