### ISSUE TITLE
Tooltip is broken when `<svg>` is supplied with `viewBox`

### ISSUE THREAD

**Issue by matwey** [naver/billboard.js#3414]
## Description
I am using `billboard.js` 3.9.4 and see the tooltip issue when I create the plot as the following:
```javascript
      var viewbox_chart = bb.generate({
        data: { columns: columns, types: types },
        resize: { auto: false },
        size: { width: 320, height: 240},
        svg: {classname: "img-fluid w-100"},
        bindto: "#viewbox"
      });
      viewbox_chart.$.svg.attr("viewBox", "0 0 320 240");
```

Please note, that I attach `viewBox` attribute to the `<svg>` tag. This is done intentionally to achieve scaling behavior I want.
When `viewBox` is set then the plot is scaled as a whole. Please mind the difference in the example below.
I am not sure if this scenario is supported or not, but everything works fine except the tooltip. The tooltip does not appear at the mouse positions where it should and appears where it should not.

## Steps to check or reproduce
Minimal example: https://jsbin.com/luzohuvita/edit?html,output

**Comment by netil** [comment]
Hi @matwey, the toolip positon's coordinate comes from the mouse event coordinate and it uses [`d3-pointer`](https://github.com/d3/d3-selection/blob/main/README.md#pointer).  
Try using `tooltip.position` option to set different position coordinate in this case.

**Comment by matwey** [comment]
It is still an issue for 3.10.3.

**Comment by matwey** [comment]
The issue is still persists in 3.11.1

**Comment by netil** [comment]
@matwey, would you like contribute fixing this?

**Comment by matwey** [comment]
Just for information, the issue is this there is 3.13.0: https://jsbin.com/wefihonina/1/edit?html

**Comment by netil** [comment]
@matwey, I'll go over it.
