### ISSUE TITLE
Api tooltip.hide gives error

### ISSUE THREAD

**Issue by porfirioribeiro** [naver/billboard.js#343]
## Description
On mobile i want to hide the tooltip when user clicks out of the chart.
So i gave a tab-index of -1 and on blur i call `chart.tooltip.hide()`
But its giving error:
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at ChartInternal.dispatchEvent (billboard.js:5743)
    at Chart.hide (billboard.js:11330)
```

**Comment by netil** [comment]
Hi @porfirioribeiro, could you provide the full option code you've been used?
I need to check if is a bug or something else. Thanks!

**Comment by porfirioribeiro** [comment]
Ok, this is what i have +-
```javascript
this.chart = bb.generate(
        {
          bindto: this.ref,
          axis: {
            x: {
              type: 'timeseries',
              tick: {
                centered: true,
                culling: {
                  max: 5,
                },
                outer: false,
                format: formatDay,
              },
            },
            y: {
              tick: {
                count: 4,
              },
            },
            y2: {
              tick: {
                count: 4,
              },
            },
          },
          grid: {
            y: {
              show: true,
            },
          },
          legend: {
            show: false,
          },
          point: {
            show: this.showPoints,
          },
          tooltip: {
            contents: renderTooltipContainer,
            position: tooltipPosition,
          },
        },
    );
```

**Comment by porfirioribeiro** [comment]
I am updating to the latest version and it seems to be fixed.
I will test more and confirm

**Comment by porfirioribeiro** [comment]
It seems to work, it does not give error with the latest version.
But it does not hide the tooltip on mobile.


![imagem](https://user-images.githubusercontent.com/499246/37901293-b774ccb8-30e8-11e8-9ee9-d827262e70ed.png)

**Comment by netil** [comment]
Tooltip's display APIs are using mouse events, maybe these can be the reason on mobile not working properly. I'll try to improve this for the next release.

For now, you can hide tooltip manually on your event callback doing:

```js
d3.selectAll(".bb-tooltip-container").style("display", "none");
```
