### ISSUE TITLE
`isPointFocusOnly` throws error when not importing scatter from modules

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3456]
## Description
In [3.10.0-next.2](https://github.com/naver/billboard.js/compare/3.10.0-next.1...3.10.0-next.2) `isPointFocusOnly` got implemented in [`point.ts`](https://github.com/naver/billboard.js/commit/787fd153aa8a440be0aa04fca73e8f3f8442a652#diff-7d64ccbaae7b5e9ae25ea32ca3d0591d69ec3904db575adb46b56b76c51adcb0R350) for scatter type. 

This is problematic when importing from modules, because as long as scatter is not imported, it won't import the `isPointFocusOnly`-Function. This function is also used in [`interaction.ts`](https://github.com/naver/billboard.js/commit/787fd153aa8a440be0aa04fca73e8f3f8442a652#diff-a426435dc68ce4590fa0578c8f1e1ff7d1fedf380351a0dd250c2336615fb9a7R107) (which is also called for tooltip for `bar` for example) and this leads to following error:
![grafik](https://github.com/naver/billboard.js/assets/42860868/a433ca75-6c52-4df2-8188-cc65fdd986af)

It doesn't break the chart or anything, but on every hover over the chart it tries to call `isPointFocusOnly()` and throws the error. 

## Steps to check or reproduce
1. Open this [link](https://codesandbox.io/p/sandbox/billboard-bug-report-8nxwzy)
2. Navigate to `src/app/app.component.ts`
3. Hover over the chart --> no error in the console
4. Remove `scatter();` in line 13
5. Hover over the chart --> error in the console

**Comment by netil** [comment]
@michkami, thanks for the report.  
Is a side effect caused by #3407 changes.
