### ISSUE TITLE
Remove instance when .destory() is called

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#347]
## Description

When `.destory()` is called, it should remove the destroyed instance from `bb.instance`.

**Comment by rolandoarteagaram** [comment]
When using the destroy function repeatedly this generates memory leak for example, when it receives new data and apply destroy function every 2 minutes the memory increases above 1 Gb.
@netil could you review that scenario please?

**Comment by netil** [comment]
@rolandoarteagaram, I did a test which looping the generation and destroy continuously.
The memory size is managed reasonably, doing GC(you can check it via chrome devtools - performance monitor tab).

Here is the sample code I made.
- https://jsbin.com/dogokigifu/edit?html,js,output

I know that this can have different result according different situation. If you can provide the 'happening case', would be more easier to figure out the case.
