### ISSUE TITLE
wrong x-coordinate for tooltip when chart has left padding

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3473]
## Description
Using `padding_left` leads to wrong calculation of the x-coordinate for the tooltip when current x position of the mouse + tooltip width is wider than the cahrt.

As you can see in the screenshot below, the tooltip is positioned far too left (the last bar is hovered)
![grafik](https://github.com/naver/billboard.js/assets/42860868/44171cfd-7303-48b7-ac68-2bd37a340f07)

Without padding it is positioned correctly next to the bar.
![grafik](https://github.com/naver/billboard.js/assets/42860868/c62f20af-6e27-46a5-b6c8-24ac55b29b0c)

This seems to happen since #1267 and change in [this line](https://github.com/naver/billboard.js/pull/1268/commits/d4912b2abead81a3f2edbb9ec298e5d42383b6af#diff-8e9d31b6caa40cdae13e97bb349ed578c7746a8df9a7aa2d0e1696aa105784c2R266)

## Steps to check or reproduce
[Link to jsfiddle](https://jsfiddle.net/michkami/dtqa2w64/)

**Comment by netil** [comment]
@michkami confirmed the issue. Thanks for the report.

**Comment by creage** [comment]
@netil This change to `getSvgLeft` function breaks our donut charts tooltips

```
billboard.js:7481 Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at ChartInternal.getSvgLeft (billboard.js:7481:1)
    at ChartInternal.getTooltipPosition (billboard.js:8661:1)
    at ChartInternal.setTooltipPosition (billboard.js:8634:1)
    at ChartInternal.showTooltip (billboard.js:8742:1)
    at selectArc (billboard.js:17708:1)
    at SVGPathElement.eval (billboard.js:17740:1)
    at SVGPathElement.eval (on.js:3:14)
```

because our `$$.config` doesn't have any `axis_y_label` property.

**Comment by netil** [comment]
@creage confirmed the issue. I'll release the patch soon.
