### ISSUE TITLE
Ticks with 0 value get overlaped

### ISSUE THREAD

**Issue by porfirioribeiro** [naver/billboard.js#348]
## Description
I have a chart with fixed tick count (4) but when data has only 0 values the ticks are all in the same position, overlapping.
Also grid lines wont show because they are all stacked at 0

## Steps to check or reproduce
![imagem](https://user-images.githubusercontent.com/499246/37902778-6ce4cf90-30ed-11e8-9905-9dff900a8a68.png)
![imagem](https://user-images.githubusercontent.com/499246/37902877-c5aad098-30ed-11e8-885d-584c5b1eeeae.png)

**Comment by netil** [comment]
You mean the y axis, right? (the 2nd image)
Could you provide the generation code?

**Comment by porfirioribeiro** [comment]
The y2 axis on the first image and the y axis on the second image.
I will try to extract the generation code to send to you.

**Comment by porfirioribeiro** [comment]
You can try this sandbox: https://codesandbox.io/s/wn35kyj9k8

**Comment by netil** [comment]
Set axis max value to fix.
- [axis.y.max](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4max)
- [axis.y2.max](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y2%25E2%2580%25A4max)

```js
y2: {
	show: true,
	label: 'mm',
	default: [0, 100],
	max: 100,
	tick: {
		format: formatInt,
		count: 4,
	},
},
```

Aside of this, the axis tick should be rendered more reasonably than being overlapped.

**Comment by porfirioribeiro** [comment]
It fixes the error but then i loose dynamic range of axis.
Thanks anyway!

**Comment by netil** [comment]
It looks same bug as #387. 

@porfirioribeiro, could you test with the latest nightly build?
- https://github.com/naver/billboard.js/tree/nightly/dist

**Comment by porfirioribeiro** [comment]
Same error

![imagem](https://user-images.githubusercontent.com/499246/40855356-490c5ae8-65cc-11e8-9272-0c55a74a9d4c.png)
