### ISSUE TITLE
Area-spline chart breaks on iPhone with versions 3.10.0 or 3.10.1

### ISSUE THREAD

**Issue by mattxtaz** [naver/billboard.js#3489]
## Description
With 3.9.4 area-spline chart works fine in both Firefox on my desktop and Safari on my iPhone but upgrading to either 3.10.0 or 3.10.1 it only works in Firefox. On iPhone (iOS 17.0.3) the chart div is completely blank. iPhone doesn't have any javascript console though to be able to tell what's broken.

## Steps to check or reproduce
Links to working and broken versions: [3.9.4](https://xtaz.uk/tracks/896) / [3.10.1](https://tao.xtaz.uk/tracks/896) but you'll obviously need an iPhone or possibly a Mac.

**Comment by netil** [comment]
Hi @mattxtaz, thanks for the report.
My main dev environment is on MacOS, but generally using chromium based browsers.
I could reproduce the issue on desktop Safari.

<img width="483" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/c632e191-e6db-45ac-b0ca-8dfcb46255cb">

**Comment by netil** [comment]
@mattxtaz, released the patch `v3.10.2`

**Comment by mattxtaz** [comment]
@netil Yes. Thank you for this quick fix. I can confirm it works fine now.
