### ISSUE TITLE
question:   What is wrong with lines chart?

### ISSUE THREAD

**Issue by Phil353556** [naver/billboard.js#3494]
Hi,
I follow examples on the website: for bar chart, it is realy nice
however for line and multi lines charts, some areas are in black color.
What is wrong?
Thank your for your patience, i'm a newbie there

![image](https://github.com/naver/billboard.js/assets/64729485/2fd85bad-447a-4f2b-98d2-299dee043107)

**Comment by netil** [comment]
@Phil353556, did you included loading basic style file?
```html
 <link rel="stylesheet" href="$YOUR_PATH/billboard.css">
```

**Comment by Phil353556** [comment]
Yes, I made several tests before posting

![image](https://github.com/naver/billboard.js/assets/64729485/2e964e6d-9cea-4711-acb1-3c2a76ac1704)

**Comment by netil** [comment]
@Phil353556, css file must be loaded using `<link>` tag, not from `<script>` tag.

**Comment by Phil353556** [comment]
oups  / thank you / my bad,  the line was not correctly written, not only <link missing but also rel="stylesheet"  href=  ... 
far better, now. 
Thank you for your patience,  I discover billboard.js and will use it now on webpages
![image](https://github.com/naver/billboard.js/assets/64729485/1c3dd7b0-4afa-4836-9f34-b99e54442ce3)
![image](https://github.com/naver/billboard.js/assets/64729485/cf321e4e-c5ba-4150-98b8-ddc23a0e5b64)
