### ISSUE TITLE
Data labels not working on non zerobased bar charts

### ISSUE THREAD

**Issue by filipfloden** [naver/billboard.js#3495]
## Description
When using a bar chart, data labels are not working/supported on bars that are non zerobased, i.e., has a start and end value.
<img width="640" alt="image" src="https://github.com/naver/billboard.js/assets/48211957/a51bbe25-e65a-4e32-b8ed-024b4fc2f4e7">

## Steps to check or reproduce
Turn on labels on a bar chart that has non zerobased values. Example code below.
``` 

var chart = bb.generate({
  data: {
    columns: [
	["data1", [50, 100], [100, 250], 100, 400, 150, 250],
    ],
    type: "bar", 
    labels: {
	format(value, id, index) {
		return value
	}
     }
  },
  bar: {
    width: {
      ratio: 0.5
    }
  },
  bindto: "#barChart_1"
});

```

**Comment by netil** [comment]
@filipfloden thanks for the report.
There's one more issue on this, which what is the label text for those ranged values?
ex. [50, 100] --> 100? or 50~100?

<img width="181" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/99dd16ab-ea45-43fd-96d0-b94dc500610b">

**Comment by filipfloden** [comment]
@netil Since tooltips display it as [50, 100] --> 50~100 I think it's reasonable to show the label in the same way.
If both are possible with an option that would be great but it's not needed.

Thank you for the response.

**Comment by bj00rn** [comment]
@netil IMHO ideally the label format function should be called once with [start, end] to allow for custom format logic. I think this reasoning applies to tooltip format function as well.

**Comment by netil** [comment]
> ideally the label format function should be called once

The fix will not call `data.labels.format` multiple times. 
It will pass array value for ranged values as argument.

```js
data: {
  labels: {
    format(value, id, index) {
         // for ranged data, the `value` is array
    }
  }
}
```
