### ISSUE TITLE
Chart title is not present?

### ISSUE THREAD

**Issue by brandonros** [naver/billboard.js#3496]
## Description

Title is not visually present?

## Steps to check or reproduce

https://jsfiddle.net/rqyvz6nf/

**Comment by Phil353556** [comment]
should this should be added?
<style>
#multilinedTitle .bb-title tspan:first-child { font-size: 17px; font-weight: bold; }
</style>
see https://naver.github.io/billboard.js/demo/#Title.MultilinedTitle

**Comment by brandonros** [comment]
I have my chart options wrong, apologies.
