### ISSUE TITLE
question / request on tooltip template

### ISSUE THREAD

**Issue by Phil353556** [naver/billboard.js#3497]
## Description
Hi I follow what is written there:
https://naver.github.io/billboard.js/demo/#Tooltip.TooltipTemplate
works perfectly
I noticed that if the word "left" is replaced by "right" the display is on the right side  (see the screenshot attached)

However is there a way to get the result displayed in the center of the page?
The word "center" do not make it happen correctly.
Thank you
![Capture d’écran du 2023-10-27 18-15-38](https://github.com/naver/billboard.js/assets/64729485/ab8bd5b4-9b75-4edc-8a61-a7be2cc2489e)

**Comment by netil** [comment]
@Phil353556 the issue is nothing about the functionality of the library.
I made an example, but this are kinda css styling issue, not the library issue.
- https://jsfiddle.net/netil/s5z0havq/
