### ISSUE TITLE
missing x axis tick overflow since 3.10.0

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#3499]
## Description
With the rework of how padding is handled in #3433 the calculation of `xAxisTickTextOverflow` (which got added with #1250) got removed. Because of this overflow is not added to the right padding when `x.axis.tick.autorotate = true` and the text of one of the x axis ticks is longer than the width of the chart.

Before 3.10.0:
![grafik](https://github.com/naver/billboard.js/assets/42860868/6fa4b34d-d52e-4498-bf8e-0d8cd7380452)

After 3.10.0:
![grafik](https://github.com/naver/billboard.js/assets/42860868/0177e990-dc1a-4b59-8342-d0733b023010)

## Steps to check or reproduce
[jsfiddle](https://jsfiddle.net/michkami/z1gf026d/)

**Comment by netil** [comment]
@michkami thanks for the report.
I'll check that.
