### ISSUE TITLE
i want to custom this graph

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [naver/billboard.js#350]
i want to make this graph
![image](https://user-images.githubusercontent.com/30399546/37941366-da7eb17c-31a8-11e8-85ce-2df205af0303.png)

It is a graph according to the flow in time.
for example  data is
```js
[
   [
     {Occurrence time: "09:10,11", Time taken: '2' , count '10'} ,
     {Occurrence time: "09:10,11", Time taken: '4' , count '10'} ,
     {Occurrence time: "09:10,11", Time taken: '10' , count '3'} ,
  ], 
   [
      {Occurrence time: "09:10,12", Time taken: '2' , count '30'} ,
   ],
   [
     {Occurrence time: "09:10,13", Time taken: '2' , count '40'} ,
     {Occurrence time: "09:10,13", Time taken: '6' , count '1'} ,
   ]
]
```
Occurrence time means x asix and time taken means y asix and count means color.
for example if the count > 10, color is red,
if the count <10 , color is blue,
if the count >100, color is purple.,,,

using columns, rows, jsonData...? 
how to mapping this data???
i don't know.. 

안녕하세요~
신입개발자입니다~
실시간으로 그래프를 구현하려고 합니다.
실시간으로 이동하는 부분은 settimeout을 걸어서 구현을 하면 될거 같습니다.
제가 궁금한 점은 바로 데이터를 매핑하는 부분입니다.
위에 데이터를 보시면 배열 - 배열 - object 이런 구조로 되어있습니다.
Occurrence time 은 발생시간으로 x축에 있어야하며 Time taken은 y축에 표시되는 시간입니다. count는 Time taken이 걸린 총 서비스들의 카운트를 의미합니다.
그래서 제가 나타내려는 그래프는 위에 있는 그래프입니다.
예를 들어 10:11시에 2초가 걸린 데이터가 총 10개여서 파란색 표시, 10:12시에 2초가걸린 데이터 총 1개 여서 노란색 표시, 10:12 시에 6초가 걸린 데이터 총 10개여서 빨간색 표시...
그래프 타입은 scatter를 사용하고 같은 x축에 여러개의 점을 찍어야하는 경우가 있습니다.
이런식으로 하고 싶은데 데이터를 어떤식으로 매핑하여야 할지 감이 안잡힙니다...ㅠㅠ 도와주세요...ㅠㅠㅠㅠ

**Comment by netil** [comment]
You need to handle the data separately. I made example according your data example.
But, I think you should find the best way which fits you.

```js
  // given data
  var data = [
	[
  	    { "Occurrence time": "09:10,11", "Time taken": 2, count: '10'},
            { "Occurrence time": "09:10,11", "Time taken": 4, count: '10'},
            { "Occurrence time": "09:10,11", "Time taken": 10, count: '3'}
        ],
        [
            { "Occurrence time": "09:10,12", "Time taken": 2, count: '30'}
        ],
        [
            { "Occurrence time": "09:10,13", "Time taken": 2, count: '40'},
            { "Occurrence time": "09:10,13", "Time taken": 6, count: '1'}
        ]
    ];

    // flattening the array
    data = [].concat.apply([], data);

    bb.generate({
        data: {
            json: data,
            keys: {
	         value: ["Time taken"],
                 x: "Occurrence time"
            },
            color: function(color, d) {
            	if (d && typeof d === "object" && "index" in d) {
		    var count = data[d.index].count;

            	    if (count < 10) {
            			return "red";
                    } else if( count > 100) {
			        return "yellow";
                    } else {
            			return "cyan";
                    }
	        }

            	return color;
            },
            type: "scatter"
        },
        axis: {
	    x: {
	        type: "category"
	    }
        }
    });
```

This will render as
![image](https://user-images.githubusercontent.com/2178435/37950587-11479914-31d4-11e8-922f-66f822c76ea5.png)

**Comment by juuuuuuuuuuuuuu** [comment]
i will consult your advice!!   oh thank you 👍  :)

**Comment by juuuuuuuuuuuuuu** [comment]
i want flow api.
 setTimeout(function() {
            chart.flow({
                json: [
                    [{"Occurrence time": "09:10,14", "Time taken": 2, count: '30'}],
                ],
                  keys: {
                    value: ["Time taken"],
                    x: "Occurrence time"
                },
            });
        }, 1000);

but error:  Uncaught TypeError: Cannot read property 'count' of undefined ..
how to using flow in this case??
