### ISSUE TITLE
[Question] Can the y axis be set on a range?

### ISSUE THREAD

**Issue by TheTimKiely** [naver/billboard.js#3518]
I've done some digging, but I haven't found how to set the y axis on a region.  
I have a time series dataset with some boolean data points that I'd like to display as regions.  If values overlap on the x axis, the chart gets difficult to read.  
I'd like to "stack" the different datapoint on the y axis, so that they don't overlap. 

Is this in anyway possible with billboard.js?  Could I set a region's y values in a callback?

Thanks

**Comment by netil** [comment]
Hi @TheTimKiely, could you provide some visual example to get more undestanding about it?

**Comment by TheTimKiely** [comment]
I was thinking of something like this:
![chart_with_regions](https://github.com/naver/billboard.js/assets/34795732/792863c2-8fd0-495c-bcee-40cb779996bb)

The green and blue rectangles at the bottom would be regions that have y values of something like 0-10 and 10-20.  This way I could "stack" different boolean data points without them obscuring each other.  Since the data points are boolean, the y value is not significant so it can be used for layout.

Another approach that occurs to me is adding a secondary chart with the same x axis.  Something like what matplotlib supports with subplots:

![matplotlib_subplots](https://github.com/naver/billboard.js/assets/34795732/c02e8a31-1199-48fa-8e67-5a32cabc199d)

Does that make sense?
Thanks again!

**Comment by netil** [comment]
@TheTimKiely, it can't be implemented by one instance.
For not to achieve this, it needs generate multiple chart instances as you need to stack

https://jsfiddle.net/netil/k2eaLs7q/

**Comment by TheTimKiely** [comment]
Thanks.  And is setting the 'y' axis values on a range not an option?
-Tim

**Comment by netil** [comment]
> And is setting the 'y' axis values on a range not an option?

It means the way to not set y axis value range as below?

```js
axis: {
  y: {
    tick: {
      values: [-1, 0, 1]
    }
  }
}
```

If so, you can, but the y axis value will show the range of data range bound.
<img width="75" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/b6ae5feb-de30-4286-86d2-f3080490297a">

If your data's range are `-1 ~ 1`, it's better specifying y tick values to simplify readability.
