### ISSUE TITLE
[@billboard.js/react] Fail to build with TypeScript using "moduleResolution: bundler"

### ISSUE THREAD

**Issue by nekoya** [naver/billboard.js#3540]
## Description

Setting "moduleResolution": "bundler" in tsconfig.json results in the following TypeScript error.

>path/to/Component.tsx:XX:XX - error TS7016: Could not find a declaration file for module '@billboard.js/react'. '/path/to/node_modules/@billboard.js/react/dist/billboardjs-react.js' implicitly has an 'any' type.
>  There are types at '/path/to/node_modules/@billboard.js/react/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@billboard.js/react' library may need to update its package.json or typings.

## Steps to check or reproduce

At the project use TypeScript, set `moduleResolution` in tsconfig.json.

```
"moduleResolution": "bundler",
```

Build the project like this (depending on your environment):

```
yarn tsc --noemit --project .
```

Then, an error similar to above occurs.

**Comment by netil** [comment]
published [`@billboard.js/react v1.1.1`](https://www.npmjs.com/package/@billboard.js/react/v/1.1.1)
