### ISSUE TITLE
Add a way to control X axis width in rotated mode

### ISSUE THREAD

**Issue by m-gallesio** [naver/billboard.js#3550]
## Description
There does not seem to be a way to control the **width** of the X axis when the `rotated` flag is set to true. This is important when using long category labels.
The equivalent in non-rotated mode should be `axis.x.height` which does work, but has no apparent effect in rotated mode.

## Steps to check or reproduce
![immagine](https://github.com/naver/billboard.js/assets/46478501/d388a124-e402-41ca-b797-8037c7634275)
```typescript
import "billboard.js/dist/billboard.css";
import bb from "billboard.js";

bb.generate({
  data: {
    x: "x",
    columns: [
	["x", "Some long category text which will be wrapped", "Some other very long category text", "Yet another long category name", "Again, a long category name"],
	["One", 30, 200, 100, 400],
	["Two", 90, 100, 140, 200]
    ],
    type: "bar",
  },
  axis: {
    rotated: true,
    x: {
      height: 100,
      type: "category"
    }
  },
  padding: {
    left: 200,
  },
  bindto: "#categoryData"
});
```

**Comment by m-gallesio** [comment]
The problem with `padding` is that the free space is not optimized. I added it in the sample code to show how narrow the actually allocated space is.
In our actual use case the (customer-provided) labels can be even longer than those I gave as samples, so just disabling `multiline` would not solve all cases.

**Comment by netil** [comment]
how about setting as `padding.mode='fit'`?
Setting as is, will make chart elements to fully occupy the container. If needs add some space, can adjust by giving `padding.left` value and in this case the value will be applied relative from the initial(mode='fit') state.

- https://jsfiddle.net/netil/k2eaLs7q/

**Comment by m-gallesio** [comment]
It does not really solve the underlying problem, which is an unbalancedly small space for the label
Another approach I tried is using combining `multiline` with *manual* `\n`s instead of relying on the library to split the text, but `multiline` just ignores them.

**Comment by netil** [comment]
@m-gallesio, maybe there's misunderstanding on this.
As the issue title "way to control X axis width in rotated mode", 

<img width="373" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/940c04a6-a4ca-4f82-91cf-05c6ce52ae34">

if some option `axis.x.width` is provide, and assume setting width of x axis as below
<img width="368" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/937fb3b6-ce8f-4f69-a3cc-72a077cef9a5">

I don't get any visual difference on giving left padding. 
<img width="274" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/395bc19a-32d6-4b33-a388-0041125ae7cf">

Can you provide a visual description? What is the usability for `axis.x.width` option?

**Comment by m-gallesio** [comment]
Making sure the text fills as much as the allocated space as possible:
![billboard_category_axis](https://github.com/naver/billboard.js/assets/46478501/d523a94e-f274-4e7c-a717-22a62f7bb4a8)

**Comment by netil** [comment]
@m-gallesio, for that reason you can use [axis.x.tick.width](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4width) option.

- https://jsfiddle.net/6gbt4syx/2/

**Comment by m-gallesio** [comment]
It works, thank you for your attention and sorry for the late response.
