### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by TheTimKiely** [naver/billboard.js#3554]
After following the steps on the development page, DEVELOPMENT.md, I'm unable to run the tests.
It looks like there's a problem with the path to the 'browser' module.
The error indicates that webpack is looking in a non-existent directory: "billboard.js\\test\\src\\module\\browser doesn't exist".  But the browser module exists in the 'assets' directory under test - 'billboard.js\\test\\assets\\module\\browser'.

Sorry if this is a noobie question, I'm pretty new to JavaScript and webpack.  How do I correct this?

I tried editing the karma.conf.cjs file('test: require.resolve("./src/module/browser.ts"),' to 'test: require.resolve("./assets/module/browser.ts"),'), but that causes an error too.

Error:
```
Webpack starts watching...
[
  {
    moduleIdentifier: 'C:\\code\\tools\\billboard.js\\node_modules\\babel-loader\\lib\\index.js!C:\\code\\tools\\billboard.js\\test\\assets\\module\\util.ts',
    moduleName: './test/assets/module/util.ts',
    loc: '7:0-50',
    message: "Module not found: Error: Can't resolve '../../src/module/browser' in 'C:\\code\\tools\\billboard.js\\test\\assets\\module'",
    moduleId: './test/assets/module/util.ts',
    moduleTrace: [ [Object] ],
    details: "resolve '../../src/module/browser' in 'C:\\code\\tools\\billboard.js\\test\\assets\\module'\n" +
      '  using description file: C:\\code\\tools\\billboard.js\\package.json (relative path: ./test/assets/module)\n' +
      "    Field 'browser' doesn't contain a valid alias configuration\n" +
      '    using description file: C:\\code\\tools\\billboard.js\\package.json (relative path: ./test/src/module/browser)\n' +
      '      no extension\n' +
      "        Field 'browser' doesn't contain a valid alias configuration\n" +
      "        C:\\code\\tools\\billboard.js\\test\\src\\module\\browser doesn't exist\n" +
      '      .ts\n' +
      "        Field 'browser' doesn't contain a valid alias configuration\n" +
      "        C:\\code\\tools\\billboard.js\\test\\src\\module\\browser.ts doesn't exist\n" +
      '      .js\n' +
      "        Field 'browser' doesn't contain a valid alias configuration\n" +
      "        C:\\code\\tools\\billboard.js\\test\\src\\module\\browser.js doesn't exist\n" +
      '      as directory\n' +
      "        C:\\code\\tools\\billboard.js\\test\\src\\module\\browser doesn't exist",
```

**Comment by netil** [comment]
@TheTimKiely confirmed the issue. Thanks for the report.
it happens on windows environment only.

**Comment by TheTimKiely** [comment]
@netil Yes, I'm seeing it on Windows 11.  I'm using the master branch.  I'll try other branches.  I'll be able to try on Linux tomorrow.  I'll let you know what I see as soon as possible.
Thanks.

**Comment by netil** [comment]
@TheTimKiely fixed module import path.
Tested on Node v18 ~ v20(not working on Node 21, due to the other dependency module issue).
Also it has some tests errors due to test environment issue, which can ignore for now.

**Comment by TheTimKiely** [comment]
@netil That did it!  Thank you!
