### ISSUE TITLE
Question: How can I hide the default first and last ticks on a chart

### ISSUE THREAD

**Issue by Bobakanoosh** [naver/billboard.js#3562]
## Description
Every graph has these extra ticks at the start and end of each axes. Is there an option to remove these? I notice they are built into the svg and there isn't a class or anything similar I could override.

![image](https://github.com/naver/billboard.js/assets/10647192/5fddfa6c-173c-445f-981c-87ba6e823328)

## Steps to check or reproduce
Just any line chart, even the example ones

**Comment by netil** [comment]
@Bobakanoosh, each axes has `tick.outer` option to control that. (ex. [axis.x.tick.outer](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4outer))
Setting `false` will hide outer ticks.
```js
axis: {
   y: {
    tick: {
      outer: false
    }
   }
}
```

**Comment by Bobakanoosh** [comment]
Thank you!!
