### ISSUE TITLE
Feature request: Rounded corners for bar chart

### ISSUE THREAD

**Issue by ivarkallejarv** [naver/billboard.js#359]
What the title says. C3 didn't have rounded corners, except someone's custom solution [here](http://jsfiddle.net/5hzxegxx/2/).
So would like to know, if this is planned for billboard or what it would take to have it implemented?

**Comment by netil** [comment]
Hi @ivarkallejarv, it looks useful to be implemented.

**Comment by netil** [comment]
Hi @ivarkallejarv, the feature you requested was implemented and will be out on the next release.

Meanwhile, you can use via nightly build: 
- https://github.com/naver/billboard.js/tree/nightly/dist

Checkout #476 for the option interface.

**Comment by ivarkallejarv** [comment]
Hey, @netil, thank you, this is great news. This is the biggest incentive for me to migrate to bb from c3.  👍
