### ISSUE TITLE
Get the SVG bounding box as viewbox attribute

### ISSUE THREAD

**Issue by NeomMob** [naver/billboard.js#361]
## Description
In order to have a graph scaling nicely (and to avoid using resize) I would like to know the bounding box of the SVG and get it as viewBox attribute.

How can I achieve this ?

Thanks

**Comment by netil** [comment]
Hi @NeomMob, the initial viewBox is equivalent as the width and height attributes values.
For example, if the chart has width=300 and height=200, the viewBox is `viewBox=0 0 300 200`.

```js
var chart = bb.generate( ... );

var svg = d3.select("#chart svg");
svg.attr("width");  // will return 300
svg.attr("height");  // will return 200
```

If you need change, simply set viewBox attribute to `<svg>` element

**Comment by NeomMob** [comment]
@netil Thanks for your answer, there are case (especially for Donut and Pie) where I am expecting a boundingBox smaller than the 300x200 of your example: : 
- 300x200 are the red area when the real bounding box is actual bounding box is the one in blue
![spring_sld](https://user-images.githubusercontent.com/326762/38456841-30fbe054-3a89-11e8-810b-e3f0c1b68244.png)

Any pointer go get the blue one?

Thanks for your help,

**Comment by netil** [comment]
Try this

```js
var bounding = d3.select(".bb-chart-arcs").node().getBBox();
bounding.width;
bounding.height;
```

**Comment by NeomMob** [comment]
It works fine, thanks a lot for your support.
