### ISSUE TITLE
[Question] Add label to single point

### ISSUE THREAD

**Issue by TheTimKiely** [naver/billboard.js#3616]
Is it possible to add a text label to a single data point?
I've tried using the 'onmax' callback to add text using d3 ('d3.select(".bb-chart-texts");'), but if I haven't turned on labels in the chart config, there is no 'chart-texts' node in the svg.
Is this possible?  Something like OptionalXGridLines would be great.
Thanks!

**Comment by michkami** [comment]
Hi,
Do you mean normal data labels like this: https://jsfiddle.net/michkami/qg18nLvd/
Or can you provide a code example of what you are trying to achieve?

**Comment by TheTimKiely** [comment]
Thanks!  That's what I was looking for.  I wasn't clever enough to think of adding text during formatting;-)
