### ISSUE TITLE
Point hiding not working with line chart and bubble chart combination. 

### ISSUE THREAD

**Issue by flickz** [naver/billboard.js#3624]
## Description
I'd like to hide the points but `point.show = false` doesn't seem to work with this chart's combinations.  Any idea how to fix this? 

<img width="1196" alt="Screenshot 2023-09-24 at 23 08 04" src="https://github.com/naver/billboard.js/assets/15707013/7f056b90-a91a-4d4d-be75-6e6035d92170">

**Comment by netil** [comment]
Hi @flickz, did you set `point.show` option below the line option?
```js
  line: {
    point: {
      show: false
    }
  }
```

Here's an combination example, which bubble is showing and line & area data points are hidden.
- https://jsfiddle.net/netil/n148rk95/1/

**Comment by flickz** [comment]
Thanks, @netil I did not use it within the `line` object. I'll close the issue now.
