### ISSUE TITLE
[question] How to set the font size of axis tick labels and axis labels?

### ISSUE THREAD

**Issue by lasseaeggen** [naver/billboard.js#3625]
## Description
When setting the `font-size` with CSS the text is rendered at the given size.
However, the calculations to avoid overlapping is not accounting for this size setting so that we get overlapping text, text that goes outside the SVG viewport, etc.
E.g. culling, rotation, etc. works for the normal font size and to some degree the 

How do we set a font size that the tool will pick up on and take into account when rendering the charts?

## Steps to check or reproduce
```
.bb svg, .bb text {
    font-size: 32px;
}
```

**Comment by netil** [comment]
As you already mentioned, the size of 1 character is taken from `.bb text` selector element
- https://github.com/naver/billboard.js/blob/master/src/ChartInternal/Axis/AxisRendererHelper.ts#L37

And will be rendered as below:
<img width="762" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/7ec8cb41-3d4e-4ff1-84b6-d81170fb8850">
- checkout fiddle: https://jsfiddle.net/netil/n148rk95/3/
