### ISSUE TITLE
Question: How to remove the tooltip of the graph type set in Types and how do I label the graph without being visually visible?

### ISSUE THREAD

**Issue by yunhyuck** [naver/billboard.js#3626]
## Description
I can only see the label in Total designated as types, and I want to delete other tooltips or graphs, is there a way?

<img width="1227" alt="image" src="https://github.com/naver/billboard.js/assets/39765493/783eccdb-af69-4c7e-ae64-678fdf3b6e97">

## Steps to check or reproduce
```script
chartProductOpt1.value = {
  legend: {
    show: false,
  },
  size: {
    height: 180,
  },
  padding: {
    bottom: 30,
  },
  data: {
    x: "x",
    columns: columns,
    groups: [
      groups
    ],
    type: "bar",
    types: {
      "Total": "line",
    },
    labels: {
      colors: "black",
      centered: true,
      position: {
        Total: {
          y:-1,
        }
      },
      format: 
        function(x:any) {
          if( x == 0 || x == 1) {
            return '';
          } else {
            return x + " 건"; 
          }
        }
    }
  },
  axis: {
    x: {
      type: "category",
    },
    y: {
      padding: {
        top: 0,
      },
      max: maxY,
      tick: {
      
        count: 5,
        format: function (x: any) {
          return x + " 건";
        }
      },

    },
    
  },
  bar: {
    width: {
      ratio: 0.7,
    },
  }
}

```

**Comment by netil** [comment]
Hi @yunhyuck,
> I can only see the label in Total designated as types, and I want to delete other tooltips or graphs, is there a way?

I'm not sure if understood correctly, you want to display on tooltip only when value is greater than zero, right?
If so, you can customize tooltip base on your needs using `tooltip.contents` option.

checkout the example, which zero value will be excluded from the tooltip.
- https://jsfiddle.net/netil/ebwomLzc/1/

**Comment by yunhyuck** [comment]
@netil Hi ! 
Thanks..! 

By any chance, can you set the columns designated as types to be invisible?

**Comment by netil** [comment]
@yunhyuck, just define style rule for `Total` dataserie as below.

```css
.bb-target-Total {
  display: none;
}
```
- Working demo: https://jsfiddle.net/netil/ebwomLzc/6/
