### ISSUE TITLE
How to modify the color indicated on the screenshot [ Question ]

### ISSUE THREAD

**Issue by Phil353556** [naver/billboard.js#3646]
Hi,
Using the latest version
How to modify the color of the text indicated on the screenshot? 
Thank you so much
kind regards
![question](https://github.com/naver/billboard.js/assets/64729485/84893d25-df42-4627-b3c7-6a1faaa530ac)

**Comment by netil** [comment]
@Phil353556, from the example tooltip element has id value of "tooltip".
You can easily manipulate styles by adding styles properties against it.

```css
#tooltip { color: blue; ... }
```

checkout the demo:
- https://jsfiddle.net/netil/6g0zour9/

**Comment by Phil353556** [comment]
Hi, Thank you, it works perfectly.
May be three caracters  siz   not needed  on this webpage?
 I deleted them and it is ok
Thank you again
![image](https://github.com/naver/billboard.js/assets/64729485/6d8a6c0a-65db-4397-8e3c-e5a47f29a603)
