### ISSUE TITLE
Custom point in legend does not display if chart type is Donut

### ISSUE THREAD

**Issue by jarrod-cummings** [naver/billboard.js#3653]
## Description
I'm trying to use a custom symbol, like a rounded square, in the legend for a donut chart that I'm creating. I've been trying to do this through a combination of the legend.usePoint and point.pattern settings. However, I've found that while custom symbol will show up in the legend as expected if the chart type is line, if I switch the chart type to donut it no longer displays.

## Steps to check or reproduce

```
var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 100, 200, 100, 250, 150],
	
    ],
    type: "line",  // Switch this to donut and the symbol won't display in the legend
  },
  point: {
    pattern: [
      '<rect width="15" height="15" rx="5" ry="5" ></rect>',
    ]
  },
  legend: {
    usePoint: true,
    position: 'inset'
  },
  bindto: "#usePoint"
});
```
<img width="542" alt="Screenshot 2024-02-19 at 5 38 59 PM" src="https://github.com/naver/billboard.js/assets/122934542/323a28a8-da96-4e2a-8b8a-7de54cb6569e">
<img width="515" alt="Screenshot 2024-02-19 at 5 39 11 PM" src="https://github.com/naver/billboard.js/assets/122934542/7babcd0f-ebe6-4319-87a4-020d5eaec072">

I inspected the html for the chart and I found that the symbols in the legend are set with a <use> tag that has an href pointing to the symbol which exists somewhere else in the page. When I inspected the html with the chart type set to donut, the href is still there, but the element it is referencing does not seem to exist.
Line chart html:
<img width="879" alt="Screenshot 2024-02-19 at 5 46 58 PM" src="https://github.com/naver/billboard.js/assets/122934542/f8d18a02-9364-4f29-be9b-afef7f1f4dac">
<img width="884" alt="Screenshot 2024-02-19 at 5 47 08 PM" src="https://github.com/naver/billboard.js/assets/122934542/3635444e-b9b9-428c-bd9b-bcc606e21ea1">

Donut chart html
<img width="830" alt="Screenshot 2024-02-19 at 5 46 24 PM" src="https://github.com/naver/billboard.js/assets/122934542/59c1f62f-2267-41e7-bd7d-6487de71ae0d">

**Comment by netil** [comment]
Hi @jarrod-cummings, basically `custom point` defined via `point.pattern` is an option dedicated to be used for axis based charts. It doesn't work on Arc based chart for that reason.

Let me consider if this approach is generally useful or not.
