### ISSUE TITLE
🐛 TypeError: $$.getZoomTransform() is not a function

### ISSUE THREAD

**Issue by blackjak231** [naver/billboard.js#3657]
## Description
In the latest fix release 3.11.1, there is a type error which causes the chart to not generate. 

Seems related to the following commit in zoom.ts and shape.ts : [170d836](https://github.com/naver/billboard.js/commit/170d836f374e08fd7d33be91892da39debde201a)

## Steps to check or reproduce
Try to initiate any chart with billboard 3.11.1

![Capture d’écran 2024-02-22 à 16 54 52](https://github.com/naver/billboard.js/assets/1529214/dda82752-61ed-487c-b723-89ad08a971cc)

**Comment by netil** [comment]
Hi @blackjak231, thanks for the reprot.
Is a side effect of #3647. I'll be releasing the patch soon.

**Comment by netil** [comment]
Already fixed from https://github.com/naver/billboard.js/pull/3656/files#diff-0255833099492949447c5a8b30480196007240511238d25f9ad9d027877d4014R428
