### ISSUE TITLE
legend: Legend tooltip ignores data.names

### ISSUE THREAD

**Issue by adschmu** [naver/billboard.js#3662]
## Description
When using data.names to provide friendly names for the data columns, the legend will use the long name in the format method properly, but the tooltip will only show the "identifier" (i.e. the key in the data.names dictionary.

## Steps to check or reproduce

```
bb.generate({
  data: {
    names: {"data": "Detailed Name"},
    columns: [
      ["data", 91.4]
    ],
    type: "gauge"
  },
  interaction: {
    enabled: false
  },
  gauge: {
    expand: false,
    type: 'multi', // multi-mode is more flexible, even for single data value
    label: {
      format: function () { return ""; }
    }
  },
  legend: {
      format: function (id) {
          return id.substr(0, 2) + "...";
      },
      tooltip: true
  }
});
```

This will properly convert "Detailed Name" to "De..." in the legend, but the tooltip will show "data".

https://jsfiddle.net/adrianschmutzler/shgx7otj/6/

**Comment by adschmu** [comment]
Related feature request:

Though not necessary to fix the issue above, one could provide both the identifier (key in data.names) and the friendly name (value in data.names) as arguments in the legend.format function. If data.names is not used in the config, both arguments could just contain the same value.

**Comment by netil** [comment]
Hi @adschmu, thanks for the report.

**Comment by adschmu** [comment]
Thanks, tested with the latest nightly and can confirm the fix.
