### ISSUE TITLE
Is there any way to create two combined charts which share a single x-axis?

### ISSUE THREAD

**Issue by njh7799** [naver/billboard.js#3683]
## Description

Is there any way to create two combined charts which share a single x-axis like graph below?
(candle chart + bar chart)

<img width="755" alt="스크린샷 2024-03-07 오후 3 17 31" src="https://github.com/naver/billboard.js/assets/40619551/5d5b43db-a3c7-4ab3-b0c7-15f21794c665">

## Steps to check or reproduce

example link: https://m.stock.naver.com/domestic/stock/006400/total

**Comment by netil** [comment]
Hi @njh7799, for now this can be achieved with some customization.
Using subchart option and hiding & displaying the chart type in main chart area and subchart area.

Checkout the below working example:
- https://jsfiddle.net/netil/a1snqrLd/

<img width="550" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/82a8503e-0278-4873-ac07-3dec51aa0011">
