### ISSUE TITLE
Scatter Plot points not displaying when loaded into chart in some cases

### ISSUE THREAD

**Issue by jarrod-cummings** [naver/billboard.js#3740]
## Description
I have a combination chart in which I am displaying data for several lines and a scatter plot, and the contents of the chart can be updated dynamically based on filtering from a user. I've been running into some odd behavior where if when the chart is initially generated there is no data loaded for the scatter plot, the points for the scatter plot will not display even if data is loaded in later.  It looks like when this happens, the bb-charts-circles container where the scatter plot points would normally be does not exist. Here's a minimal example:
 
## Steps to check or reproduce
```
var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 20, 50, 40, 60, 50],
	["data2"]
    ],
    type: "line", 
    types: {
      data2: "scatter", 
    },
  },
  bindto: "#scatterPlot"
});

setTimeout(function() {
	chart.load({
		columns: [
			["data2", 200, 130, 90, 240, 130, 220],
		]
	});
}, 3000);
```
![Screenshot 2024-04-17 at 4 13 31 PM](https://github.com/naver/billboard.js/assets/122934542/260f4589-24de-42fd-a241-69f9f009d720)
<img width="806" alt="Screenshot 2024-04-17 at 4 20 05 PM" src="https://github.com/naver/billboard.js/assets/122934542/a79c8b1b-df15-434c-8de3-24670be79154">

If there is some data when the chart is first generated, then the scatter plot will display when loaded in
```


var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 20, 50, 40, 60, 50],
	["data2", 1]
    ],
    type: "line",
    types: {
      data2: "scatter",
    },
  },
  bindto: "#scatterPlot"
});

setTimeout(function() {
	chart.load({
		columns: [
			["data2", 200, 130, 90, 240, 130, 220],
		]
	});
}, 3000);

```
![Screenshot 2024-04-17 at 4 16 52 PM](https://github.com/naver/billboard.js/assets/122934542/2086ea92-6aee-429e-8f87-1d982d740a49)
<img width="808" alt="Screenshot 2024-04-17 at 4 19 31 PM" src="https://github.com/naver/billboard.js/assets/122934542/b3dc208b-ade4-445e-b58b-06682227ae2b">

**Comment by netil** [comment]
Hi @jarrod-cummings, confirmed the issue.
I'll look for it. Thanks!
