### ISSUE TITLE
Treemap error while building chart

### ISSUE THREAD

**Issue by Patrick-Keenan** [naver/billboard.js#3777]
## Description
I get this same error when trying to create a treemap myself. I figured it was a problem with my setup but when going into the editor on the demo site I get the same error.

<img width="1374" alt="Screenshot 2024-05-22 at 2 19 20 PM" src="https://github.com/naver/billboard.js/assets/87655487/ed1c014c-670f-4d90-ba88-e268302504ef">

## Steps to check or reproduce
1. Go to the treemap demo
https://naver.github.io/billboard.js/demo/#Chart.TreemapChart

2. Open up the code editor and click the preview tab

**Comment by netil** [comment]
Hi @Patrick-Keenan thanks for the report.
