### ISSUE TITLE
Stacked barchart changes the order of the groups after resize the browser

### ISSUE THREAD

**Issue by ChoeYoonSeop** [naver/billboard.js#379]
## Description

Stacked barchart changes the order of the groups after resize the browser

## Steps to check or reproduce

https://codepen.io/choeyoonseop/pen/mxYpON

before
![image](https://user-images.githubusercontent.com/10969212/38727517-2d8cae44-3f48-11e8-896d-e957d9e78cd7.png)

open the tooltip once, then resize the browser
![image](https://user-images.githubusercontent.com/10969212/38727556-4d9a6b72-3f48-11e8-86f7-60d4ef117744.png)

group order changed (data1, data2 -> data2, data1)

**Comment by netil** [comment]
Hi @ChoeYoonSeop, thanks for reporting.
Once the tooltip appeared, and doing resize the legend's position changes.

I'll look for that.
