### ISSUE TITLE
Remove unused wheel listener

### ISSUE THREAD

**Issue by szendezsombor** [naver/billboard.js#3791]
## Description
`src/ChartInternal/interactions/zoom.ts`
```ts
		// Since Chrome 89, wheel zoom not works properly
		// Applying the workaround: https://github.com/d3/d3-zoom/issues/231#issuecomment-802305692
		$$.$el.svg.on("wheel", () => {});
```
This is resolved issue by the browser, can't be removed? 
(https://github.com/d3/d3-zoom/issues/231#issuecomment-819604071)

This cause warnings when zoom enabled:
<img width="776" alt="image" src="https://github.com/naver/billboard.js/assets/42742129/f0dee729-c2f6-4d2c-8945-4b943d49de9e">

## Steps to check or reproduce
Create a chart with a zoom enabled, and it will show up.
[example](https://naver.github.io/billboard.js/demo/#Interaction.Zoom)

**Comment by netil** [comment]
Hi @szendezsombor, thanks for sharing. I'll go over it.

**Comment by netil** [comment]
For Safari desktop browser, it needs bind event as before - #3856
