### ISSUE TITLE
Treemap tooltip not shown in latest Chrome and Firefox

### ISSUE THREAD

**Issue by J4gQBqqR** [naver/billboard.js#3838]
## Description
Treemap tooltip not shown in latest Chrome and Firefox

## Steps to check or reproduce
Visit this page with Chrome dev or Firefox nightly:
https://naver.github.io/billboard.js/demo/#Chart.TreemapChart
Hover the mouse over the treemap, no tooltip is shown.

Operating system: Verified on Windows 10 and Windows 11

**Comment by netil** [comment]
On MacOS(Sonoma 14.5), FF and chrome works fine.
- Firefox 128, Chrome 126.0.6478.127

**Comment by J4gQBqqR** [comment]
Tested on Firefox Nightly 129.0b2 on Windows 10 and Firefox 127.0.2 on Windows 10. It is working.
For Chrome dev 128.0.6559.0 (Official Build) dev (64-bit), it is not working.

On windows 11, both Firefox Nightly 129.0b2 and Chrome dev 128.0.6559.0 are not working.

**Comment by netil** [comment]
@J4gQBqqR, tested on below environments and couldn't notice any defect on tooltip display.

- OS: Wnddows 10 Pro, 22H2 (Build 19045.4123)
- Tested on:
  Browsers | Version
  :---: | :---:
  Chrome | 126.0.6478.127
  Chrome(dev) | 128.0.6585.0(
  Firefox | 128.0
  Firefox(dev) | 129.0b3
- Working screeenshot:
  - Firefox(dev)
  ![treemap](https://github.com/user-attachments/assets/a89e23a7-f53a-413b-80a8-3a36007f42f7)
  - Chrome(dev)
  ![treemap-chrome](https://github.com/user-attachments/assets/84b11a12-b180-4a2d-8f1f-a372cb38dcb9)

**Comment by J4gQBqqR** [comment]
After update to latest Chrome and Firefox, it started to work again on Windows 10.
I will test at home for Windows 11 later today and let you know. If they started to work again, I will close this issue.

Thank you.

**Comment by J4gQBqqR** [comment]
I verified that this is working in Windows 11 as well.
