### ISSUE TITLE
Padding "fit" overflows with pie/donut charts

### ISSUE THREAD

**Issue by grassick** [naver/billboard.js#3872]
## Description

If padding "fit" is turned on, then the legend can overflow in pie and donut charts. Turning it off leaves the appropriate amount of room.

## Steps to check or reproduce

https://jsfiddle.net/grassick/mjhdof13/6/

If you comment out the: `{ padding: "fit" }`, it works perfectly. But with it on, it clips:

![image](https://github.com/user-attachments/assets/6111357e-e414-4333-ba88-35908103be8c)

**Comment by netil** [comment]
Hi @grassick, thanks for the report.
It's happening only in Safari. I'll go over it.
