### ISSUE TITLE
reset button of zoom in "drag" mode is not worked properly after load() new data

### ISSUE THREAD

**Issue by monexiao** [naver/billboard.js#3878]
## Description
In "drag" zoom mode, the reset button will unzoom the graph to default settings.
If I use chart.load() to load new data, the and drag to zoom, and then click reset button, the unzoom() will show previous data range, not new data range.

## Steps to check or reproduce

I use timeseries data, for example:
1. Load 8hr data with 1data/6min.
2. Drag any region to zoom.
3. Click reset button to unzoom, the chart shows 8hr data.
4. Load 1 day data to replace. **(should unzoom to hidden the old reset button otherwise the old one still show but it is not work.)**
5. Drag any region to zoom.
**6. click reset button to unzoom, the chart show 8hr data, but actually total data is 1day data.**

Refer to: https://codepen.io/monexiao/pen/bGPZPaQ

**Comment by netil** [comment]
Hi @monexiao, please provide reproducible online fiddle for the check.

**Comment by monexiao** [comment]
After checking, I found the phonmenon occurs when the zoom option rescale is set as true.
Like as the issue I post previously.
https://github.com/naver/billboard.js/issues/2926
The rescale option will cause the zoom function work.

**Comment by netil** [comment]
@monexiao confirmed the issue. I'll go over it.
