### ISSUE TITLE
When use json data, can I use 'setTimeout' for each index?

### ISSUE THREAD

**Issue by 0eunee** [naver/billboard.js#388]
## Description
I'm a beginner.
I use bar chart, json data.
I want to make each bar (each json data) appear one by one, so as a beginner, I tried every possible ways I could come up with. but couldn't get through it.
I wonder how can I work with one json data.
How do I use `setTimeout()` for each index? please help me :sob:

## Steps to check or reproduce
![chart](https://user-images.githubusercontent.com/21076605/39174099-a795ed9e-47e1-11e8-87fb-ce36e4006234.PNG)
```javascript
var chart = bb.generate({
  data: {
	json: dataList, // dataList like [{name:"", rate:""}, {name:"", rate:""}]
	keys: {
	  x: "name",
	  value: ["rate"]
	},
    type: "bar",
    color: function(color, d) {
		if ((d.value >= 0 && d.value < 90) || (d.value >= 110 && d.value < 999)) {
			color = "#ef4030";
		} else if ((d.value >= 90 && d.value < 95) || (d.value >= 105 && d.value < 110)) {
			color = "#ed9c2c";
		} else if ((d.value >= 95 && d.value < 110)) {
			color = "#71af19";
		}
		return color;
    }
  },
  bar: {
	width: 10,
	padding: 10
  },
  axis: {
	x: {
	  type: "category",
	},
	y: {
	  max: 200,
	  tick: {
		format: function (x) {
		  return x + "%";
		},
		count: 5
	  },
	  padding: 0,
	},
    rotated: true
  },
  grid: {
	y: {
	  lines: [{value:50}, {value:100}, {value:150}, {value:200}]
	},
  	lines: {
  	  front: false
  	}
  },
  bindto: "#chart"
});
```

**Comment by netil** [comment]
Hi @0eunee, I can't get your needs.
What does means `one json data` and `setTimeout`?

**Comment by 0eunee** [comment]
짧은 영어로 설명하자니 어려워서 일단 한글로 남기겠습니다! 
제가 하나의 리스트로 이루어진 json 데이터로 위 캡쳐 사진의 바 차트를 구현했는데, 바가 순서대로 하나하나 나오는 액션을 주고 싶습니다.
예제들을 보니 `setTimeout()` 함수로 액션을 줬길래 그 함수로 하나하나 뜨게 하는건가 싶어서 `setTimeout`을 언급했던 것입니다!
`one json data`라고 표현한건, `setTimeout` 함수를 사용해서 액션을 준 다른 예제들을 보니 
```javascript
setTimeout(function() {
	chart.load({
		columns: [
			['data3', 130, -150, 200, 300, -200, 100]
		]
	});
}, 1000);
```
와 같이 새로운 데이터를 추가하였더라고요.
저는 데이터를 추가하는 방식이 아닌 하나의 데이터의 인덱스 등을 통해 액션을 줄 수 있는지를 표현했으나 영어가 짧아서 설명이 부족했네요....ㅠ.ㅠ
질문을 한줄로 요약하자면,
*json 데이터 하나로 인덱스 하나씩 순서대로 바가 촥촥촥 뜨게 구현할 수 있을까요?* 입니다. 감사합니다!

**Comment by netil** [comment]
I'm not sure if this is what you want to achieve.
I made an example loading each items one by one.
- https://jsbin.com/tejovoz/edit?html,js,output

![data-load](https://user-images.githubusercontent.com/2178435/39286052-be4c55fc-4956-11e8-9dd9-11723e4385d3.gif)

**Comment by 0eunee** [comment]
You're always working hard.
That's what I want! :laughing: so amazing. :thumbsup::thumbsup::thumbsup:
Thank you. 감사합니다!
