### ISSUE TITLE
Problems with axes with custom font size + Discrepancies in font rendering across browsers

### ISSUE THREAD

**Issue by m-gallesio** [naver/billboard.js#3889]
Operating system: Microsoft Windows 10 Pro - 10.0.19045 Build 19045
Browser: Firefox 130.0.1 / Edge 129.0.2792.65

## 1. Custom font size in axis labels
We use custom CSS to slightly increase the font size used in charts. Of course the library is not designed for this, so this change can cause oddities when calculating the size and spacing of text elements. I noticed this in particular for **axis labels**, where some text can even end up truncated.

**Firefox**:
![actual_firefox_nofix](https://github.com/user-attachments/assets/97ebaeef-4e0c-4dd2-a293-c24d4d9da021)
**Edge**:
![actual_edge_nofix](https://github.com/user-attachments/assets/bdd38b3e-d01a-499c-94f6-9e566e4a5130)

After some digging through the code I found the logic which determines the font size at `AxisRendererHelper.getSizeFor1Char`:

https://github.com/naver/billboard.js/blob/9c668e688624e0003d6dca6ea00fcf79a3f1b782/src/ChartInternal/Axis/AxisRendererHelper.ts#L37-L63

I assume the memoization at line 60 is meant to increase performance, but by **removing it** the issue gets fixed.

**Firefox**:
![actual_firefox_fix](https://github.com/user-attachments/assets/9d6b2044-6fcb-4825-8dea-2fffd42cf8b6)

**Edge**:
![actual_edge_fix](https://github.com/user-attachments/assets/9a864cce-3cb6-4929-81c1-928febbe17af)

Note the lack of truncation in the Edge version, as well as the increased line spacing in both browsers (and the fact that lines get overlapped in Firefox, but that's another issue).

I could not find a way to monkeypatch this method since it's in an internal class. Of course removing the line would cause a performance degradation which could be siginificant in more complex use cases.

## 2. Discrepancies in font rendering

Related to the above, I noticed Firefox renders fonts differently from Chromium which means labels often end up slightly larger and cause more line breaks.
Additionally, there seem to be some inconsistencies in the interpretation of `padding.left` + `axis.x.tick.width` (related to https://github.com/naver/billboard.js/issues/3550).
This happens regardless of whether a custom font size is set.

**Firefox**:
![demo_firefox](https://github.com/user-attachments/assets/2cefaaa3-a0dd-450a-aac6-bf34d7037679)

**Edge**:
![demo_edge](https://github.com/user-attachments/assets/f134b3ad-fe94-4147-a8d9-9937ee162a9a)

**Source**:
[custom_font_size_demo.zip](https://github.com/user-attachments/files/17241552/custom_font_size_demo.zip)

Ideally the rendering of labels should be more consistent, but I acknowledge this could be outside the technical possibilities of this library.

**Comment by netil** [comment]
Hi @m-gallesio,

> 1. Custom font size in axis labels

As your examination, after evaluating each axes tick text dimension, will get memoized for performance issue.
But it doesn't iterate for all ticks to get the text dimension.

Probably providing an option to let user can control the way to evaluate text dimension will solve the issue.

> 2. Discrepancies in font rendering

Tested on below browser with the example you provided, and each browser evaluated differently the text dimension.
So, having some discrepancies among browsers is inevitable.

- Chrome v129.0.6668.90: w: 6.3046875, h: 12
- Safari v18.0.1: w: 5.5625, h: 11.515625
- Firefox v131: w: 8.300000190734863, h: 12
