### ISSUE TITLE
Data label to show category

### ISSUE THREAD

**Issue by flipcode1973** [naver/billboard.js#390]
I was looking for a way to show the x axis 'category' on a barchart data label (in addition to the value itself). Is this possible?

**Comment by netil** [comment]
Hi @flipcode1973, you mean `data value + x Axis category` text together?
For example, `150 + 1` in the below image?
![2018-04-26 11 34 32](https://user-images.githubusercontent.com/2178435/39282791-de3c1a7a-4945-11e8-91d0-d19316365ef9.png)

**Comment by flipcode1973** [comment]
Hi @netil, thanks for the prompt reply. Yes,  I have the x-axis ticks switched off as per picture below and wanted to show the category alongside the label

![image](https://user-images.githubusercontent.com/38728488/39289946-d7d87b58-4925-11e8-9850-be71f4c747e6.png)
Assuming using code somewhere here but unsure as to whether I can access the category data here...
```
labels: {
			show: true,
			format: function (v, id, i, j) {
				var formatPercent = d3.format(",.2%");
				return formatPercent(v);
			}
		},
```

**Comment by netil** [comment]
The `data.labels.format` is called in a global context, which you can't get access chart instance on it.
How about having separated category data and access it as indexed value?

```js
var data [ 
    ["x", "a", "b", "c"],
    ["data1", ... ]
];

var bb.generate({
    data: {
        data: data,
        x: "x",
        labels: {
            format: function (v, id, i, j) {
                return d3.format(",.2%")(v) + data[0][i + 1];
            }
        }
    }
});


```

**Comment by flipcode1973** [comment]
Thats great thankyou!

**Comment by sinisarudan** [comment]
This helped me. But I provide a 'correction' to the solution by @netil. some syntax missing and actually making it simpler by my opinion and correcting the result of the format function
```
**JS:**
generateTestChart1():void{
    var data = [ 
      ["data1", 0.1, 0.3, 0.2, 0.4, 0.5]
    ];
    
    var chart = bb.generate({
        bindto: "#test_chart",
        data: {
          type: "bar",
          columns: data,
          labels: {
              format: function (v, id, i, j) {
                  return d3.format(",.2%")(v);
              }
          }
        }
    });
  }

**HTML:**
<div id="test_chart">
      test chart
    </div>
```
It generates the Result which I also needed:
![image](https://user-images.githubusercontent.com/1769627/49026184-7df27000-f19d-11e8-8282-cbf4001f0ef3.png)
