### ISSUE TITLE
TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite

### ISSUE THREAD

**Issue by alanhamlett** [naver/billboard.js#3909]
The [Document.elementFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) call here is throwing an exception. Maybe from more than one element at the point coordinates or invalid x,y coordinates?

https://github.com/naver/billboard.js/blob/f941bbe664777577c58c3dfe065174ea596cf2ec/src/ChartInternal/internals/tooltip.ts#L666

User-Agent:
`Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36`

Billboard.js: v3.14.0 stable

Not able to reproduce this error myself, but seeing it in my error logs.

I can submit a PR, @naver would a try/catch block work here or is there some way to validate the coordinates before passing to [elementFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint)?

**Comment by netil** [comment]
> Not able to reproduce this error myself, but seeing it in my error logs.

@alanhamlett, anyway can you provide your generation option?

> I can submit a PR

please.

**Comment by alanhamlett** [comment]
#3910
