### ISSUE TITLE
d3 dependency

### ISSUE THREAD

**Issue by porfirioribeiro** [naver/billboard.js#391]
Is d3 using all of the d3 api? Maybe you could have as a dependency just the required packages and not the full d3 suite.
Also, i don't know if possible, would be great to be able to make billboard more modular, that would make it smaller and the apps end up with less dead code.

**Comment by netil** [comment]
Hi @porfirioribeiro, thanks for the suggestion.

It has `d3` as a dependency, but it doesn't mean using all of the d3 APIs.
About importing only necessary d3 modules was already treated on #285, but as you mentioned this can be more improved.

And making more modular is the next consideration for the next `2.0.0` release.

Anyway, thanks for the feedback, which is the good source on making future plans and always are worth to hear!
