### ISSUE TITLE
When point.sensitivity is a function then data.onclick is not working

### ISSUE THREAD

**Issue by kisyov21** [naver/billboard.js#3912]
## Description
With this ticket I am referring to the second issue from the already closed ticket - https://github.com/naver/billboard.js/issues/3900 
When point.sensitivity is a function then data.onclick is not working.
## Steps to check or reproduce
check the code attached to https://github.com/naver/billboard.js/issues/3900

**Comment by netil** [comment]
Hi @kisyov21, the `data.onclick` will work based on the value `poinst.senstivity` returned from the function.

Checkout the example below, when senstivity is near bubble shape, the mouse cursor will change.
And when the pointer is within the senstivity value, data.onclick will work.

![Nov-07-2024 12-20-52](https://github.com/user-attachments/assets/957a64d3-e84c-46d8-af2f-8749a6fe7950)

- https://jsfiddle.net/netil/bsgh3Ln7/

So combining two options, point.senstivity fulfill the first requirement and when is in the boundary that's the moment which data.onclick work.

**Comment by kisyov21** [comment]
@netil thanks for the response, but I think the jsfiddle link is wrong.. Can you please update it?

**Comment by netil** [comment]
@kisyov21 updated the link

**Comment by kisyov21** [comment]
@netil thank you for your time! I will check what might be the problem on my end.

**Comment by kisyov21** [comment]
@netil actually I found why it is not working on my side. When the type is "timeseries" not "bubble", onclick is not fired. Is it by design or it is a bug?
https://jsfiddle.net/2ku058de/4/

**Comment by netil** [comment]
@kisyov21 quite busy these days. I'll go over it soon.
