### ISSUE TITLE
Tooltip misalignment when using viewBox auto resize

### ISSUE THREAD

**Issue by LMasterGame** [naver/billboard.js#3917]
## Description

The tooltip gets misaligned with the cursor when the viewBox resize option is enabled.
Here is an example screenshot:
![image](https://github.com/user-attachments/assets/8b84473d-4b69-4a24-8ad7-35677d1f6a17)

I already have a workaround for this, which consists of a position function for the tooltip:
```
tooltip: {
    order: 'desc',
    grouped: true,
    position: function (data, width, height, element, pos) {
        // get root svg from element
        let svg = element;
        while (svg && svg.tagName !== 'svg') {
            svg = svg.parentElement;
        }
        // use jquery to get properties of root svg
        svg = $(svg);
        const viewBox = svg.attr('viewBox').split(' ').map(Number);
        const svgWidth = svg.width();
        const svgHeight  = svg.height();
        // calculate final coordinates
        const scaleX = svgWidth / viewBox[2];
        const scaleY  = svgHeight / viewBox[3];
        let transformedX = pos.xAxis * scaleX;
        const transformedY = pos.y * scaleY;
        if(transformedX + width > svgWidth) {
            // avoid out of bounds
            transformedX -= width;
        }
        return {
            top: transformedY,
            left: transformedX
        };
    },
},
```
Here is a screenshot while using the position function above:
![image](https://github.com/user-attachments/assets/77296e0e-2cbb-4b12-9ee4-8cdb92077f7e)

Although i found a solution for myself, it would be great if the tooltip becomes aware of the viewBox scaling.

## Steps to check or reproduce

1. define a chart that uses viewBox resizing:
```
resize: {
    auto: "viewBox"
}
```
2. Scale the SVG so the viewBox size doesn't match the actual SVG size in pixels.

**Comment by matwey** [comment]
Same for me, even on the official demo page:
https://naver.github.io/billboard.js/demo/#ChartOptions.resizeViewBox
