### ISSUE TITLE
Combination graph with 2 Y-Axis

### ISSUE THREAD

**Issue by flipcode1973** [naver/billboard.js#395]
Hi, I am struggling with the correct syntax to use in order to add another graph to a Stacked Bar graph. 

My current graph retrieves data from a CSV file via URL and I want to overlay a line graph (on a separate 2nd Y-Axis) with data (also from a CSV file via URL) but I don't know what syntax to use.

**Comment by netil** [comment]
You can retrieve data from one URL. If the 2nd data is retrieved from another URL, you need to get data separately.

```js
// pseudo code
var data1 = getData("some1.csv");  // main data
var data2 = getData("some2.csv");  // 2nd Y axis data

bb.generate({
    data: merge(data1, data2);
    ...
```
I can give more detailed comment, if you provide a real like data.

**Comment by flipcode1973** [comment]
With a CSV (data_stackedbar.csv) in the format...

Month,Col1,Col2,Col3,Col4
Feb-2017,1,2,3,4
Mar-2017,4,5,6,7
...

I wanted to overlay a spline chart (on separate Y2 axis) with as CSV (data_spline.csv) with the format...

Month,Col5
Feb-2017,100
Mar-2017,200
...

The code I'm using to generate the grouped stacked bar chart is as follows
```
bindto: "#panelNetLA",
			data: {
				url: "/Content/Data/data_stackedbar.csv",
				type: "bar",
				x: "Month",
				xFormat: "%b-%Y",
				order: "asc",
				groups: [
					[
						"Col1",
						"Col2"
					],
					[
						"Col3",
						"Col4"
					]
				],
		}, ...
```
I am unsure as to how to extend this code to add the new data/chart. Any help is greatly appreciated.

**Comment by netil** [comment]
You need to set options as below to display `Col5` to be aligned y2 Axis.
But, before to do that, it needs to merge your two csv files data.

I made an rough example below in case you're using with d3 v5.

```js
var data = [];

// load 1st csv file
d3.csv("test1.csv").then(function(res) {
	data = res;

        // load 2nd csv file
	return d3.csv("test2.csv");
}).then(function(res) {
        // merge test2.csv data to test1.csv
	data.forEach((v, i) => {
		const key = Object.keys(res[i])[1];

		v[key] = res[i][key];
	});

	data.columns.push(res.columns[1]);

    // Script
    bb.generate({
        data: {
            json: data,
            keys: {
                x: "Month",
                value: data.columns.concat().splice(1),
            },
            type: "bar",
            types: {
                Col5: "spline"
            },
            order: "asc",
            groups: [
                [
                    "Col1",
                    "Col2"
                ],
                [
                    "Col3",
                    "Col4"
                ]
            ],
            axes: {
                Col5: "y2"
            }
        },
        axis: {
            x: {
                type: "category"
            },
            y2: {
                show: true
            }
        }
    });
});
```

And the result will be as:
![image](https://user-images.githubusercontent.com/2178435/39517956-65fc2ff4-4e3c-11e8-9ac0-21eed53133da.png)

**Comment by flipcode1973** [comment]
Thanks for the prompt and detailed reply. I ended up just adding the extra axes code e.g.

`axes: {
                Col5: "y2"
            }`

and then loading the 2nd CSV after a small timeout :-)
```
setTimeout(function () {
			myGraph.load({
				url: '/Content/Data/data_splinechart.csv',
				type: "spline",
			});
		}, 1000);
```
Thanks again for your reply, the code for loading and merging the data will prove useful.
