### ISSUE TITLE
Change color theme

### ISSUE THREAD

**Issue by francisco-orduna** [naver/billboard.js#403]
## Description
Is there a way to configure a color theme? We would like to change the default theme to a darker one changing texts to brighter colors.
Thanks and regards

**Comment by netil** [comment]
Every basic styles are defined at css file.
- https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.css

Update or add the styles as your needs.

**Comment by francisco-orduna** [comment]
Thanks,
We found it! But I would add some documentation on how to create your own theme. 
We did it looking at the chart in your main page (https://naver.github.io/billboard.js/) after struggling some time trying to change the color of legend items and axis lines. The trick is in the CSS "fill" property and not in "color" one but we didn't see it at first sight.
Cheers.

**Comment by netil** [comment]
Yeah, it needs more description on this.
BTW, there's a plan(#241) to add different styles like theme via css files.

It'll be appreciated to be contributed your styles later :smiley:
