### ISSUE TITLE
README.md should recommend https links instead of http

### ISSUE THREAD

**Issue by Loksly** [naver/billboard.js#406]
## Description

The _README.md_ file suggests the usage of links like:

* http://naver.github.io/billboard.js/release/latest/dist/billboard.js
* http://naver.github.io/billboard.js/release/latest/dist/billboard.css

## Suggested fix

It is supported and much better to use the https links:
* https://naver.github.io/billboard.js/release/latest/dist/billboard.js
* https://naver.github.io/billboard.js/release/latest/dist/billboard.css

Please consider to add an 's' on every link to _github.io_ cdn.

**Comment by netil** [comment]
Hi @Loksly, thanks for suggesting.
Updated every links' protocol to `https` on readme file. :smiley:
