### ISSUE TITLE
Trouble with export method

### ISSUE THREAD

**Issue by pvictor** [naver/billboard.js#418]
## Description
Hello, I have issues using the export method, the result is not what I expected : 

![image](https://user-images.githubusercontent.com/4415580/40350140-1f17daee-5da9-11e8-991f-1786ecdd8a25.png)

I use D3 (v4 or v5) and billboard 1.4.1, am I missing a dependency ?

## Steps to check or reproduce
I used code from demo page, here's a fiddle : https://jsfiddle.net/5twwj0gd/1/

Thanks!

Victor

**Comment by netil** [comment]
Hi @pvictor, it seems css styling wasn't applied. I'll try to check it.

**Comment by netil** [comment]
The error happens because the css file is coming from different domain than the execution domain.
![2018-05-23 2 32 59](https://user-images.githubusercontent.com/2178435/40405136-3f108268-5e96-11e8-826c-b41d49f3795e.png)

It will work if css is at same domain as export API is called.

**Comment by pvictor** [comment]
Thanks @netil !
