### ISSUE TITLE
Padding on timeseries

### ISSUE THREAD

**Issue by drazik** [naver/billboard.js#42]
Hello,

## Description
I am trying to add a padding on a chart that use a timeseries based x axis. But nothing happens. What I'm trying to achieve is to prevent my points to be cut on left and right when they are on the edges of my chart (see below).

![screenshot_5](https://user-images.githubusercontent.com/1606068/27691357-104bfcdc-5ce4-11e7-8399-122c48699d7c.png)

## Steps to check or reproduce
You can see [this codepen](https://codepen.io/anon/pen/EXQazq) to reproduce.

Thank you very much.

EDIT : I found a workaround by using min/max and substracting/adding some days on my boundaries. It works, but I think it would be better if we could use padding since it is made for that purpose I guess.

**Comment by netil** [comment]
@drazik, in that case padding values should be set in numeric time value.

For example, if you want give left padding as one day's width, set time value as `1000*60*60*24` which is corresponding the numeric time values of 24hs.

```js
axis: {
	x: {
		padding: {
			// set left padding as the width of one day
			left: 1000*60*60*24
		}
```

![image](https://user-images.githubusercontent.com/2178435/27779639-53370384-5fff-11e7-9445-62729e0a5a51.png)


I think on API isn't fully detailed described that. I'll be clarifying that on docs.

**Comment by drazik** [comment]
Oh yeah OK thank you very much @netil. Should I close the issue then ? Or you want to keep it opened to remind yourself to clarigy the docs ? Maybe I can help by writing this part of the doc and make a PR ?

**Comment by netil** [comment]
I'll close after the PR merge. :)

**Comment by drazik** [comment]
I didn't see that you already made a PR 👍 nice work !
