### ISSUE TITLE
support multiple YAxis (3 axis)

### ISSUE THREAD

**Issue by kinonia** [naver/billboard.js#422]
## Description
Is it possible to use 3 axis using billboard.js chart.

**Comment by netil** [comment]
Hi @kinonia, multiple y Axis is part of the future plan(check for the issue #98).

**Comment by mageshveeraa** [comment]
@netil  is there any progress on the y3 axis.

**Comment by netil** [comment]
@kinonia, @mageshveeraa 
the feature was released by [`v1.7`](https://github.com/naver/billboard.js/releases/tag/1.7.0).

Checkout the example:
- https://naver.github.io/billboard.js/demo/#Axis.MultiAxes
