### ISSUE TITLE
Update chart with parameters

### ISSUE THREAD

**Issue by arakovskis** [naver/billboard.js#424]
![github](https://user-images.githubusercontent.com/37780449/40534837-fd715406-600f-11e8-92de-243850fb1a98.png)

I need to update chart with new parameters from form. For example I want to change legend position, if I write:

` me.chart.internal.config.legend_position = "right";`  
` me.chart.legend.show();`  
` me.chart.flush(); `  

It's not working.

**Comment by netil** [comment]
Hi @arakovskis, the way you're approaching isn't correct way.
If you need change certain option, aside the API handlings, do `.destroy()` and generate again.

**Comment by arakovskis** [comment]
Thanks @netil :)
