### ISSUE TITLE
truncated labels when using custom font by CSS

### ISSUE THREAD

**Issue by NeomMob** [naver/billboard.js#425]
## Description
Labels are truncated when setting up a different font by CSS
![screen shot 2018-05-26 at 10 36 17](https://user-images.githubusercontent.com/326762/40574389-fc7ce4fe-60d0-11e8-8e94-d3133391a1be.png)

Using version 1.3 and look like #323 which seems to be fixed in 1.3

## Steps to check or reproduce
- Set a different fornt ot font size by CSS by example:

```
html{
	font-size: 28px;
}
```

**Comment by NeomMob** [comment]
Hi @netil Thansk for your support.
using `clipPath:false` had no effect. However trying `chart.selectAll('.bb-axis').attr('clip-path',null);` did the trick.

Thanks

**Comment by netil** [comment]
There're 5 areas applying the `<clipPath>`. The `clipPath` option is for chart area only.

![image](https://user-images.githubusercontent.com/2178435/40703086-0ebcb0b2-641f-11e8-87cb-a521380528c0.png)

What do you think provide as an option for this?
But I'm not sure the needs of the others, excluding this one.

**Comment by NeomMob** [comment]
An option would be good but it has to be applicable to the majority of users. Because we have now a clean workaround, we could keep it as it is. Anyway thanks for your support, Really appeciated.

**Comment by netil** [comment]
@NeomMob, from the 1.5.0 release, added axes `clipPath` options. (ref. https://github.com/naver/billboard.js/issues/458)
Now you can handle the `clip-path` attributes for [chart](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.clipPath), [x-axis](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4clipPath) and [y-axis](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4clipPath).

Hope this can help :)
