### ISSUE TITLE
X axel strings instead of numbers

### ISSUE THREAD

**Issue by veriuportal** [naver/billboard.js#432]
Hi,

How can user names(john, aron, ect.) instead of number as default (1,2,3..) in X axel?

thanx

**Comment by netil** [comment]
Set [axis.x.type](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4type) as `category`. 

Check the two examples below:
- https://naver.github.io/billboard.js/demo/#Axis.CategoryAxis
- https://jsbin.com/wunipoy/edit?html,js,output
