### ISSUE TITLE
Add text to gauge chart

### ISSUE THREAD

**Issue by arakovskis** [naver/billboard.js#437]
Hello, is it possible to add text to the gauge chart like in this example?
Thanks 

![screenshot_1](https://user-images.githubusercontent.com/37780449/40978374-2604630c-68dc-11e8-92eb-a1e733222c6e.png)

**Comment by netil** [comment]
Hi @arakovskis, currently there's no option for that. But you can add text manually using [`onrendered`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.onrendered)  option.

```js
bb.generate({
  ...
  onrendered: function() {
    var arc = d3.select(".bb-chart-arc");
    var text = arc.select("text")
      .attr("dy", "-.7em");

    arc.append("text")
      .classed(text.attr("class"), true)
      .attr("style", text.attr("style"))
      .style("font-size", "20px")
      .style("opacity", "1")
      .text("hours");  // <-- add your text here
  }
}
```

![image](https://user-images.githubusercontent.com/2178435/40988268-a2275cac-6925-11e8-961c-f518b33271c0.png)


Checkout the working example I made:
- http://jsbin.com/fabudo/2/edit?html,js,output

**Comment by arakovskis** [comment]
Thank you @netil
