### ISSUE TITLE
Add multilined support for gauge label text

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#442]
## Description

Ref. #437

![image](https://user-images.githubusercontent.com/2178435/41214980-03052f1a-6d89-11e8-970e-107613d3cc88.png)

```js
bb.generate({
  gauge: {
     label: {
         format: function(value, ratio) {
             return value + "\nhours";  // multilined using `\n`
         }
     },
});
```

**Comment by arakovskis** [comment]
![screenshot_20](https://user-images.githubusercontent.com/37780449/41602289-29036244-73e3-11e8-99e9-d34e82f93fcc.png)

It's not working :/

**Comment by netil** [comment]
Isn’t implemented yet. When is implemented this issue will be closed.
