### ISSUE TITLE
Chart Request

### ISSUE THREAD

**Issue by ghost** [naver/billboard.js#446]
Hi, maybe in the future you can add this type of chart?

![screenshot_12](https://user-images.githubusercontent.com/37780449/41402120-2678ca68-6fca-11e8-8de3-ee44591803cb.png)

**Comment by netil** [comment]
Hi @arakovskis, the `Treemap` is one of the already planned for the future.

Checkout the types we're planning for the future:
- https://github.com/naver/billboard.js/wiki/Roadmap#new-chart-types

**Comment by netil** [comment]
treemap has been implemented by #3012
