### ISSUE TITLE
Is possible draw donut in order?

### ISSUE THREAD

**Issue by bongdan** [naver/billboard.js#452]
도넛 챠트를 순서대로 그릴수 잇나요?

 도넛 챠트를 그릴때 

data 넣은 순서대로 

오른쪽으로 순서대로 그리고 싶은데요.

 지금은 넣은 순서대로 그려지지가 않네요

혹시 옵션이 잇는지 궁금합니다.

**Comment by netil** [comment]
Hi @bongdan, there's an option for data ordering.
- [data.order](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4order)

```js
bb.generate({
	data: {
		columns: [
			["data1", 60],
			["data2", 40],
			["data3", 100]
		],
		type: "donut",
		order: null  // <-- set 'null' to keep the order as the bound order
	}
});
```
