### ISSUE TITLE
Bars in Bar Chart are overlapping when using chart.toggle()

### ISSUE THREAD

**Issue by kasparsaleksejevs** [naver/billboard.js#454]
## Description
When toggling data visibility in a Bar chart, it may result in a visual glitch when one bar overlaps another:
![billboardjs_bar](https://user-images.githubusercontent.com/20342419/41656284-200768e2-7498-11e8-9af4-9d27eef17ea6.png)
Or in other case - leaving a large gap between bars:
![billboardjs_bar2](https://user-images.githubusercontent.com/20342419/41656384-6b5eb25a-7498-11e8-9aa3-96262c77480c.png)

## Steps to check or reproduce
Using BillboardJS 1.4.1, D3 4.13.0
In my case, a have 3 data points, first one is always visible, but pressing the button toggles the visibility of the second and third so that only one of them is visible at the same time (think of it like a XOR function).

Example: https://codepen.io/anon/pen/MXQLQR (click the 'Toggle Second/Third Percentages' button).

## Known workarounds
When setting the `transition.duration = 0`, the issue goes away, but that means - no cool animations. 
Also, calling the `chart.flush()` after some seemingly magic timeout (~250ms on my machine) helps to mitigate the issue, but the transition to the 'correct' state is still noticeable.

**Comment by netil** [comment]
Hi @kasparsaleksejevs, thanks for reporting the issue.

It seems having an issue on `.toggle()` API, because clicking the legend works well as expected.
![toggle](https://user-images.githubusercontent.com/2178435/41694654-4668178a-7546-11e8-9431-e0117841f988.gif)

I'll look for that.

**Comment by netil** [comment]
Fixed and it works as
![toggle2](https://user-images.githubusercontent.com/2178435/41705947-7b034346-7575-11e8-956c-d07a9544f358.gif)
