### ISSUE TITLE
Order of data in RadarChart

### ISSUE THREAD

**Issue by muratkemaldar** [naver/billboard.js#464]
## Description
Hi! 

Was trying out the RadarChart, and it seems currently you cannot change the order of the radar chart. It is counter-clockwise from the top. I would like to change it to clockwise, for my use case. 

## Steps to check or reproduce
You can see it in the example.
https://naver.github.io/billboard.js/demo/#Chart.RadarChart

There is no option to change the order:
https://naver.github.io/billboard.js/release/latest/doc/Options.html#.radar

**Comment by netil** [comment]
Hi @muratkemaldar, there's [data.order](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4order) option, but isn't applicable for `radar` yet.

I'll be try implementing ordering data on next release.
