### ISSUE TITLE
Problem with resize when multiple charts on the same page 

### ISSUE THREAD

**Issue by dosource** [naver/billboard.js#466]
## Description
When there are multiple charts on one webpage, only the last one (the one for which `bb.generate()` is called the last) is resized when window is resized.

## Steps to check or reproduce
[https://codepen.io/dosource/pen/ERebpz](https://codepen.io/dosource/pen/ERebpz)

**Comment by netil** [comment]
Hi @dosource, I'll take a look on it.
Thanks for the report.

**Comment by netil** [comment]
A side effect caused by #404.

**Comment by netil** [comment]
Hi @dosource, just released 1.5.1 with the fix of this issue.

**Comment by dosource** [comment]
Great ! Thank you for your quick feedback.
