### ISSUE TITLE
Feature Request: Make zooming scale the graph on the Y axis

### ISSUE THREAD

**Issue by naor2013** [naver/billboard.js#470]
## Description
When you zoom on specific X values (like dates on my example), it's hard to see any meaningful data from it when it's not scaled on the Y axis too. So if you zoom on a part where all the Y values are low, you can't see the differences between the lines.

Example:
Before zoom - 
![before-zoom](https://user-images.githubusercontent.com/5496913/42084663-ef04c522-7b96-11e8-9833-fb41cc4e0363.png)

After zoom -
![after-zoom](https://user-images.githubusercontent.com/5496913/42084669-f6776b66-7b96-11e8-8ea2-0f2dfbe23107.png)

**Comment by netil** [comment]
Hi @naor2013, thanks for  suggesting.
I'll try consider to implement for the future release feature.

**Comment by netil** [comment]
There's [zoom.rescale](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.zoom) option alreaday, but it seems not working properly.
