### ISSUE TITLE
area-step chart when rotated

### ISSUE THREAD

**Issue by denny313** [naver/billboard.js#471]
Hi.
First, thank you for billboard.js

i have problem with billboard.js

## Description
I want that figure like this with rotated

```js
bb.generate({
    bindto: "#chart",
    data: {
        x:"x",
        columns: [
            ["x","1","2","3","4","5","6"],
            ["data1", 30, 200, 100, 170, 150, 250],
            ["data2", 130, 100, 140, 35, 110, 50]
        ],
        types: {
          data1: "bar",
          data2: "area-step"
        },
        colors: {
          data1: "red",
          data2: "green"
        }      
    }
  , axis:{
    //rotated:true
    rotated:false 
  }            
});
```

![before rotated](https://user-images.githubusercontent.com/40747426/42141984-c4c38be2-7de7-11e8-9cde-832d55ea1170.PNG)

but when i rotate it and

```js
bb.generate({
    bindto: "#chart",
    data: {
        x:"x",
        columns: [
            ["x","1","2","3","4","5","6"],
            ["data1", 30, 200, 100, 170, 150, 250],
            ["data2", 130, 100, 140, 35, 110, 50]
        ],
        types: {
          data1: "bar",
          data2: "area-step"
        },
        colors: {
          data1: "red",
          data2: "green"
        }
      
    }
  , axis:{
    rotated:true
    //rotated:false
    
  }
            
});

```

![after rotated](https://user-images.githubusercontent.com/40747426/42142013-f0cfdd58-7de7-11e8-81a8-20e10ac50c91.PNG)

then area-step is something wrong....
area-chart slip half unit...

if i make something wrong. please check me out

thanks

**Comment by netil** [comment]
Hi @denny313, thanks for the report.
It seems having an issue on `step` related types. I'll try fixing that.

**Comment by netil** [comment]
When chart is rotated, computes its coordinate values simply inverting the x and y axes with the help of the d3's related functions.

For the step type, [d3.curvStep](https://github.com/d3/d3-shape#curveStep) is used.

Non step types, just inverting the x/y, works well, but for the step it doesn't work as others. Because of the computation nature it has.

It should find different way on getting computed coordinate values(not using the D3's method) for this case.

**Comment by denny313** [comment]
i change d3.curvStep script little bit, and it solved out.

when billboardchart is always rotated, i solve this by change x,y in d3.v4.js , function Step(context,t)

(i use d3js version5.5.0 )

here is the example

function Step(context, t)
...
 var x1 = this._x*(1-this._t) + x*this._t
this._context.lineTo(x1, this._y)
this._context.lineTo(x1, y)
....

->
function Step(context, t)
...
 var y1 = this._y*(1-this._t) + y*this._t
this._context.lineTo(this._x, y1)
this._context.lineTo(x, y1)
....

it is temporary solve. in condition of all chart is rotated.
but my charts are rotated, so i use this

thanks~

**Comment by netil** [comment]
Thanks! @denny313 for the workaround.
I'll try be considering on implementing this to solve the issue.

**Comment by denny313** [comment]
Thank you! 
It works very well !!!!

감사합니다~~~ 잘쓰겠습니다~~!!
