### ISSUE TITLE
Data order in Stacked Bar Chart

### ISSUE THREAD

**Issue by James1345** [naver/billboard.js#477]
## Description

Is it / can it be possible to specify the order of groups in the stacked bar chart? Currently when data are added to a group they come out in what seems like a random order. Our groups are coloured, and I want the red bar to always be at the bottom of the stack. Is there a way to specify this in billboard?

## Steps to check or reproduce

Create stacked bar chart like the example...

**Comment by netil** [comment]
Hi @James1345, there's [data.order](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4order) option for data ordering.

Set the proper value as your needs.

**Comment by James1345** [comment]
Looks useful.

Is there a reason it defaults to `"desc"` rather than `null`? The descending option seems a little counter intuitive for a stacked bar chart as it sorts the first bar into descending order, then appears to sort each subsequent bar into the same order (even if that is neither asc nor desc)

**Comment by netil** [comment]
The ordering default option was set as is when I forked and started the project. The exact reason I don't know either. But, the default option can't be changed, because it's affecting others already using as is.

**Comment by James1345** [comment]
Makes sense not to change a default. Thanks
