### ISSUE TITLE
Combination chart for bubble not working

### ISSUE THREAD

**Issue by jeesim2** [naver/billboard.js#481]
## Description
Bubble type can not be shown in combination chart.
https://codepen.io/anon/pen/VBYrGR

## Steps to check or reproduce
* area-line-range + bar ( working! )
https://codepen.io/anon/pen/VBYrGR
![image](https://user-images.githubusercontent.com/1100831/42576866-4e41bfce-855e-11e8-9938-66b859e5779e.png)

* area-line-range + bubble ( NOT working !)
https://codepen.io/anon/pen/mjyqob
![image](https://user-images.githubusercontent.com/1100831/42576906-685ae494-855e-11e8-86a4-61f85f38daf7.png)

I am not sure that it is a bug. : )

**Comment by netil** [comment]
Hi @jeesim2, thanks for the report.
It seems a bug. I'll try fix that.

**Comment by netil** [comment]
Fixed and will work as:
![image](https://user-images.githubusercontent.com/2178435/42672917-c93f6456-86a3-11e8-8985-9170272ce64a.png)

**Comment by jeesim2** [comment]
@netil Looks good! Thanks for the quick fix!
