### ISSUE TITLE
Area-line-range chart draw invalid zero point when It does not starts from head of series.

### ISSUE THREAD

**Issue by jeesim2** [naver/billboard.js#482]
## Description
Area-line-range chart draw invalid zero point when It does not starts from head of series.

## Steps to check or reproduce
https://codepen.io/anon/pen/wxBpwz
```
bb.generate({
  data: {
    x: "x",
    bubble: {
      maxR: 50
    },
    columns: [
      ["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
      ["data1", [null, null, null],
        [null, null, null],
        [160, 135, 120],
        [135, 120, 110],
        [180, 150, 130],
        [199, 160, 125]
      ],
      ["data2", null, null, null, 500, 250, 350]
     ],
   
    types: {
      data1: "area-line-range",
      data2:"line"
    }
  },
  axis: {
    x: {
      type: "timeseries",
      tick: {
        format: "%Y-%m-%d"
      }
    },
    y2:{
      show:true
    }
  },
})
```
![image](https://user-images.githubusercontent.com/1100831/42606113-8ffbb386-85b6-11e8-9177-4f7f80f19275.png)

When I draw area-line-chart only in some range for the dates,
It starts with invalid zero point.(in the picture area-line-range should not be drawn at 2013-01-02.

: )

**Comment by netil** [comment]
Hi @jeesim2, fixed the issue and it will work as:
![image](https://user-images.githubusercontent.com/2178435/42683217-aba8c3be-86c7-11e8-81e7-3eef78d47be9.png)

Meanwhile the official release, you can use `nightly`, which is the latest build from master branch :smiley: 
- https://github.com/naver/billboard.js/tree/nightly/dist

**Comment by jeesim2** [comment]
@netil Thanks! I'll try nightly build!
