### ISSUE TITLE
Region does not zoomed with others.

### ISSUE THREAD

**Issue by jeesim2** [naver/billboard.js#483]
## Description
When chart has regions and zoomed, regions left the origin size and place.

## Steps to check or reproduce
https://codepen.io/anon/pen/qyEpaG
```
bb.generate({
  zoom: {
    enabled: true
  },
  data: {
    x: "date",
    columns: [
	["date", "2014-01-01", "2014-01-10", "2014-01-20", "2014-01-30", "2014-02-01"],
	["sample", 30, 200, 100, 400, 150, 250]
    ]
  },
  axis: {
    x: {
      type: "timeseries"
    }
  },
  regions: [
    {
      start: "2014-01-05",
      end: "2014-01-10"
    },
    {
      start: "2014-01-14T15:00:00.000Z",
      end: "2014-01-19T15:00:00.000Z"
    },
    {
      start: 1390575600000,
      end: 1391007600000
    }
  ],
})
```

* initial status
![image](https://user-images.githubusercontent.com/1100831/42577953-765c4f68-8560-11e8-988c-5ce077905f9f.png)

* zoomed
![image](https://user-images.githubusercontent.com/1100831/42577983-84ff41e2-8560-11e8-90a0-8d17b28065b3.png)
regions, not zoomed.

**Comment by netil** [comment]
Hi @jeesim2, fixed the issue. Thanks again for reporting the issue :)

Checkout the working example:
![zoom-region](https://user-images.githubusercontent.com/2178435/44571627-3f26d580-a7bc-11e8-87b9-3363059948ac.gif)
