### ISSUE TITLE
Add support for changing bubble radius size using a third dimension

### ISSUE THREAD

**Issue by kbaumCon** [naver/billboard.js#484]
untie bubble radius from y axis values

**Comment by irislieuw** [comment]
+1 for this feature

**Comment by irislieuw** [comment]
Hey @netil any update on this?

**Comment by netil** [comment]
@kbaumCon, @irislieuw to clarify the needs, this request is about something similar as the below chart, right?

![image](https://user-images.githubusercontent.com/2178435/60950061-697c7580-a331-11e9-893e-50ec441e88e9.png)

**Comment by irislieuw** [comment]
@netil Hmm the request is more to allow the user to pass an additional data vector that can be used to set the radius of each bubble. At the moment the radius size is tied to the y-axis, it'd be great to have this untied so there is an additional axis that can be used to convey information.

for example (from VisualCinnamon): 
![image](https://user-images.githubusercontent.com/11950094/60984962-72e5ed80-a2f1-11e9-9e24-78ac9e7ffebe.png)

Some additional tooltip labeling changes would probably be needed as well to display the z value.. 

A clustered bubble viz would be cool to have as well!!

**Comment by netil** [comment]
thanks @irislieuw for the explanation.

> Example from VisualCinnamon:
> - https://www.visualcinnamon.com/2015/07/voronoi.html

Based on the needs, the data value should have different format as the normal.
```js
// the current
["data1", 30, 350, 200, 380, 150],

// maybe the data format should be like this way
// 'y' is to coordinate with the y Axis, 'z' is for bubble radius
// 'x' is coordinated sequentially
["data1", {y: 30, z: 15} , {y: 350, z} , {y: 200, z}, {y: 380, z}, {y: 150, z}],
```

**Comment by netil** [comment]
@irislieuw, I did early implementation on this.
- data1: the current
- data2: `y`(for y axis) and `z`(radius)
  > when data format is `{y, z}`, the tooltip & data label text will display `z` value.

![image](https://user-images.githubusercontent.com/2178435/61035705-9c426e80-a402-11e9-8584-9be74759d049.png)

Let me know if you have any comments.
