### ISSUE TITLE
How to Use Pie with json?

### ISSUE THREAD

**Issue by SeungjaeKim** [naver/billboard.js#486]
## Steps to check or reproduce

I'd like to use a pie using json data

var chart = bb.generate({
  data: {
	json: objData,
	keys: {
		x: "deptName", // it's possible to specify "x" when category axis
		value: ["persent"],
	},
    type: "pie",
  },
  bindto: "#PieChart"
});
![image](https://user-images.githubusercontent.com/12381719/42682216-dd786c44-86c4-11e8-8826-72bc2e1031e6.png)

It looks like the picture above.

![image](https://user-images.githubusercontent.com/12381719/42682280-14f757e8-86c5-11e8-91a3-98f0a211a00a.png)

Json data is as shown above.
I want to know how to use json data for sure.

Thank you in advance.

**Comment by netil** [comment]
Hi @SeungjaeKim, for pie type you should transform to be correctly rendered.

```js
// the given JSON data
[
        {deptName: "data1", percent: 26},
	{deptName: "data2", percent: 17},
	{deptName: "data3", percent: 10}
]

// it is transformed internally like
["percent", 26, 17, 10]

// the correct data format pie should be like
bb.generate({
	data: {
		columns: [
			["data1", 26],
			["data2", 17],
			["data3", 10]
		],
		type: "pie"
	}
});
```
