### ISSUE TITLE
Data labels don't work with scatter charts

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#488]
## Description
The option `data.labels` does not work with scatter charts. No label shows up for each point in the chart

## Steps to check or reproduce
https://jsfiddle.net/irislieuw/fh5x0ru6/

**Comment by netil** [comment]
Hi @irislieuw, fixed the issue and will be showing as:
![image](https://user-images.githubusercontent.com/2178435/42804446-06c23bf8-89e4-11e8-830d-8b45be214db3.png)

Thanks again for reporting the issue :smiley:
