### ISSUE TITLE
Line chart w/ regions styling?

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#491]
## Description
Is it possible to style the dashed sections of a line chart with regions?

**Comment by netil** [comment]
Hi @irislieuw, I can't get that exactly. Could you attach img or more detailed info for this?

**Comment by irislieuw** [comment]
@netil Thanks for the quick response! Yes, I'd like to apply styling for the dashed sections of a line in a line chart with regions (https://naver.github.io/billboard.js/demo/#Chart.LineChartWithRegions). For example, I'd like to adjust the stroke-dasharray, similar to this example https://naver.github.io/billboard.js/demo/#Style.StyleForLines

I've got some line charts now that I'm applying a thicker stroke width to, which makes the dashed sections of the line "fuzzy" 

![image](https://user-images.githubusercontent.com/11950094/42838174-e898722a-89b4-11e8-98dd-dcdc7373e16f.png)

**Comment by netil** [comment]
From the image above, the first part looks "fuzzy" and isn't really distinguishable from other part of the region and you want to style in somehow to get some differentiation from others, right?

![image](https://user-images.githubusercontent.com/2178435/42874169-688d25f0-8abb-11e8-946e-48a32e622767.png)

Well, there're two ways on doing for now.
- Via [CSS](https://naver.github.io/billboard.js/demo/#Style.StyleForLines)(the second example you mentioned) property, `stroke-dasharray`
  > The style is applied to whole line. You can't style a partial of line.
- Or via using provided [data.regions](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4regions) option
  > This option makes to draw partial or entire line as "dashed" style. This is done manipulating its path data directly. But the dashes aren't configurable.

IMO, the best way is provide a configurable dashed option(like stroke-dasharray) for this.
I'll take considering to implement for the future release.

**Comment by irislieuw** [comment]
Thanks! Passing along a stroke-dasharray property when specifying the dashed sections of the line would be awesome.

**Comment by irislieuw** [comment]
Thats awesome!! Thanks for the quick turnaround! Billboard.js is the best 🎉
