### ISSUE TITLE
Error when charts with linked tooltips don't have the same x values.

### ISSUE THREAD

**Issue by lorgan3** [naver/billboard.js#494]
## Description
Hey again, I found another issue. I have multiple charts with a timeseries x axis and i want to have a linked tooltip. The linked tooltip doesn't seem to work because the timestamps I have don't line up 100%, I've included a simple codepen that has the same issue.

An easy solution would be ignoring the charts that don't have a matching x value, but it would be really cool if it could select the nearest point on the other charts!

## Steps to check or reproduce
https://codepen.io/anon/pen/RBRroy

**Comment by netil** [comment]
Hi @lorgan3, updated to be linked based on the index value instead of `x` value.

So, if hovering on the third(which is index 2), will be showing every linked chart tooltips on that position.
