### ISSUE TITLE
Radar charts don't resize

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#497]
## Description
Radar charts do not resize. Try resizing the window in the fiddle I attached.

## Steps to check or reproduce
https://jsfiddle.net/irislieuw/32ymdrpt/

**Comment by netil** [comment]
Confirmed the issue. I'll check that.
Thanks for the report. :)

**Comment by irislieuw** [comment]
Thank you @netil !

**Comment by netil** [comment]
Hi @irislieuw, fixed the issue. Checkout the demo below.

![radar-resize](https://user-images.githubusercontent.com/2178435/44081862-c3fda8da-9fea-11e8-89ba-0bfb812415f4.gif)
