### ISSUE TITLE
Enlarge only one point on a line (Question)

### ISSUE THREAD

**Issue by TinusJ** [naver/billboard.js#499]
## Description
Hi is it possible to custom only one point in index on the line data?

Example enlarge one point or change color of point to show focus.

**Comment by netil** [comment]
Hi @TinusJ, yes you can. Take a look on the below example.
- https://naver.github.io/billboard.js/demo/#Data.OnMinMaxCallback

```js
// ex) updating the 2nd(index:1) data point style of 'data1' 
d3.select(".bb-shapes-data1 .bb-circle-1")
    .style("fill", "red")
    .attr("r", "8");
```

**Comment by TinusJ** [comment]
![image](https://user-images.githubusercontent.com/16685359/42942450-309b401e-8b60-11e8-962f-30f5b79191b6.png)

Ok so this might differ from original question. is it possible to add a circle to lines that crosses? 

Also if i add a point on the chart with the previous code, using Installments instead of the provided Outstanding Balance.  The red dot shows big, but once the user hovers over it, it reverts back to normal

**Comment by netil** [comment]
#### 1) Styling a specific data point
The default action when you do `mouseover` on data points, are expanding its radius.
If you disable this, you can maintain the style you set on.

```js
point: {
	focus: {
		expand: {
			enabled: false
		}
	}
}
```

But if you need styling maintaining the current behavior, also possible, but you need to make some work to be done, which I can't help on this case.

#### 2) Add data points where crossing lines
There's no option to doing that for now. Doing some work, it can be done.
But I think isn't really easy work.

**Comment by TinusJ** [comment]
Thank you. Closing this
