### ISSUE TITLE
Is it possible to update the config of an existing chart?

### ISSUE THREAD

**Issue by lorgan3** [naver/billboard.js#500]
## Description
I have a gauge chart and I want to change some of the properties after drawing it. I got it working by editing the internal chart config and then calling `chart.flush()`. This works but I have no transitions and it's a bit annoying that the format is different than config format used when generating the chart.

Is there a better way to do this which I missed or is this currently the only way?

example code:
https://codepen.io/anon/pen/YjpzBq

**Comment by netil** [comment]
@lorgan3, currently there's no API nor property to access config object. 
Basically, the use of `internal` is treated as private. This needs to be exposed in someway as "public" and I'm planning implement for the next release.

Anyway, just for not call `.show()` API, which internally will trigger to redraw.

```js
window.setTimeout(() => {
	chart.internal.config.gauge_max = 100;
	chart.show();
}, 1000);
```

This will work as:
![gauge](https://user-images.githubusercontent.com/2178435/42983513-29949802-8c22-11e8-8261-cd618e3f7d6e.gif)
