### ISSUE TITLE
Add getter/setter API for config object

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#502]
## Description

There's needs to redraw changing its initial configuration or needs to get it.
Currently it can be accessed via `internal.config`, which isn't "public".

It might provide an public API for these to improve the access and handling on config object.

```js
const chart = bb.generate({ ... });

chart.config("axis.rotated", false);  // setter
chart.config("axis.rotated");  // getter
```

Ref #423, #500

**Comment by netil** [comment]
It should be also allowing falsy value setting.

```js
// this makes axis.y.max value to undefiend
chart.config("axis.y.max", undefined);
```

**Comment by porfirioribeiro** [comment]
Is there any place to know which config can be changed?

I was trying to do `chart.config('axis.x.show', false, true)` and it didn't work.
For what i can see there is no way to hide and show the x axis without destroy and re generate it

**Comment by netil** [comment]
Unfortunately, there's no place for that. This implementation is more for getting config values rather than controlling the generated elements.
