### ISSUE TITLE
[Question] Choosing dataset to show via checkbox

### ISSUE THREAD

**Issue by jungbinn** [naver/billboard.js#503]
Is there any function to choose dataset to show on the graph?
For example, TOAST UI chart supports like this (green box).

<img width="872" alt="2018-07-20 6 56 39" src="https://user-images.githubusercontent.com/22424776/42996745-68b0491e-8c4f-11e8-9af5-8e6946837b4a.png">

**Comment by netil** [comment]
Hi @jungbinn, there're several ways to customize legend.
The one of the practical usage will be setting a template to customize legend as your needs.
- https://naver.github.io/billboard.js/demo/#Legend.LegendTemplate1

And if you need to make legends to be shown/hidden clicking the checkbox, checkout the example I made.
- https://jsbin.com/yuqoyum/edit?html,css,js,output
