### ISSUE TITLE
Tooltip size (size increase..)

### ISSUE THREAD

**Issue by daehee84** [naver/billboard.js#505]
## Description

I  generate a chart with sample code. I wonder why it grows in tooltip size.
How can I resize tooltip?

And tooltip size increases when i move the cursor to  values.

![20180723_135043](https://user-images.githubusercontent.com/41564269/43064399-c20470c0-8e99-11e8-9903-8f112ead52dc.gif)

## Steps to check or reproduce

	var chart = bb.generate({
	    bindto: "#chart1",
	    data: {
	        type: "bar",
	        columns: [
	            ["data1", 30, 200, 100, 400, 150, 250]
	        ]
	    }
	});

**Comment by lorgan3** [comment]
The barchart tooltip works fine for me.
Do you perhaps have some css on your page that also affects the tooltip?
By adding this css rule I got a similar effect to your screenshot:
```
td {
  width: 100%;
}
```

**Comment by netil** [comment]
Hi @daehee84, plz provide full code used to generate the chart.

**Comment by daehee84** [comment]
Hi I solved the issue.
As @lorgan3 said, I have another .css file.  
So I edited billboard.css file.  

.bb-tooltip {
  table-layout:auto;  //  added this line. 
 .....
}

Thank you :) @lorgan3 @netil
