### ISSUE TITLE
[Bar chart] Option to not align ticks and bars.

### ISSUE THREAD

**Issue by lorgan3** [naver/billboard.js#506]
## Description
Currently there seems to be the `centered` option which allows you to (not) center both the labels and the bars, but I want to center the labels and not the bars (The bars contain show data about a range, not about 1 point)

Here I made a codepen with 3 charts, the first 2 is what's currently possible, the last one is what I want
https://codepen.io/anon/pen/ZjyaJQ

I achieved the effect by changing the text position, but it is not correct when the chart is resized because the offset is hardcoded. Is there a better way to do this?

**Comment by lorgan3** [comment]
Thanks, I'll use that.

**Comment by 2kne** [comment]
Hello, I share my solution in my case to not align ticks and text : 
```
onrendered: function() {
                const tick = this.main.selectAll(".bb-axis-x .tick");
                const dataColumn = this.main.selectAll(".bb-event-rect");
                tick.select("line").each(function(key, value) {
                   //Here to delete the last one, you can delete this condition
                    if (this.nextSibling.firstChild.textContent == "{YOUR LAST ONE TEXT}") {
                        this.remove();
                    } else {
                        let width = dataColumn._groups[0][value].getAttribute("width");
                        if (value == 0) {
                            width = dataColumn._groups[0][1].getAttribute("width");
                        }
                        this.setAttribute("x1", width/2);
                        this.setAttribute("x2", width/2);
                    }
                });
            },
```
