### ISSUE TITLE
Zoom api improvements

### ISSUE THREAD

**Issue by lorgan3** [naver/billboard.js#508]
## Description
I had a go at implementing this feature request because I would also like this: https://github.com/naver/billboard.js/issues/416

I got this working: https://codepen.io/anon/pen/KBqbMg?editors=1010
When dragging the new area is highlighed, and if you check the console the right domain to zoom to is reported.

I have some issues with the zoom api to make the example usable though.
I have to enable zooming in order for `.zoom()` to have effect. This is a bit strange and I think it shouldn't be required to first enable zooming when using the zoom api manually.

Because currently I have to enable zooming, the user can zoom 'the normal way' after doing the initial drag. Disabling zooming after that resets the zoom level which makes the zoom api useless if you don't want the user to zoom using the scrollwheel...

A third issue I have is that my events don't trigger anymore after calling `.zoom()`. Maybe `onrendered` also needs to be called after zooming or I'm doing something wrong. I'm not very familiar with d3 so any tips are appreciated!

**Comment by netil** [comment]
Hi @lorgan3, nice try!

I think, it should adopt new option interface to distinguish the `normal`(by wheel) and the drag.
```js
zoom: {
	enabled: {
		type: "drag" (default "wheel") 
	}
}
```

As you said, you need to set `zoom.enabled=true` to make `.zoom()` works. To make it possible it should change from the internal, not approaching like this way.

Take a look on subchart interaction, which is using [d3-brush](https://github.com/d3/d3-brush).
- https://github.com/naver/billboard.js/blob/master/src/interactions/subchart.js#L33

Subchart interaction is some how similar zooming by dragging
- https://naver.github.io/billboard.js/demo/#Interaction.SubChart

IMO, requesting a PR for this new feature will be great.

**Comment by lorgan3** [comment]
I'll see if I can give it a try later this week.
