### ISSUE TITLE
Set Tick Step (Question)

### ISSUE THREAD

**Issue by TinusJ** [naver/billboard.js#515]
## Description
Is is possible to set the tick step count.

Currently the tick's offset is .5 if the values goes lower the tick offset becomes .2 

## Steps to check or reproduce
Fiddle to see the current issue https://codepen.io/anon/pen/ejyZOg
![image](https://user-images.githubusercontent.com/16685359/43386067-cc209392-93e2-11e8-98ee-abb47082937d.png)

What i tried was setting the format of the tick, but this is not the way to do it because it duplicates the values. 

` tick: {
       format: function(x) {
		    	return x.toFixed(0);
       }
      }`

Expected outcome i want is the ticks should be 1 , 2, 3 ,4 etc

**Comment by netil** [comment]
Hi @TinusJ, you can try using [axis.y.tick.values](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4values) option

```js
y: {
      tick: {
        values: [1,2,3,4]
      }
}
```

![image](https://user-images.githubusercontent.com/2178435/43388402-f8083078-9423-11e8-9072-fd33d119204a.png)

**Comment by TinusJ** [comment]
@netil  Problem with using the values like that is that i dont know the values, and cannot hard code it. the values may be large and thus cannot even set 1-100 hardcoded. Is there possibly another way?

**Comment by netil** [comment]
This will make displaying integer values, but you'll notice tick lines still showing.

```js
y: {
	tick: {
		format: x => x % 1 === 0 ? x : ""
	}
}
```

![image](https://user-images.githubusercontent.com/2178435/43389262-402e04c0-9426-11e8-97e0-a0186612fa4f.png)

If you want to remove tick lines, you can do something like:
```js
onrendered: function() {
	this.main.selectAll(".bb-axis-y .tick text tspan").each(function() {
		!this.textContent &&
			this.parentNode.previousSibling.style.opacity = 0;
		})
},
```

**Comment by TinusJ** [comment]
Thanks @netil  the first one is sufficient the requirements.
