### ISSUE TITLE
Tooltip display error when loading additional timeline data

### ISSUE THREAD

**Issue by TommyShoulders** [naver/billboard.js#517]
## Description
I receive timeline information from various sources and need to load them as they are returned as some of them take a long time.
When the additional timeline data is loaded after the chart has been initialised, the tooltip displays incorrectly.

## Steps to check or reproduce
https://codepen.io/anon/pen/oMpGdJ

**Comment by netil** [comment]
Hi @TommyShoulders, thanks for the report.
I'll take on look that.

**Comment by netil** [comment]
@TommyShoulders, fixed the issue and will work as;
![data-load](https://user-images.githubusercontent.com/2178435/43455190-12afaa24-94fa-11e8-8e70-e8921ace2582.gif)

Try the nightly build:
- https://github.com/naver/billboard.js/tree/nightly/dist
