### ISSUE TITLE
Best way to make billboard charts responsive & scalable?

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#518]
## Description
This is just a general question on making billboard charts responsive. I use billboard for a charts that needs to display well on all screen sizes (phones -> 4k and higher). I don't have issues with the chart itself in billboard resizing, but am having issues figuring out the best way for the fonts, stroke thickness, alignment, etc to scale as well. 

This is what is currently happening:

* Example without adjusting anything except the line's stroke width
![image](https://user-images.githubusercontent.com/11950094/43413378-c039f8b4-93e4-11e8-8f46-173e1c9da4e3.png)

* Example adjusting font size (things are overlapping now, stuff gets cut off, legend tile height doesn't match the font size, etc)
![image](https://user-images.githubusercontent.com/11950094/43413323-a182d33c-93e4-11e8-9fc3-ddea552f9015.png)

Do you have any advice for scaling _all_ the elements in a billboard chart w/o manually adjusting each element separately?

Thanks!

**Comment by netil** [comment]
Hi @irislieuw, the basic approach than I can recommend is update your css file to handle these cases.

I know that, providing a proper way by default from the library itself is the best case, but as you know the users needs can't be generalized by one default setting.

Maybe in the future, or from someones contribution likely, this should be improved obviously.
Just for now, billboard.js is aiming to style as the users' necessities updating the default css file by users. 

So, in this case I recommend add some media query to handle different styles.

```css
@media(min-width:768px) {
     .bb-text {
          font-size: 13px;
     }

     .bb-line {
         stroke-width: 1px;
     }
    ...
}
....
```

If have any best idea on this, will be appreciated :smiley:
