### ISSUE TITLE
Scatterplot becomes invisible when hiding points

### ISSUE THREAD

**Issue by lorgan3** [naver/billboard.js#520]
## Description
It's a bit of a weird edge case but I want to have a line without points and a scatterplot on the same chart. This is currently not possible because hiding points also hides the scatterplot's points.

I suggest adding something like this to the options to specifically hide line points
```
line: {
    points: false
}
```

I'll make a small pr that adds this shortly.

## Steps to check or reproduce
https://codepen.io/anon/pen/jpzqoq

**Comment by netil** [comment]
@lorgan3 thanks for suggesting, but currently you can add css rule to hide a specific data line to not be shown.

For ex, when `data1` is scatter and `data2` is line, you can hide circles by adding:
```css
.bb-target-data2 circle {
    display: none;
}
```
Maybe is straight forward providing an option like you suggested. In this case how about extending the use of the option hiding specific data as below?

```js
line: {
	point: {
		// show/hide entire line data
		show: false,
		
		// show points only indicated data
		show: ["data1", "data2"]
	}
}
```

**Comment by lorgan3** [comment]
I don't like drawing the points and hiding them using css, that feels like a waste.

Extending it so you can pass an array of ids sounds good, I'll also add that.
