### ISSUE TITLE
Chart Request

### ISSUE THREAD

**Issue by cj213x** [naver/billboard.js#526]
What do you guys think about adding histogram chart option? It's very similar to a bar chart, but serves a distinct purpose.
<img width="528" alt="screen shot 2018-08-03 at 5 10 54 pm" src="https://user-images.githubusercontent.com/26426085/43670597-5cb2e25e-9742-11e8-95ee-189ba5a2bc75.png">

**Comment by netil** [comment]
Hi @cj213x, IMO you can achieve this using [bar.width.ratio](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.bar) option.

```
// (1) width with default value
bb.generate({
    data: {
	    columns: [
		    ["data1", 30, 200, 100, 400, 150, 250],
		    ["data2", 130, 100, 140, 200, 150, 50]
	    ],
	    type: "bar"
    }
});

// (2) make bar width to be w/o gaps
bb.generate({
    data: {
	    columns: [
		    ["data1", 30, 200, 100, 400, 150, 250],
		    ["data2", 130, 100, 140, 200, 150, 50]
	    ],
	    type: "bar"
    },
    bar: {
	    width: {
	    	ratio: 1
	    }
    }
});
```

![image](https://user-images.githubusercontent.com/2178435/43763345-7f77c108-9a65-11e8-8f06-1eae04857cf7.png)
