### ISSUE TITLE
chart export does not work for bar

### ISSUE THREAD

**Issue by bogdan-iuga** [naver/billboard.js#530]
## Description
When trying to export a chart, it seems that the chart of type 'bar' is not working as expected.

## Steps to check or reproduce
https://codepen.io/anon/pen/PBdvJb
In this fiddle : the callback when exporting the bar chart does not get called at all.

create a bar chart - try to export it. nothing happens.
create a line chart - try to export it. works as supposed

**Comment by netil** [comment]
Hi @bogdan-iuga, thanks for the report.
Fixed the issue and you can try with the [nightly](https://github.com/naver/billboard.js/tree/nightly/dist) build.
![export-bar](https://user-images.githubusercontent.com/2178435/43827177-3307549e-9b34-11e8-94a2-59750e69b28e.gif)
