### ISSUE TITLE
data․selection․draggable not working

### ISSUE THREAD

**Issue by matiramos** [naver/billboard.js#532]
## Description
When data․selection․draggable is true the following error appears in the console.

![screenshot from 2018-08-07 22-38-28](https://user-images.githubusercontent.com/4369713/43811770-a5ee50d4-9a94-11e8-84d6-36044034af7f.png)

## Steps to check or reproduce
1. Enter to https://naver.github.io/billboard.js/playground/
2. Disable data․selection․draggable
3. Enable data․selection․draggable
4. Chart will be empty and the error will appear in the console.

**Comment by netil** [comment]
Hi @matiramos, the issue was already fixed. (Ref #493)
Will be out in the next release, meanwhile you can try with the [nightly](https://github.com/naver/billboard.js/tree/nightly/dist) build.
