### ISSUE TITLE
Y Axis Label Position Incorrect When Using Tick Count

### ISSUE THREAD

**Issue by TommyShoulders** [naver/billboard.js#534]
## Description
When using the Y Axis tick count property, the label position is incorrect when new data is loaded. 

## Steps to check or reproduce
https://codepen.io/anon/pen/pZxQPq

**Comment by netil** [comment]
Hi @TommyShoulders, fixed the issue.

![y-label](https://user-images.githubusercontent.com/2178435/43953973-c2317be8-9cd5-11e8-8cff-dcdc69526c62.gif)

You can try with nightly before the official release.
- https://github.com/naver/billboard.js/tree/nightly/dist
