### ISSUE TITLE
Improving custom shapes for points functionality

### ISSUE THREAD

**Issue by brattpurrie** [naver/billboard.js#537]
### **Description**
The custom shapes are a nice addition on the graphs. Only thing that a find missing is that the legend does not reflect the shape being hovered over. The legend will always be squares with matching colors. When in reality the shape is a triangle or something else.

### **Steps to check or reproduce**
[Example from the documentation](https://naver.github.io/billboard.js/demo/#Legend.usePoint)

Could this be improved?

**Comment by netil** [comment]
Hi @brattolo, there's already [legend.usePoint](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.legend) option to reflect the shape of the data points.
![image](https://user-images.githubusercontent.com/2178435/44013253-6cd813c4-9eff-11e8-99ad-4e0c89c51e13.png)

I think you're referring the tooltip area, which only is showing as square. Well, in that case you can add use the [tooltip.contents](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option to reflect the shape on tooltip.

Anywya, I'll be considering for the future implementation.
