### ISSUE TITLE
chart ungrouped tooltip not reconizing path points

### ISSUE THREAD

**Issue by bogdan-iuga** [naver/billboard.js#547]
## Description
The following options combination :
- point pattern containing path strings
- tooltip.grouped: false

The tooltip won't show up for those points. It will only appear for "circle","rectangle"..
## Steps to check or reproduce
https://codepen.io/iuboga/pen/gjVgLz

**Comment by netil** [comment]
Hi @bogdan-iuga, thanks for the report. 

The issue was fixed and will be out on next release.
Checkout the working demo:

![tooltip-grouped-false](https://user-images.githubusercontent.com/2178435/44319349-42e1f180-a476-11e8-9635-022735991293.gif)

**Comment by bogdan-iuga** [comment]
Just a curiosity: How did you make the points hollow on hover?

**Comment by netil** [comment]
The screenshot is when applied the new css theme, which will be the upcoming feature for the next release.
You can try this just loading the css file in below location.
- https://github.com/naver/billboard.js/tree/nightly/dist/theme

And to make hollow is easy. Just set data point element's fill to white and set something like:
```css
node {
    fill: #fff;
    stroke: red;
    storke-width: 1px;
}
```
