### ISSUE TITLE
Question: Update Label Background

### ISSUE THREAD

**Issue by serres2** [naver/billboard.js#554]
Is it possible to adjust the contents of a label outside of just adjusting the formatting?

An example would be including a background color or something of the sort to improve the label's readability.

<img width="179" alt="screen shot 2018-08-21 at 2 30 38 pm" src="https://user-images.githubusercontent.com/14003373/44424464-ce2eb600-a54e-11e8-8dfb-b435ee96d232.png">

**Comment by netil** [comment]
Hi @serres2, I'm not clear what you're referring on `label`.
You mean, [axis labels](https://naver.github.io/billboard.js/demo/#Axis.AxisLabel)? 

If so, you can style with the class name `bb-axis-y-label`, but adding background color it needs add some element(ex. `<rect>` element) manually to achieve that.

**Comment by serres2** [comment]
@netil => I am actually referencing [data labels](https://naver.github.io/billboard.js/demo/#Data.DataLabel).

Here is a larger image.

<img width="926" alt="screen shot 2018-08-21 at 3 33 51 pm" src="https://user-images.githubusercontent.com/14003373/44462228-8e60e080-a5d9-11e8-946e-25ce1275e736.png">

How would you suggest going about adding a `<rect>` element manually? Is this something that can be added via [data label formatting](https://naver.github.io/billboard.js/demo/#Data.DataLabelFormat)?

**Comment by netil** [comment]
@serres2, `data.labels.format` option is only for formatting. You can't add some other nodes from there.

I made an example adding rounded background for data labels. Checkout the working code from the below link.
- https://jsbin.com/woretiv/edit?html,css,js,output

```js
onrendered: function() {
    	const padding = 5;

    	this.main.selectAll(".bb-texts text").each(function() {
    		const rect = this.getBBox();

    		d3.select(this.parentNode)
			.insert("rect", "text")
			.attr("class", "bb-texts-bg")
			.attr("x", rect.x - padding)
			.attr("y", rect.y)
			.attr("rx", 5)
			.attr("ry", 5)
			.attr("width", rect.width + padding * 2)
			.attr("height", rect.height);
    	});
}
```

![image](https://user-images.githubusercontent.com/2178435/44506466-84c2a000-a6e1-11e8-83f9-7236f3b10318.png)

**Comment by serres2** [comment]
@netil => This works as expected on render, but if the screen is resized, the rectangle is drawn again on the canvas.

<img width="939" alt="screen shot 2018-08-23 at 6 56 18 am" src="https://user-images.githubusercontent.com/14003373/44524107-dfd4a280-a6a1-11e8-9852-42429b33ba54.png">

**Comment by netil** [comment]
@serres2, I just gave an initial idea on how to approach this.

Well, the full example code to be responsible on resizing checkout:
- https://jsbin.com/fumoqaxomu/2/edit?js,output

```js
onrendered: function() {
    const padding = 5;

    this.main.selectAll("g.bb-texts").each(function() {          
      let g = d3.select(this);
      const data = [];

      g.selectAll("text").each(function() {
        data.push(this.getBBox());
      });

      g = g.selectAll("rect").data(data);
      g.exit().remove();

      g.enter()
        .insert("rect", "text")
        .merge(g)
        .attr("class", "bb-texts-bg")
        .attr("x", d => d.x - padding)
        .attr("y", d => d.y)
        .attr("rx", 5)
        .attr("ry", 5)
        .attr("width", d => d.width + padding * 2)
        .attr("height", d => d.height);
    });
  }
```

**Comment by serres2** [comment]
@netil => AMAZING! Not only does it work, that piece of code is a great representation of how to use  D3 when needing some extra control over the chart within the DOM.
