### ISSUE TITLE
Question: How to remove axis max value

### ISSUE THREAD

**Issue by TommyShoulders** [naver/billboard.js#555]
## Description
Is it possible to set the Y axis max value then remove it again at a later time? I'm trying to view a list of percentages and want to be able to toggle between a dynamic range and 0-100%.

## Steps to check or reproduce
https://codepen.io/anon/pen/OoPrWE

**Comment by netil** [comment]
Hi @TommyShoulders, just for not try this.

```js
setTimeout(function() {
    chart.axis.max({
	   y: 100
    });
}, 1000);

setTimeout(function() {
  chart.internal.config.axis_y_max = undefined;
  chart.show();
}, 3000);
```

For the next release will be added new API(#502) to handle this issue.
With the new API, the latter code block to rever y axis max value and redrawing it, can be done as:
```js
chart.config("axis.y.max", undefined, true);
```
