### ISSUE TITLE
How to support custom point consisting of svg shape tag with children

### ISSUE THREAD

**Issue by bogdan-iuga** [naver/billboard.js#562]
## Description
I'm trying to add some custom points to the chart. I can use [svg shape tag interpreted as string](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.point).
Now, if I use something like `<polygon points='2.5 0 0 5 5 5'></polygon>` [like in this example](https://naver.github.io/billboard.js/demo/#Point.CombinationPoints), everything works out just fine. 

## My question is: 
how can I use a svg shave tag with children? For example: a
```
<g>
    <circle cx='0' cy='0' r='10'></circle>
    <rect x='-5' y='-5' width='10' height='10'></rect>
</g>
```

If I try to add this string `"<g><circle cx='0' cy='0' r='10'></circle><rect x='-5' y='-5' width='10' height='10'></rect></g>"` then billboard will only add the encapsulating `<g>`, and the points will be [an empty `<g>`](https://imgur.com/RMEBBF7).

One thing I can do is to append the body `"<circle cx='0' cy='0' r='10'></circle><rect x='-5' y='-5' width='10' height='10'></rect>"` to the `<g>` from `<defs>`, in `onrendered`, but that means you would have to do that for every custom point you add, so I'm wondering if you have something else in mind?
[example what `<defs>` contains at inspect](https://imgur.com/PEbaKmX)

## Codepen example
https://codepen.io/iuboga/pen/JaXrQN

**Comment by netil** [comment]
Hi @bogdan-iuga, there's no way doing that for now, but it seems nice implement this feature.
I'll try do that for next release~

**Comment by netil** [comment]
Implemented the feature. From this changes, will be allowing set node with child nodes.

```js
point: {
    pattern: [
	    "<g><circle cx='10' cy='10' r='10'></circle><rect x='5' y='5' width='10' height='10'></rect></g>"
    ]
}
```

![image](https://user-images.githubusercontent.com/2178435/44703549-08f69800-aad3-11e8-9379-6155a8591bf3.png)

Try the nightly:
- https://github.com/naver/billboard.js/tree/nightly/dist

**Comment by bogdan-iuga** [comment]
Nice! 
I appreciate your quickness to check out the new issues.
