### ISSUE TITLE
'Reset Zoom' button covers chart line.

### ISSUE THREAD

**Issue by jeesim2** [naver/billboard.js#574]
'Reset Zoom' button covers chart lines.

### Origin view
![image](https://user-images.githubusercontent.com/1100831/44963192-7edf8100-af63-11e8-8a74-0f3b4fadbd26.png)

### Zomed view
![image](https://user-images.githubusercontent.com/1100831/44963205-94ed4180-af63-11e8-8614-413ebd2c7b25.png)

How about replace ![image](https://user-images.githubusercontent.com/1100831/44963239-ebf31680-af63-11e8-8453-ef9d6f3c6a45.png) with simple small button?

some icons, ![image](https://user-images.githubusercontent.com/1100831/44963252-00cfaa00-af64-11e8-9857-be2d7f50582c.png) ![image](https://user-images.githubusercontent.com/1100831/44963263-0cbb6c00-af64-11e8-864b-59b857757cf0.png)

**Comment by netil** [comment]
Hi, @jeesim2 

There's [zoom.resetButton.text](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.zoom) option to customize text value.

```js
zoom: {
    enabled: {
	 type: "drag"
    },
    resetButton: {
	 text: "u"  // <-- will display 'u' instead of default 'Reset Zoom' text
    }
}
```
And if you need style differently than the default value, try adding css rule for below dom structure.
```html
<div class="bb-button">
    <span class="bb-zoom-reset" style="">u</span>  <-- the text value set -->
</div>
```

**Comment by jeesim2** [comment]
@netil That looks good enough. Thanks for the quick response!!
