### ISSUE TITLE
Tooltip vertical line does not displayed on line+scatter combination chart

### ISSUE THREAD

**Issue by jeesim2** [naver/billboard.js#577]
#### Tooltip vertical line does not displayed on line+scatter combination chart.
https://codepen.io/anon/pen/NLjOex
![image](https://user-images.githubusercontent.com/1100831/45007802-7312be00-b03a-11e8-8433-4e593b963744.png)
```
bb.generate({
  data: {
    columns: [
	      ["data1", 30, 200, 100, 400, 150, 250],
       	["data2", 50, 0, 10, 40, 15, 25]
    ],
    types: {
      data2: "scatter"
    }
  },
  point: {
    r : 10
  }
});
```

#### When set both type to 'line' , vertical line displayed.
https://codepen.io/anon/pen/QVvZYE
![image](https://user-images.githubusercontent.com/1100831/45007853-a6554d00-b03a-11e8-9452-41ead08c296a.png)
```
bb.generate({
  data: {
    columns: [
	      ["data1", 30, 200, 100, 400, 150, 250],
       	["data2", 50, 0, 10, 40, 15, 25]
    ]
  },
  point: {
    r : 10
  }
});
```

**Comment by netil** [comment]
Hi @jeesim2, this is the default behavior not a bug. When chart contains `bubble`, `scatter` or `arc`(pie, donut, gauge), by default focus grid line isn't be showing.

So, try this instead.

```css
// hide line path
.bb-lines-data2 path {
    visibility: hidden;
}
```
```js
bb.generate({
    data: {
	    columns: [
		    ["data1", 30, 200, 100, 400, 150, 250],
		    ["data2", 50, 0, 10, 40, 15, 25]
	    ]
    },
    point: {
	    r : 10
    }
});
```

**Comment by jeesim2** [comment]
@netil I mean not the series' point path, 

but  this vertical line 
`bb-xgrid-focus` 
![image](https://user-images.githubusercontent.com/1100831/45012950-5b483380-b054-11e8-8cf0-87c97a164a05.png)
![image](https://user-images.githubusercontent.com/1100831/45012972-6733f580-b054-11e8-9fe1-230e8eb238b7.png)

**Comment by netil** [comment]
@jeesim2, as I explained above, `x-grid-focus` line isn't being displayed for certain types by default.
`x-grid-focus` line node exists, but the x and y coordinates won't be updated for that types.

So, to fulfill your necessity, just hiding line path will be behave exactly as you want.

Checkout the example:
- https://jsbin.com/zejohar/2/edit?html,css,js,output

![lines](https://user-images.githubusercontent.com/2178435/45017323-4d99aa80-b062-11e8-909e-f7cdb0726cff.gif)

I'll take considering enabling grid line showing for future release.

**Comment by jeesim2** [comment]
Ah, I understand . I'll try to what says.
Thanks again.
