### ISSUE TITLE
Error occured during regions remove

### ISSUE THREAD

**Issue by tahuba** [naver/billboard.js#578]
## Description
I want to delete the regions and I get an error that the `$$` variable does not have the `getOption()` method.

The error is occuring with the Billboard version 1.6.x.

## Steps to check or reproduce

```
// ...
chart.regions.remove();
```

Error stack:
```
core.js:1673 ERROR TypeError: $$.getOption is not a function
    at Chart.remove (billboard.js:12297)
    // ...
```

The error points to this line: https://github.com/naver/billboard.js/blob/4d84cf630d8860a04d3a1935b74423718ef6f1a7/src/api/api.region.js#L96

**Comment by netil** [comment]
Hi @tahuba, thanks for the report.
This will be out in patch release.

**Comment by tahuba** [comment]
Hi @netil ,

the fix was very fast. Thank you very much!
