### ISSUE TITLE
Stack arcs in a gauge chart

### ISSUE THREAD

**Issue by jeroen-hoekstra** [naver/billboard.js#580]
## Description
Is it possible to stack the arcs in a gauge chart. In the Codepen example each arc starts at it's minimal value of 0. What I need is that 'data1' starts at 0 and ends at 35 and 'data2' starts at 35 and ends at 55. Is this possible? Or can you configure a donut chart to visually look like a half circle? Thanks!

## Steps to check or reproduce
[Codepen example](https://codepen.io/anon/pen/EeXJJV)

**Comment by jeroen-hoekstra** [comment]
@netil thanks for the reply. The image shows what I have created with D3. This would indeed be a nice feature for the gauge chart or having this option for the donut chart.

![gauge](https://user-images.githubusercontent.com/42991987/45085103-24c7f280-b100-11e8-8ed7-23bb06eba949.png)

**Comment by jeroen-hoekstra** [comment]
Is it maybe possible to adjust the arcs in an onrendered callback, like doing some animation to move the arcs to the correct position?

**Comment by netil** [comment]
Hmm... there's no way for now. IMO, it should being implemented as a feature for correct approach.
