### ISSUE TITLE
How to develop new chart type as plugin

### ISSUE THREAD

**Issue by mageshveeraa** [naver/billboard.js#586]
## Description
I want gantt chart like chart, so I would like to develop as plugin in billboard js. So, I can use the same axis api from billboard. 

Any possibilities now? Any sample plugin would be nice.

**Comment by mageshveeraa** [comment]
@netil  Thanks for the reply. Yeah, I will check the possibilities to splitting different chart types.

**Comment by netil** [comment]
@mageshveeraa, it took long time for this :)

Take a look on doc and the implementation:
- [Plugin Interface Documentation](https://github.com/naver/billboard.js/wiki/Plugin-Interface)
- [The "Stanford Diagram" plugin source](https://github.com/naver/billboard.js/tree/master/src/plugin)

**Comment by mageshveeraa** [comment]
@netil  Thanks for the effort. I will check it out.
