### ISSUE TITLE
Center tick line relative to axis line

### ISSUE THREAD

**Issue by jgoley** [naver/billboard.js#588]
I'm wondering if there's an option to center the tick line relative to the axis line. And increase the width/height (depending on which axis). As in this image below. I suppose there is a `centered` option but looks like that may be related to how the text is positioned with tick line?
<img width="579" alt="screen shot 2018-09-18 at 2 26 04 pm" src="https://user-images.githubusercontent.com/4105343/45708400-5c4a8c00-bb4f-11e8-9e3b-58d4dc33eaa1.png">

**Comment by netil** [comment]
Hi @jgoley, there's no option for this for now.
The `tick.centered` is for when the axis type is `category`.

So, to fulfill your needs for now, it should manipulate tick's value manually.

```js
var chart = bb.generate({
  data: {
    columns: [
      ["data1", 30, 200, 100, 400, 150, 250],
      ["data2", 130, 100, 140, 200, 150, 50]
    ]
  },
  onrendered: function() {
    this.main.selectAll(".tick line")
      .attr("x1", function() {
         if (this.getAttribute("x2") !== "0") {
           return 6;
         } 
      })
      .attr("y1", function() {
         if (this.getAttribute("y2") !== "0") {
           return -6;
         } 
      })
  }
});
```

- working demo: https://jsbin.com/fiketup/2/edit?html,js,output

![2018-09-24 2 34 16](https://user-images.githubusercontent.com/2178435/45938654-f22a5f00-c006-11e8-9b2b-ac82086b29a9.png)

**Comment by jgoley** [comment]
@netil Thanks! 
I had to change it up slightly to check for the attribute:
```javascript
 return this.getAttribute("x2") && this.getAttribute("x2") !== "0" ? 6 : 0
```
