### ISSUE TITLE
Rotated x axis ticks

### ISSUE THREAD

**Issue by jeroen-hoekstra** [naver/billboard.js#596]
I would like to have the x-axis ticks rotated, so I set the tick rotate property to 135 which gave me the result as shown in the image.

![ticks](https://user-images.githubusercontent.com/42991987/46191539-3912a000-c2f8-11e8-8115-309edddcf91b.png)

What I would like to see is the shown in the image below.

![ticks](https://user-images.githubusercontent.com/42991987/46191988-d7ebcc00-c2f9-11e8-9798-76e1743bcb2c.png)

As you can see the text should be rotated as well. Is this possible?

**Comment by netil** [comment]
try `rotate:-45`

**Comment by jeroen-hoekstra** [comment]
@netil that worked, thanks! Also had to adjust the bottom padding.
