### ISSUE TITLE
The mid value of the AreaRangeChart tooltip is not displayed correctly

### ISSUE THREAD

**Issue by ChoeYoonSeop** [naver/billboard.js#597]
## Description
the mid value is showing "{high},{low}" instead "{mid}"

![image](https://user-images.githubusercontent.com/10969212/46193710-0be6e180-c33a-11e8-9a9a-d1a3e5149668.png)

## Steps to check or reproduce
https://naver.github.io/billboard.js/demo/#Chart.AreaRangeChart @.@

**Comment by netil** [comment]
Thanks for the report. Tooltip is erroneously concatenating `high` value in the mid value.
