### ISSUE TITLE
bb v1.6 now has inline styling for circle stroke?

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#599]
## Description
In the charts we create, we commonly apply css after the chart has been drawn via javascript. Due to the nature of our dashboards, the charts are immediately resized or interacted with in some other way.

I've noticed with billboard 1.6 that theres now some inline `stroke` styling being applied to the `bb-circle` class and our css applied after-the-fact no longer works. This is causing some issues with our dashboards. 

Any idea how to get around this? I'd really like to use the new features in v1.6.

## Steps to check or reproduce

I made a couple fiddles that compare the same code in v1.5 and v1.6.

### Using billboard v1.5:
The red stroke will be maintained
https://jsfiddle.net/irislieuw/Lyteqp0j/

### Using billboard v1.6 
The red stroke shows up until the chart is resized, data is toggled, etc. 
https://jsfiddle.net/irislieuw/z61dvsa4/

**Comment by irislieuw** [comment]
Before resizing, the circle has `stroke: red` applied
![image](https://user-images.githubusercontent.com/11950094/46484088-e7618e00-c7ad-11e8-8a0c-e380219a54af.png)

Immediately after resizing
![image](https://user-images.githubusercontent.com/11950094/46484137-006a3f00-c7ae-11e8-856f-d01290825fdb.png)

**Comment by netil** [comment]
Hi @irislieuw, the `stroke` style on `<circle>` elements were added to make `theme` style feature.
For your case, using `onrendered` option will solve the issue.

Try this:
```js
// Script
var chart = bb.generate({
  data: {
    columns: [
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 50, 20, 10, 40, 15, 25]
    ]
  },
  bindto: "#LineChart",
  point: {
  	r: 6
  },
  onrendered: function() {
	this.main.selectAll(".bb-circle-3")
    	  .style("stroke", "red")
          .style("stroke-width", "0.7%");
  }
});
```

**Comment by netil** [comment]
@irislieuw, reopen this issue if didn't worked.
