### ISSUE TITLE
Chart with custom points throws errors in IE11/Edge

### ISSUE THREAD

**Issue by bogdan-iuga** [naver/billboard.js#601]
## Description
When trying to add custom points to a billboard.js chart in IE11/Edge, it throws :

> TypeError: Unable to get property 'length' of undefined or null reference
> at insertPointInfoDefs ...

![resulting in a blank chart](https://i.imgur.com/lcBVHao.png)

**Comment by netil** [comment]
Hi @bogdan-iuga, thanks the report and PR!
I'll be checking this.
