### ISSUE TITLE
Bind several charts to the same legend template

### ISSUE THREAD

**Issue by pvictor** [naver/billboard.js#605]
## Description
Hi, do you think it's possible to bind several charts to the same legend template ? If charts have the same data, it'll be a cool feature. I think it's possible with a complete custom legend (like in your exemple https://naver.github.io/billboard.js/demo/#Legend.CustomLegend), but it will be nice with the template option.

## Steps to check or reproduce
Here is a pen (just two pie charts and a unique legend, legend works only for the last pie generated) : https://codepen.io/pvictor-r/pen/yRMmGz

Thank you very much,

Victor

**Comment by pvictor** [comment]
Hi @netil ,
I admit this is a special case.
I have a project to visualize the number of tweets mentioning disrupted traffic on the Parisian subway, you can see it here (sorry it's in French) : https://dreamrs.github.io/tweets-transports/

What I would like to be able to do is have the legend above connected to all the graphics, to toggle series for example.

But I don't know if this deserves an implementation in billboard.

In any case, thank you for your hard work, this library is excellent !

Victor

**Comment by netil** [comment]
@pvictor, I got it what you want.

As having same data names for all generated charts, you want to make top positioned legend to be interacting all generated charts, right?

![image](https://user-images.githubusercontent.com/2178435/46858708-dddbc400-ce46-11e8-9a2c-200f9e16af7a.png)

I don't think that this is a general feature to be implemented. Is much better to approach as service code.
This will work as your needs.

```js
// (1) Set legend template option for the 1st chart element only
bb.generate({
	...
	legend: {
		contents: {
			bindto: "#legend",
			template: "<span style='color:#fff;padding:10px;background-color:{=COLOR}'>{=TITLE}</span>"
		}
	}
});

bb.generate(...);
bb.generate(...);
...

// (2) Bind new event handler to handle all generated charts
d3.selectAll("#legend span")
        .on("mouseover mouseout click", () => {
            const id = d3.event.target.innerHTML;
            const type = d3.event.type;

        	bb.instance.forEach(v => {
        		switch (type) {
                    case "mouseover":
                    	v.focus(id);
                    	break;
                    case "mouseout":
                    	v.revert();
                    	break;
                    case "click":
                    	v.toggle(id);
                }
            });
        });
```

**Comment by pvictor** [comment]
Perfect, it works great.

Thank you!
