### ISSUE TITLE
billboard.js 문의

### ISSUE THREAD

**Issue by alsrnkmg** [naver/billboard.js#606]
## Steps to check or reproduce

```js
var aa = new Array(10,20)
for (i=0;i<aa.length;i++){
bb.generate({
    bindto: "#chart",
    data: {
        columns: [
            ["data1", aa[i]]{
          
          }],
            
        ],
        types: {
          data1: "line",
          data2: "area-spline"
        },
        colors: {
          data1: "red",
          data2: "green"
        }
    }
});
}
```

순서대로 10,20 찍고 싶은데 for문을 돌려도 안되네요
어떻게 해야하나요?

**Comment by netil** [comment]
Hi @alsrnkmg, I can't get what is your purpose exactly.
- If you want to display two charts sequentially at same time, you need to have another binder element.
- If you want to display the array data `10,20`, just do without loop
```js
columns: [
    ["data1"].concat(aa)
],
```

**Comment by alsrnkmg** [comment]
function Region(){			
		var list1 = new Array('<?php echo $chkValue?>');
		
	
		var chart = bb.generate({
			
			  data: {
				
			    columns: [

					["체중 %"].concat(list),
					["체지방 %", 100]
			    ],
			    
			    axes: {
			      	"체지방 %": "y2"
			    }
			  },
			  axis: {
			    y2: {
			      show: true
			    }
			  },
			 
			  bindto: "#Region"
			});
		
	}		

DB에서 불러온  PHP배열값을 그래프에 보여주고 싶습니다. 
근데 위에같이 하면 안되네요

**Comment by netil** [comment]
I don't know the "not working" here.
If the values are set correctly, will work as the example I made:
- https://jsbin.com/weducir/2/edit?html,js,output

![image](https://user-images.githubusercontent.com/2178435/46846276-1dd88200-ce1a-11e8-8d93-1a165103d0a5.png)

**Comment by alsrnkmg** [comment]
function Region(){			
		var list2 = [];
		<? foreach (chkValue as key => val) {?> 
		list2 += ","+val 
		<?}?> 
		   alert(typeof(list2)); 
		   
		var chart = bb.generate({
			
			  data: {
				
			    columns: [

					["체중 %"].concat('list2'),
					["체지방 %", 100]
			    ],
			    
			    axes: {
			      	"체지방 %": "y2"
			    }
			  },
			  axis: {
			    y2: {
			      show: true
			    }
			  },
			 
			  bindto: "#Region"
			});
		
	}	

위의 소스로 반영을 해보면 반영이 되지 않네요
list2의 값을 로그로 찍어보면 
,75.0,56.0,45.0 이 값이 찍히고 
string형으로 찍히네요 
그래프로 반영하려면 object만 가능한가요?
