### ISSUE TITLE
multiline title issue

### ISSUE THREAD

**Issue by alwaysrejoice** [naver/billboard.js#612]
## Description

Hi,
I am trying to make multiline for title manually, but I found when I try to resize the window, the multiline title change back to one line. can you find out what's the problem there? following is the sample code that reproduce the issue.
https://jsfiddle.net/y09cb1x5/2/
## Steps to check or reproduce

<!doctype html>
<html>
<head>
  
    <link rel="stylesheet" href="billboard.css" />
		<script type="text/javascript" src="d3.v4.js"></script>
		<script type="text/javascript" src="jquery-3.3.1.min.js"></script>
		<script type="text/javascript" src="billboard.js"></script>

</head>
<body>
    <div id="BarChart"></div>
    <script>
        
        var chart = bb.generate({
        size:{
            height: 350,
            width: 500
            },
          data: {
            columns: [
            ["data1", 30, 200, 100, 400, 150, 250],
            ["data2", 130, 100, 140, 200, 150, 50]
            ],
            type: "bar"
          },
          bar: {
            width: {
              ratio: 0.5
            }
          },
          title:{
            text: "Title text multiline testing Title\ntext multiline testing Title text multiline testing"
          },
          bindto: "#BarChart",
          onrendered: function(){
            var _title=this.title 
            console.log(_title.text())
            var multiline=_title.text().split("\n")
            _title.text('')
            var x = _title.attr('x')
            var y = _title.attr('y')
            multiline.forEach(function(v,i){
                var line=_title.append('tspan').text(v)
                var tt=line.node().getComputedTextLength()
                line.attr('x',275-(tt/2)).attr('y',Number(y)+i*15)
            })  
          }
        });

    </script>
</body>

![bbtitle](https://user-images.githubusercontent.com/8529933/47181364-cf7f2380-d2f0-11e8-98ce-9603a7223683.png)
After resize the window:
![bbtitle_resize](https://user-images.githubusercontent.com/8529933/47181456-06edd000-d2f1-11e8-93e7-315c119fd99d.png)

**Comment by netil** [comment]
Hi @alwaysrejoice, for your case I recommend approach using normal HTML.
With the title option, the `title` text will be displayed via SVG's text element and the handling of line breaking is not easy task as the HTML's `<br>` tag.

So, rather than using `title` option, just put title value using HTML tag above the chart element.

```html
    <div style="width:500px;margin-bottom:-10px;text-align:center">
      Title text multiline testing Title<br>
      text multiline testing Title text multiline testing
    </div>
    <div id="BarChart"></div>
```
