### ISSUE TITLE
time series issue

### ISSUE THREAD

**Issue by serzhiio** [naver/billboard.js#615]
i've deeped a bit in library and found very freustrating how it keeps time points.
Actually its not a real timeseries...
```
  data: {
    x: "x",
    columns: [
	["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
	["data1", 30, 200, 100, 400, 150, 250],
	["data2", 130, 340, 200, 500, 250, 350]
    ]
  },
```
Here we need to have point for all time points which should be defined!
...but time is constant and it flows with or without points, IMO data should be defined like below:
```
  data: {
    x: "x",
    columns: [
	["data1", [132456721,30], [132456756,200], [132456777,100], [132456888,250]],
	["data2", [132456333,130], [132456337,340], [132466856,200]]
    ]
  },
```
P.S.: Each time series datapoint has [**time**] and [**value**] values.

**Comment by netil** [comment]
@serzhiio, date values for x Axis, can be defined as: string, number or Date object values when they're valid to be parsed as datetime.

Here is the example on representing, datetime values starting from 2018-01-01 to 03.

```js
data: {
	x: "x",
	columns: [
		["x", 1514764800000, new Date("2018-01-02"), "2018-01-03"],
		["data1", 30, 200, 100],
		["data2", 130, 340, 200]
	]
},
```

The interface value you commented isn't allowed way for the library. 
```js
    columns: [
	["data1", [132456721,30], [132456756,200], [132456777,100], [132456888,250]],
```

If you need each data to be based on different x Axis, you can deal with `xs` option I already commented from previous issue.
