### ISSUE TITLE
Time Series - Scale & Ticks

### ISSUE THREAD

**Issue by ataft** [naver/billboard.js#628]
I understand how to use the `axis.x.type='timeseries'` and `axis.x.tick`, but would really love for Billboard to automatically scale the ticks to fix the screen and/or zoom focus.

In this d3 block, see how it gets more granular automatically as you zoom in:
https://bl.ocks.org/mbostock/4015254

Here's an example with Highcharts:
https://www.highcharts.com/demo/line-time-series

Lastly, NVD3 can do this but doesn't have good documentation for it. In fact, a lot of people are still using NVD3, which hasn't had a release in over a year, just for it's timeseries chart. NVD3 looks slick out-of-the-box too, but the timeseries was why I used it for a while before realizing that it's not active.

**Comment by netil** [comment]
Hi @ataft, thanks for the request. It seems useful having this feature.

![auto-tick](https://user-images.githubusercontent.com/2178435/47539796-0bc40c80-d90d-11e8-8538-321ac2772b4b.gif)

Recently there're lots of feature request, which needs to be organized based on the priorities.

**Comment by ataft** [comment]
Hi @netil, thanks for all the recent improvements in the 1.7 release!

Do you have an idea of where this is on the priority list, perhaps even an estimated release date? I still have to use NVD3 because of it's time-series capabilities, but would love to drop that library since it hasn't had a release since August 2017.

Thanks!

**Comment by netil** [comment]
Hi @ataft, thanks!

You can find rough release plans & schedules from [milestone](https://github.com/naver/billboard.js/milestones).
The priority are set depending the user's reaction or just simply from my understandings.

So, please give us lots of feedback to put some feature as high priority :smiley:

**Comment by ataft** [comment]
Thanks, but I don't think the billboard.js community is going to bump this up in priority for one major reason, they don't use timeseries extensively. Any developer that needs to do time-based charting simply isn't going to choose Billboard. They're either going to use Highcharts (not free though) or NVD3 (not maintained). Thus, you won't get feedback because people are disqualified from using Billboard because of time-series charting. But look at how many people are still using the unmaintained NVD3 libarary: https://www.npmtrends.com/nvd3-vs-billboard.js. The way I look at it, it's an opportunity to pick up a LOT of new users.

Anyhow, no pressure, just trying to make some points to get a feature I'd love. Thanks again for all your hard work!

**Comment by netil** [comment]
Thanks @ataft for the sincere opinion.

Everyone's necessities are different and all have their own priorities. I referred `community`, because that's the basic source of taking on what to be done.
Of course, as you mentioned, with the new features, improvements is the new opportunity to get new users. But currently there's limited resource to handle that.

One thing that I want to request is, please keep showing opinions, interests or some contribution to make some improvements. Because they're the main source on motivating this project to move forward.

**Comment by nirmal93guna** [comment]
Hi @netil, I'm facing the same issue and I would like this feature to be present as well. I could see that the feature is not yet completed in the milestone and I would be willing to contribute towards adding the feature if no one is working on it.

**Comment by ataft** [comment]
Awesome, thanks @netil! It looks great in my initial testing and I'll continue to test. I set `x.tick.fit = false` and it looks great, but when I zoom in very close to just a couple data points, it looks like this:

![image](https://user-images.githubusercontent.com/11670864/53901994-1ac27600-3ff5-11e9-9032-12521fc7f145.png)

As you can see, there are only 2 points of data, but each date shows up many times. It's not a big issue at all, and perhaps I'm misusing it.

Thanks again!!!

**Comment by netil** [comment]
@ataft try limiting the tick count using [axis․x․tick․count](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4count) option.

And if you are zooming by `drag`, you can zoom-in deeper than the actual data value. If you zoom by `wheel`, will see at certain point will stop going more deeper.
