### ISSUE TITLE
Tooltip line and optional grid line not correctly positioned when zoomed in

### ISSUE THREAD

**Issue by waspo** [naver/billboard.js#639]
## Description
When you zoom in the tooltip line showing the current value is not positioned correctly. The same for the OptionalXGridLine. It stays on the same absolute position ond not at the value itself.

## Steps to check or reproduce
1. Open example with zoom functionality: https://naver.github.io/billboard.js/demo/#Interaction.Zoom
2. Use scroll wheel to zoom into the chart (1...2 steps not more)
3. Move cursor horizontally and check position of vertical tooltip line
4. If you don't see the tooltip line you might have zoomed in too deep and be out of the range

**Comment by netil** [comment]
Hi @waspo, thanks for the report. I'll check that.

**Comment by waspo** [comment]
Hi @netil, great to hear that you're on track. Thank you!

**Comment by netil** [comment]
I think the issue was fixed by #906 & #926.
Try with the [nightly](https://github.com/naver/billboard.js#nightly-version). If not fixed, plz reopen the issue.
