### ISSUE TITLE
chart.tooltip.hide() does not work

### ISSUE THREAD

**Issue by ataft** [naver/billboard.js#640]
## Description
After the chart is created, `chart.tooltip.hide()` does not do anything.

## Steps to check or reproduce
https://codepen.io/anon/pen/zMrvOr

**Comment by netil** [comment]
@ataft, I can't get the intention from the codepen. There's nothing to hide at the beginning. 
To make sense, tooltip is displayed at the initialization and then hide the tooltip.

```js
bb.generate({
    ...
	tooltip: {
		init: {
			show: true,
			x: 2,
			position: {
				top: "15px",
			        left: "100px"
		        }
		}
	}
});

setTimeout(() => {
	chart.tooltip.hide();
}, 500);
```

**Comment by ataft** [comment]
Oh, this is my mistake. I thought `tooltip.hide()` was used to disable the tooltip, but I see my error.

I was looking for a way to disable options (tooltip, zoom, etc.) without redrawing the chart. Is there a best way to do that?

**Comment by netil** [comment]
For that, set `interaction.enabled=false`.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.interaction
