### ISSUE TITLE
New points "swoop" in when added to existing data.

### ISSUE THREAD

**Issue by nwpappas** [naver/billboard.js#648]
## Description

When adding a new point to an existing data column, the new point appears in the upper-left of the chart and "swoops" to the right to its value.

Looking at the example here - https://naver.github.io/billboard.js/demo/#Data.LoadData - the 6th update (which loaded a new point into an existing data column) exhibits the same behavior.

## Steps to check or reproduce

Codepen: https://codepen.io/nwpappas/pen/ZmBgvz

1 second after loading a new point will be added to 'data1'. The point appears in the upper-left and "swoops" to the right to its resting spot.

## Expected Behavior

I would expect the new point to appear in place as the graph animated to the left, in order to make room for the new point.

**Comment by netil** [comment]
@nwpappas done. Checkout the `nightly`.
- https://github.com/naver/billboard.js/tree/nightly/dist

![point-transition](https://user-images.githubusercontent.com/2178435/48692933-1bd4c080-ec1b-11e8-9bb5-b0b158341c3a.gif)

**Comment by nwpappas** [comment]
Awesome!

What are you thoughts about moving the chart to the left _first_ and then adding the new point; or fading the new point in shortly after the chart begins the shift to the left?

In your example, the line connecting points 2 & 3 creates an odd loop as the graph animates to the left. It is understandable why this happens, but I can see the potential for it being distracting on a graph this is updating at a frequent interval.

**Comment by netil** [comment]
@nwpappas, I know what you're saying, but I don't think is a serious issue like points.
I'll be taking this in consideration for future release.
Thanks for the opinion. :)
