### ISSUE TITLE
Zoom goes back to normal after chart.zoom()

### ISSUE THREAD

**Issue by UdgeMe** [naver/billboard.js#654]
I had this as part of my last question but I prefer opening an issue about it.
There is an issue occuring if you programmatically force the zoom on a generated chart, and then you make a mousemove on the chart (to zoom/unzoom or to move right or left), the zoom of the chart resets to normal.

You can try it in the [playground](https://naver.github.io/billboard.js/playground/) with this in the text editor :
```javascript
{
    "data": {
      x: "x",
        "columns": [
            ["A", 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            ["x", "2018-11-13", "2018-11-12", "2018-11-11", "2018-11-10", "2018-11-09", "2018-11-08", "2018-11-07", "2018-11-06", "2018-11-05", "2018-11-04", "2018-11-03", "2018-11-02", "2018-11-01", "2018-10-31"]
        ],
    },
    "axis": {
        "x": {
          "type": "timeseries"
        },
    },
    "zoom": {
        "enabled": true,
    }
}
```

And try forcing the zoom (in the browser console for example) with : 
`chart.zoom([new Date("2018-11-06 00:00"), new Date("2018-11-10 00:00")]);`
or
`chart.zoom(["2018-11-06", "2018-11-10"]);`

Thanks in advance

**Comment by netil** [comment]
Hi @UdgeMe, confirmed the issue. To solve your previous posted issue, this might be solved.

**Comment by UdgeMe** [comment]
Hello @netil, thanks for your investigation and thanks for your hard work.

**Comment by Punkiebe** [comment]
We have the same issue.
If the zoom is enabled on a graph, and you apply a zoom to it. 
That if you want to zoom in or out, that he starts from where you placed the zoom and doesn't go first to the non zoomed graph.
Currently yhis makes for a very strange user experience.

You could even say when the zoom isn't enabled, that he then just stays at the zoomed area and you can't zoom in or out.
