### ISSUE TITLE
데이터 영역이 자동으로 잡히는것을 고정영역으로해서 위에서부터 쌓이게 하는 방법이 있나요?

### ISSUE THREAD

**Issue by choisc0318** [naver/billboard.js#658]
바형 차트에서 데이터 양에 따라 데이터의 영역이 잡히는데 영역크기를 지정하고 위에서부터 쌓이는 방식으로 변경할 수 있나요?
![untitled-2](https://user-images.githubusercontent.com/23649960/48670293-b3250f80-eb58-11e8-8179-f5205b98e74a.png)

**Comment by netil** [comment]
I'm not sure on stacking from the top to the bottom flow.
The chart's height is automatically calculated depending the data lengths and there's no functional option to make this.

If just wants to display data from the top and having some gaps on the bottom, maybe you can add `null` values to increase those gaps.
![image](https://user-images.githubusercontent.com/2178435/48682349-44dd5d00-ebeb-11e8-9e30-8bea3e96e251.png)

```js
bb.generate({
	data: {
		columns: [
			["data1", 30, 200, 100, null, null, null],
			["data2", 50, 20, 10]
		],
		type: "bar",
   		 groups: [
    			["data1", "data2"]
    		]
	},
	axis: {
		rotated: true
	}
});
```

Or if you want just setting heights value, you can do via setting `height` property to chart's holder element or use [`size`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.size) option for that.

```html
<!--Set the chart's height. This will limit chart not surpassing 300px -->
<div id="chart" height="height:300px"></div>
```
