### ISSUE TITLE
chart.data.shown() is invalid after chart.toggle(id) is called

### ISSUE THREAD

**Issue by DemersM** [naver/billboard.js#662]
On legend click, I use a function that toggle the data, but the chart.data.shown() is not updated accordingly.

To reproduce: 

https://jsfiddle.net/y09cb1x5/3/

**Comment by netil** [comment]
Hi @DemersM, is because when you click the legend and executing `.data.shown()` right after, it means invoking during the element's transition.

To make work as your expectation, do :
```js
legend: {
	item: {
		onclick: function(id) {
			chart.toggle(id);

			setTimeout(() => {
			    console.log(chart.data.shown())
			}, 0)
		}
	}
}
```

**Comment by DemersM** [comment]
Ok! Thanks for your reply!
