### ISSUE TITLE
onrendered - this.api.data.values() error

### ISSUE THREAD

**Issue by DemersM** [naver/billboard.js#665]
there is an error when we try to use `this.api.data.values()` in the `onrendered` callback function

https://jsfiddle.net/y09cb1x5/5/

**Comment by netil** [comment]
@danelkhen, the use of `this.api` isn't adequate approach accessing private members.
Anyway, there're 2 options to solve this.

```js
function onrendered() {
   // (1)
    console.log(this.api.data.values.call(this.api, "data1"));

   // (2)
   setTimeout(function() {
       console.log(chart.data.values("data1"));
   }, 0);
}
```

**Comment by DemersM** [comment]
Thank you for your reply. I understand your point.

Won't it be more easy/logical to pass the chart instance in every callback?

function onrendered(chart) {
    chart.data.values("data1");
}

**Comment by netil** [comment]
Roughly speaking, there're context inconsistency across all callbackish options. (And is quite complicate change to not break unexpected incompatibility, but at some point this should be arranged)

You can access via `this` keyword within `onrendered` callback, which is referring to `ChartInternal` instance.
