### ISSUE TITLE
Option axis.x.tick.count 0 not working

### ISSUE THREAD

**Issue by DemersM** [naver/billboard.js#673]
It seems the option axis.x.tick.count: is not working with the value 0:

```
axis: {
    x: {
        tick: {
            count: 0
        }
    }
}
```
https://jsfiddle.net/y09cb1x5/5/

Is there another option that could be used to hide all the x axis tick lines and text?

**Comment by HYU-LeeHG** [comment]
axis: {
  	 x: {
        show : false
    }
  },

I think it would be work.

**Comment by DemersM** [comment]
@HYU-LeeHG 

This option hides the x axis line. I only want to hide the ticks and the texts

**Comment by HYU-LeeHG** [comment]
@DemersM 

![image](https://user-images.githubusercontent.com/31696105/49025650-7784e800-f1df-11e8-888f-24590a654c1b.png)

This is what you want?

then, code is

```
axis: {
  x:{
    tick: {
      values : [], 
    } 
  }
}

```

**Comment by DemersM** [comment]
Exactly! Thanks a lot for your help!
