### ISSUE TITLE
Billboard on mobiles - on small screens

### ISSUE THREAD

**Issue by sinisarudan** [naver/billboard.js#675]
## Description

**PieChart** getting too small on small screens
on big screen - both Bar and Pie Charts look good:
![screen shot 2018-11-26 at 17 17 30](https://user-images.githubusercontent.com/1769627/49026932-59979300-f19f-11e8-99c0-b4d2edf9f121.png)

while when resizing a screen or watching it on a mobile phone,
Bar Chart doesn't lose visual integrity, yet Pie Chart becomes unreasonably small compared to legend, to bar chart and to available horisontal space for displaying it:

![screen shot 2018-11-26 at 17 18 02](https://user-images.githubusercontent.com/1769627/49027017-864baa80-f19f-11e8-9f3d-a3de5b8bb961.png)

## Steps to check or reproduce
if needed I can provide code, but it's a simple data for PieChart generation

**Comment by sinisarudan** [comment]
the option:
`chart.resize({height: 600, width: 600})`
is not a good solution even though it forces the pie chart to stay big
but then it is not responsive, even the legend stays fixed, not-breaking and resizing:

![image](https://user-images.githubusercontent.com/1769627/49028339-6e295a80-f1a2-11e8-916d-ba52de587aa0.png)

**Comment by sinisarudan** [comment]
another issue visible above is tick labels being broken to unreadable on small screens:
![image](https://user-images.githubusercontent.com/1769627/49072837-69f84e00-f231-11e8-9aca-91d49d83c6a7.png)

What would be the best approach to solve this?
So far we are thinking of using this printing on grids, switching to it in responsive manner, when the screen gets too small:
![sdg chart](https://user-images.githubusercontent.com/1769627/49073129-04589180-f232-11e8-9fb2-20020bb86c7f.png)

**Comment by netil** [comment]
Hi @sinisarudan,

Basically, the chart size will depends on bind element's size.
So, checkout if bind element is correctly being responsible in different screen sizes.

And you can make defining some responsible rules using media queries as well.
