### ISSUE TITLE
Add second y axis dynamically?

### ISSUE THREAD

**Issue by jgoley** [naver/billboard.js#677]
Is it possible to add a second y axis when the `load` method is called or otherwise dynamically?

**Comment by netil** [comment]
Hi @jgoley, adding multi axes feature is on the plan for the next release(#98).
But it will not have dynamic support for now.

Take a look #439 for adding axis programmatically.

**Comment by jgoley** [comment]
@netil Thanks for the quick response! I think the solution in #439 is a little heavy—I've set things up to destroy the chart then re-generate when an axis is added/subtracted
