### ISSUE TITLE
Stacked bar charts: bar is cut off

### ISSUE THREAD

**Issue by rexebin** [naver/billboard.js#685]
## Description

When using stacked bar, bar could be cut off i.e. maximum value of y is not correctly calculated when the highest point is the sum of two values. 

## Steps to check or reproduce
Please see the below image. Sell(orange bar) and Buy(blue bar) are both 33, when stacked, total is 66(this stacked bar is the highest in the chart.), `y` is maxed to 50. Orange and blue bar should be the same hight and y should max to at least 66. 

<img width="358" alt="wx20181203-132910 2x" src="https://user-images.githubusercontent.com/10893959/49376542-77b14600-f6ff-11e8-8efc-5ded344567cc.png">

**Comment by netil** [comment]
If y axis' max is set to 50, is overly passing the max, which will be cut the remaining area.
To be correctly shown, y max should be at least 66 in this case.

The basic behavior for the options are when values are explicitly set(not just for this option only), will be working based on that. 

@rexebin, what is your expectation for this case?

**Comment by rexebin** [comment]
@netil Sorry, I didn't make myself clear. 

I did not set y axis max to 50, Billboard.js calculated. I expect the calculated value to be 66 or rounded to 70.

**Comment by netil** [comment]
I'll check that.

**Comment by rexebin** [comment]
sure, I will send you a set of data and options via email.

**Comment by rexebin** [comment]
@netil here you go: [Stackblize](https://stackblitz.com/edit/angular-mtkfrk). 
You can see the data and options in file `bb-chart-component.ts`.

**Comment by netil** [comment]
@rexebin got it. Simplified the reproducible example.

It's happening, when data are bound to different x Axis and correlates same x Axis value in different sequential position.

The example below, x Axis `2018-07-05` is in different position and for that case the max of y Axis isn't correctly set as expected.

I'll be heading to fix the issue.

![image](https://user-images.githubusercontent.com/2178435/49435936-2b4b3080-f7fb-11e8-9bd7-99343b9ae4a0.png)


```js
bb.generate({
    data: {
        xs: { "Buy": "xBuy", "Sell": "xSell" },
        columns: [
            ["xBuy", "2018-07-05", "2018-07-11"],
            ["xSell","2018-07-02","2018-07-05"],
            ["Buy", 33, 3],
            ["Sell", 7, 33]
        ],
        type: "bar", 
        groups: [[ "Buy", "Sell"]]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
            format: '%d/%m/%y'
            }
        }
    },
    bar: {
        width: 30
    }
});
```

**Comment by rexebin** [comment]
@netil Cool, thank you. It is amazing how relaxable your generator is.

**Comment by netil** [comment]
@rexebin done. Try `nightly`.
![image](https://user-images.githubusercontent.com/2178435/49570506-26f95180-f97a-11e8-9c01-a58a5b57283b.png)

**Comment by rexebin** [comment]
@netil thanks, I tried the nightly build, and it is indeed fixed.
