### ISSUE TITLE
minified version at NPM

### ISSUE THREAD

**Issue by miriyalee** [naver/billboard.js#696]
npm install billboard.js

gets 500kb dev version.

I humbly think npm library should provide minified version.

Is there any ways to get a minified version via npm/yarn?

or I should fork and change settings.

**Comment by netil** [comment]
Hi @miriyalee, billboard.js package was published with demo and source code files till now.

This will be updated starting the next coming release(which is expected to be this Fri.), releasing  build & types files only.

Checkout the details on #680.

**Comment by miriyalee** [comment]
Hi, @netil , I installed 1.7.0 and I cannot found minified version only changes, yet.

**Comment by netil** [comment]
Hi @miriyalee, excluded `src`, `doc` & `demos` folders from the previous publish.
The files on `dist` folder remains same as before.

**Comment by miriyalee** [comment]
![image](https://user-images.githubusercontent.com/35829622/49985365-03a05900-ffaf-11e8-89e8-b3651092f2a2.png)

So you mean file size will be same as before?

**Comment by netil** [comment]
@miriyalee I think there was misunderstanding on this.
Minified version was always provided with npm package.

If import as
```js
import bb from "billboard.js";
```
it's pointing `dist/billboard.js` file, which isn't minified version. 

If wants import minified version do
```js
import bb from "billboard.js/dist/billboard.min.js";
```

But in most cases this isn't really necessary, because normally  each usage environment possess their own build process with minification.

**Comment by miriyalee** [comment]
Oh yes thank you.
We have a some problem with certain version of webpack,
so I cannot use node_modules folder for minification.
Thanks, maybe it will help so much.

**Comment by miriyalee** [comment]
I should ask react-billboardjs owner to update library, or folk my own.
Thanks, I should close this issue.
