### ISSUE TITLE
Resizing not working when using custom legend contents in v1.7.0

### ISSUE THREAD

**Issue by Cyphur** [naver/billboard.js#705]
## Description
Chart auto-resizing is not working in cases where chart is configured to use custom legend contents.

## Steps to check or reproduce
[Click to view example in Codepen](https://codepen.io/eSpire/pen/WLxGRO)

1. Resize window - notice chart does not resize
2. Remove custom legend contents and resize window - notice chart resizes

NOTE: Downgrade billboard.js resource to latest CDN (v1.6.2) and everything works as expected.

**Comment by netil** [comment]
Hi @Cyphur, thanks for reporting.
This will be out as patch update when is fixed.

**Comment by netil** [comment]
Side effect caused by #622
