### ISSUE TITLE
TypeError: null is not a object (evaluating "body"["__colorPattern__"]')

### ISSUE THREAD

**Issue by userguide22** [naver/billboard.js#713]
## Description
Code works on JSFiddle, but doesn't load on a local version. I ran an inspection and found this error (see screenshot). Please help.

<img width="1311" alt="screenshot 2018-12-24 at 12 33 51 pm" src="https://user-images.githubusercontent.com/45838032/50390957-c428f800-0778-11e9-9952-af2192e97c12.png">

## Steps to check or reproduce
https://jsfiddle.net/userguide22/cd0mh28L/42/

**Comment by netil** [comment]
Hi @userguide22, the error comes where `document.body` is treated as `null`.
Could be more specific on your working environment?

**Comment by userguide22** [comment]
Hi netil, 

I’m using Brackets. It happened as I placed the scripts in the header without using the window.onload = function() {

In experience on my part. I’ve placed the codes in the body and it works now. Appreciate your reply very much!

Cheers and happy holidays!
