### ISSUE TITLE
Feature request: Partialy hiding data: shown in tooltip only

### ISSUE THREAD

**Issue by 4refr0nt** [naver/billboard.js#715]
`hide` - hide data in all place works ok.
With prior versions of billboard I can use `subx` axis for partialy hiding data, but shown in tooltip.
We need show in tooltip several values, related with current value.

For example:
```
0: {time: 1545739200000, data: 22.39, temp: 27, ts: 1545740806025, value: 0}
1: {time: 1545735601000, data: 22.39, temp: 27, ts: 1545737206176, value: 0}
2: {time: 1545732000000, data: 22.39, temp: 27, ts: 1545733606393, value: 0}
3: {time: 1545728400000, data: 22.39, temp: 26, ts: 1545730006575, value: 0}
...
```
fragment of options:
```
      json: data,
      keys: {
        x: 'time',
        value: ['value', 'temp', 'data', 'ts'],
      },
```
I need show `temp`, `data` and `ts` show in tooltip only.

**Comment by netil** [comment]
Hi @4refr0nt, I can't get exactly what do you need.

Maybe this is what you need?
```js
bb.generate({
    data: {
        json: [
            {time: 1545739200000, data: 22.39, temp: 27, ts: 1545740806025, value: 0},
            {time: 1545735601000, data: 22.39, temp: 27, ts: 1545737206176, value: 0},
            {time: 1545732000000, data: 22.39, temp: 27, ts: 1545733606393, value: 0},
            {time: 1545728400000, data: 22.39, temp: 26, ts: 1545730006575, value: 0}
        ],
        keys: {
            x: 'time',
            value: ['value', 'temp', 'data', 'ts'],
        },
        hide: ["value"]
    }
});
```

**Comment by 4refr0nt** [comment]
`hide` option hided data in all place (graph, legend and tooltip)

**Comment by netil** [comment]
Probably already fixed or figured out how to.

For those who're reaching by search, this issue can be solved by customizing tooltip contents.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip

But the hassle is, it should be setting all formatted html code.
