### ISSUE TITLE
Create custome theme

### ISSUE THREAD

**Issue by benj-spectory** [naver/billboard.js#716]
hi, I want to create a custom theme to change the color of the axis and more things I want to change but can't.
one other thing, how do I change the theme on typescript (angular 7)
thanks,
![screenshot from 2018-12-27 17-25-09](https://user-images.githubusercontent.com/46196704/50485415-e54e4a80-09fd-11e9-9fa5-e264ee7aab69.png)

**Comment by netil** [comment]
Hi @benj-spectory.

To customize x and y Axes, just set styles for that elements. 
For example, to change line colors do:

```css
.bb-axis-x path, .bb-axis-y path {
    stroke: red;
}
```
Just apply appropriate styles according the elements structure.
![image](https://user-images.githubusercontent.com/2178435/50553537-052a8a80-0cec-11e9-8d1f-12214fdaf9c0.png)

And for the second question, I don't know in which environment you're working on, but in most cases just importing(or loading it) theme css file will change the styles.

```js
import "billboard.js/dist/theme/insight.css"
```
