### ISSUE TITLE
Feature Request: Enable Title and Subtitle with Chart

### ISSUE THREAD

**Issue by andileco** [naver/billboard.js#727]
I think having the ability to include a title and subtitle, such as is done in Highcharts (https://www.highcharts.com/demo/line-basic) would be a great feature. I would think it would be fairly easy to implement too.

**Comment by netil** [comment]
Hi @andileco, thanks for suggesting. I'll consider adding for the next release.

**Comment by netil** [comment]
Implemented adding mulitiline support adding `\n` where you want to break the line.

```js
bb.generate({
  title: {
    text: "Temperature History by Region, 2017-2018\nSource: community weather center"
  },
  ...
}
```
You can style title elements to make shown as main and sub title.
```css
.bb-title tspan:first-child {
    font-size: 17px;
    font-weight: bold;
}
```


![image](https://user-images.githubusercontent.com/2178435/51165495-bc75f280-18e3-11e9-9dee-6c58dbbd92e8.png)

**Comment by andileco** [comment]
Thank you! I have created an issue in the Drupal Charts module to implement this change: https://www.drupal.org/project/charts/issues/3026099
