### ISSUE TITLE
Issue in zoom for line chart with regions

### ISSUE THREAD

**Issue by mageshveeraa** [naver/billboard.js#728]
## Description
I am plotting line chart with dotted regions. When I zoom the chart, the line in the fixed position.

<img width="1283" alt="screenshot 2019-01-10 at 12 45 00 pm" src="https://user-images.githubusercontent.com/29809713/50954339-0c1b7f00-14dc-11e9-8902-1032855423ca.png">

**Comment by mageshveeraa** [comment]
`{
  "padding": {
    "top": 40,
    "right": 100,
    "bottom": 10,
    "left": 100
  },
  "size": {
    "height": 450
  },
  "grid": {
    "x": {
      "show": false
    },
    "y": {
      "show": true,
      "lines": [
        {
          "value": 0,
          "class": "x-axis-zero-line"
        }
      ]
    },
    "y2": {
      "lines": [
        {
          "value": 0,
          "class": "x-axis-zero-line"
        }
      ]
    }
  },
  "point": {
    "show": false
  },
  "line": {
    "connectNull": true
  },
  "data": {
    "x": "x",
    "json": {
      "Temperature": [
        "29.39",
        "29.7",
        "29.37",
        "28.87",
        "28.62",
        "27.72",
        "27.61",
        "27.82",
        "27.48",
        "26.78",
        "26.62",
        "26.64",
        "26.29",
        "26.01",
        "25.84",
        "25.07",
        "24.85",
        "24.01",
        "23.83",
        "22.8",
        "23",
        "22.64",
        "22.77",
        "22.64",
        "22.64",
        "22.62",
        "22.51",
        "21.42",
        "21.18",
        "20.93",
        "20.66",
        "20.48",
        "20.7",
        "21.24",
        "22.14",
        "22.78",
        "23.43",
        "23.16"
      ],
      "x": [
        "01-10-2019 00:00",
        "01-10-2019 00:30",
        "01-10-2019 01:00",
        "01-10-2019 01:30",
        "01-10-2019 02:00",
        "01-10-2019 02:30",
        "01-10-2019 03:00",
        "01-10-2019 03:30",
        "01-10-2019 04:00",
        "01-10-2019 04:30",
        "01-10-2019 05:00",
        "01-10-2019 05:30",
        "01-10-2019 06:00",
        "01-10-2019 06:30",
        "01-10-2019 07:00",
        "01-10-2019 07:30",
        "01-10-2019 08:00",
        "01-10-2019 08:30",
        "01-10-2019 09:00",
        "01-10-2019 09:30",
        "01-10-2019 10:00",
        "01-10-2019 10:30",
        "01-10-2019 11:00",
        "01-10-2019 11:30",
        "01-10-2019 12:00",
        "01-10-2019 12:30",
        "01-10-2019 13:00",
        "01-10-2019 13:30",
        "01-10-2019 14:00",
        "01-10-2019 15:00",
        "01-10-2019 16:00",
        "01-10-2019 17:00",
        "01-10-2019 18:00",
        "01-10-2019 19:00",
        "01-10-2019 20:00",
        "01-10-2019 21:00",
        "01-10-2019 22:00",
        "01-10-2019 23:00"
      ]
    },
    "type": "area",
    "xFormat": "%m-%d-%Y %H:%M",
    "names": {
      "Temperature": "Temperature"
    },
    "colors": {
      "Temperature": "#9d827b"
    },
    "types": {},
    "groups": [],
    "axes": {
      "Temperature": "y"
    },
    "regions": {
      "Temperature": [
        {
          "start": "01-10-2019 14:43",
          "end": "01-10-2019 23:00",
          "style": {
            "dasharray": "2 3"
          }
        }
      ]
    }
  },
  "axis": {
    "rotated": false,
    "x": {
      "show": true,
      "label": {
        "text": "Timestamp",
        "position": "outer-center"
      },
      "tick": {
        "fit": false
      },
      "height": 70,
      "type": "timeseries",
      "min": "01-10-2019 00:00",
      "max": "01-10-2019 23:59"
    },
    "y": {
      "show": true,
      "label": {
        "text": "TEMPERATURE (°F)",
        "position": "outer-middle"
      },
      "tick": {
        "count": 5
      },
      "min": null,
      "padding": {
        "bottom": 0
      }
    },
    "y2": {
      "show": false,
      "label": {
        "text": null,
        "position": "outer-middle"
      },
      "tick": {
        "count": 5
      },
      "min": null,
      "padding": {
        "bottom": 0
      }
    }
  },
  "tooltip": {
    "show": true
  },
  "zoom": {
    "enabled": {
      "type": "drag"
    }
  },
  "legend": {
    "show": false
  },
  "bar": {
    "padding": 1,
    "width": {
      "ratio": 0.5,
      "max": 75
    }
  }
}`

**Comment by netil** [comment]
@mageshveeraa confirmed the bug. I'll try fix this.

**Comment by netil** [comment]
@mageshveeraa fixed the issue.
![region-zoom](https://user-images.githubusercontent.com/2178435/51020748-d00f1980-15c2-11e9-92aa-8f968e4759c5.gif)

**Comment by mageshveeraa** [comment]
Thanks for the quick fix. @netil
