### ISSUE TITLE
Subchart & zoom API don't work in a rotated bar chart

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#736]
## Description
Subcharts and the zoom api (chart.zoom) don't seem to work with a rotated bar (& perhaps others) chart 😥

The subchart shows up, but you cannot interact with it. The zoom api just doesn't do anything.
If you switch it to _not_ be a rotated bar chart, the subchart works. The only way I can get the zoom api to work is if I enable zoom, but interaction becomes very strange in the chart afterwards.

## Steps to check or reproduce
https://jsfiddle.net/irislieuw/5qyg4zdh/7/

* Switch `axis.rotated` to `false` to see the subchart work
* Switch `zoom.enabled` to `true` to see the zoom api work, but interaction gets weird afterwards

**Comment by netil** [comment]
Hi @irislieuw, this issue is somehow not focused well.
This will be take time to be solved.

**Comment by chrischris96** [comment]
Hi @netil, is there any update on the issue? I am running into the same bug.

**Comment by netil** [comment]
@chrischris96 not yet. I'll try to be fixed on next release.
> BTW, I put more priority based on users' requests or interests.

**Comment by netil** [comment]
checkout the working example
![rotated-zoom](https://user-images.githubusercontent.com/2178435/58143204-f20d5c80-7c84-11e9-97f1-368376729d57.gif)
