### ISSUE TITLE
Add option to not show x-axis in subchart

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#737]
## Description
The subchart can get quite crowded sometimes when the x-axis is visible. It would be nice to have an option to hide the x-axis in the subchart only.

As far as I can tell, using css won't work since the x axis class applies to both the main chart's x-axis & the one in the subchart. Let me know if there is another way to workaround this.

## Steps to check or reproduce
An example of a crowded subchart
![image](https://user-images.githubusercontent.com/11950094/51289018-79835000-19b3-11e9-8ba3-41ec49792ba4.png)

**Comment by netil** [comment]
@irislieuw, well for this case you can easily hide subchart's axis text.

```css
.bb-axis-x:last-child text {
    visibility: hidden;
}  
```

To implement as an option, there're points to be considered.
- Hiding entire axis is required?
- Or just hiding text is ok?

**Comment by irislieuw** [comment]
@netil If I just use css to hide it, There is a large gap between the subchart and the legend/bottom of the container 

![image](https://user-images.githubusercontent.com/11950094/51407441-c6306d80-1b10-11e9-8763-25360d18de0c.png)

I would be fine with hiding the entire axis, if it were available as an option

**Comment by netil** [comment]
Got it. Something like axis tick show option should be provided.

```js
subchart: {
    show: true,
    axis: {
      tick: {
        show: false
      }
    }
  }
```

**Comment by irislieuw** [comment]
@netil That would be perfect!!! Thanks for quick response as usual 👏

**Comment by netil** [comment]
@irislieuw done. Added new options to handle the visibility of tick lines & texts.

```js
x: {  // all same for 'x', 'y' and 'y2' axis
	tick: {
		show: true,  // show or hide tick lines
		text: {
			show: true  // show or hide tick texts
		}
	}
},
subchart: {
	show: true,
	axis: {
		x: {
			show: true,  // show or hide subchart's x axis
			tick: {
				show: false,  // show or hide axis tick lines
				text: {
					show: false  // show or hide tick texts
				}
			}
		}
	}
}
```
![image](https://user-images.githubusercontent.com/2178435/51720027-2e41ff00-208f-11e9-87b8-52fedee2fd22.png)

checkout the `nightly` when is built (nightly is built automatically, so wait till is updated)

**Comment by irislieuw** [comment]
🔥 So awesome!!! Thanks @netil
