### ISSUE TITLE
bindto option omission throws error

### ISSUE THREAD

**Issue by DemersM** [naver/billboard.js#743]
Contrary to the documentation (https://naver.github.io/billboard.js/release/latest/doc/Options.html#.bindto), the omission of the **bindto** option throws an error.

See: https://jsfiddle.net/x4saqtjk/

**Comment by netil** [comment]
Hi @DemersM, thanks for the report.
By default, if `bindto` isn't specified, it looks for element with id `chart`.
So, in your example, the bind element should have `<div id='chart'></div>`.

I'll be fixing the doc.

**Comment by netil** [comment]
@DemersM, changed the action when `bindto` option is not specified or not exist in the current document as:
> In case of element doesn't exist or not specified, will add a `<div>` element to the body.
