### ISSUE TITLE
Max value of Y axis is being set to 10% added to Y axis data set maximum value

### ISSUE THREAD

**Issue by Aashiq25** [naver/billboard.js#745]
## Description

When I draw a chart the Maximum value in y axis graph is being set to Plus 10% of my maximum y axis dataset value. In this case the tick points are getting random values and not Rounded Numbers. In this case is there any solutions to set the maximum value at the Y axis bar as I wish (Not the Maximum of the Y axis Dataset).

<img width="1142" alt="screen shot 2019-01-24 at 6 47 28 pm" src="https://user-images.githubusercontent.com/44645166/51680743-94d00a00-2008-11e9-9cea-86fb22ff1b94.png">

In this case the max value is 6839 and adding 10 % to it the max in y axis is being set to 7524 and the tick values are random.In case If I am able to set the maximum value by nearest rounded of value so that the the tick values are rounded off(I tried finding the nearest rounded off value and reduced it by 9% to compensate the 10% increment but still the problem exists is some cases Thus if am able to set the value without the 10% increment then i would get accurate value in all the cases)

<img width="1143" alt="screen shot 2019-01-24 at 6 14 54 pm" src="https://user-images.githubusercontent.com/44645166/51679128-17a29600-2004-11e9-9051-0e8d880269e8.png">

**Comment by Aashiq25** [comment]
Thanks @netil

**Comment by Aashiq25** [comment]
Is there any algorithm in billboardjs for Nice Tick Values . Have Used few algorithms but if there is any inbuilt better algorithms it would be awesome....!!!

**Comment by netil** [comment]
@Aashiq25, you can format via [tick.format](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4format) option. Using `d3-format` will facilitate your needs.
- https://github.com/d3/d3-format#d3-format

```js
axis: {
    y: {
        tick: {            
            format: d3.format(".2s")  // SI-prefix with two significant digits, "42M"
        }
    }
}
```
