### ISSUE TITLE
tooltip.format.title - wrong x value is passed to the function for category graph

### ISSUE THREAD

**Issue by DemersM** [naver/billboard.js#753]
It seems like the wrong x value is passed into the `tooltip.format.title` function for **category graph**

Here you can test a category graph that is using a `tooltip.format.title` function: https://jsfiddle.net/gwpdaxru/ 

It seems that the x value passed is the index, not the value itself.

------------------

Here you can test the same graph without the `tooltip.format.title` function: https://jsfiddle.net/tvb398so/

You will see that the title is correctly written with the correct x value.

**Comment by netil** [comment]
@DemersM, from the API doc it states as:
> Set format for the title of tooltip.
> Specified function receives x of the data point to show.

So, to the function it will pass the corresponding index value of the x axis.

If you want access the category value, do:

```js
tooltip: {
    format: {
    	title: function(x) {
            return chart.categories()[x];
        }
    }
}
```
