### ISSUE TITLE
Full modularization by its functionality

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#756]
## Description

Make each module as independent, to be more loose coupled.
This task should have:
- Split as separate module by its functionality.
- An non-breaking interface to use them.
  > This should come with the capability to import only used modules to cut the bundling size.

**Comment by stof** [comment]
this would be great. Do you have an idea how the new interface should look like ?

**Comment by stof** [comment]
@netil is there any progress on that front in the upcoming v2 ? billboard.js is currently the biggest contributor to my bundle size, and I only use some of the supported chart types. Being able to import only the one I use would be great (the current API indeed does not fit that, it would require building a new tree-shakeable API and then rebuilding the current API on top of it for BC for people preferring ease of use over smaller size)

**Comment by netil** [comment]
@stof, just released the first RC of `v2`.

```sh
# you can install '@next' tagged version via following command
npm i billboard.j@next
```

Using v2, can reduce bundle size from `10 ~ 43%`.
Checkout the [changelog](https://github.com/naver/billboard.js/blob/next/CHANGELOG-v2.md#modularization-by-its-functionality) for the details

**Comment by stof** [comment]
Making type callbacks extend the internal APIs with necessary config looks like a nice trick to implement this without redoing the whole API.

**Comment by netil** [comment]
Restructured whole file system based on its functionality and grouped by its type (shape & interaction).
- https://github.com/naver/billboard.js/blob/v2/CHANGELOG-v2.md#modularization-by-its-functionality

Close for now, but looking a continuous improvements on this.
