### ISSUE TITLE
Improvements in performance

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#757]
## Description

Find the way to increase performance in:
- Initial execution time
- during the redraw process
- reduce unnecessary node generation/handling (#36)

**Comment by Cyphur** [comment]
@netil - I am wondering if you plan on investigating these performance issues in the near future, or is this something farther off in priority?

**Comment by netil** [comment]
@Cyphur, performance improvements are always a topic of concern and it can't be done by once.
If you've been following this repos issues, that efforts are shown one by one(ex. #759).

I'm planning v2.0 by the end of this year, so hopefully these improvements were made for that release.

Thanks anyway for the interests :)

**Comment by netil** [comment]
Is a never ending task where should aim continuously to improve the performance, but it has reached some progress from the work of `v2`. Enough to close the issue for now.
- Benchmark: https://output.jsbin.com/pecafih
