### ISSUE TITLE
Support for Candlestick (OHLC) chart

### ISSUE THREAD

**Issue by JamieWritesCode** [naver/billboard.js#76]
I know it's only early days, but is there any intent to ship a candlestick chart?  Seems to be a popular request across many charting libraries.

![alt Candlestick Chart](http://i.imgur.com/KETquiN.jpg)

Google Charts for reference:
https://developers.google.com/chart/interactive/docs/gallery/candlestickchart

**Comment by netil** [comment]
thanks @TehCrucible for the suggestion!
Of course, `candlestick` type is one of the types that we care, but I can't not guarantee in very near future.
We'll be implementing new type by type and `candlestick` will be one of them definitely.

**Comment by rolandblain** [comment]
any updates?

**Comment by netil** [comment]
Planning for 2021.

**Comment by michkami** [comment]
Would it also be possbile to support waterfall charts if `candlestick` is implemented?
It does not seem to be much work to support it, after `candlestick` is implemented.

**Comment by netil** [comment]
@rolandblain @JamieWritesCode, sorry for the long wait on this.

Want to share that new `candlestick` type works almost reaching the end 😃 !
Within few days, the updates will be merged to [`d3v6`](https://github.com/naver/billboard.js/tree/d3v6) branch and planning to release on `v3`.

<img src=https://user-images.githubusercontent.com/2178435/109791755-25e92480-7c56-11eb-956d-41e0b9a09eed.png width=800>
