### ISSUE TITLE
Question: Wrap Rotated X Axis Labels

### ISSUE THREAD

**Issue by serres2** [naver/billboard.js#761]
With a rotated x axis, some labels run long. Is there any way to wrap labels?

Example:

<img width="150" alt="screen shot 2019-02-05 at 4 25 15 pm" src="https://user-images.githubusercontent.com/14003373/52308507-20c82700-2963-11e9-846f-42d4f5845196.png">

**Comment by netil** [comment]
Hi @serres2, try adjusting with different tick options.
In this case, maybe limiting the width will help.
- [axis․x․tick․width](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4width) option

**Comment by serres2** [comment]
@netil - Awesome. When looking through the documentation, I found the [axis․x․tick․multiline](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4multiline) option. Works like a charm.
