### ISSUE TITLE
Scheduled callbacks are not cancelled after chart is destroyed.

### ISSUE THREAD

**Issue by pakerhoi** [naver/billboard.js#766]
## Description
When destroying the chart it should also destroy all the upcoming transitions and callbacks, otherwise they are called on destroyed chart and produce errors.

## Steps to check or reproduce

I'm not sure how to make the clear reproducible code but the example of the flow is to make a load of data to the chart with unload option and then immediately destroy it.

E.g. of error:
```
Uncaught TypeError: Cannot read property 'data_x' of null
    at t.isX (billboard.js:5702)
    at t.isNotX (billboard.js:5707)
    at Array.filter (<anonymous>)
    at t.convertDataToTargets (billboard.js:6467)
    at t.loadFromArgs (billboard.js:6563)
    at SVGGElement.<anonymous> (billboard.js:11246)
    at SVGGElement.<anonymous> (billboard.js:2131)
    at r.call (dispatch.js:57)
    at a (schedule.js:143)
    at c (timer.js:61)

  | isX | @ | billboard.js:5702
-- | -- | -- | --
  | isNotX | @ | billboard.js:5707
  | convertDataToTargets | @ | billboard.js:6467
  | loadFromArgs | @ | billboard.js:6563
  | (anonymous) | @ | billboard.js:11246
  | (anonymous) | @ | billboard.js:2131
  | call | @ | dispatch.js:57
  | a | @ | schedule.js:143
  | c | @ | timer.js:61
  | s | @ | timer.js:71
  | requestAnimationFrame (async) |   |  
  | d | @ | timer.js:108
  | u | @ | timer.js:96
  | s | @ | timer.js:74
  | requestAnimationFrame (async) |   |  
  | d | @ | timer.js:108
  | restart | @ | timer.js:39
  | o | @ | timer.js:52
  | o | @ | schedule.js:59
  | e.e | @ | schedule.js:19
  | e.a | @ | transition.js:36
  | value | @ | billboard.js:1847
  | value | @ | billboard.js:1834
  | value | @ | billboard.js:1709
  | value | @ | billboard.js:1662
  | t | @ | billboard.js:2250
  | generate | @ | billboard.js:12854
  | y | @ | BillboardChart.js:160
  | o | @ | index.js:74
  | Z | @ | BillboardChart.js:241
  | o | @ | index.js:74
  | (anonymous) | @ | BillboardChart.js:31
  | requestAnimationFrame (async) |   |  
  | p | @ | BillboardChart.js:30
  | o | @ | index.js:74
  | commitLifeCycles | @ | react-dom.production.min.js:149
  | e | @ | react-dom.production.min.js:158
  | y | @ | react-dom.production.min.js:169
  | v | @ | react-dom.production.min.js:168
  | batchedUpdates | @ | react-dom.production.min.js:171
  | $ | @ | react-dom.production.min.js:54
  | _t | @ | react-dom.production.min.js:71
```

![screen shot 2019-02-12 at 16 33 55](https://user-images.githubusercontent.com/1148745/52642684-26ce8280-2ee4-11e9-8370-49c104a4ef58.png)

**Comment by netil** [comment]
Hi @pakerhoi, thanks for reporting.
I think this can be reproduced with this.
```js
var chart = bb.generate({
    data: {
        columns: [
	    ["data1", 50, 20]
	]
    }
});

setTimeout(() => {
	chart.load({
		columns: [
		    ["data1", 100, 150]
		],
		unload: ["data1"]
	});

	chart.destroy();  // <-- will throw error at this point
}, 500);
```

Cancelling the possible pending transition make sense, but what will be the real usecase on destroying right after the load happens? Just to get know the reason.

**Comment by pakerhoi** [comment]
@netil

Real life usecase -- I'm rendering a list of charts inside virtualized react component (specifically [react-virtualized](https://github.com/bvaughn/react-virtualized)).

When the user scrolls the list fast enough the components with charts are starting to render and then immediately destroyed. They are destroyed before the load transitions had chance to execute.

By the way, the performance of such a list with many charts that need to render / destroy quickly is not very good and I'm thinking of ways to improve it. One idea is to add a delay before rendering a chart. Another -- to add some kind of caching for the charts to render them once and just put them in the DOM when needed. Maybe you have some ideas how to deal with it? Sorry for offtopic.
