### ISSUE TITLE
Onzoom function doesn't return the updated domain values

### ISSUE THREAD

**Issue by nirmal93guna** [naver/billboard.js#770]
## Description
When using the onzoom() or onzoomend() function with the domain value. It is not being updated according to the current zoomed range. Instead it just returns the start and end values without zoom

## Steps to check or reproduce
https://codepen.io/nirmal93guna/pen/KJxgGg
I have reproduced the bug here. Kindly take a look.

**Comment by netil** [comment]
Hi @nirmal93guna, thanks for the report.
I'll be checking this issue. (appreciated if you can make some contribution on this)
