### ISSUE TITLE
Question - Dynamic data.labels.position

### ISSUE THREAD

**Issue by serres2** [naver/billboard.js#774]
Is it possible to generate a dynamic `data.labels.position` based on the charted dataset?

Something like:

```
data: {
  labels: {
    position: {
       y: v => (v >= 0 ? 5 : -5)
    }
  }
}
```

**Comment by netil** [comment]
Hi @serres2, try this.

```js
// generate chart
var chart = bb.generate({ ... });

chart.config("data.labels.position", {
    // update x, y coordinate value
    x:-25, y:5
}, true);
```

**Comment by serres2** [comment]
Hey @netil - can I access the current data value within `.config`?

For example, I have a chart like this:

<img width="404" alt="screen shot 2019-02-18 at 2 18 19 pm" src="https://user-images.githubusercontent.com/14003373/52975707-20c91d80-338c-11e9-9237-f0645018d4de.png">

When the data value is negative (-15 in the chart), I want the `data.labels.position` for y to be 5, otherwise, it should remain as -5.

**Comment by netil** [comment]
@serres2, I misunderstood the `dynamic` in the first comment.
Anyway, for now there's no way to access the way you mentioned. The data.labels.position only accept number.

If you need modify text's position according the data value, you need handle manually.
Try this.

```js
bb.generate({
  data: {
    columns:[
		["data1", 10, 20, 30, -5, 15]
	],
	type: "bar",
	labels: {
		show: true
	}
  },
  onrendered: function() {
	this.main.selectAll(".bb-texts text").each(function(d) {
		const y = +this.getAttribute("y");

		this.setAttribute("y", y + (
			d.value >= 0 ? 5 : -5
		));
	});
  }
});
```

**Comment by serres2** [comment]
@netil => thanks for the clarification!
