### ISSUE TITLE
[질문] area-line-range 타입 데이터에서 area 부분의 마우스오버가 발생했을때 tooltip 을 띄울수 있을까요?

### ISSUE THREAD

**Issue by kwonhyucknae** [naver/billboard.js#775]
## Description

안녕하세요
![image](https://user-images.githubusercontent.com/18182656/52923349-b653b580-336a-11e9-8286-451d3591b938.png)
해당 이미지의 오른쪽 끝 부분의 초록색 데이터는 
area-line-range 타입의 데이터에서 mid 값을 주지 않고 low 와 high 데이터 만 줘서 
점을 찍지 않고 영역만 표시한 상태입니다

<pre><code>
['test2', { low: 280000, high: 350000 }
            , { low: 280000, high: 350000}]
</code></pre>

저는 저 영역 부분의 마우스 오버 이벤트가 발생했을때 tooltip 을 띄우고 싶은데,
tooltip의 contents 의 d(data) 파라미터에서는 해당 영역이 안 들어가는것 같습니다

데이터의 mid 값을 추가하면 영역에 점이 생기고
contents 의 d 파라미터에서 mid 값을 받을 수 있는 것 같은데
저는 점을 찍지 않고 이미지와 같이 영역으로만 표시하고 싶습니다
혹시 저 영역에서 tooltip을 사용할 수 있는 방법이 있을까요?

**Comment by netil** [comment]
Hi @kwonhyucknae, to be properly working you should give `mid` value.
And if you want hide data points, you can use `point.show` option to hide.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.point

```js
bb.generate({
	data: {
		columns: [
			['test2',
				{ low: 280000, high: 350000, mid: 0 },
				{ low: 280000, high: 350000, mid: 0 }
			]
		],
		type: "area-line-range",
	},
	point: {
		show: false
	}
});
```

**Comment by kwonhyucknae** [comment]
@netil 
답변 감사합니다!
포인트를 숨기는 이슈는 잘 해결할 수 있었습니다
한가지만 더 여쭤보고 싶은게
<pre><code>
data: {
		columns: [
			['test2',
				{ low: 280000, high: 350000, mid: 0 },
				{ low: 280000, high: 350000, mid: 0 }
			]
		],
		type: "area-line-range",
	},
</code></pre>

와 같이 mid 값을 0으로 준 데이터에서는
![image](https://user-images.githubusercontent.com/18182656/52991303-73b7d900-344f-11e9-912c-98cf286e8d36.png)

mid 값이 0 이기 때문에 
해당 초록 영역 부분에 마우스오버를 해도 툴팁이 생기지 않고

<pre><code>
data: {
		columns: [
			['test2',
				{ low: 280000, high: 350000, mid: 280000 },
				{ low: 280000, high: 350000, mid: 350000 }
			]
		],
		type: "area-line-range",
	},
</code></pre>

![image](https://user-images.githubusercontent.com/18182656/52991521-59cac600-3450-11e9-8d35-4673957c00d5.png)

mid 값을 각 꼭지점으로 줬을 때는 
이미지와 같이 mid 값에 해당되는 각 꼭지점에서 툴팁을 발생시킬 수 있는데

해당 mid 값이 아닌 초록색 영역에서 툴팁을 발생시킬 수 있는 방법이 혹시 있을까요?
api 문서에서 못 찾고있어서 여쭤봤습니다
버전은 1.7.1 을 사용하고 있습니다 
감사합니다

**Comment by netil** [comment]
@kwonhyucknae, can you provide full generation option?

**Comment by kwonhyucknae** [comment]
<pre><code>  

  billboard.bb.generate({
      data: {
        xs: {
          testDataYList: 'x',
          test2: 'liveMarketPriceXList',
        },
        columns: [
          ['x', '2018-01-1', '2018-03-1', '2018-06-1', '2018-9-1', '2018-12-1', '2019-01-1', '2019-02-1'],
          ['liveMarketPriceXList', '2019-02-14', '2019-02-28'],
          ['testDataYList', 130, 340, 200, 500, 250, 350, 400, 500],
          ['test2'
            , { low: 280, high: 350, mid: 350 }
            , { low: 280, high: 350, mid: 350 },
          ],
        ],
        types: {
          testDataYList: 'line',
          test2: 'area-line-range',
        },
      },
      axis: {
        x: {
          type: 'timeseries',
          tick: {
            format: '%Y-%m-%d',
          },
        },
      },
      tooltip: {
        show: true,
        grouped: false,
        contents: (d, defaultTitleFormat, defaultValueFormat, color) => {
          if (d) {
            console.log(d)

            const selectedPoint = d[0]
            switch (selectedPoint.id) {
              case 'test2':
                return '<div class=\'tool_tip\' id=\'chart_tooltip\'>' + 'zzz' + '</div>'
              case 'testDataYList':
                return '<div class=\'tool_tip\' id=\'chart_tooltip\'>' + 'zzz' + '</div>'
            }
          }
        },
      },
      bindto: this.chartzzz,
    })
</code></pre>

![image](https://user-images.githubusercontent.com/18182656/53076365-dafa8980-3532-11e9-983f-25677a6024c4.png)

테스트 데이터는 위와 같이 사용하고 있습니다
'testDataYList' , 'test2' 처럼 데이터가 여러개 있는데
데이터들의 시작점이 달라서 
<pre><code>
data: {
        xs: {
          testDataYList: 'x',
          test2: 'liveMarketPriceXList',
        },
</code></pre>
처럼 xs 로 사용하고 있습니다.
<pre><code>
data: {
        x: 'x',
}
</code></pre>
로 사용할때와 다르게 xs 로 사용할때는 
정확히 포인트에 마우스오버가 발생해야 툴팁이 띄어지고 있는것 같은데

![image](https://user-images.githubusercontent.com/18182656/53077071-8d7f1c00-3534-11e9-882a-7b5c666b9ec3.png)

저는 위 이미지와 같이 영역에 마우스 오버가 발생했을때도 툴팁을 띄우고 싶습니다
혹시 다른 방법이 있을까요?

**Comment by netil** [comment]
This is very customized usage and it's not functionality which is supported as an option.
But, you can make to work doing some manual implementation.

```js
bb.generate({
      data: {
        xs: {
          testDataYList: 'x',
          test2: 'liveMarketPriceXList',
        },
        columns: [
          ['x', '2018-01-1', '2018-03-1', '2018-06-1', '2018-9-1', '2018-12-1', '2019-01-1', '2019-02-1'],
          ['liveMarketPriceXList', '2019-02-14', '2019-02-28'],
          ['testDataYList', 130, 340, 200, 500, 250, 350, 400, 500],
          ['test2'
            , { low: 280, high: 350, mid: 350 }
            , { low: 280, high: 350, mid: 350 },
          ],
        ],
        types: {
          testDataYList: 'line',
          test2: 'area-line-range',
        },
      },
      axis: {
        x: {
          type: 'timeseries',
          tick: {
            format: '%Y-%m-%d',
          },
        },
      },
      tooltip: {
        show: true,
        contents: (d, defaultTitleFormat, defaultValueFormat, color) => {
            const value = d[0].value;

            return isNaN(value) ? value.high : value;
        }
      },
      onrendered: function() {        
        const rect = this.main.select(".bb-area-test2").node().getBoundingClientRect();

        // attach event for the data area
        this.main.select(".bb-event-rect").on("mousemove.area", () => {
          const event = d3.event;
          const {clientX, clientY} = event;

          // check if the mouse point is within
          if (
            clientX >= rect.x && clientX <= (rect.x + rect.width) &&
            clientY >= rect.y && clientY <= (rect.y + rect.height)
          ) {
            const data = this.main.selectAll(".bb-shapes-test2 circle").data();

            this.showTooltip([data[0]], event.target);
          }
        });
      }
});
```

**Comment by kwonhyucknae** [comment]
@netil
감사합니다
덕분에 해결한 것 같습니다
좋은 하루 되세요!
