### ISSUE TITLE
Is possible to show actual value instead of percentage in pie/donut slice?

### ISSUE THREAD

**Issue by mageshveeraa** [naver/billboard.js#776]

**Comment by netil** [comment]
Hi @mageshveeraa, you can do by [pie.label.format](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.pie) or [donut.label.format](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.donut).
Just set callback for format option, which will receive data value as parameter.

```js
bb.generate({
  data: {
    columns: [
	["data1", 150],
	["data2", 150],
    ],
    type: "donut",
  },
  pie: {
	format: d => d
  },
  donut: {
	format: d => d
  }
});
```
