### ISSUE TITLE
Window resize does not position subchart selection

### ISSUE THREAD

**Issue by creage** [naver/billboard.js#778]
## Description

I have a timeseries subcharted widget, and when I select some range in this subchart, the main chart gets zoomed matching the selection. But, when I resize my window, selection does not resize/reposition, but looks sticking to its place, leading to wrong zooming in main chart.
## Steps to check or reproduce

1. Maximize you browser window
2. Go to Demo page https://naver.github.io/billboard.js/demo/#Interaction.SubChart
3. Select a zone ``1<->2`` in the subchart
![image](https://user-images.githubusercontent.com/910967/52957156-545a7680-3391-11e9-8eb4-7ae2eaf93c32.png)

4. Now resize your browser window so it is like a half of initial width

**Expected**: Zone in subchart still shows range of ``1<->2``.
**Actual**: Zone is showing somewhere between ``2<->4``
![image](https://user-images.githubusercontent.com/910967/52957265-92f03100-3391-11e9-9af4-c529f341b8fb.png)

**Comment by netil** [comment]
@creage, thanks for reporting.
I'm little bit on doubt identify this as bug, but will label it as is.

**Comment by creage** [comment]
@netil well, let me explain a typical scenario.

We use this combination of timeseries with subchart for rendering small widgets. Usually we have up to 6 such widgets on a kind of dashboard. We also have an ability to maximize the widget, so it resizes to the size of whole dashboard.

So, our timeresies widget renders some timeline, user select some range on subchart, and maximizes widget to get better overview of selection.

The problem is, that once resized (maximized), the range is moved, leading into wrong selection on the main chart, and user cannot see what he previously selected. This is very confusing.

**Comment by netil** [comment]
@creage, fixed. Checkout the working example.

![subchart](https://user-images.githubusercontent.com/2178435/53714421-9efbe880-3e91-11e9-8ab3-89a1be037db1.gif)

**Comment by creage** [comment]
@netil animation looks really promising, looking forward to play with a new release

**Comment by netil** [comment]
not working properly when x axis type is `category`.
