### ISSUE TITLE
Y axis tick values are random numbers instead of rounded when we give tick count

### ISSUE THREAD

**Issue by mageshveeraa** [naver/billboard.js#783]
Hi,

Please check this screenshot, the Y tick values are random numbers when we specify tick count... It would be nice it rounded value...

<img width="1260" alt="screenshot 2019-02-20 at 4 04 06 pm" src="https://user-images.githubusercontent.com/29809713/53085665-666f1d00-3529-11e9-86d8-100247fa78b9.png">

**Comment by netil** [comment]
@mageshveeraa, they're not random numbers.
The values are determined by the bound data values, so according the amount of the values y Axis will be displaying corresponding values on its position.

If you want to be displayed as `rounded` or `formatted`, there're some options you might consider.

```js
axis: {
	y: {
		tick: {
			count: 3,  // Set the number of y axis ticks.
			format: function(v) {
                                // you can format here by returning tick value.
				return v;
			},
                        // or implicitly set what values will be displayed
			values: [100, 200, 300, 400]
		}
	}
}
```

checkout [axis.y.tick](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4count) related options from API doc.

**Comment by mageshveeraa** [comment]
@netil  Thanks for the suggestion, will try it out.
