### ISSUE TITLE
Multiline support in Pie Chart Label

### ISSUE THREAD

**Issue by TruongHuuTien** [naver/billboard.js#784]
## Description
It will be cool to add multiline feature into Pie Chart Label. In the pie.label.format custom function.
I need to display informations like: ${value} \n ${ratio}%

**Comment by netil** [comment]
Hi @TruongHuuTien, done.

You can return text with the `\n` for line breaking from the `pie.label.format` and `donut.lable.format` option.

```js
pie: {   // or donut
    label: {
        format: function(value, ratio, id) {
	  return value +"\nText";
       }
    }
}
```

**Comment by TruongHuuTien** [comment]
Thanks

**Comment by netil** [comment]
Buggy when toggle legend, appending duplicated text nodes
