### ISSUE TITLE
Multi arc gauge

### ISSUE THREAD

**Issue by michkami** [naver/billboard.js#787]
Hi,
It would be good to have multi arc gauge chart like this one: [Multi Arc Gauge PR in c3.js](https://github.com/c3js/c3/pull/1355) and the [follow up](https://github.com/c3js/c3/pull/2278)

Is there any chance to get this feature in the near future?

**Comment by netil** [comment]
Well, it looks good. It will be great if you make some contribution on this. :)

**Comment by michkami** [comment]
I actually started to migrate the Multi Arc Gauge from the links above.
I can't tell you how long it will take, as I am a trainee, but I made some progress in last few days.
I will comment here, if there is anything to discuss.

**Comment by netil** [comment]
Hi @michkami, love the idea of `multi-arc` (`single` & `multi` sounds more simple for me).
Hope to be implemented soon!.

And the `legend` visibility on gauge, I think it should be displaying as you mentioned. 
The issue will be handle by #1136.

Thanks for the comments!
