### ISSUE TITLE
category bars with grouping

### ISSUE THREAD

**Issue by alwaysrejoice** [naver/billboard.js#789]
## Description

Can this library draw category bars with grouping as the picture below?
## Steps to check or reproduce

![33eqw](https://user-images.githubusercontent.com/8529933/53268810-1755f300-36b5-11e9-88ce-588f136a89e3.png)

**Comment by netil** [comment]
Hi @alwaysrejoice, yes you can with some data handling.

```js
bb.generate({
	data: {
		columns: [
			["data1", 30, 200, 100],
			["data2", null, null, null, 400, 150, 250],
			["data3", null, null, null, null, null, null, 50, 100, 250]
		],
		type: "bar",
		groups: [["data1", "data2", "data3"]]
	},
	axis: {
		x: {
			type: "category",
			categories: [
				"cat1",
				"cat2",
				"cat3",
				"cat4",
				"cat5",
				"cat6",
				"cat7",
				"cat8",
				"cat9"
			]
		}
	}
});
```

and you'll get 
![image](https://user-images.githubusercontent.com/2178435/53309520-9cc2e880-38eb-11e9-9d3f-8b8e5d4ee248.png)
