### ISSUE TITLE
Dynamic Grid Lines on Zoom

### ISSUE THREAD

**Issue by nirmal93guna** [naver/billboard.js#799]
## Description
Adding Dynamic Grid Lines on Zoom

## Steps to check or reproduce
Is there a way to make the grids dynamic on zoom. Currently it is static. It would be lovely if the grid lines can be made dynamic like below

![
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14155901/53952692-7a08af00-40f7-11e9-94d8-f499e133eb32.gif)

**Comment by netil** [comment]
Hi @nirmal93guna, thanks for the suggestion.
As you said, currently `grids` aren't zoom attached  scalable.
