### ISSUE TITLE
Event rects are buggy when loading new timeseries data

### ISSUE THREAD

**Issue by sebzap** [naver/billboard.js#804]
I noticed when i load new timeseries data for my chart that the tooltips sometimes are very buggy. The cause are some really big event rects (like width=200 when it should be ~10).

I finally could reproduce it in a JSFiddle: https://jsfiddle.net/27ju6vhg/
Note that the first data set(loaded after 1sec) behaves correctly, but when the second dataset is loaded (after 3 secs) the tooltip behaviour is not as expected.

How the data is loaded does not have impact, when i loaded the data via the `columns` option i witnessed the bug as well.
It looks to me like the bug only happens when you load data entries prior to the current entries, meaning you add timestamps that are sooner. When loading additional entries with timestamps after the initial dataset or reducing the dataset the bug is not happening.
The bug is very hard to reproduce, this fiddle: https://jsfiddle.net/1dgpfvh0/ should be the same but no bug here.

**Comment by netil** [comment]
Hi @sebzap, really appreciate for the report & detailed explanation about it.
I'll look for that issue.

**Comment by netil** [comment]
Fixed on release 1.8.1.
