### ISSUE TITLE
Config setter not updating donut title

### ISSUE THREAD

**Issue by angajime** [naver/billboard.js#809]
## Description
After creating a simple _donut_ chart with billboard.js, using _.config()_ to change the title, changes the property in the object but it is not updated on the view.

## Steps to check or reproduce
https://stackblitz.com/edit/angular-v8jgfk

**Comment by Mangu93** [comment]
I'm having the very same issue :(

**Comment by netil** [comment]
@angajime, @Mangu93 the below code, will update text directly without using any API.

```js
chart.$.main.select(".bb-chart-arcs-title").text("my new title");
```

When `.config()` is called with the redraw option set to true, will invoke `.flush()` at the end.
The call of flush will force redrawing, but it doesn't mean re-rendering whole elements from the ground.

This is the reason which I added a NOTE on API doc.
> NOTE: Doesn't guarantee work in all circumstances. It can be applied for limited options only.

If whole rendering is happening on this scenario, is like destroying and re-generating chart. So, basically there's no difference as executing `.destroy()` -> `.generate()`.

**Comment by angajime** [comment]
@netil Your solution works perfectly. Thank you very much!

**Comment by eanders** [comment]
@netil , your solution works perfectly, unless the string contains a new line.  Realizing that this is a closed issue, I'm posting this for posterity.  This is not ideal since it access some of the internal API, but here's a solution that will work with multi-line titles:
```
chart.config('donut.title', 'Two Line \n Title');
// this uses jQuery to remove the current title, but could be done in pure JS
$(chart.internal.config.bindto.element + ' .bb-chart-arcs-title').remove();
chart.internal.setArcTitle();
```

**Comment by jorgeG92** [comment]
> @netil , your solution works perfectly, unless the string contains a new line. Realizing that this is a closed issue, I'm posting this for posterity. This is not ideal since it access some of the internal API, but here's a solution that will work with multi-line titles:
> 
> ```
> chart.config('donut.title', 'Two Line \n Title');
> // this uses jQuery to remove the current title, but could be done in pure JS
> $(chart.internal.config.bindto.element + ' .bb-chart-arcs-title').remove();
> chart.internal.setArcTitle();
> ```

@eanders Netil's solution works for me and in my case, I'm using a title with a new line. This second line contains the total sum of values. I add `tspan:last-of-type` CSS selector aim to the second line to update my total in the title.

chart.$.main.select(".bb-chart-arcs-title tspan:last-of-type").text(Number(total));

I hope this work for you!
