### ISSUE TITLE
Question: Pasting chart definition into playground

### ISSUE THREAD

**Issue by schulm** [naver/billboard.js#810]
## Description
If I paste a chart definition into the playground, the chart does not change. Is it intentional behavior. I expected c3js playground like behavior, where the chart adapts to the definition.

**Comment by netil** [comment]
Hi @schulm, the playground is not updating as code changes.
I'll be trying improving this on example's source section enabling code changes directly.

Meanwhile you can use tools like codepen or playground from observable
- https://codepen.io/netil/pen/mwWvGO?editors=1010
- https://observablehq.com/@idris-maps/billboard-js-playground
