### ISSUE TITLE
Change the thickness of an axis

### ISSUE THREAD

**Issue by LeonardAB** [naver/billboard.js#811]
## Description

I tried to create a bar graph. The bars are fine but the thickness of the axis seems odd. It also creates a square gap on the axis junction. 
I tried to follow this [SO post](https://stackoverflow.com/a/46886347/5122657) to change the thickness but it does not work. 

## Steps to check or reproduce

https://jsfiddle.net/h5c8df4n/ 

Thank you!

**Comment by netil** [comment]
Hi @LeonardAB, you missed loading css file.
Checkout the working example - https://jsfiddle.net/goxbv8Le/2/

**Comment by LeonardAB** [comment]
Thank you! Yes I missed the css.
