### ISSUE TITLE
$chart.export() quality

### ISSUE THREAD

**Issue by darian314** [naver/billboard.js#815]
## Description
Can't set image quality for export image. Is there a place to set pixel density?

**Comment by netil** [comment]
Hi @darian314, the export is done by serializing svg node and then imported on canvas, where final export is done calling `.toDataURL()`.

According the canvas API, there's parameter for image quality, but I don't think is what you need.
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#Parameters

So, for now there's no implicit option for quality, but you can handle with the returning `dataURL` string.

Maybe this can help:
- https://github.com/niklasvh/html2canvas/issues/241#issuecomment-247705673  

And I think it'll be good idea implement as new feature.
