### ISSUE TITLE
Gauge chart data is not updated when using load()

### ISSUE THREAD

**Issue by renakim** [naver/billboard.js#817]
Hello,
I'm using a gauge chart of billboard.js in the react project.
(I used react-billboardjs.)

I initialize gauge chart with value 0, and load new data using 'load', the graph is updated but the text(bb-gauge-value) is not updated like below image.
The new data of columns are all different. (different label, different value)

![image](https://user-images.githubusercontent.com/29771876/55043715-c56d0800-507a-11e9-90ae-17120226ba4c.png)

```
chartInstance.chart.load({
  columns: [[label, value]],
});
```
Please check this. Thank you.

**Comment by netil** [comment]
Hi @renakim, in most circumstances it should work.
Checkout the examples below for loading.

- https://jsbin.com/pasilij/edit?html,js,output
- https://naver.github.io/billboard.js/demo/#Chart.GaugeChart

![gauge-load](https://user-images.githubusercontent.com/2178435/55061075-34b41d80-50b6-11e9-911a-ff6c9a94da52.gif)

```js
const chart = bb.generate({
  data: {
    columns: [
		["data", 0]
    ],
    type: "gauge"
  }
});

setTimeout(function() {
   chart.load({ columns: [["data", 30]] });
}, 1000);
```

**Comment by renakim** [comment]
Thank you for reply.
I tested again with example, but when I use a different label, the text value is incorrect.
Should I use unload in this case?

![image](https://user-images.githubusercontent.com/29771876/55118550-0ecc5e80-5132-11e9-9d7f-522df35ad34f.png)

```
const chart = bb.generate({
  data: {
    columns: [
		["data", 0]
    ],
    type: "gauge"
  }
});

setTimeout(function() {
   chart.load({ columns: [["data1", 30]] });
}, 1000);
```

**Comment by netil** [comment]
@renakim well, in this case you should use `unload` option.
- https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load
```js
chart.load({
   columns: [["data1", 30]],
   unload: ["data"]
});
```
