### ISSUE TITLE
Zooming out of rotated bar chart shifts y-axis labels 

### ISSUE THREAD

**Issue by chrischris96** [naver/billboard.js#818]
When zooming out of a bar chart, the labels don't align properly.

Reproducing code:
https://jsbin.com/qusutojoxu/edit?html,js,output

**Comment by netil** [comment]
@chrischris96 thanks for reporting.
I'll try check the issue :0

**Comment by chrischris96** [comment]
Thanks for helping out!

**Comment by chrischris96** [comment]
Let me know if you need a helping hand!

**Comment by netil** [comment]
@chrischris96, well any kind of contributions are always welcomed! (specially PRs) 😄

**Comment by chrischris96** [comment]
It looks very good! Thanks for the effort :)
