### ISSUE TITLE
Playground is not working properly

### ISSUE THREAD

**Issue by dae20254** [naver/billboard.js#822]
playground 에서 아래 소스로 테스트 중인데 
x 축이 역순으로 정렬되고 그래프 마우스 오버도 잘 동작하지 않습니다.
뭐가 문제일까요?

{
    "data": {
      "x" : "x",
        "type": "bar",
        "columns": [
            ["x", 900, 1500, 2000, 3000, 4000],
            ["data1", 50, 20, 10, 40, 15]
        ]
    }
}

**Comment by netil** [comment]
Hi @dae20254, the current playground isn't really maintained well, due to lack of resource.
I have plan to deprecate or find simple way for this.

So, meanwhile try test codes on different online code editors (like jsfiddle, codesandbox, etc.)
- https://codepen.io/netil/pen/mwWvGO
