### ISSUE TITLE
CSS ids case issues on examples' page

### ISSUE THREAD

**Issue by FreezinG117** [naver/billboard.js#824]
## Description
When building the demo examples, the id of the chart element starts as lowercase, causing issues with the CSS styles.

For example:
![firefox_mSB9BdLVZM](https://user-images.githubusercontent.com/8019593/55567931-97309d80-56f6-11e9-89c8-fcac879af404.png)

Compared to live docs:
![firefox_8XqCpxks6O](https://user-images.githubusercontent.com/8019593/55568061-deb72980-56f6-11e9-9415-4ad8f8ba8bb2.png)

**Comment by netil** [comment]
@FreezinG117, I can't get what the point is.
The purpose of the examples is to letting know how to style chart element. You don't need to follow exactly as is.

**Comment by FreezinG117** [comment]
I'm not trying to change any code, just pointing an error in the current master demo page.

Here's what I did step by step:

1. git clone git@github.com:naver/billboard.js.git
2. npm install
3. npm start
4. go to http://localhost:8080/demo/#Axis.RotatedAxisGroupedBar

And the styles included are no longer working in the demo.

**Comment by netil** [comment]
@FreezinG117, Got it. Thanks for pointing this.
Fixed the demo's style rules to be lowercase.
