### ISSUE TITLE
Feature Request: add comment to tooltips

### ISSUE THREAD

**Issue by rexebin** [naver/billboard.js#826]
## Description
I have a chart show stock out and in on a day for a stock management feature. 
At the moment, the tooltip would show `legend name | quantity`. I now have a requirement, I want to show additional comment on each node, say showing customer name for each stock out. The tooltip would show `Stock out | 5 | Customer A`. 

At the moment the `columns` define data, I would suggest add a `tooltips` or `comments` node to allow us to add comment for each node in corresponding legend. It would look like this: 
['Stock Out', 'Customer A','Customer B',''] (empty string means no comment)

Is it possible?

**Comment by rexebin** [comment]
I could use format value in `tooltip`, but would be better to have the option to setup additional tool tips.

**Comment by netil** [comment]
Hi @rexebin, thanks for the idea, but I don't know if this can be a generalized feature for all.

The needs on displaying "what" contents vary among users, this is why fully customizable [tooltip.contents](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) is available.

Maybe recent added new [`tooltip.contents.template`](https://github.com/naver/billboard.js/issues/813) option to facilitate making customized HTML help on this. (I'm seeing add some updates to handle this case)

**Comment by netil** [comment]
@rexebin, implemented to add additional texts for tooltip using newly added `template` feature.
Hope this helps :)

```js
tooltip: {
contents: {
	bindto: "#tooltip",  // you need to set a tooltip holder selector
	text: {
		VAR: [ "A", "B", "TextA" ]
	},
	template: "<ul><li>Index<br>{=TITLE}</li>{{<li class={=CLASS_TOOLTIP_NAME}><span>{=VALUE}:{=VAR}</span><br><span style=color:{=COLOR}>{=NAME}</span></li>}}</ul>"
	}
}
```

![tooltip-template-text](https://user-images.githubusercontent.com/2178435/55714247-46d67a00-5a2d-11e9-9ad9-75ddc470750f.gif)
