### ISSUE TITLE
leaflet.js pie chart marker

### ISSUE THREAD

**Issue by MartijnHarmenzon** [naver/billboard.js#830]
Has anyone ever created a pie chart marker for Leaflet using Billboard.js? An example would be much appreciated. Or maybe an example of using Leaflet and Billboard using SVG. Thanks in advance.

**Comment by netil** [comment]
IMO, this isn't project related question.

I'm not a leaflet.js user, but according their example, you can set the marker image by exporting visualized chart.

```js
// (1) generate chart
var chart = bb.generate({
	size: {
		width: 200,
		height:100
	},
	data: {
		columns: [
			["data1", 10, 20, 30]
		]
	},
	legend: {
		show: false
	}
});

// (2) set marker getting image url using 'chart.export()'
var map = L.map('map').setView([51.5, -0.09], 13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

var LeafIcon = L.Icon.extend({
	options: {
		iconSize:     [38, 95],
		shadowSize:   [50, 64],
		iconAnchor:   [22, 94],
		shadowAnchor: [4, 62],
		popupAnchor:  [-3, -76]
	}
});

var greenIcon = new LeafIcon({iconUrl: chart.export()});

L.marker([51.5, -0.09], {icon: greenIcon}).addTo(map);
```

**Comment by MartijnHarmenzon** [comment]
Thank you for the quick response. I agree, this is not a project lated question. But I did not know where else to ask. I will try your example and will let you know the result.

**Comment by MartijnHarmenzon** [comment]
I modified your code a little and used the Leaflet L.divIcon. Now the normal Billboard.js functionality works inside a Leaflet map. Thanks for the support. This is the resulting code if anyone would like to use it.

`          var someIcon = new L.divIcon({
            className: 'some_class',
            iconSize: [50, 50],
            popupAnchor: [0, -25],
            html: '<div id="someID"></div>'
          });
          
          var someMarker = L.marker([latlng.lat, latlng.lng], {
            icon: someIcon,
            riseOnHover: true
          });
          
  bb.generate({
    size: {
      width: 50,
      height: 50
    },
    data: {
      columns: [
        ["data1", 75],
        ["data2", 25]
      ],
      type: "donut",
    },
    donut: {
      title: 'someName',
      label: {
        show: false
      },
      padAngle: 0.1
    },
    bindto: '#someID'
  });
`
