### ISSUE TITLE
About tooltip.grouped. How to catch only one element.

### ISSUE THREAD

**Issue by hinnalear** [naver/billboard.js#831]
## Description
I try tootip.grouped to false.
But, some member data smaller has been grouped.
From the picture. Can't focus only data7. Its show tootip grouped with nearby data.

![image](https://user-images.githubusercontent.com/725122/55774153-36baab00-5abe-11e9-9bdd-ebb066787cc9.png)
And onclick fires double event.

How to catch only near one element (close to mouse point). 

## Steps to check or reproduce
https://codepen.io/hinnalear/pen/gyLBdX

**Comment by netil** [comment]
Hi @hinnalear, by default there's an offset of 2px set for bar elements.
- https://github.com/naver/billboard.js/blob/master/src/shape/bar.js#L217

Currently, there's no configurable option. I'll be try implement for next release.
