### ISSUE TITLE
Dual chart not along center.

### ISSUE THREAD

**Issue by hinnalear** [naver/billboard.js#832]
## Description
On dual chart.
Option "bar.width" make the bar not along center.
`bar: {
  width: {
    ratio: 0.9
  }
}`

![image](https://user-images.githubusercontent.com/725122/55788192-0e44a800-5ae2-11e9-8957-3f8988574d32.png)

Not appear in version 1.7.1.

## Steps to check or reproduce
https://codepen.io/hinnalear/pen/ZZBdVp

**Comment by netil** [comment]
@hinnalear, thanks for reporting the issue.
It seems to be a some 'side effect' caused by some update of 1.8 release.

I'll be digging to fix the issue.

**Comment by netil** [comment]
released on 1.8.1
