### ISSUE TITLE
Question: How to show the actual values in the tick values popup of a donut chart

### ISSUE THREAD

**Issue by MartijnHarmenzon** [naver/billboard.js#833]
Question: How to show the actual values in the tick values popup of a donut chart?
The popup shows the percentages by default.

![image](https://user-images.githubusercontent.com/23123158/55791570-12ab9980-5abf-11e9-8e19-f7f887f4c1b1.png)

**Comment by netil** [comment]
@MartijnHarmenzon, you can use [tooltip.format.value](http://jindo.com/git/billboard.js/doc/Options.html#.tooltip) option.

```js
tooltip: {
    format: {
      value: function(x) {
        return x;
      }
    }
  }
```
