### ISSUE TITLE
Possible to display categories in a PieChart

### ISSUE THREAD

**Issue by Cathy347Le** [naver/billboard.js#839]
## Description

Instead of displaying a legend, it is possible to display the categories in the pie chart itself. Sort of like this image? 

![image](https://user-images.githubusercontent.com/46338135/56005502-c74fe180-5c9e-11e9-8d7f-3733faa38232.png)

## Steps to check or reproduce
This is what I have in React so far:

```
class PieChart extends Component {
  componentDidMount() {
    this.renderPieChart();
  }

  renderPieChart() {
    bb.generate({
      bindto: "#piechart",
      data: {
        columns: [
          ["Voted Clinton", 19.8],
          ["Voted Trump", 19.5],
          ["Didn't vote", 29.9],
          ["Ineligible to vote", 28.6],
          ["Voted other", 2.2]
        ],
        type: "pie",
        labels: true
      },
      pie: {
        padding: 2
      }
    });
  }
```

I appreciate your help and thank you for all the hard work.

**Comment by netil** [comment]
Hi @Cathy347Le, you can use [pie.label.format](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.pie) option.

![image](https://user-images.githubusercontent.com/2178435/56008775-4c2b1180-5d18-11e9-929e-c75220900389.png)

```js
bb.generate({
	bindto: "#piechart",
	data: {
		columns: [
			["Voted Clinton", 19.8],
			["Voted Trump", 19.5],
			["Didn't vote", 29.9],
			["Ineligible to vote", 28.6],
			["Voted other", 2.2]
		],
		type: "pie"
	},
	legend: {
		show: false
	},
	pie: {
		padding: 2,
		label: {
			ratio: 1.2,
			format: (value, ratio, id) => `${id}\n${(ratio * 100).toFixed(1)}%`
		}
	}
});
```

**Comment by Cathy347Le** [comment]
@netil wow Thank you!
