### ISSUE TITLE
Can we bind both Bar & Line chart to a div?

### ISSUE THREAD

**Issue by sraghudatta94** [naver/billboard.js#847]
## Description

Hi Team,
I tried going thru all the example charts, do we have provision to keep both line and bar chart as a single chart? Something like below Image
![bar_line](https://user-images.githubusercontent.com/23648455/56557359-54a50700-65b8-11e9-857f-db196309a7ac.gif)

## Steps to check or reproduce

Currently i am able to bind either line/Bar chart but not both

**Comment by netil** [comment]
Hi @sraghudatta94, do you mean displaying both types using one dataset?

```js
bb.generate({
  data: {
    columns: [
      // do you mean this data is displayed as bar & line at same time?
      ["data", 30, 100, 400, 150]
    ]
  }
})
```

If so, the answer is no. To display two types, you should set data for each type.

```js
bb.generate({
  data: {
    columns: [
      ["data1", 30, 100, 400, 150],
      ["data2", 30, 100, 400, 150]
    ],
    types: { data1: "bar" }
  }
})
```

**Comment by sraghudatta94** [comment]
Thanks @netil
