### ISSUE TITLE
Is it possible to create a chart that is a mix between donut and pie like this one? 

### ISSUE THREAD

**Issue by BGuidi73** [naver/billboard.js#856]
![Screen Shot 2019-04-30 at 17 05 49](https://user-images.githubusercontent.com/50146483/56971836-40d64380-6b6a-11e9-90c2-b24a9ac0bf18.png)

**Comment by netil** [comment]
Hi @BGuidi73, not possible yet, but It looks useful implementing as new feature.
I'll work for that :)

**Comment by netil** [comment]
@BGuidi73, done. Checkout the details from #858.

Try `nightly` build before the official release happens.
- https://github.com/naver/billboard.js/tree/nightly/dist

**Comment by BGuidi73** [comment]
Wonderful! Thanks!!!!
