### ISSUE TITLE
Dynamically loading data mixes hover legend 

### ISSUE THREAD

**Issue by austince** [naver/billboard.js#863]
## Description
Dynamically loading data through `chart.load({ columns })` displays correctly but hover legend becomes mixed up and will select records that are not being hovered over. I am using the area-spline chart. I have also ensured that the x-axis data is properly ordered for both sets. Unloading each column resolves the issue, but forces an "empty" flash.

I have seen issue https://github.com/naver/billboard.js/issues/771, but they are using a category chart.

## Steps to check or reproduce
Using Billboard.js version 1.8.0

Here's a link to a CodePen: https://codepen.io/austince/pen/mYyBxX?editors=0010
The config code is way at the bottom. Click `switch` to see the chart become confused. 

Thank you!

**Comment by netil** [comment]
Hi @austince, thanks for reporting the issue.

Fixed the issue as you can see from the screenshot below.
Try with the [`nightly`](https://github.com/naver/billboard.js/tree/nightly/dist) build.

![data-load-rect](https://user-images.githubusercontent.com/2178435/57284257-c79b9b00-70eb-11e9-89a1-bffa702245bd.gif)

**Comment by austince** [comment]
Awesome, thanks @netil, we'll try it out!

**Comment by austince** [comment]
Is there any chance this will be able to be released in the near future?

**Comment by netil** [comment]
@austince, the next coming release is planned by 14th, June.
- https://github.com/naver/billboard.js/milestone/12

**Comment by austince** [comment]
Great, thanks for the link! Would you be open to considering integrating something like [semantic release](https://github.com/semantic-release/semantic-release) so that you could ship more frequently and take some burden off of you?

**Comment by netil** [comment]
@austince, contributions are always welcomed!

**Comment by netil** [comment]
released on 1.8.1
