### ISSUE TITLE
Intent to ship data.labels.colors

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#871]
## Description

Current data label text color is same as data's color.
Sometimes there's needs on positioning within element's area, and this makes difficult to read.

Adding an option to apply different colors would be useful functionality.

```js
data: {
    labels: {
       // applied to all data labels
       colors: "red",

       // or
       colors: {
            data1: "red",
            data2: "white",
            ...
       }
   }
}
```

**Comment by elyobo** [comment]
Great, thanks @netil.
