### ISSUE TITLE
Load chart data including timeseries

### ISSUE THREAD

**Issue by dl0312** [naver/billboard.js#880]
## Description

I'm trying to show the date data for the three movies via `setinterval`, but the error message continues.
```
Error: <right> attribute x: Expected length, "NaN"
```
when I correct the date with sliding and set the length of x same, the error message does not appear, so the error appears to occur when the length of x corresponding to the timeseries is changed. It seems same bug as #804 

## Steps to check or reproduce

https://codesandbox.io/embed/jzw29px0xy

**Comment by netil** [comment]
Hi @dl0312, the issue was already fixed by ##865.
I'll be releasing this fixes on 1.8.1 release.
