### ISSUE TITLE
Theme for charts

### ISSUE THREAD

**Issue by sraghudatta94** [naver/billboard.js#885]
## Description
Is there any way to list the colors in some order, where all the charts follows that color?

## Steps to check or reproduce
For a single HTML i am trying to put multiple charts, where for every chart i am writing the below code
```js
color: function(color, d) {
	return ["#68B5F2", "#7A82CC", "#F9A74E", "#6DCCC5", "#1A6EA7", "#575DA0","#DD7300","#0A7C7C","#FFCC80","#9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA"][d.index];
}
```
So do we have a way to describe the theme somewhere once and use it every where in all charts?

Thanks.

**Comment by netil** [comment]
checkout [color.pattern](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.color) option.

```js
bb.generate({
   ...
   color: {
        pattern: ["#68B5F2", "#7A82CC", "#F9A74E", "#6DCCC5", "#1A6EA7", "#575DA0","#DD7300","#0A7C7C","#FFCC80","#9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA","98D6CB","9FA8DA"]
    }
}
```

**Comment by sraghudatta94** [comment]
Instead of doing this for each chart do we have any possibility to make for all charts? Somewhere changing the default color pattern?

**Comment by netil** [comment]
Well, there's another way doing that.

Add `.bb-color-pattern` css rule as below on your css file, and will take color pattern from that definition without defining as an option.

```css
/*-- Default color pattern --*/
.bb-color-pattern {
    background-image: url("#00c73c;#fa7171;#2ad0ff;#7294ce;#e3e448;#cc7e6e;#fb6ccf;#c98dff;#4aea99;#bbbbbb;");
}
```
- https://github.com/naver/billboard.js/blob/master/src/scss/theme/insight.scss#L7-L9

**Comment by sraghudatta94** [comment]
Thank you very much @netil
