### ISSUE TITLE
y2.min not working properly

### ISSUE THREAD

**Issue by jinayshah0506** [naver/billboard.js#888]
## Description
`y2.min` is set to **0** still the **y2 axis** shows **-10** on it, even though the data _does not_ contain any negative values.

## Steps to check or reproduce
https://codepen.io/jinayshah0506/pen/gJRPja

**Comment by netil** [comment]
Hi @jinayshah0506, try adjusting with [axis.y2.padding](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y2%25E2%2580%25A4padding) option

```js
y2: {
	show: true,
	min: 0, // On removing this attribute, deselect the data3 line by clicking on data4 legend and the negative value can be seen again.
	padding: {
		bottom: 0
	}
}
```

**Comment by jinayshah0506** [comment]
@netil Thanks for the help. It works!! :slightly_smiling_face:
