### ISSUE TITLE
Chart fails to render when there is data for y2 axis and axis.y2.show is set to false

### ISSUE THREAD

**Issue by dimusic** [naver/billboard.js#894]
## Description
Attempting to hide y2 axis with the data assigned throws an error and fails to render the whole chart

## Steps to check or reproduce
https://codesandbox.io/s/5d4ye

```javascript
bb.generate({
  data: {
    columns: [
      ["data1", 30, 200, 100, 400, 150, 250],
      ["data2", 50, 20, 10, 40, 15, 25]
    ],
    axes: {
      data1: "y",
      data2: "y2"
    }
  },
  axis: {
    y2: {
      show: false
    }
  },
  bindto: "#chart-container"
});
```

![axis y2 show false](https://user-images.githubusercontent.com/1485977/58111560-e9e2ed80-7bae-11e9-8b8f-12b0eac1e91b.PNG)

axis.y2.show set to false causes chart to fail. Could be related to the changes in #717

**Comment by netil** [comment]
Hi @dimusic, when explicitly set to not show y2 axis, will not generate related node(the change comes from the issue you pointed).

IMO, is counter intuitive set to not showing, but want to be aligned on that axis.
If you want to work as is, set `axis.y2.show=true` and handle the visibility with css.

```css
.bb-axis-y2 {
    display: none;
}
```
