### ISSUE TITLE
Hidden state (class) for custom legend item. How to?

### ISSUE THREAD

**Issue by solo-way** [naver/billboard.js#907]
## Description
Hi.
What is the best/simpest way to toggle "hidden" class ( .bb-legend-item-hidden ) for custom legend item as it's done for default legend items?
And shouldn't this be a default behavior?

## Steps to check or reproduce
https://naver.github.io/billboard.js/demo/#Legend.LegendTemplate1

**Comment by netil** [comment]
Hi @solo-way, do

```js
item: {
	onclick: function(id) {
		const selector = `.bb-legend-item-${id}`;
		const isShown = !document.querySelector(selector).style.opacity;
		this.api.toggle(id);

		if (isShown) {
			setTimeout(() => {
				document.querySelector(selector).style.opacity = "0.3";
			}, 200);
		}
	}
}
```

The [`.toggle()`](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#toggle) API with the second argument value, also can handle the visibility of the legend.

```js
chart.toggle("data1", {
    withLegend: true
});
```

But with this argument, will hide the legend. And will not be able to click the legend later on.
I'll be trying improve this to not hide completely, and make to work as the normal legend behaves.

**Comment by solo-way** [comment]
Thanks @netil 

The first solution works not exectly correct :(
Looks like .toggle() comletely rebuilds legend, thus state of all items reseted (lost), and then we set state for only one item.

Second solution - ok, but useless :(

> I'll be trying improve this to not hide completely, and make to work as the normal legend behaves.

I think, toggling class ( .bb-legend-item-hidden ) instead of visibility can be a good and straightforward behavior for chart.toggle().
Anyway, will wait for your decision.

Thank You.
