### ISSUE TITLE
Config to rotate category axis labels

### ISSUE THREAD

**Issue by radiantone** [naver/billboard.js#914]
## Description
When using category labels for x axis, the letters are being wrapped to fit the bar spacing, provide a config to allow for different rotation angles for these labels. For example, 90 degrees, so the text will fit the bar spacing.

**Comment by netil** [comment]
Hi @radiantone, there's [`axis.x.tick.rotate`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4rotate) option already, but this isn't working with rotated axis.

You can achieve this simply by css.

```css
.bb-axis-x .tick text {
	transform: rotate(10deg);
}
```
