### ISSUE TITLE
color.onover should be an optional type

### ISSUE THREAD

**Issue by bryceosterhaus** [naver/billboard.js#924]
## Description
The docs list `color.onover` as an optional type. The typescript definition lists it as required.

## Steps to check or reproduce
See https://naver.github.io/billboard.js/release/latest/doc/Options.html#.color
vs
https://github.com/naver/billboard.js/blob/master/types/options.d.ts#L113

**Comment by netil** [comment]
Hi @bryceosterhaus, thanks pointing this :)
