### ISSUE TITLE
area.linearGradient doesn't work if data name has a space

### ISSUE THREAD

**Issue by irislieuw** [naver/billboard.js#930]
## Description
The linear gradient doesn't get applied if the data name has a space in it

## Steps to check or reproduce
https://jsfiddle.net/irislieuw/ntybzp9L/

**Comment by netil** [comment]
@irislieuw thanks for reporting :)

**Comment by irislieuw** [comment]
@netil Thanks for the quick turnaround!! Awesome, as usual 😄
