### ISSUE TITLE
Pie charts fail when loading new data and the previous value was zero

### ISSUE THREAD

**Issue by ernestoalejo** [naver/billboard.js#935]
## Description
When new data is added to the chart with `.load()` in a pie chart, the graph starts to dissapear on hover and has a strange behaviour.

## Steps to check or reproduce
https://jsfiddle.net/ernestoalejo/ug3hk4Ly/

The code is simply creating a new basic pie chart:
```js
var chart = bb.generate({
  data: {
    columns: [
      ["data1", 0],
      ["data2", 0],
    ],
    type: "pie",
  },
  bindto: "#pieChart"
});
```

And 3 seconds later it changes the values:
```js
setTimeout(function() {
	chart.load({
		columns: [
			["data1", 3],
			["data2", 6],
		]
	});
}, 3000);
```

When you move the mouse over the graph it starts to flicker, dissapear and do strange things. It only happens when the first value was zero.

**Comment by netil** [comment]
Hi @ernestoalejo, thanks for reporting.
For workaround, unload data when you load.

```js
chart.load({
	columns: [
		["data1", 3],
		["data2", 6],
	],
	unload: true
});
```
