### ISSUE TITLE
Is there a way to disable event rects?

### ISSUE THREAD

**Issue by AyshvaryaLaxmiK** [naver/billboard.js#937]

**Comment by netil** [comment]
Hi @AyshvaryaLaxmiK, could you be more specific?
If you're trying to disable the interaction you can do with [interaction.enabled](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.interaction) option.

**Comment by AyshvaryaLaxmiK** [comment]
Hi!
I am trying to optimise my code and the chart generation time taken is
about 2.5 seconds . I want to minimize this to least 1 second.Hence I want
to stop the generation of event rects.This there anyway I could only
generate the chart and not the event rects?
Thanks in advance

**Comment by AyshvaryaLaxmiK** [comment]
PFA-chart generated

The total generation time of this chart after invoking bb.generate()
function is 9.619 seconds.
Is there anyway to reduce this time to 1 second?

**Comment by netil** [comment]
@AyshvaryaLaxmiK, I can't help without any details.
At least provide some generation code or reproducible online fiddle to examine some possible solution.

**Comment by netil** [comment]
@AyshvaryaLaxmiK, maybe this help on your needs.
Try disable interaction, and `<rect class=" bb-event-rect>` element won't be generated.

- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.interaction
```js
interaction: {
    enabled: false
}
```
