### ISSUE TITLE
How to submit an application using billboard.js

### ISSUE THREAD

**Issue by NeomMob** [naver/billboard.js#945]
## Description
I've developed a Markdown presentation Editor using billboard.js to render graphs. Graph renderign is working very well, thanks for the library and following https://github.com/naver/billboard.js/wiki/Who's-using-billboard.js I would like to add a link to the application.

## Steps to check or reproduce
Cannot find a wa to contact

**Comment by netil** [comment]
Hi @NeomMob, thanks for the interest! 😃 

There's no application for that. Just open a new issue or comment with the info is enough.
Then, I'll be adding the info to the wiki.

**Comment by NeomMob** [comment]
@netil , thanks for your answer. Application is a Markdown presentation editor called Slideas (https://www.slideas.app/ ) that generate Reveal.js presentation that can have billboard.js powered graphs

**Comment by netil** [comment]
@NeomMob, done, and thanks for the request!
> https://github.com/naver/billboard.js/wiki/Who's-using-billboard.js#applications
