### ISSUE TITLE
Gauge chart color option not working properly

### ISSUE THREAD

**Issue by renakim** [naver/billboard.js#950]
Hello,

## Description
When setting the color option on the gauge chart, Depending on the 'values', different actions are taken.

In the example below, when 'values' is [20, 40, 60, 80, 100], it's working.
but when 'values' is [0, 20, 40, 60, 80], It does not work. (only one color displayed)
What's the problem?

## Steps to check or reproduce

```js
const chart = bb.generate({
  data: {
    columns: [
		["data", 0]
    ],
    type: "gauge"
  },
  color: {
        pattern: ["#FF0000", "#e27600", "#F1C600", "#6aB044", "#e12345"],
        threshold: {
           //values: [20, 40, 60, 80, 100]
           values: [0, 20, 40, 60, 80]
        }
      }
  
});

setTimeout(function() {
   chart.load({ columns: [["data", 10]] });
}, 1000);

setTimeout(function() {
   chart.load({ columns: [["data", 50]] });
}, 2000);
```

**Comment by netil** [comment]
Hi @renakim, literally `0` has no meaning, but syntactically it should work.

Currently if the threshold value is `falsy`(zero), the color will be set as the last pattern value.
And also, to be aligned with the documentation, the threshold should work as:

```js
color: {
	pattern: ["red", "orange", "yellow", "green", "blue"],
	threshold: {
	   values: [10, 20, 40, 60, 80]
	}
}
```

- 0 ~ 10: red
- 11 ~ 20: orange
- 21 ~ 40: yellow
- 41 ~ 60: green
- 61 ~ 80+: blue
