### ISSUE TITLE
How to show only max and minimum value in Y axis

### ISSUE THREAD

**Issue by sraghudatta94** [naver/billboard.js#958]
## Description
How to show only the maximum and minimum value in step chart - Y axis?
## Steps to check or reproduce
![image](https://user-images.githubusercontent.com/23648455/60389555-e8c3ab00-9ae0-11e9-9b7f-4cc8a7ba50c1.png)

I have a step chart where the possible values are only 1 and 0 in Y axis. Is there a way to show only 1,0 ? Currently it shows 0,0.1,0.2 ---- 0.9,1

**Comment by netil** [comment]
@sraghudatta94, you can control via [axis.y.tick.values](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4y%25E2%2580%25A4tick%25E2%2580%25A4values) option.

```js
  axis: {
	y: {
		tick: {
			values: [0, 1]
		}
	}
  },
```

**Comment by sraghudatta94** [comment]
Thanks @netil
