### ISSUE TITLE
Incompletes timeseries tooltip bug (wrong data displayed)

### ISSUE THREAD

**Issue by eweap** [naver/billboard.js#963]
## Description
I try to load 2 differents timeseries in the same chart but I encounter a bug with the data displayed in tooltip.

## Steps to check or reproduce
See https://stackblitz.com/edit/uxszjg?file=index.ts

My first timeserie has 6 values, and I load a second timeserie with only 5 values (supposing that we don't have to data for this date) without unloading the first one. All linechart points are placed to their corresponding date but when hovering, lets say, the first data, the tooltip is displaying n+1 data for the second timeserie.

Thanks by advance for your help !

**Comment by netil** [comment]
Hi @eweap, do you have any issue load additional data like this way?

```js
setTimeout(function() {
	chart.load({
		columns: [
       			["data2", null, 220, 150, 40, 250, 150]
		]
	});
}, 1000);
```

**Comment by eweap** [comment]
@netil The problem is that the following outputs come from 2 distinct API calls:
```
[
    // 6 values
    ["x", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
    ["data2", 220, 150, 40, 250, 150]
]
```
and
```
[
    // 5 values
    ["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
    ["data1", 30, 200, 100, 400, 150, 250]
]
```

The API returns only the data it has (that's why there can be different dates between timeseries) and timeserie are loaded progressively (after each API call) in the chart with `load`.

Should I extract all previously loaded data from the chart to check every missing date and try to find the right index to fill with `null` ? Even if it is feasible it seems to me not the right way to go.

The library has all the data it needs to do this work itself no ? I think this should be done internally.

What are your toughts about it ?

Thanks.

**Comment by netil** [comment]
@eweap, I misunderstood the issue.
It seems the tooltip isn't aligned correctly with the data loaded.

Thanks for the report!
