### ISSUE TITLE
Options to draw a histogram chart 

### ISSUE THREAD

**Issue by jeesim2** [naver/billboard.js#985]
## Steps to check or reproduce

![image](https://user-images.githubusercontent.com/1100831/61441243-2ac56b80-a980-11e9-85eb-3b2ccc8970a1.png)

Hello developers,
I've two questions about drawing a histogram chart.

1. Tick of bar chart placed in the middle of each bar's horizontal center.
   But, one rectangle in histogram have it's lower bound and upper bound.
   So for histogram tick need to represents the boundary of each bar and located between bars. How can we do this?

2. If distribution of data is very long tailed, general workround is gather the tail area data into one bar. In this case, last tick of x axis will have not the same data range to  others.
   This can be done in billboard?

**Comment by netil** [comment]
Hi @jeesim2, from what I understood is:
1) About the x Axis tick text position
   - Try with [axis.x.tick.text.position](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4text%25E2%2580%25A4position) option. But to be used, you need to know chart size to point exact position.
2) About the x Axis tick text value
   - Try setting Axis x's type as `category`.

![image](https://user-images.githubusercontent.com/2178435/61502238-0f08a680-aa0e-11e9-97e2-dc9ab8c87dc3.png)


```js
// when chart width is 400px
var chart = bb.generate({
  data: {
	x: "x",
	columns: [
		["x", 0, 10, 20, 30, 100],
		["data1", 80, 100, 250, 200, null]
	],
	type: "bar"
  },
  axis: {
	  x: {
		type: "category",
		tick: {
			text: {
				position: {
                                       // the value will differ based on the chart size
					x: -30
				}
			}
		}
	  }
  },
  bar: {
    width: {
      ratio: 1
    }
  }
});
```

Let me know if this wasn't what you looking for.

**Comment by jeesim2** [comment]
Hi @netil ,
Those are what I expected.
It looks almost find : ).
One thing thought difficult is tick positioning by giving an absolute pixel, because chart width can be responsive. :)

**Comment by netil** [comment]
@jeesim2, try adding as follows.

```js
onrendered: function() {
	const tickWidth = this.main.select(".tick").node().getBoundingClientRect().width - 4;
	
	this.main.selectAll(".bb-axis-x tspan").attr("x", -tickWidth);
}
```

**Comment by jeesim2** [comment]
@netil WOW! Great!
