### ISSUE TITLE
Typings issues in types/plugin/stanford/options.d.ts

### ISSUE THREAD

**Issue by Guymestef** [naver/billboard.js#987]
## Description
Typescript is throwing the following errors while type checking:

ERROR in ./node_modules/billboard.js/types/plugin/stanford/options.d.ts(68,23):
TS7006: Parameter 'x' implicitly has an 'any' type.

ERROR in ./node_modules/billboard.js/types/plugin/stanford/options.d.ts(108,11):
TS7006: Parameter 'value' implicitly has an 'any' type.

ERROR in ./node_modules/billboard.js/types/plugin/stanford/options.d.ts(108,18):
TS7006: Parameter 'percentage' implicitly has an 'any' type.

## Steps to check or reproduce
Use billboard.js with typescript

**Comment by netil** [comment]
Hi @Guymestef, thanks for the report.
I'm seeing some of the parameters types aren't defined. I'll be fixing that.
