### ISSUE TITLE
[Feature Suggestion] Custom Tooltip position

### ISSUE THREAD

**Issue by SoYoung210** [naver/billboard.js#990]
It would be nice if tooltips appeared in various positions. Please let me know if you have already offer  this feature.
I would like to be able to provide the same functionality for **n** data.
## Description

I want to make custom tooltip position.  (dynamically)

i have two data, like this 
![image](https://user-images.githubusercontent.com/18658235/61766266-29ca8900-ae1b-11e9-925c-5b6757e1bf2d.png)

When i click `.bb-event-rect` area, make tooltip **close point. **

![billboard](https://user-images.githubusercontent.com/18658235/61766415-baa16480-ae1b-11e9-8f3c-8231f25709d4.gif)

With [tooltip options](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) , i think it's limited... 

So i do this with DOM API, innerHTML and setAttribute(for style). 

I add code that I have implemented, but my code is only available when there are only two data.

I would like to be able to provide the same functionality for **n** data.

### Make Tooltip (Helper function) 
```tsx
const generateTooltipTemplate = (data: any) => {
    console.log('data', data);
    const { firstDataValue, secondDataValue, month } = data;

    const balance = firstDataValue - secondDataValue;
    return `<div id='my-line-chart-tooltip' style='min-width: 145px;'>
              <div>
                <b>${month}월</b>
              </div>
              <div>data1 : ${firstDataValue}</div>
              <div>data2 : ${secondDataValue}</div>
              <div class='balance'>test : ${balance}</div>
            </div>`;
  };

  const setTooltipPosition = (data, index) => event => {
    const eventLayerX = event.layerX;
    const tooltipContainer = document.querySelector('.bb-tooltip-container');
    const chartWrapper = document.getElementById('my-line-chart');
    const chartTopOffset = chartWrapper.getBoundingClientRect().top;
    const viewPortWidth = document.body.clientWidth;
    const chartHeight = chartWrapper.clientHeight;
    const tooltipWidth = tooltipContainer.clientWidth;
    const tooltipHeight = tooltipContainer.clientHeight;

    const circles: NodeListOf<HTMLElement> = document.querySelectorAll(
      `.bb-circle-${index}`
    );

    tooltipContainer.innerHTML = generateTooltipTemplate(data);

    const closePosition = getClosePosition(circles, event);
    const closePositionY = closePosition.top - chartTopOffset;
    const closePositionX = closePosition.left;

    const targetPositionX =
      eventLayerX + tooltipWidth > viewPortWidth
        ? closePositionX - tooltipWidth
        : closePositionX;

    const targetPositionY =
      chartHeight - (closePositionY + tooltipHeight) < 0
        ? closePositionY - tooltipHeight
        : closePositionY;

    tooltipContainer.setAttribute(
      'style',
      `position: absolute; top:${targetPositionY}px; left: ${targetPositionX}px;`
    );
  };

  const getClosePosition = (
    circleElements: NodeListOf<HTMLElement>,
    event
  ): ClientRect =>
    Math.abs(circleElements[0].getBoundingClientRect().top - event.clientY) >
    Math.abs(circleElements[1].getBoundingClientRect().top - event.clientY)
      ? circleElements[1].getBoundingClientRect()
      : circleElements[0].getBoundingClientRect();
```

### Add EventListener
```ts
    bb.generate({
      onafterinit() {
        document.querySelectorAll('.bb-event-rect').forEach((el, i) => {
          const firstDataValue = data[firstDataKey][i];
          const secondDataValue = data[secondDataKey][i];
          el.addEventListener(
            'click',
            setTooltipPosition(
              {
                firstDataValue,
                secondDataValue,
                month: i,
              },
              i
            )
          );
        });
      },
// ..... 
})
```

**Comment by netil** [comment]
Hi @SoYoung210, did you tried [tooltip.position](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option?

```js
tooltip: {
     position: function(data, width, height, element) {
         return {
             top: 0,
             left: 0
         }
     },
```

**Comment by SoYoung210** [comment]
yes i tried!
As you know, `element` is chart container.
Eventually i had to access the DOM directly to show the tooltip for each point.
> .bb-circle-${index} 

Because, i can't know circle position.

**Comment by netil** [comment]
@SoYoung210, IMO is not about the lack of functionality.
There're many alternative ways to achieve your needs.

# 1
Tooltip is basically works for `mouseover` event, but your implementation is done via `click`.
If you need tooltip to be appeared on `click`, you might consider [`data.onclick`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4onclick) option.

# 2
- For `tooltip.position` option, will pass correspond `data` object as argument.
You can use data value to look for data point element(represented as the `<circle>` node) and then determine the point's current position.
- The second way is if `d3` object can be accessed in some way, use `d3.event` object to determine current mouse position.


```js
  tooltip: {
	position: function(data, width, height, element) {
		// 1) get data points' position
		var circles = chart.$.line.circles.filter(d => d.x === data[0].x).nodes();

		circles.forEach(v => {
                        // note: using .getBoundingClientRect() will force layout trahsing
			v.getBoundingClientRect();  

                        // maybe using point's 'cx/cy' attribute value for computation can be more efficient
			v.getAttribute("cx");
		});

		// 2) If d3 is exposed on global, you can access mouse event
		var e = d3.event;

		console.log(e.clientX, e.clientY);

         return {top: 0, left: 0}
     },
  }
```

**Comment by SoYoung210** [comment]
Thanks for kind reply! i will try it. :)
