### ISSUE TITLE
[Question] How can i make dash array at spline chart ? 

### ISSUE THREAD

**Issue by SoYoung210** [naver/billboard.js#992]
## Description

Related : #986 

I want to know **how line chart make dasharray style** . 
I know Billboard does not support dash arrays for spline charts.

I would like to apply `dash array` to the spline chart in such a way that I customize the svg inside the billboard or cover the css based on the class name.

It would be very helpful if you could simply explain how the line chart draws the dash array.

**Comment by netil** [comment]
For this moment partial dashed style can't be applied for `spline`.
But, you can make whole `spline` as dashed easily via [stroke-dasharray](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray) css property.

Checkout the below example, updating data.type to spline.
- https://naver.github.io/billboard.js/demo/#Style.StyleForLines

![image](https://user-images.githubusercontent.com/2178435/61773421-9f405480-ae2f-11e9-8b24-98629106bb71.png)

**Comment by SoYoung210** [comment]
Thank you ... I will share if i implement a partial dash array..
